### ISSUE TITLE
Travis CI is discontinuing free plans

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1009]
Effectively, Travis will not offer free CI any longer: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Starting immediately, they will start to migrate accounts to a plan with a starting number of credits that will last us for a while (depending how much activity we have, probably a few weeks to months). Open source projects can apply for some free credits, but that's not a monthly number, but you have to reapply every time the credits run out.
Thus, we should probably either ask the CXC to pay, or we move to another CI provider (e.g. github actions, microsoft azure pipelines).

**Comment by DougBurke** [comment]
Yay. :kermitflail:

#1007 is my **VERY** limited attempt at trying out GitHub actions but

- it's not clear if anything is being run (I did get emails to point out YAML format issues during development) - it may require the code to hit the master branch
- it's not at all clear how to actually build a python package with compiled code with GitHub actions - the examples have a 'pip install -r requirements.txt' line, but my understanding was that this wouldn't build things for us. We can't move to using tox just at this time either as we haven't really got far with #784

**Comment by hamogu** [comment]
pip, if set up correctly following PEP 518 etc., will compile with system tools. I can pip install astropy from source and that's definitely a package with compiled code.
I'm attempting to replicate that in #784, I just have not put much time into it. Look like now would be a good time to do that...

However, I think the timing is still not terrible: We are just through 4.12.2, which is essentially also 4.13 (except that we might want to text with different python versions etc.). So, while it's good to continue development, there is no hurry to merge anything. Travis will also give each project 10000 credits, which will last us a while, in particular if we are a little more careful. We can take steps to stretch that out further by reducing the build matrix (for the time being), ask for OSS credits, and move away eventually.

Given our limited resources, I actually suggest that we wait till 4.13 is out of the door before we spend too much time on that. A large number of OSS projects will look into Travis alternatives (incl. astropy, where I'm most looped into the discussion) and several of thme will have lessons learned soon, so that we don't have to research all the alternatives ourselves.

**Comment by hamogu** [comment]
@Marie-Terrell and others already solved this.
