### ISSUE TITLE
Jupyter notebook representation not ideal if model components don't have unique names

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1013]
It's not ideal to have the parameters listed twice under the same name, just because two model have the same name. Might be confusing after the fit when the parameters of the two models are actually different. 

![Screen Shot 2020-11-12 at 4 04 42 PM](https://user-images.githubusercontent.com/498688/98996497-f1aff380-2500-11eb-8531-cd210ddc480f.png)

Not ideal, but also clearly not a dealbreaker. Maybe that's a good incentive for the user to ensure unique names!

@DougBurke

**Comment by DougBurke** [comment]
Try `print(mymodel)` and you'll also see this duplication (although it has a different form), so it's technically not just a notebook issue. 

It's not obvious to me how to "fix" this. For the notebook output we don't have a way to distinguish the two components **UNLESS** we use the `id()` of the object, and how useful would that be. Similarly, the `print(mymodel)` output only really has the id of the two components to distinguish the two. You could think about carrying along other fields to add some sort of discriminatory power, but that way lies madness, I tell ya!

**Comment by hamogu** [comment]
Mmmm. I can cofuse the table a lot more if the models of identical name are not listed consecutively:
![Screen Shot 2020-11-12 at 4 56 47 PM](https://user-images.githubusercontent.com/498688/99001021-2bd0c380-2508-11eb-92b3-8d1a4d3f0a19.png)

**Comment by hamogu** [comment]
I think I have a solution. Just needs a little more tinkering before I'll issue a PR.

**Comment by DougBurke** [comment]
Is this only going to address the notebook, or the more general case (e.g. the output of `print(mymodel)` is not that obvious)?

**Comment by hamogu** [comment]
I'll start with the notebook, but then I'll see if I can do the same thing for `print`.

**Comment by hamogu** [comment]
``print`` is different in the sense that models are not delinated anyway so that I did not expect to see a delimiter between models. On the other hand, in the notebook, the "Component" has a rowspan that makes it look as if models were separated by model (but are not, they are separated by having different string names).
