### ISSUE TITLE
plot_model_component does not work well for PHA data

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1020]
You need to include the response in the model component, which is not easy to get (better recently now #888 has been merged but still not ideal). That is, you for something like

```
set_source(xstbabs.amdl * (xsvapec.m1 + xsvapec.m2))
```

you would say something like (safest)

```
rsp  = _session._get_response(1, get_data())
```

or (less general - e.g. doesn't handle pileup, multiple responses or fancy background cases)

```
rsp = sherpa.astro.instrument.Response1D(get_data())
```

and then

```
plot_model_component(rsp(m1), alpha=0.5)
plot_model_component(rps(m2), alpha=0.5, overplot=True)
```

or perhaps

```
plot_model()
plot_model_component(rsp(amdl * m1), alpha=0.5 ,overplot=True)
plot_model_component(rsp(amdl * m2), alpha=0.5, overplot=True)
```

![sherpa](https://user-images.githubusercontent.com/224638/101025456-9abb9e00-3543-11eb-9750-59bcae4409fb.png)

If you don't include the response you get garbage results.

We should probably add the response in automatically. The questions then are:

- if we want to use a different response then how would that work (is just checking for a subclass of `sherpa.astro.instrument.RSPModel` sufficient? I doubt it as what about RMF-only responses?)
- if I've used set_full_model then we don't have a way to "get" a response, which would require the user to supply their own (i.e. a use case for the first point)
- what happens if I really don't want to use a response (perhaps add a flag for this case)

**Comment by anetasie** [comment]
@DougBurke Is this only relevant to XSPEC models or the PHA with the response? I can `plot_model_component` in v.4.13 without the need for a response.

**Comment by DougBurke** [comment]
While you can plot the model component in 4.13, you're not actually getting a sensible output. This is irrelevant of model type. If your PHA file has no associated response then it's not a problem, but then you aren't doing anything sensible by fitting it anyway.

In the following I've fitted `xsphabs.gal * powlaw1d.pl` and you can see it's reasonable (orange line passing through the blue points), but ...

```
sherpa In [6]: plot_fit(ylog=True)

sherpa In [7]: plot_model_component(pl, overplot=True)
```

creates

![sherpa](https://user-images.githubusercontent.com/224638/112929736-fdced300-90e6-11eb-8759-374dc96d092e.png)

where the green line is the pl component - it is **NOT** the model after passing through the response.

**Comment by DougBurke** [comment]
If I use #1022 - which I have some reservations for the API but the functionality works - then I get

![sherpa](https://user-images.githubusercontent.com/224638/112986727-dbad7300-912f-11eb-978a-d1596e242c13.png)

The difference between the fit blot (grouped) and model component plot (ungrouped) is a separate issue which I have thoughts about (there's a lot of behavior I don't like with PHA source plotting).

**Comment by DougBurke** [comment]
With CIAO 4.13/main branch you have to say something like

```
sherpa In [10]: plot_fit(ylog=True)

sherpa In [11]: rsp = get_response()

sherpa In [12]: plot_model_component(rsp(pl), overplot=True)
```

to get that last plot.

**Comment by anetasie** [comment]
This sounds good. My earlier comment was related to plots for radial profile or other type of ascii files, where `plot_model_component` would not have had any response, so be equivalent of `plot_source_component`.

**Comment by anetasie** [comment]
> If I use #1022 - which I have some reservations for the API but the functionality works - then I get
> 
> ![sherpa](https://user-images.githubusercontent.com/224638/112986727-dbad7300-912f-11eb-978a-d1596e242c13.png)
> 
> The difference between the fit blot (grouped) and model component plot (ungrouped) is a separate issue which I have thoughts about (there's a lot of behavior I don't like with PHA source plotting).

There is definitely a need for plotting the models at different resolution that the data and I don't think we have a perfect solution at this moment. I guess models defined on user supplied grid add the complications.
