### ISSUE TITLE
SABnzbdplus 2.x conflicting with SABnzbd 3.x, how to uninstall if not detected with cli ?

### ISSUE THREAD

**Issue by tristanbes** [sherpa/sherpa#1023]
Hello,

I had an old install of sherpa including SABnzbdplus.
I tried an upgrade (installing the new qpkg), but sherpa cli is not picking the installation of SABnzbdplus.

I tried installing SABnzbd but it fails (I imagine because of the existing installation of the 2.x)

```
[~] # tail -f /var/log/SABnzbd.log
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py", line 40, in <module>
    import feedparser
  File "/opt/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'"
result: [1]


[~] # sherpa list-installed
Entware
Par2
SABnzbd
nzbToMedia
SickChill
```

What's the procedure to uninstall SABnzbdplus please ? Cannot do it through the UI.
![Capture d’écran 2020-12-05 140522](https://user-images.githubusercontent.com/346010/101243829-1d3e8c00-3703-11eb-925e-a7fb4f952b23.png)

![Capture d’écran 2020-12-05 141522](https://user-images.githubusercontent.com/346010/101244031-5297a980-3704-11eb-946c-194207b5bef0.png)

Thank you.

**Comment by DougBurke** [comment]
I'm sorry but you've got the wrong Sherpa. This is about a Python package for modelling and fitting data.

I think you meant https://onecdonly.github.io/sherpa/ - I don't know where their issue list is.

**Comment by tristanbes** [comment]
oh wow sorry 😱

**Comment by DougBurke** [comment]
No problems - unfortunately sherpa is  a popular name ...
