### ISSUE TITLE
PHA data, models, and notice - what is going on

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1024]
This is with CIAO 4.13.0 developmemt but I've seen this with the master branch:

# OKAY

```
sherpa In [1]: load_pha('3c273.pi')
...

sherpa In [2]: set_source(xsphabs.gal * powlaw1d.pl)

sherpa In [3]: notice(0.5, 5)

sherpa In [4]: plot_data()
```

![sherpa](https://user-images.githubusercontent.com/224638/101379249-11c59f00-3882-11eb-820b-ad6414d5e7a3.png)

# WAT

The only difference is a call to `plot_model` before the `notice` call, and it looks like the `notice` has been ignored!

```
sherpa In [1]: load_pha('3c273.pi')
...

read background file 3c273_bg.pi

sherpa In [2]: set_source(xsphabs.gal * powlaw1d.pl)

sherpa In [3]: plot_model()

sherpa In [4]: notice(0.5, 5)

sherpa In [5]: plot_data()
```

![sherpa](https://user-images.githubusercontent.com/224638/101379445-45a0c480-3882-11eb-8b6a-97e224bc9885.png)

**Comment by anetasie** [comment]
@DougBurke it may  be related to the `notice/ignore` order - when these are issued for the first time than the required filter is automatically set. For example if you `notice` for the first time than `ignore` of the data outside the bound will be done. If you do this after a few `notice/ignore` - you have to `ignore()` first to get the required `notice` range.

**Comment by DougBurke** [comment]
This is in a new session - I have not called `notice` or `ignore` before.

**Comment by DougBurke** [comment]
The "good" news is that I also see this in CIAO 4.12.1, so it's not due to one of my recent changes (which was my fear).

So with 

```
% python -c 'import sherpa; print(sherpa.__version__)'
4.12.1
```

we have

`% cat okay.py
import logging

from sherpa.astro.ui import *

logging.getLogger('sherpa').level = logging.WARN
load_pha('3c273.pi')
logging.getLogger('sherpa').level = logging.INFO

set_source(xsphabs.gal * powlaw1d.pl)

notice(0.5, 5)
print(get_filter())
plot_data()

% python okay.py
WARNING: systematic errors were not found in file '3c273.pi'
WARNING: systematic errors were not found in file '3c273_bg.pi'
0.518300011754:4.869099855423
```

So we can see it's approximately 0.5 to 5 keV, as requested.

Adding in a `plot_model` causes problems - the filter appears to have been ignored:

```
% diff -u okay.py bizarre.py
--- okay.py     2020-12-07 12:27:33.960505748 -0500
+++ bizarre.py  2020-12-07 12:30:02.807113639 -0500
@@ -8,6 +8,8 @@

 set_source(xsphabs.gal * powlaw1d.pl)

+plot_model()
+
 notice(0.5, 5)
 print(get_filter())
 plot_data()
% import logging

from sherpa.astro.ui import *

logging.getLogger('sherpa').level = logging.WARN
load_pha('3c273.pi')
logging.getLogger('sherpa').level = logging.INFO

set_source(xsphabs.gal * powlaw1d.pl)

plot_model()

notice(0.5, 5)
print(get_filter())
plot_data()

% python bizarre.py
WARNING: systematic errors were not found in file '3c273.pi'
WARNING: systematic errors were not found in file '3c273_bg.pi'
/home/dburke/anaconda/envs/ciao412/lib/python3.7/site-packages/sherpa/plot/pylab_backend.py:330: MatplotlibDeprecationWarning: Passing the drawstyle with the linestyle as a single string is deprecated since Matplotlib 3.1 and support will be removed in 3.3; please pass the drawstyle separately using the drawstyle keyword argument to Line2D or set_drawstyle() method (or ds/set_ds()).
  zorder=zorder)
0.124829999695:12.410000324249
```
```

**Comment by DougBurke** [comment]
My bet is that it's related to the `ModelHistogram` plot object which does "strange" things to allow it to display the model at the native instrument resolution rather than the grouped data. It looks like the following has some sort of error in the `finally` logic.

```
class ModelHistogram(ModelPHAHistogram):
    """Plot a model for a PHA dataset with no grouping.

    The model is drawn at the native resolution of
    the instrument response, or ungrouped channels.
    The model is filtered to the minimum and maximum
    of the PHA dataset but any ignored ranges within
    this are ignored.
    """

    def prepare(self, data, model, stat=None):

        old_filter = parse_expr(data.get_filter())
        old_group = data.grouped
        new_filter = parse_expr(data.get_filter(group=False))
        try:
            if old_group:
                data.ungroup()
                for interval in new_filter:
                    data.notice(*interval)

            super().prepare(data, model, stat=stat)

        finally:
            if old_group:
                data.ignore()
                data.group()
                for interval in old_filter:
                    data.notice(*interval)
```

**Comment by DougBurke** [comment]
So, actually, I think that it is actually @anetasie 's [comment from above](https://github.com/sherpa/sherpa/issues/1024#issuecomment-740047436), it's just that the `plot_model` code has secretly "set" the state so it thinks that I have already called a `notice` command, hence the `notice` call I make is ignored.

This is wrong, but is not a show-stopper for the 4.13 release (and is not a recent regression).

**Comment by anetasie** [comment]
@DougBurke yes, not a show-stopper, just a feature :-)
