### ISSUE TITLE
An interesting issue with the plot_model handling for DataPHA: last bin

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1026]
![sherpa](https://user-images.githubusercontent.com/224638/101699661-8991f600-3a49-11eb-95f9-1cada80d5a6e.png)

Note that the model in the last "bin" is not flat. In fact, it looks like it hasn't been grouped.

I expect that this is because the last bin isn't completely grouped, so has a grouping flag of 2 (or maybe it's got a 5 in this case). A ignore_bad() removes the points.

For further research.

**Comment by anetasie** [comment]
@DougBurke if `ignore_bad()` ignores these channels then they have a bad quality and are ignored in 'group'. Has the pha file been already grouped?

**Comment by DougBurke** [comment]
Not sure I understand the question - whether the grouping was read in or by the group* functions shouldn't matter.

**Comment by DougBurke** [comment]
I can't re-create this so I'm closing it.

**Comment by hamogu** [comment]
As @DougBurke said a while ago: Can't be re-created right now, so closing.
