### ISSUE TITLE
Sherpa is failing to compile on OSX due to error in region-4.11

### ISSUE THREAD

**Issue by steveehlert** [sherpa/sherpa#1029]
Relevant output of setup.py build command:

Making install in region-4.11
Making install in src
/Library/Developer/CommandLineTools/usr/bin/make  install-am
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"region\" -DPACKAGE_TARNAME=\"region\" -DPACKAGE_VERSION=\"4.11\" -DPACKAGE_STRING=\"region\ 4.11\" -DPACKAGE_BUGREPORT=\"cxchelp@head.cfa.harvard.edu\" -DPACKAGE_URL=\"\" -DPACKAGE=\"region\" -DVERSION=\"4.11\" -DYYTEXT_POINTER=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBM=1 -DHAVE_FLOAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_SQRT=1 -DHAVE_STRCASECMP=1 -DHAVE_STRCHR=1 -DHAVE_STRPBRK=1 -I.     -g -O2 -MT regparser.lo -MD -MP -MF .deps/regparser.Tpo -c -o regparser.lo regparser.c
libtool: compile:  gcc -DPACKAGE_NAME=\"region\" -DPACKAGE_TARNAME=\"region\" -DPACKAGE_VERSION=\"4.11\" "-DPACKAGE_STRING=\"region 4.11\"" -DPACKAGE_BUGREPORT=\"cxchelp@head.cfa.harvard.edu\" -DPACKAGE_URL=\"\" -DPACKAGE=\"region\" -DVERSION=\"4.11\" -DYYTEXT_POINTER=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBM=1 -DHAVE_FLOAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_SQRT=1 -DHAVE_STRCASECMP=1 -DHAVE_STRCHR=1 -DHAVE_STRPBRK=1 -I. -g -O2 -MT regparser.lo -MD -MP -MF .deps/regparser.Tpo -c regparser.c  -fno-common -DPIC -o regparser.o
regparser.y:629:5: error: implicit declaration of function 'regYYrestart' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    regYYrestart(NULL);
    ^
1 error generated.
make[3]: *** [regparser.lo] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

Attempting to install on OSX 10.15.7. I have a Homebrew installed gcc-10 but I'm not sure if the sherpa install is using that.

**Comment by wmclaugh** [comment]
As a work around, please try running your build with the CLFAGS environment variable set to include '"-Wno-implicit-function-declaration". For example, the following commands allow me to successfully build sherpa on macOS 10.15.6 with clang 12.0.0.

     setenv CFLAGS "-Wno-implicit-function-declaration"
     python setup.py develop

**Comment by steveehlert** [comment]
So I figured out what happened - due to institutional restrictions i had to sudo install, and settings like that weren't making their way to setup. Making a little script to set those environments within a sudo made it work.
