### ISSUE TITLE
Controlling verbosity of fitting and error estimation in stand-alone sherpa

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1032]
I'm using Sherpa in a script that fits hundreds of relatively small and simple datasets and I see a lot of output like this
```
gauss1d.pos lower bound:	-0.178148
gauss1d.pos upper bound:	0.178148
```

I would like to switch that off. After doing some code digging, the best solution I cam up with is this.
At the import section of my code:

```
import logging
sherpablog = logging.getLogger('sherpa')
old_level = sherpablog.level
```
And then in the place where I do the fitting:
```
sherpablog.setLevel(logging.WARNING)
my_fittter.est_error()
sherpablog.setLevel(old_level)
```
That seems pretty complicated and I only found it by reading through the source code. So, I have two questions: 

- Is there an easier way?
- I did not see it in the stand-along docs. Did I miss that?

If this is indeed the way to do it, then I'll look for a place in the docs where I can add that.

**Comment by DougBurke** [comment]
Changing the logging level is the only way to do this. I don't believe we
have any helper routines to do this, but we could add a context manager so
you could say (name completely open for bike-shedding)

foo.set_sherpa_verbosity('warning')
blah-blah()
foo.set_sherpa_verbosity('info')

or

with foo.set_sherpa_verbosity(logging.WARNING)
  blah-blah()

(accepting a string as a helper to avoid having to explicitly import
logging..)

Does this seem sensible?

For the docs, we can either describe each function that supports the
logger, or just have a single section that describes it. I think I'd
suggest the latter, even though we do not use the logging infrastructure in
all places (we probably should use it more, but probably not in all cases).

**Comment by hamogu** [comment]
I was, in fact, very surprised that the logging module itself does not provide such a decorator already. I'll put this issue on my list. Seem pretty simple.

**Comment by hamogu** [comment]
Mmm. More difficult than I thought because sherpa creates a number of loggers (most are initialized when a module is important, so the number depend on what exactly was imported before this point. So, we really need to know which logger writes specific output, which is not always clear to users, e.g. I might call "ui.fit()", but the logging is really done by the "sherpa" logger. 

```
logging.root.manager.loggerDict

{'concurrent.futures': <Logger concurrent.futures (WARNING)>,
 [... removing a bunch of non-sherpa logger ...]
 'sherpa': <CIAOLogger sherpa (DEBUG)>,
 'sherpa.models.parameter': <CIAOLogger sherpa.models.parameter (DEBUG)>,
 'sherpa.models': <logging.PlaceHolder at 0x7fa255119710>,
 'sherpa.astro.utils': <CIAOLogger sherpa.astro.utils (DEBUG)>,
 'sherpa.astro': <logging.PlaceHolder at 0x7fa2552ab5d0>,
 'sherpa.models.regrid': <CIAOLogger sherpa.models.regrid (DEBUG)>,
 'sherpa.models.model': <CIAOLogger sherpa.models.model (DEBUG)>,
 'sherpa.models.basic': <CIAOLogger sherpa.models.basic (DEBUG)>,
 'sherpa.optmethods': <CIAOLogger sherpa.optmethods (DEBUG)>,
 'sherpa.fit': <CIAOLogger sherpa.fit (DEBUG)>,
 'sherpa.plot': <CIAOLogger sherpa.plot (DEBUG)>,
 'sherpa.plot.pylab_backend': <CIAOLogger sherpa.plot.pylab_backend (DEBUG)>,
 'matplotlib.legend': <CIAOLogger matplotlib.legend (WARNING)>,
 'sherpa.all': <CIAOLogger sherpa.all (DEBUG)>,
 'sherpa.image': <CIAOLogger sherpa.image (DEBUG)>,
 'sherpa.astro.data': <CIAOLogger sherpa.astro.data (DEBUG)>,
 'sherpa.instrument': <CIAOLogger sherpa.instrument (DEBUG)>,
 'sherpa.astro.all': <CIAOLogger sherpa.astro.all (DEBUG)>,
 'sherpa.astro.io.crates_backend': <CIAOLogger sherpa.astro.io.crates_backend (DEBUG)>,
 'sherpa.astro.io': <CIAOLogger sherpa.astro.io (DEBUG)>,
 'sherpa.astro.background': <CIAOLogger sherpa.astro.background (DEBUG)>,
 'sherpa.astro.plot': <CIAOLogger sherpa.astro.plot (DEBUG)>,
 'sherpa.ui.utils': <CIAOLogger sherpa.ui.utils (DEBUG)>,
 'sherpa.ui': <logging.PlaceHolder at 0x7fa1c62acd10>,
 'sherpa.astro.ui.serialize': <CIAOLogger sherpa.astro.ui.serialize (DEBUG)>,
 'sherpa.astro.ui': <logging.PlaceHolder at 0x7fa1c657ec90>,
 'sherpa.astro.ui.utils': <CIAOLogger sherpa.astro.ui.utils (DEBUG)>,
 'sherpa.astro.datastack.plot_backend': <CIAOLogger sherpa.astro.datastack.plot_backend (WARNING)>,
 'sherpa.astro.datastack': <CIAOLogger sherpa.astro.datastack (WARNING)>,
 'sherpa.astro.datastack.utils': <CIAOLogger sherpa.astro.datastack.utils (WARNING)>,
 'sherpa.astro.datastack.ds': <CIAOLogger sherpa.astro.datastack.ds (WARNING)>}
```

Do we really need that many different loggers? (For comparison, astropy uses the same logger for everything, while matplotlib uses one logger per modules like we do in sherpa.) That's a bigger discussion though. So, for now, I'm just adding docs to fitting.

**Comment by DougBurke** [comment]
I was under the impression that using 'sherpa' should trigger all the "sub
loggers" - eg 'sherpa.models.basic'. Is this not the case?

**Comment by hamogu** [comment]
I did not know that, I learned something new. Good! Here is another bit: The `setLevel` accepts strings and ints already (`logging.WARNING` is just a fancy way to say `30`). Will have new code shortly, but might take till later to turn into PR because I've not yet upgraded my development environment to 4.13.

**Comment by hamogu** [comment]
Interestingly, the datastack module already has a function like that on the module level:
https://github.com/sherpa/sherpa/blob/aac024fffa2b5900ca88798438cce24bb1e6878d/sherpa/astro/datastack/__init__.py#L234

**Comment by DougBurke** [comment]
Well, it's not a context manager!

[must stop working, as I'm supposed to be on vacation today]
