### ISSUE TITLE
`DataPHA` object fails display if channel does not start from 0

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1040]
I found the following behaviour surprising:

This works fine:
```
from sherpa.astro.data import DataPHA
x = np.arange(15)
d = DataPHA('test',x, np.arange(15))
d.group_counts(4)
d
```
This is in the jupyter notebook, so the last line gives me a nice plot and summary of my data object.

However, if the channel number does not start at 0, e.g. I replace the second line with `x = np.arange(15) + 10` then I get instead:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in _group_to_channel(self, val, group, response_id)
   1902         try:
-> 1903             return mid[val]
   1904         except IndexError:

IndexError: index 12 is out of bounds for axis 0 with size 12

During handling of the above exception, another exception occurred:

DataErr                                   Traceback (most recent call last)
~/anaconda3/envs/ciao/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in _repr_html_(self)
   1446         """Return a HTML (string) representation of the PHA
   1447         """
-> 1448         return html_pha(self)
   1449 
   1450     def __getstate__(self):

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in html_pha(pha)
    273     # Should this only be displayed if a filter has been applied?
    274     #
--> 275     fexpr = pha.get_filter_expr()
    276     bintype = 'groups' if pha.grouped else 'channels'
    277     nbins = pha.get_dep(filter=True).size

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in get_filter_expr(self)
   3419     def get_filter_expr(self):
   3420         return (self.get_filter(format='%.4f', delim='-') +
-> 3421                 ' ' + self.get_xlabel())
   3422 
   3423     def notice_response(self, notice_resp=True, noticed_chans=None):

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in get_filter(self, group, format, delim)
   3401 
   3402         # Convert channels to appropriate quantity if necessary
-> 3403         x = self._from_channel(x, group=group)
   3404 
   3405         if mask is None:

~/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/data.py in _group_to_channel(self, val, group, response_id)
   1903             return mid[val]
   1904         except IndexError:
-> 1905             raise DataErr('invalid group number: {}'.format(val))
   1906 
   1907     def _channel_to_energy(self, val, group=True, response_id=None):

DataErr: invalid group number: [ 9 10 11 12 13 14 15 16 17 18 19 20]
```

I'm not actually sure if the OGIP standard allows PHA that don't start at 0, so maybe this is intentional. If it is, we might want to think about a better error message. However, on first sight, it looks to me like a bug in the grouping with seems to implicitly assume that the channel number always starts at 0.

**Comment by DougBurke** [comment]
Actually, the default is to start channel numbers at 1. The TLMIN value for the channel column in the FITS file is used to indicate a non-unity value - see https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node6.html

It wouldn't surprise me if Sherpa only works correctly with 0 or 1 as the starting point (and there may well be problems with the 0 case as I'm not sure we have any test cases). For instance the RMF has support for an offset - see https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002/cal_gen_92_002.html#tth_sEc3.1.1 and https://sherpa.readthedocs.io/en/latest/data/api/sherpa.astro.data.DataRMF.html but I don't know what happens if `offset != {0, 1}`

**Comment by anetasie** [comment]
I think OGIP standard does not allow for TLMIN be different than {0,1}, so implementation of offset in Sherpa was only to support these two. @hamogu what happens when you try to read this pha file into XSPEC?

**Comment by hamogu** [comment]
It's not a PHA file. I create the DataPHA object "by hand". First, let me state that I don't need this to work, I have a workaround and it's just fine, so if you think this is out of scope, just close the issue.

What I did was this: I read several evt2 files into Python (using astropy tables in this case, but that's not relevant). Then, I did some merging of evt files and filtering to make a histogram of counts in a certain range of CHIPX/CHIPY and PHA (e.g. 450 - 650) to calibrate the GAIN correction. I put my histogram into a DataPHA object - because that's exactly what it is: a histogram of PHA values - to use the grouping and plotting that's already defined on DataPHA objects. 

Here is the workaround that I'm using: I make sure that my histogram starts at 0 (so I use the range 0-650) and then I ignore 0-450. 

I don't see why our DataPHA object need to be constrained by what OGIP allows for the file format that hold PHA files, but of course typically you'll make a DataPHA object from reading in the PHA file, so we can just say: It's OK, we'll live with this limitation.

*Thought*: We might want to have a `DataBinnedCounts` class at some point. There are other things one can count than just events in PHA channels, e.g. I might have "stars in spectral class" or "AGN in mass bin" and I might want to fit, e.g. a powerlaw to that. All the grouping and ignoring methods of `DataPHA` would be useful in this case, too (e.g. I might want to ignore masses below the completness limit and then group to min 5 objects per bin for plotting). If we ever introduce a class like that, then it should not be restricted to {0,1} as starting values for the x-axis. `DataPHA` would inherit from this new class and add the background and exposure time stuff that's specific for PHA files.

**Comment by anetasie** [comment]
@hamogu Is `Data1DInt` not what you need? `DataPHA` assumes that you will have RMF/ARF files there. `Data1DInt` is basically binned data and `Data1D` supports non-binned data.

**Comment by hamogu** [comment]
`Data1DInt` does not have things like `group_min` or `group_snr`. On the other hand, `DataPHA` works just fine without ARF/RMF as long as you fit in channel space.

**Comment by anetasie** [comment]
Perhaps we just need to expand the grouping options. Only PHA data are grouped now and there are issues and the grouping options and the code need some more thinking and work.

**Comment by hamogu** [comment]
I think that's a good "priority for 2021"...

**Comment by hamogu** [comment]
> I think OGIP standard does not allow for TLMIN be different than {0,1}, so implementation of offset in Sherpa was only to support these two. 

Actually, the OGIP standard says that is "usually" starts from 0 or 1. There is no hard requirement on the starting value: https://heasarc.gsfc.nasa.gov/docs/heasarc/caldb/docs/memos/cal_gen_92_002a/cal_gen_92_002a.html

**Comment by DougBurke** [comment]
For reference, the pyfits backend has this "interesting" bit of code https://github.com/sherpa/sherpa/blob/e2e2da29ca0b6fc3b70f21eedd478eea5203b2d1/sherpa/astro/io/pyfits_backend.py#L843-L847 which I think I need the week-end to mentally unpack

**Comment by DougBurke** [comment]
So, there's backend-specific changes needed and also changes to DataPHA. There are a bunch of places where we assume the channel array is 1-based [as also shown in https://github.com/sherpa/sherpa/issues/1040#issuecomment-877460759] so we can just treat it as an index (after correcting for the 1) - e.g. line 2072 in https://github.com/sherpa/sherpa/blob/e2e2da29ca0b6fc3b70f21eedd478eea5203b2d1/sherpa/astro/data.py#L2047-L2080 and the other `_channel_to_xxx` routines (but it's a bit harder to see there). I'm hoping it's relatively contained to a few routines.

There is a related issue of what happens when the PHA file has a smaller number of channels than the TLMIN/MAX range (e,g, EXOSAT data can have this).

**Comment by DougBurke** [comment]
So, with the current HEAD I can say

```
import numpy as np
from sherpa.astro.data import DataPHA

chans = np.arange(1, 15)
counts = chans.copy()

d0 = DataPHA("chans0", chans - 1, counts)
d1 = DataPHA("chans1", chans, counts)
d5 = DataPHA("chans5", chans + 4, counts)
d15 = DataPHA("chans15", chans + 14, counts)
```

and can, in separate jupyter cells enter

```
d0
d1
d5
d15
```

and they display. I can then say

```
for d in [d0, d1, d5, d15]:
    d.group_counts(4)
```

and again display each of them in separate cells with

```
d0
d1
d5
d15
```

So I'm going to close this issue down for now.
