### ISSUE TITLE
Can we use mamba instead of mocking out modules?

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1055]
For RTD to build docs or maybe for some GH action test?
https://github.com/mamba-org/mamba

**Comment by DougBurke** [comment]
I only glanced at the mamba docs briefly so maybe it's obvious, but I couldn't work out what benefit this would give over a conda build / avoid issues with conda (primarily the extra build and "fun" with getting things to build on the RTD platform).

**Comment by hamogu** [comment]
It's supposed to be several times faster to install with mamba than with conda. Not sure that helps us, but wanted to at least have an issue so that I don't forget looking into it.

**Comment by hamogu** [comment]
As shown by #1808 , mamba works for RTD. We could consider using mamba instead of conda on normal CI to save time, but that's not be bottleneck right now, so there is no need for an open issue. We can always switch to mamba later if it turns out to be beneficial. For now, I'm just closing this issue.
