### ISSUE TITLE
group_xxx, tabStops, and mask handling

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1081]
This may relate to ideas to implement #956. Not sure how this relates to #718

# Issue 1

This is part of the grouping/filtering work, and in this case is because the `mask` attribute is grouped but for the group functions we need the ungrouped data.

```
In [2]: load_data('sherpa-test-data/sherpatest/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file sherpa-test-data/sherpatest/3c273.arf
read RMF file sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file sherpa-test-data/sherpatest/3c273_bg.pi

In [3]: ignore(None, 0.5)

In [4]: ignore(7, None)

In [5]: d = get_data()

In [6]: group_counts(20, tabStops=~d.mask)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-3b601a5fe044> in <module>
----> 1 group_counts(20, tabStops=~d.mask)

<string> in group_counts(id, num, bkg_id, maxLength, tabStops)

~/sherpa/sherpa-docs/sherpa/astro/ui/utils.py in group_counts(self, id, num, bkg_id, maxLength, tabStops)
   8132         if bkg_id is not None:
   8133             data = self.get_bkg(id, bkg_id)
-> 8134         data.group_counts(num, maxLength, tabStops)
   8135
   8136     # DOC-TODO: check the Poisson stats claim; I'm guessing it means

~/sherpa/sherpa-docs/sherpa/astro/data.py in group_counts(self, num, maxLength, tabStops)
   2561             raise ImportErr('importfailed', 'group', 'dynamic grouping')
   2562         self._dynamic_group(pygroup.grpNumCounts, self.counts, num,
-> 2563                             maxLength=maxLength, tabStops=tabStops)
   2564         for bkg_id in self.background_ids:
   2565             bkg = self.get_background(bkg_id)

~/sherpa/sherpa-docs/sherpa/astro/data.py in _dynamic_group(self, group_func, *args, **kwargs)
   2402         do_notice = numpy.iterable(self.mask)
   2403
-> 2404         self.grouping, self.quality = group_func(*args, **kwargs)
   2405         self.group()
   2406         self._original_groups = False

ValueError: grpNumCounts() The tabStops and countsArray have differing length
```

The way to fix this at present is to call `ungroup`:

```
In [7]: ungroup()

In [8]: group_counts(20, tabStops=~d.mask)
```

# Issue 2

A related issue is that setting the background grouping depends on ordering (I can understand this, but it's not clear to the users).

This works:

```
In [9]: ungroup()

In [10]: group_counts(20, bkg_id=1, tabStops=~get_bkg().mask)

In [11]: group_counts(20, tabStops=~get_data().mask)
```

This does not work because setting the grouping for the source dataset (line 13) also sets the grouping for the background dataset (which makes sense as we generally want the source settings copied to the background), but this means that at line 14 the mask has now been grouped, and so we are back to the issue-1 case:

```
In [12]: ungroup()

In [13]: group_counts(20, tabStops=~get_data().mask)

In [14]: group_counts(20, bkg_id=1, tabStops=~get_bkg().mask)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-40b4fb02c418> in <module>
----> 1 group_counts(20, bkg_id=1, tabStops=~get_bkg().mask)

<string> in group_counts(id, num, bkg_id, maxLength, tabStops)

~/sherpa/sherpa-docs/sherpa/astro/ui/utils.py in group_counts(self, id, num, bkg_id, maxLength, tabStops)
   8132         if bkg_id is not None:
   8133             data = self.get_bkg(id, bkg_id)
-> 8134         data.group_counts(num, maxLength, tabStops)
   8135
   8136     # DOC-TODO: check the Poisson stats claim; I'm guessing it means

~/sherpa/sherpa-docs/sherpa/astro/data.py in group_counts(self, num, maxLength, tabStops)
   2561             raise ImportErr('importfailed', 'group', 'dynamic grouping')
   2562         self._dynamic_group(pygroup.grpNumCounts, self.counts, num,
-> 2563                             maxLength=maxLength, tabStops=tabStops)
   2564         for bkg_id in self.background_ids:
   2565             bkg = self.get_background(bkg_id)

~/sherpa/sherpa-docs/sherpa/astro/data.py in _dynamic_group(self, group_func, *args, **kwargs)
   2402         do_notice = numpy.iterable(self.mask)
   2403
-> 2404         self.grouping, self.quality = group_func(*args, **kwargs)
   2405         self.group()
   2406         self._original_groups = False

ValueError: grpNumCounts() The tabStops and countsArray have differing length
```

**Comment by anetasie** [comment]
@DougBurke A decision on syncing background grouping to grouping of the source data was made at some point, as to avoid issues with `subtraction' or calculating statistics for the simultaneous fitting of source and background data. In the simultaneous fitting the background contribution to the statistics has to match the bin/group of the source data bin/group. In a separate fitting of the background such limitation would not be necessary, but the grouping of the background was left to match the source data to avoid complication of the code.

**Comment by anetasie** [comment]
I guess I should have said - in calculation of the statistics for the simultaneous fit of source & background the groups  of the source and background needs to match, but perhaps not if the statistics for source and background are 
 are calculated separately and then added at the final step of calculating the statistics, but if the `backscale` is an array then things will get more complicated.

**Comment by DougBurke** [comment]
@anetasie - I'm aware of these issues, and I agree that we do want to default to mirroring the soruce dataset - but I think the usability of this is potentially surprising. Unfortunately we want to be able to go from "automagically mirroring the source dataset" to "using background-specific settings" which is not a well-specified problem (given that we are having enough trouble trying to track the behavior when we are just thinking about the source dataset)!

**Comment by DougBurke** [comment]
@anetasie - the source and background datasets only need match filter and grouping if we subtract the data. When doing a simultaneous fit (e.g. bmodel to background, smodel + scale * bmodel to source) the filtering and grouping can be different for the two datasets.

**Note to self** This suggests one interesting thought: we can have the background have different filter/grouping, but when you can subtract() the background values are ignored (and we just use the source settings). This would remove some of the "magic" behavior, but I think it would be less usable - e.g. we would still want ignore/group commands to also apply to the background by default. So maybe not that interesting.

**Comment by DougBurke** [comment]
So, one issue is what to do with filters when you have grouped data. The following is with CIAO 4.13 but it's the same as the `main` branch:

```
sherpa In [1]: load_pha(1, 'sherpa-test-data/sherpatest/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file sherpa-test-data/sherpatest/3c273.arf
read RMF file sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file sherpa-test-data/sherpatest/3c273_bg.pi

sherpa In [2]: load_pha(2, 'sherpa-test-data/sherpatest/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file sherpa-test-data/sherpatest/3c273.arf
read RMF file sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file sherpa-test-data/sherpatest/3c273_bg.pi

sherpa In [3]: ungroup(2)

sherpa In [4]: ignore(None, 0.5)

sherpa In [5]: get_data_plot(1).xlo[0:5]
Out[5]: array([0.56940001, 0.64240003, 0.7008    , 0.7446    , 0.78839999])

sherpa In [6]: get_data_plot(2).xlo[0:5]
Out[6]: array([0.51099998, 0.52560002, 0.5402    , 0.55479997, 0.56940001])

sherpa In [7]: ungroup(1)

sherpa In [8]: get_data_plot(1).xlo[0:5]
Out[8]: array([0.56940001, 0.58399999, 0.59859997, 0.61320001, 0.62779999])
```

So, if we ignore up to 0.5 keV then [the bin values refer to the center of the

- the originally grouped data starts at 0.57 keV
- the ungrouped data starts at 0.51 keV [a "better" answer but there are very-important reasons why the previous value is 0.57 keV]
- if we ungroup the first dataset then we say starting at 0.57 keV but you can see the bins are narrower

This means that the choice of setting a filter before or after grouping has consequences! This makes sense, but it would be nice if we could re-apply filters after a change of grouping to get the "closest" values to what was asked for. 

Naively, we could store the requested ranges in `notice`/`ignore` calls, so these could get re-applied, but there are difficulties, such as "user manually sets the mask value for bins with `set_filter`" which we can't reverse-engineer. This would probably require a "you're previous filter has been lost" warning case. I also wonder if there's hidden pitfalls to this approach.
