### ISSUE TITLE
filter expressions for PHA datasets could be improved

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1129]
The filter expression for a PHA dataset reports the center of the bin when I think it would make sense to use the low edge (for lower) and high edge (for upper).

The following is with CIAO 4.13 but the exact version doesn't matter too much as this hasn't changed for a while:

```
sherpa In [1]: load_pha('3c273.pi')
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi

sherpa In [2]: get_filter()
Out[2]: '0.124829999695:12.410000324249'

sherpa In [3]: ungroup()

sherpa In [4]: get_filter()
Out[4]: '0.008030000201:14.943099975586'
```

Notice that the filter expression has changed because I've changed from grouped to ungrouped data. The actual filtered data range (which is this case is the full dataset) hasn't actually changed, just the reported values.

```
sherpa In [5]: notice(0.5, 7)

sherpa In [6]: get_filter()
Out[6]: '0.503699988127:7.000699996948'
```

This seems sensible, but as shown below the limits 0.5037 and 7.0006 are actually the mid-points of the bins, and I claim that it would be better to report here (modulo number of decimal places):

    0.496399...:7.00799...

```
sherpa In [7]: pha = get_data()

sherpa In [8]: elo, ehi = pha._get_ebins()

sherpa In [9]: elo[pha.mask][0], ehi[pha.mask][0]
Out[9]: (0.49639999866485596, 0.5109999775886536)

sherpa In [10]: elo[pha.mask][-1], ehi[pha.mask][-1]
Out[10]: (6.9934000968933105, 7.007999897003174)

sherpa In [11]: (0.4964 + 0.5111) / 2
Out[11]: 0.50375

sherpa In [12]: (6.9934 + 7.0080) / 2
Out[12]: 7.0007
```

If we report the bin edges then the response to

    load_pha('3c273.pi')
    get_filter()
    ungroup()
    get_filter()

would be to return the same string for both `get_filter` calls (in this case it would be '0.0014600000577047467:14.950400352478027')

**Comment by hamogu** [comment]
Agreed that lower/upper bin would be better.

**Comment by DougBurke** [comment]
I think that this is "purely" a descriptive deature - i.e. changing it may cause some user confusion but wouldn't really change any analysis results. In other words it should be a relatively safe change, but  not enough to bet money (but enough to work out a PR).
