### ISSUE TITLE
numpy 1.10: histo test failure

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#113]
# Test failure

Using numpy 1.10.0, the test_histo test will fail with

```
E   TypeError: histogram() got an unexpected keyword argument 'new'
```

This is in `sherpa/astro/tests/test_astro.py`.

# Warning note, possibly not relevant

The numpy 1.9 release notes - currently at http://docs.scipy.org/doc/numpy/release.html as I couldn't find a versioned URI - has this in the 'Future changes' section

- Default casting for inplace operations will change to ‘same_kind’ in Numpy 1.10.0. This will certainly break some code that is currently ignoring the warning.

The Sherpa code has been somewhat lax about numpy warnings - some modules override the current value "globally" (i.e. without restricting to a particular function), and this can lead to odd behaviour depending on the order modules are imported. I have not checked to see if we have any code that ignores the warning mentioned above, but it should probably be done since numpy 1.10.0 has just been released: https://mail.scipy.org/pipermail/scipy-user/2015-October/036709.html

A run of the test suite with numpy 1.10.0 doesn't seem to show any problem related to this particular change.

**Comment by DougBurke** [comment]
Actually, it appears that this particular change isn't that much of a problem (or our tests are oblivious to it). However, I've edited in a note about the known test failure.

**Comment by DougBurke** [comment]
How is this fixed by #109 - which only involves matplotlib?

**Comment by olaurino** [comment]
The bug (and the fix) is in https://github.com/sherpa/sherpa-test-data/commit/b06d88d1a4cb61f579976f880710ad8a6ca41fc2

I had to include this fix as otherwise the combination matplotlib 1.5 numpy 1.10 would have triggered failures in the tests.

However, I forgot to merge the relative PR in sherpa-test-data, which may be a problem.

**Comment by olaurino** [comment]
Ok, that branch is merged, it should be all good.

**Comment by DougBurke** [comment]
Aha, that makes sense (re the problem with matplotlib version 1.10 actually being in the test code rather than sherpa code itself). I'll re-close this now you've merged in the sherpa-test-data changes.
