### ISSUE TITLE
Consider the structure of our documentation

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1133]
Sherpa has (at least it feels like that) more functions and ways to do the same thing than numpy or e.g. matplotllib Even after contributing to the Sherpa codebase a bit, I still constantly discover new functions, new parameters, etc. It often does not feel "coherent" and the fact that our docs are organized to be read by function (docstrings, ahelp "see also"), to just skim the surface (readthedocs text) or in threads (ciao website) instead of systematically explain all options does not help.

Threads are good as examples, but if you want to do something just slightly different, it's hard to find out how because you don't know where to start looking and looking things up by function requires knowing what those functions are called.

I know it's a lot of work to write good documentation and the fact that we serve two different communities (through the stand-alone release and as part of CIAO) and then we have two totally different interfaces (UI layer and OO) does not make it easier.

Still, I'm missing pages like 
- https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html (concept)
- https://docs.scipy.org/doc/scipy/reference/stats.html (list)
- https://matplotlib.org/stable/users/interactive_guide.html (concept)
- https://docs.astropy.org/en/latest/time/index.html (concept and list in one page)

that explain the concept and/or list all available options for one topic (e.g. all plotting commands with a shot explanation what they do beyond the name of the function I get in he "see also" list).
https://cxc.cfa.harvard.edu/sherpa/snapshot.html is pretty close to what I have in mind, but not complete in any sense (because it, again, it meant to just skim the surface).

I'm not advocating to write that *right now* because that's too much work, but I'd like to know or discuss (if not yet decided) what our vision for the future is.

Can we unify the CIAO website and readthedocs? Generate them from the same input files? Do we keep them totally separate (one for the ui layer, one for OO), but increase linking between them? Where do we add more content? Where would a more systematic overview go?

I know @DougBurke has done a lot of work to unify docstrings and ahelp files and has probably thought about this...

**Comment by DougBurke** [comment]
To be honest what would help is people contributing (like this suggestion is) to where to go next and then **actually writing** the documentation. So far I see people say the documentation is lacking, and then stopping there. I can not write all the documentation.

I do **not** see the CIAO and readthedocs pages being unified - they serve different use cases and the different backends (crates vs astropy is the main issue but there are some other subtle differences in region filtering) have enough functional differences to make it hard to argue that a CIAO user (my main paying customer) should spend a lot of time reading about stuff they don't care about.

**Comment by DougBurke** [comment]
I guess another way of saying this is that while working out an overall plan for our documentation would be great, it may be better to just pick an area that needs work and work on it.

**Comment by hamogu** [comment]
At @DougBurke I'm not asking you to write anything; I'm just putting down my thoughts in writing so that I don't forget; I was not going to spend my time to write a detailed plan, I just wanted an issue to remember and to ask you for your general thoughts.

**Comment by hamogu** [comment]
This issue is not actionable as written, so I'm closing it.
