### ISSUE TITLE
add a python 3.9 CI run (and review existing setup)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1176]
I've been able to build with python 3.9, astropy, and matplotlib and the test pass. So that's good but we should have CI tests to check.

We can't include DS9 at the moment as our xpa conda build won't work - the conflict I got was

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package xz conflicts for:
python=3.9 -> xz[version='>=5.2.5,<6.0a0']
xpa -> gtk3[version='>=3.22.30,<3.23.0a0'] -> xz[version='>=5.2.4,<6.0a0|>=5.2.5,<6.0a0']

Package libgcc-ng conflicts for:
python=3.9 -> libgcc-ng[version='>=7.3.0']
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
```

**Comment by hamogu** [comment]
We are adding 3.10 to CI already, so I think this can be closed. If we discover the same incompatible specifications there, we can open a new issue.
