### ISSUE TITLE
PHA channel not starting at 1

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1197]
I am not convinced we handle PHA files where the channel does not start at 1 (from some testing I added in #1151). Keith Arnaud points me to the file file1.pha in ftools/spectral/session of the HEAsoft distribution as a good test case.

**Comment by hamogu** [comment]
I believe this is a (partial) duplicate of #1040. While #1040 deal with plotting specifically, it's the same underlying cause: THe channel does not start at 1.

**Comment by DougBurke** [comment]
I'm going to close this and keep #1040 open
