### ISSUE TITLE
Files opened with the wrong mode (r, w, etc.) in sherpa regression test

### ISSUE THREAD

**Issue by jbudynk** [sherpa/sherpa#123]
A warning message is shown if someone tries to open a read-only files. Running the sherpa regression tests with the data directory specified in a CIAO environment will give a warning:

```
% source /proj/xena/ciaod/Linux64/ciao_1021/bin/ciao.csh
CIAO configuration is complete... 
CIAO 4.8 Wednesday, October 21, 2015
  bindir      : /proj/xena/ciaod/Linux64/ciao_1021/bin
  CALDB       : 4.6.9
% python -c "import sherpa; sherpa.test(datadir='/data/regression_test/master/in/sherpa')"
Found 7/7 tests for sherpa.astro.tests.test_datastack
Found 1/1 tests for sherpa.astro.models.tests.test_models
...
................................./proj/xena/ciaod/Linux64/ciao_1021/lib/python2.7/site-packages/pycrates/io/dm_backend.py:140: UserWarning: File '/data/regression_test/master/in/sherpa/aref_Cedge.fits' does not have write permission.  Changing to read-only mode.
  warnings.warn("File '" + fname + "' does not have write permission.  Changing to read-only mode.")
/proj/xena/ciaod/Linux64/ciao_1021/lib/python2.7/site-packages/pycrates/io/dm_backend.py:140: UserWarning: File '/data/regression_test/master/in/sherpa/aref_sample.fits' does not have write permission.  Changing to read-only mode.
  warnings.warn("File '" + fname + "' does not have write permission.  Changing to read-only mode.").....
```

The files the test is trying to read in do not need to be edited, so this read-only mode shouldn't affect the results of the regression tests. I have write permissions to the files in `/data/regression_test/master/in/sherpa` and can confirm that files haven't been modified after running the tests.

The test in which these warnings pops up is in `sherpa/astro/sim/tests/test_astro_sim.py`. Specifically, the test calls `pragbayes.py:ARFSIMFacory.read()` method, which uses the `read_table_blocks()` method of the io backend. This function does not accept a mode string, neither in the pycrates nor in the pyfits implementations.

This was an issue that was brought up last year, but was never fixed. @olaurino had done some investigations into this issue last year, which is summarized here.

The `pycrates` backend uses the default Crates file open mode. Crates had changed the default file mode from "read-only" to "read-write" before CIAO 4.7. If a user chooses `pycrates` for I/O, and they open a read-only file in Sherpa, they will see this warning. The pyfits backend uses "read-only" mode for all of its functions.
#### Solutions

Here are two options for fixing the issue:
1.  We can avoid this warning in the CIAO sherpa regression tests by setting the file permissions to 'rw' for the files `sherpa-test-data/sherpatest/aref_Cedge.fits` and `aref_sample.fits`, or
2. we change the read_table_blocks method in the pycrates backend to always use the 'r' mode, hoping that nobody is relying on this method opening files in "rw" mode.

Sherpa version: 4.8.0+16.gecac9ec

More info (from @olaurino):

> The pragbayes.py:ARFSIMFacory.read() method uses the read_table_blocks() method of the io backend. This function does not accept a mode string, neither in the pycrates nor in the pyfits implementations.
> 
> One option would be to change the signature of the method to accept a mode string, but this should be done in both the crates and pyfits backends. However, the mode string options are not the same for pyfits and pycrates, so the API would be somewhat different for the two backends, although the signature would be the same. One might translate the common subset of options and homogenize the API, but this looks like too much of a change for just getting rid of a warning message that, by itself, is innocent, right?
> 
> It is interesting that the pyfits.open() method used by pyfits_backend has a readonly default mode. So, I was wondering whether I should just make 'r' the default in the crates backend as well. Of course the risk is that we break somebody's scripts if they use sherpa to open files they write to using the crates backend.
> 
> As we are not doing this because something is broken, but just to get rid of a new warning, I would suggest we just change the flags of the offending files without touching any code. Is there a chance something will be broken because of the changes in the dm code? It depends on the changes. As far as I understand, they just change the opening mode to 'r' when the file is not writable, and they issue a warning. If a user relied on sherpa to write files using the pycrates backend, and the file they wanted to write was readonly, then nothing should change: the weren't able to write the file before and they are not able to do it now.
> 
> In conclusion I would suggest that we either leave the code untouched, and we change the file permissions to avoid the warning, or we change the read_table_blocks() method in the pycrates backend to always use the 'r' mode, hoping that nobody is relying on this method opening files in "rw" mode.
> 
> If we really wanted to change the read_table_blocks() signature we should do it in both backend implementations, possibly translating the common mode options to have a consistent API, and then change the calls to read_table_blocks().

**Comment by jbudynk** [comment]
We should also inspect why we don't have read-write warnings from other tests.

**Comment by DougBurke** [comment]
I don't think the semantics of the crates mode='rw' are fully understood by people, so I strongly suggest going with updating the pycrates version of `read_table_blocks` to specify mode='r', as it is "the right thing to do". Changing the permissions of the files in the test suite feels like a hack that doesn't resolve the underlying issue.

I don't see how users could be relying on the mode="rw" behavior, unless they are doing something very strange, for which there is going to be a better way of doing things (i.e. I am okay with this change even if it does break some users workflow, as there should be a better way of doing whatever they are trying to do).

**Comment by DougBurke** [comment]
Can this issue be closed now, or are there still actions left outstanding?
