### ISSUE TITLE
Return output data from sherpa regression tests

### ISSUE THREAD

**Issue by jbudynk** [sherpa/sherpa#124]
It would be good to have the ability to store the output of individual Sherpa regression test results.

CIAO tool regression tests compare a baseline file (the expected output) against the actual output of a test. Right now, the Sherpa regression tests are compared against a baseline output file of the _screen_ output from running `sherpa.test(datadir=datadir)`. In other words, we compare the expected screen outputs against the resultant screen output of the whole test suite, e.g.:

```
  Found 7/7 tests for sherpa.astro.tests.test_datastack
  <more tests found>
  ...
....<more passes>....
. Solar Abundance Vector set to angr:  Anders E. & Grevesse N. Geochimica et Cosmochimica Acta 53, 197 (1989)
 Cross Section Table set to bcmc:  Balucinska-Church and McCammon, 1998
....<more passes>....

----------------------------------------------------------------------
Ran 287 tests in 191.836s

OK (skipped=1)
```

What would work better is to compare the actual expected test results to the output for each, individual regression test. Therefore, the Sherpa regression tests should at least provide the capability to store test output to file so that Sherpa can be tested in CIAO in the same way as other CIAO tools.

For example, `sherpa/astro/ui/tests/test_astro_ui.py::test_table()` could store a file for each loaded file; a baseline would be compared against the output test file.

Another example would be to output the fit results from `sherpa-test-data/sherpatest/ciao4.3/load_template_with_interpolation/fit.py`.

Note that we don't need this for unit tests.

Sherpa version: 4.8.0+16.gecac9ec

**Comment by olaurino** [comment]
@jbudynk, this was fixed by #210, right? Can we close it?
