### ISSUE TITLE
XSkerrconv parameter-name confusion

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1275]
We currently have

```python
>>> from sherpa.astro.xspec import XSkerrconv
>>> mdl = XSkerrconv()
>>> print(mdl)
xskerrconv
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   xskerrconv.Index frozen            3          -10           10
   xskerrconv.Index1 frozen            3          -10           10
   xskerrconv.r_br_g frozen            6            1          400
   xskerrconv.a thawed        0.998            0        0.998
   xskerrconv.Incl thawed           30            0           90        deg
   xskerrconv.Rin_ms frozen            1            1          400
   xskerrconv.Rout_ms frozen          400            1          400
```

From https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSmodelKerrconv.html we have parameter names:

```
par1
par2
par3
par4
par5
par6
par7
```

and from `local/heasoft-6.29/spectral/manager/model.dat` we have (the same with `heasoft-6.28`

```
kerrconv       7  0.         1.e20           C_spinconv  con  0
Index1   " "    3.    -10.    -10.    10.       10.       -0.1
Index2   " "    3.    -10.    -10.    10.       10.       -0.1
r_br_g " "    6.0   1.0     1.0     400.      400.      -0.1
a        " "    0.998 0.0     0.0     0.998     0.998      0.1
Incl    deg     30.   0.      0.      90.       90.       -1
Rin_ms  " "    1.0   1.0     1.0     400.      400.      -0.1
Rout_ms " "    400.  1.0     1.0     400.      400.      -0.1
```

that is the parameters should be called

```
Index1
Index2
r_br_g
a
Incl
Rin_ms
Rout_ms
```

Given that the convolution model support is new and there are still issues for models like this one that need an extended energy range I am tempted to just rename our parameters

    Index -> Index1
    Index1 -> Index2

This would be a breaking change for users of the model who have set the Index1 parameter, as it would now change meaning. I am willing to bet all of 5 cents that we have no-one who is affected by this,

**Comment by DougBurke** [comment]
@anetasie do you see a problem with renaming the parameters? It would cause problems for existing users but my bet is that there aren't many.

**Comment by anetasie** [comment]
@DougBurke ok to update the parameter name. Also, we could check with the author of the original model as she might be our user.
