### ISSUE TITLE
possible documentation mismatch for optimization methods

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#128]
Some docstrings for the optimization methods seem to be out of sync with the actual code. Most likely this happened because the code was changed at some point but the documentation was not, or only partially updated, resulting in the mismatch.

In particular, the docstrings claim that the default values for some parameters are the square root of the double precision epsilon, although this does not seem to be true, at least not for all of the optimization methods. For instance, in the `LevMar` method docstring it says that the default for `ftol` is `sqrt(DBL_EPSILON) ~ 1.19209289551e-07`. There are several issues with this:
  * `1.192..e-07` is not the double precision (assuming 64 bit floating point) epsilon, but the float32 one.
  * `1.192..e-07` is indeed the epsilon itself, not its square root.
  * the `LevMar` implementation seems to be using the float32 epsilon as its default, rather than its square root. So may other methods.

See https://github.com/sherpa/sherpa/blob/master/sherpa/optmethods/__init__.py#L351

vs

https://github.com/sherpa/sherpa/blob/master/sherpa/optmethods/optfcts.py#L37 and https://github.com/sherpa/sherpa/blob/master/sherpa/optmethods/optfcts.py#L368

**Comment by dtnguyen2** [comment]
Float epsilon is the correct value for LevMar cause the code takes the
square root internally, will double check code later cause I'm at the car
dealership bleeding money right now:(

However I'm sure I'm correct though

**Comment by olaurino** [comment]
> Float epsilon is the correct value for LevMar cause the code takes the square root internally

That's why the documentation is out of sync with the implementation: the default value passed to the function is the float32 epsilon.

On the other hand it may be confusing that the value passed to the Python function is not the one being used: if I want to change the default value, should I pass the value I want the optimization function to use? Or its squared value?
