### ISSUE TITLE
GIT not defined in sherpa/_version.py

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#13]
I get an error that GIT is not defined on this line when running `python setup.py build_ext --inplace`:
https://github.com/sherpa/sherpa/blame/master/sherpa/_version.py#L129

Can someone reproduce the issue?

(My git is at `/opt/local/bin/git` in case it matters.)

**Comment by taldcroft** [comment]
I saw this too.  I think that the setup process does something like rewriting _version.py.  AFAIK right now you can't run sherpa in place, it needs to be installed.

**Comment by cdeil** [comment]
@taldcroft – Thanks for confirming the issue.
For me `python setup.py install` doesn't work because of issue #15.

**Comment by olaurino** [comment]
I recently upgraded the versioneer code because of some issues with [PEP440](https://www.python.org/dev/peps/pep-0440/), but then I didn't upgrade the relative files. I'll create a PR with the required changes. Thanks for reporting this.

**Comment by olaurino** [comment]
By the way, the versioneer is in place to make sure that when reporting a bug, a simple `python setup.py version` allows users to pinpoint the version of sherpa they are using. If it is a release, then it will be the release version (git tag), otherwise we can tell exactly what commit was used to build Sherpa, and even if the working tree is dirty (i.e. there were uncommitted changes when sherpa was built).

**Comment by olaurino** [comment]
@cdeil for some strange reason we cannot reproduce this issue anymore, so we cannot test whether PR #21 actually fixes it or not.

Could you please confirm that: a) you can still reproduce the issue from the `master` branch with a clean working tree, and b) PR #21 actually solves the issue.

Thanks.

**Comment by DougBurke** [comment]
So, I can now replicate this error by starting ipython from within the top-level sherpa directory (that is, the one that contains `setup.py`, and fits in with the comments above that Sherpa is not yet able to be run in place). In this case a

    from sherpa.astro import ui

call will raise the `NameError`. With PR #21 I no longer get this error; instead I get the error message `ImportError: No module named _utils` from the line `from sherpa.utils._utils import *` in `sherpa/utils/__init__.py`. So, it looks like PR #21 fixes the reported problem but there's still more to do with getting it to work - which is being tracked in bug #14.

Note that in both cases (using `master` or PR #21), I can import sherpa as long as I start the python/ipython from outside the Sherpa tree.
