### ISSUE TITLE
several extensions (psf, region,  wcs) are not built

### ISSUE THREAD

**Issue by chaobin** [sherpa/sherpa#131]
The file system structure I work on are unique, and we have our own equivalent of pip. Installing sherpa, I discovered that the extensions defined in helpers/extensions/\_\_init\_\_.py although later added into distribution.ext_modules through config, are not built during the procedure of build_ext.

The current strategy in sherpa packaging, specifically, in the overrode cmd_build and subclassed build(), it tries to call sherpa_config.build_configure(), in which the self.distribution.ext_modules will get written in several extensions defined in helpers/extensions/\_\_init\_\_.py. But, since what's defined in ext_modules are processed in build_ext procedure, which in time precedes build procedure, the expanded part of ext_modules won't have the opportunity to get processed, hence, those extenions won't be built. This has ultimately resulted in sherpa.test() failure, with a ImportError on looking for _psf module while importing sherpa.utils.

In the effort of mine trying to get this to work for my purpose, I "rescheduled" this to happen in the very beginning of build_ext, and it worked.

**Comment by olaurino** [comment]
Thank you for your report. I do have a fix for this, but it got to the back burner because of either priorities. I'll try and post a PR fixing the issue as soon as possible.

I am glad you could find a workaround.

**Comment by chaobin** [comment]
Thanks!

**Comment by olaurino** [comment]
@chaobin could you please confirm #132 fixes your issue? I don't know what the specifics of your setup are, but the extensions that need to be dynamically configured are now being declared by the sherpa_config command, before the standard build_ext is run, so hopefully this addresses your problem.

Thanks.
