### ISSUE TITLE
How to select Fortran compiler for build?

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#134]
This is a continuation of the discussion here: https://github.com/sherpa/sherpa/issues/133#issuecomment-165149584

I'm using Macports which has the fortran compiler in `/opt/local/bin/gfortran-mp-5`.
I haven't tried running `sudo port select mp-gcc5` to add a symlink to `/opt/local/bin/gfortran` to make `gfortran` available on my `PATH`, because in the past that has let to build issues with other software I use.

So my preference would be to instruct the Sherpa build directly which Python and compiler to use, but I don't know how. Using `F77` doesn't seem to do the trick:

```
$ export F77=/opt/local/bin/gfortran-mp-5
$ export PYTHON=/opt/local/bin/python2.7
$ $PYTHON setup.py build
...
error: extension 'sherpa.optmethods._minpack' has Fortran sources but no Fortran compiler found
```

Full build log: https://gist.github.com/cdeil/d11ed1bb8a7e0e64fe3f

**Comment by olaurino** [comment]
I just made a test in an environment that should be close enough to yours (no gfortran in the PATH), and the following seemed to work:

`F90=/opt/local/bin/gfortran-mp-4.4 python setup.py build_ext --inplace`

So, the variable name should be `F90`, not `F77` as I told you earlier. My bad.

Please let me know if it works for you with `F90`.

**Comment by cdeil** [comment]
@olaurino - Yes, specifying `F90` worked perfectly ... build and sherpa_test now works for me ... thank you!

Full build log: https://gist.github.com/cdeil/4e5d6e187399212fdb61

Doesn't look like F90 is mentioned in any end-user docs:
https://github.com/sherpa/sherpa/search?utf8=%E2%9C%93&q=f90

Worth adding this info somewhere?

**Comment by olaurino** [comment]
I'll remove the `build` label, it's now just a matter of documentation.

**Comment by cdeil** [comment]
@olaurino - Sherpa doesn't have any more Fortran code, so this issue is resolved, no? Close?

**Comment by olaurino** [comment]
Close!
