### ISSUE TITLE
handling of missing io 

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1354]
I have a build with no I/O library available - i.e. no crates, no astropy - and so we get

```
>>> from sherpa.astro.ui import *
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.plot.pylab_backend; plotting routines will not be available
WARNING: failed to import sherpa.astro.io; FITS I/O routines will not be available
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available
>>> load_arrays(1, [1, 2, 3], [4, 2, -1])
>>> save_table('x.dat', ascii=True, clobber=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in save_table
  File "/home/dburke/sherpa/sherpa-main/sherpa/astro/ui/utils.py", line 5048, in save_table
    sherpa.astro.io.write_table(filename, self.get_data(id),
AttributeError: module 'sherpa.astro' has no attribute 'io'
```

The error message is less-than ideal for the user and we could provide a warning (say), or just raise an error that is a bit-more explicit. I'm thinking an error because script users want to know they haven't been able to write out a file, rather than maybe missing a warning about there being no I/O library.

There's also a slight discrepancy with the initial warning message - it says "FITS I/O routines not available" but here I'm trying to write out an ASCII file.

This will likely change with #1185 as we would have the dummy backend. So we won't get a "no attribute 'io'" error, but what will it say here?

**Comment by hamogu** [comment]
Look at line 43 in https://github.com/sherpa/sherpa/pull/1185/files#diff-4bfbe98652c54c34fbcaa673f76567e565cc42507c3b6f37af245a71e8b2bb5e

Any attempt to call IO routince will `raise NotImplementedError('No usable I/O backend was imported.')`. So I think this is fully addressed by #1185. (I'll tweak the wording of the warning that the use will get initially to reflect that fact that it's not just FITS IO, but all IO that's unavailable.)
