### ISSUE TITLE
delete_model_component currently requires a string; it could also take the component

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1357]
In #1353 I'm adding a test

```python
def test_delete_model_component_invalid_argument():
    """We could allow the component to be deleted this way"""
 
    s = Session()
    s._add_model_types(sherpa.models.basic)

    tst = s.create_model_component('gauss1d', 'gmdl')

    with pytest.raises(ArgumentTypeErr) as te:
        s.delete_model_component(tst)

    assert str(te.value) == "'name' must be a string"```
```

but as I note, we could allow a user to call `delete_model_component` this way.

It would be a bit odd, as

```python
delete_model_component(tst)
print(tst)
```

would error out as `tst` would no-longer be defined, but maybe that's okay (**edit** actually, would need to check this).

Given the way the code works, we can't actually "properly" delete things - here this is with the `main` branch

```
>>> from sherpa import ui
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.plot.pylab_backend; plotting routines will not be available
>>> gmdl = ui.create_model_component('gauss1d', 'foo')
>>> print(gmdl)
gauss1d.foo
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   foo.fwhm     thawed           10  1.17549e-38  3.40282e+38
   foo.pos      thawed            0 -3.40282e+38  3.40282e+38
   foo.ampl     thawed            1 -3.40282e+38  3.40282e+38
>>> print(foo)
gauss1d.foo
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   foo.fwhm     thawed           10  1.17549e-38  3.40282e+38
   foo.pos      thawed            0 -3.40282e+38  3.40282e+38
   foo.ampl     thawed            1 -3.40282e+38  3.40282e+38
>>> ui.list_model_components()
['foo']
>>> ui.delete_model_component('foo')
>>> ui.list_model_components()
[]
>>> print(foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'foo' is not defined
>>> print(gmdl)
gauss1d.foo
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   foo.fwhm     thawed           10  1.17549e-38  3.40282e+38
   foo.pos      thawed            0 -3.40282e+38  3.40282e+38
   foo.ampl     thawed            1 -3.40282e+38  3.40282e+38
```

Note that `gmdl` still exists. I don't think it's worth trying to "fix" this sort of thing,

**Comment by hamogu** [comment]
I agree no need to fix what @DougBurke raised in the last comment - Python will garbage collect it when it gets out of scope and no reference exists any longer. So, we do need a way to remove it from the session objects, but we can leave the rest to Python. (Of course, the session objects are mostly used interactively and then the scope only ends when the interpreter is shut down, but I know that some people also use the UI for scripting.)

In general though, I think it's good for us to allow users to use the Python objects seamlessly. We do that the OO interface that can be used, but I also sometimes mix things. In that case, it's convenient to be able to use the Python object here interchangeably with the string label. so :+1: to the issue in general. (Although it's not a high priority IMO).

**Comment by DougBurke** [comment]
I'm going to close this for now.
