### ISSUE TITLE
make "save_source" compatible with marx

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#136]
Sherpa now seems to provide a function to save a source spectrum in the three-column format used by SAOTrace / Chart.
This is very similar to the format he MARX uses which is a 2 column format "energ_hi, flux" (see http://space.mit.edu/cxc/marx/indetail/models.html#parameter-SpectrumFile for more details).
In the current marx handbook, I recommend to write a sherpa spectrum with `save_arrays`, which is not as easy as it could be - as detailed in http://space.mit.edu/cxc/marx/examples/LETGpow/letgplaw.html#creating-sherpa-spectrum or http://cxc.harvard.edu/sherpa/threads/marx/ .

I want to suggest to add a switch to the `save_source` of the type "format=[Chart | SAOTRACE | MARX | .. other idea you might have ...]"
Alternatively, I welcome suggestions if you have a simpler way to generate the MARX input from Sherpa.

I tried to find where `save_source` function is defined to issue a PR, but `sherpa> save_source?` only told me it's dynamically generated and a grep through the source did not turn up anything else either.

**Comment by olaurino** [comment]
@hamogu thanks for the request.

If you still wanted to issue a PR, the method is located in `sherpa/astro/utils.py`. A wrapper function is generated on the fly when running sherpa from CIAO or when importing `sherpa.astro.ui`. Otherwise it is a regular method of the `sherpa.astro.ui.utils.Session` class.

**Comment by hamogu** [comment]
I don't see a `utils.py` in https://github.com/sherpa/sherpa/tree/master/sherpa/astro .
Do you mean https://github.com/sherpa/sherpa/blob/master/sherpa/astro/utils/__init__.py ?
I cannot find the method there either...

I found the method in https://github.com/sherpa/sherpa/blob/master/sherpa/astro/ui/utils.py#L3490 but the "Notes" section there indicates that it writes only two columns (X, SOURCE) not three as required by SAOTrace/Chart. (Since MARX wants two columns, maybe I don't have to do anything?

There is a DOC-NOTE: "also in sherpa.utils with a different API" but I don't understand how the code gets there. It's not in "sherpa/utils" .

**Comment by olaurino** [comment]
@hamogu sorry for the typo. You are right about the location of the method.

I'll have to check the tests/code and match them with the docs. Unless @DougBurke or @anetasie know the answer right away.

**Comment by anetasie** [comment]
@hamogu Are you referring to `save_chart_spectrum`?
This is the part of ciao contributed script, so not present in the sherpa code. Here is the doc file and @DougBurke should know the location.
<http://cxc.harvard.edu/sherpa/ahelp/save_chart_spectrum.html>

**Comment by hamogu** [comment]
Yes, that is the function I'm referring to. I'll close this issue now that I learned that it's not Sherpa code.

**Comment by DougBurke** [comment]
For reference, the contrib stuff can be found at
https://github.com/cxcsds/ciao-contrib

I can't remember now if I ever added an issue there for this
