### ISSUE TITLE
AttributeError: 'DataIMGInt' object has no attribute 'x0lo'

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#1379]
I'm checking the Sherpa/CIAO bug list and the advice for fitting `delta2d` model is to change the `dstype` to `DataIMGInt` or `Data2DInt`. In both cases I get the AttributeError in CIAO 4.14. The error is also thrown after reading fits image data.

```
-----------------------------------------------------
Welcome to Sherpa: CXC's Modeling and Fitting Package
-----------------------------------------------------
Sherpa 4.14.0

Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: sherpa
Using matplotlib backend: MacOSX

sherpa In [1]: dataspace2d([100,100], dstype=DataIMGInt)

sherpa In [2]: show_data()
AttributeError: 'DataIMGInt' object has no attribute 'x0lo'

sherpa In [3]: dataspace2d([100,100], dstype=Data2dInt)
NameError: name 'Data2dInt' is not defined

sherpa In [4]: dataspace2d([100,100], dstype=Data2DInt)

sherpa In [5]: show_data()
AttributeError: 'Data2DInt' object has no attribute 'x0lo'
```

Here is the link to the delta2d issue:
https://cxc.harvard.edu/sherpa/bugs/delta2d.html

**Comment by DougBurke** [comment]
The `*Int` classes for the 2D case have seen essentially no testing or use, so it doesn't surprise me things don't work well.

**Comment by DougBurke** [comment]
My guess is that something in #614 caused this. I'm trying to set up some tests to work out what is going on.

**Comment by DougBurke** [comment]
Just to note - unrelated to this bug - that using Data2DInt/DataIMGInt doesn't really help. As with the Delta1D case for PHA data, the problem is that within a single bin/pixel the model evaluates to a constant, so the optimiser can't improve the fit.
