### ISSUE TITLE
issues with contours

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#1380]
I'm looking at the coordinates and contour issues which have been listed on the CIAO Sherpa web site
https://cxc.harvard.edu/sherpa/bugs/contour.html

In CIAO 4.14 after setting coordinates to 'world' and resetting back to 'physical' results in an error. The contours are plotted ok before any `set_coord` updates. In the example below the first contour('data') is shown, the rest shows the errors:

```
herpa
-----------------------------------------------------
Welcome to Sherpa: CXC's Modeling and Fitting Package
-----------------------------------------------------
Sherpa 4.14.0

Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:50:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: sherpa
Using matplotlib backend: MacOSX

sherpa In [1]: load_data('/Users/aneta/git/sherpa-test-data/sherpatest/image2.fits')

sherpa In [2]: show_data()

sherpa In [3]: contour('data')

sherpa In [4]: set_coord('logical')

sherpa In [5]: contour('data')

sherpa In [6]: set_coord('world')

sherpa In [7]: contour('data')
NotImplementedErr: contours on non-uniform grids are not yet supported

sherpa In [8]: set_coord('logical')

sherpa In [9]: contour('data')
NotImplementedErr: contours on non-uniform grids are not yet supported

sherpa In [10]: set_coord('physical')

sherpa In [11]: contour('data')
NotImplementedErr: contours on non-uniform grids are not yet supported

```

**Comment by DougBurke** [comment]
In the following I would expect `args1` to be the same as `args4` as they are both created with the `logical` coordinate setting, but they're not, which leads to the behavior above.

```
In [24]: load_image("sherpa-test-data/sherpatest/image2.fits")

In [25]: data = get_data()

In [26]: data
Out[26]: <DataIMG data set instance 'sherpa-test-data/sherpatest/image2.fits'>

In [27]: data.coord
Out[27]: 'logical'

In [28]: args1 = data.to_contour()

In [29]: set_coord("physical")

In [30]: data.coord
Out[30]: 'physical'

In [31]: args2 = data.to_contour()

In [32]: set_coord("world")

In [33]: data.coord
Out[33]: 'world'

In [34]: args3 = data.to_contour()

In [35]: set_coord("logical")
In [36]: data.coord
Out[36]: 'logical'

In [37]: args4 = data.to_contour()

In [38]: (args1[0] == args4[0]).all()
Out[38]: False
```

So why are they not the same? Hmmm.

**Comment by DougBurke** [comment]
I think it's because - to save memory - we don't store the axis values for all three types of coordinate (logical, physical, and world), and instead create the values we want based on the previous setting. So changing

    logical -> physical -> world -> logical

means we change logical to physical to world then back to logical. This leads to small numerical differences, which causes the contour problem.

**Comment by hamogu** [comment]
It sounds as if we should not ever convert the stored values, but instead keep one canonical system (say, logical) and then calculate other coordinates on the fly as needed. 
Now, I have not looked at the code, so I don't know if that's an easy or a hard change to make, but conceptually that should work.

**Comment by DougBurke** [comment]
The code mentions 

        # Destroys original data to conserve memory for big imgs

but I don't think we have to be constrained by this particular comment. Supporting a canonical system should be possible, just a little bit of plumbing.

**Comment by hamogu** [comment]
Without looking at the code this might be a moot point, but we **might** want to look at something like the astropy WCS object (or even making astropy a dependency for image and contour plotting in non-local coordinates and just use **the** astropy WCS object) that holds the transformation matrices between coordinates, but not an array of coordinates.

(If we use astropy, we also get the WCXAxis object: https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html. Not saying that's the only possible option, but it might be an easy option).

**Comment by DougBurke** [comment]
We already have a WCS system in place. It is not as complete as the astropy object, but it does what we need it to do.

The use of the Astropy WCS object depends on the capabilities of the plot backend, so I wouldn't want to assume it will just work. This is only an issue if I were talking to someone who was pushing for a new plot backend....

**Comment by hamogu** [comment]
As that someone, I want to note that the astropy WCS object (similar to ours https://docs.astropy.org/en/stable/api/astropy.wcs.WCS.html#astropy.wcs.WCS) is different from the matplotlib AXIS object (https://docs.astropy.org/en/stable/visualization/wcsaxes/index.html). Anyway, we are discussion Sherpa here and not astropy, so I'll shut up.
