### ISSUE TITLE
python setup.py develop not transparent to the user

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#14]
When I work around issue #13, then `python2.7 setup.py build_ext --inplace` succeeds, but on import I get this error:
```
$ python2.7 -c 'import sherpa.all'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "sherpa/all.py", line 35, in <module>
    from sherpa.data import *
  File "sherpa/data.py", line 29, in <module>
    from sherpa.utils.err import DataErr, NotImplementedErr
  File "sherpa/utils/__init__.py", line 37, in <module>
    from sherpa.utils._psf import extract_kernel, normalize, set_origin, \
ImportError: No module named _psf
```
Most extension modules are created OK, but for some reason `_psf.so` is not:
```
$ find . -name '*.so'
./sherpa/astro/models/_modelfcts.so
./sherpa/astro/utils/_pileup.so
./sherpa/astro/utils/_utils.so
./sherpa/estmethods/_est_funcs.so
./sherpa/models/_modelfcts.so
./sherpa/optmethods/_minim.so
./sherpa/optmethods/_minpack.so
./sherpa/optmethods/_saoopt.so
./sherpa/optmethods/_tstoptfct.so
./sherpa/stats/_statfcts.so
./sherpa/utils/_utils.so
./sherpa/utils/integration.so
```
Maybe there's an issue how the extensions to build are defined here?
https://github.com/sherpa/sherpa/blob/master/helpers/extensions/__init__.py

**Comment by cdeil** [comment]
The issue is that for `python setup.py build_ext --inplace`, the `sherpa_config.build_configure` method [here](https://github.com/sherpa/sherpa/blob/c9f412a3c3d0a193ba5a65027f7630f058fe41a5/helpers/sherpa_config.py#L99) is never called, which appends the `psf` and some other extensions to `ext_modules`:
```python
            self.distribution.ext_modules.append(build_ext('psf', *build_lib_arrays(self, 'fftw')))
            self.distribution.ext_modules.append(build_ext('wcs', *build_lib_arrays(self, 'wcs')))
```
Following the advice of @taldcroft at https://github.com/sherpa/sherpa/issues/15#issuecomment-96344670 and https://github.com/sherpa/sherpa/issues/13#issuecomment-96285505 I'll now try to get `python setup.py install` working in a Conda environment for Sherpa development.

But it would be nice if in the future someone could make `python setup.py build_ext --inplace` and thus `python setup.py develop` work.

**Comment by olaurino** [comment]
You need to add the `sherpa_config` command in order to have all of the extensions built.

This seems to work for me:
`python setup.py sherpa_config build_ext --inplace`

After that, I can also `python setup.py develop`, although the `stack` extension does not get installed automatically.

I will take this ticket as a request to make `python setup.py develop` work transparently, which will include making sure that the external python extensions are correctly installed.

**Comment by cdeil** [comment]
@olaurino – I just now tried again, and now installing Sherpa and `sherpa_test` work for me with my normal Python environment (Macports), which is convenient for me. Thank you!
