### ISSUE TITLE
Do we warn every time a plot is not created because the dummy backend is active?

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1409]
From: https://github.com/sherpa/sherpa/pull/1191#issuecomment-1018887551

```
>>> plot.backend.name
'dummy'
>>> from sherpa.astro.ui import *
WARNING: imaging routines will not be available,
failed to import sherpa.image.ds9_backend due to
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
>>> load_arrays(1, [1, 2, 3], [4, 5, 6])
>>> set_source(const1d.foo)
>>> plot_fit()
>>>
```
The plot_fit command has returned but there's no indication to the user that it hasn't done anything.

Issue 1 is easy to address, with a tweak to the warning message. I am not-at-all-sure we should do anything about point 2 for various reasons, including-but-not-limited-to

 -   causing the plot_xxx commands to error out would be annoying (e.g it would make it hard to run scripts when you have no plot backend available); technically also we'd probably want the error to be raised by the plot object's plot method rather than in the UI plot_xxx routine
 -   creating a warning message each time a plot_xxx command is called (or, the plot object's plot method is called) would get old real quickly

**Comment by anetasie** [comment]
Is there a way to include a meaningful message in the warning to say what needs to be done in order to display the plots on the screen. For example that one could use ` %matplotlib`, I'm sure there are other ways depending on backend setup.

**Comment by hamogu** [comment]
The message should be specific to the backend. In matplotlib the answer is "install matplotlib if you don't have it" (`%matplotlib` only works in the notebook and only if matplotlib is already installed). But yes, a good message should be actionable. It might be "check [URL here] docs for details".

**Comment by DougBurke** [comment]
One question is whether such a warning appears once or every time.

**Comment by hamogu** [comment]
With #1382 merged, I feel this has been addressed.
