### ISSUE TITLE
calc_stat_info broken with wstat

### ISSUE THREAD

**Issue by joleroi** [sherpa/sherpa#147]
I would like to use WStat for gammapy.  The latest dev version I find with Anaconda is ``4.7+524.g2d013d1``. It does not have Wstat, though.

Would it be possible to release a new dev version?

**Comment by DougBurke** [comment]
We are working through setting up an anaconda version of the `release/4.8.0` branch. The current plan is to have this done by the end of January.

**Comment by olaurino** [comment]
@joleroi if you want to try the release candidate (I can't guarantee it will be the final cut) you can use the binaries in the test channel:
conda install -c http://conda.anaconda.org/sherpa/channel/test sherpa

**Comment by joleroi** [comment]
Thank you very much! 

No the following problem appeared. I am trying to run the PHA intro (http://cxc.harvard.edu/sherpa/threads/pha_intro/) using WStat with the following script.

```
import sherpa.astro.ui as sau

sau.load_pha("3c273.pi")
sau.set_source(sau.powlaw1d.p1)
sau.guess(p1)
sau.set_stat("wstat")
sau.fit()
stats = sau.get_stat_info()
```
Which gives this error
```
Traceback (most recent call last):
  File "fit_wstat.py", line 8, in <module>
    stats = sau.get_stat_info()
  File "<string>", line 1, in get_stat_info
  File "/home/kingj/Software/miniconda3/envs/sherpadev/lib/python2.7/site-packages/sherpa/ui/utils.py", line 7549, in get_stat_info
    return self._get_stat_info()
  File "/home/kingj/Software/miniconda3/envs/sherpadev/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", line 9411, in _get_stat_info
    statinfo = f.calc_stat_info()
  File "/home/kingj/Software/miniconda3/envs/sherpadev/lib/python2.7/site-packages/sherpa/fit.py", line 1058, in calc_stat_info
    stat, fvec = self.stat.calc_stat(dep, model, staterror, syserror)
  File "/home/kingj/Software/miniconda3/envs/sherpadev/lib/python2.7/site-packages/sherpa/stats/__init__.py", line 594, in calc_stat
    raise StatErr('usecstat')
sherpa.utils.err.StatErr: No background data has been supplied. Use cstat
```

**Comment by DougBurke** [comment]
The problem here is that `wstat` needs a background dataset. It is likely that the `3c273.pi` file doesn't have a `BACKFILE` keyword (or, if it does, it points to a missing file). If you have a background file for the data set then you can use

    sau.load_bkg(filename)

or fix up the `BACKFILE` keyword in `3x273.pi` and re-issue the `sau.load_pha()` call.

**Comment by joleroi** [comment]
I am pretty sure the background file is properly loaded (see last line)

```
In [2]: sau.load_pha("3c273.pi")
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi
```

**Comment by olaurino** [comment]
@joleroi I can reproduce your issue and I am investigating.

**Comment by olaurino** [comment]
@joleroi I believe I have a fix. In the meantime, you can try just avoiding using `calc_stat_info`. This method is not propagating the background information introduced with wstat, but methods like `fit` and `calc_stat` seem to be working properly.

Please let me know if you have other questions. I'll let you know when we have patched binaries.

**Comment by joleroi** [comment]
@olaurino Indeed, everything I personally need works fine. I just wanted to let you know that there is a potential problem (which seems to have proven true). Thanks for your help!
