### ISSUE TITLE
How to add validation to the data objects?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1470]
# Why validate?

The idea is that if we can ensure that the fields of the `Data`
objects obey certain constraints - such as they have the same length,
are one dimensional, or have a certain type - then the code is easier
to write and the user will not see errors that can be hard to
understand.

The aim is to ensure that the fields match, and that changes made to
the object - such as a filter - make sense. There is already some
validation in place (mainly ensuring that some fields are converted to
NumPy arrays), so the question becomes how much should we do?  I focus
here on the Data class, and those classes that it uses, although there
may be some related work that could be done for other classes.

## Terminology

I am going to try to use the term sequence for an array-like object.
In actuality we will use a NumPy ndarray for these but users can
supply any sequence-like object. Similarly I shall try to use field to
refer to an element of the data object, but sometimes will also use
axis.

For this document I will use the terms independent and dependent axes.
The code also uses terms like `x`, `x0`, `xlo`, `x0lo` for the
independent axis and `y` for the dependent axis. The error axes, or
fields, are `staterror` and `syserror`: these are referred to as
related fields. The `mask` field should also be considered a related
field and has a the ability to be a scalar, in this case a boolean, or
a sequence.

The PHA class also adds a number of related fields, such as grouping,
quality, and the "scaling" fields (`areascal` and `backscal`). Some of
these fields can be scalars or sequences.

## Constraints from the current design

The current design requires the independent and dependent axes to be
specified when creating a `Data` object, but they can be set to
`None`.  This means that it is possible to "build up" a data object,
rather than enforcing the constraints when `__init__` is called. The
argments for the independent and dependent axes are assumed to be
one-dimensional sequences, and the independent axis uses a tuple to
store the different components, such as the low and high edges for the
"integrated" data set and the two dimensions for the 2D case.

Users can change fields either wholesale - that is, replace the
`staterror` field with this sequence or set the `syserror` field to
`None` - or by direct manipulation of the elements of the sequence.

**Question** Supporting multi-dimensional arguments

#1446

The whole design of Sherpa is around one-dimensional sequences of the
independent and dependent axes. This allows us to think about working
on a point in the data space at a time, and just looping over the
sequence of points, and is built in to how we handle filters.

Should we allow 2D data values to be sent in when setting fields for
2D data sets? The code would internally flatten the values.

This should be possible but I have not looked at it yet.

**Question** Should a data object know what dimension it is?

#1460

Recent work added a `ndim` attribute to model classes so that we can
ensure we do not combine 1D and 2D models. Should we do something
similar so that we ensure the dimensions of the model and data object
match?

I believe we should.

**Question** Should a data object know if it is integrated or not?

Similar to knowing it's dimensionality, should the data object know
whether it contains an integrated data set or not? This is tied into
how the integrate flag of models is to be handled.

If we have implemented the dimension check, then a 1D integrated data
object can not be used with a 2D un-integrated model, or a 2D data
object used with a 1D integrated model, so it's not immediately
obvious whether this would benefit us. I do think there are issues
where this might be helpful, but that requires more research and
thinking about how to represent the independent axes beyound just
using a tuple.

**Question** Should we require the independent and dependent axes to be set in `__init__`?

The `fake_pha` routine currently creates an "empty" `DataPHA` object which
it then fills in. I have not looked at how much work it would take to
re-work this. There is also a question of whether we should only require
the independent axis in the initializer.

My suggestion is that we do not enforce this constraint.

If we were to implement this suggestion I suggest only requiring the
independent axis be set when calling `__init__`. This would simplify
some checks as the object size would always be known (assuming we
require the size be fixed).

**Question** What defines the "size" of a data object?

Two obvious suggestions are

1. the independent axis sets the size of the object
2. the first field - whether independent, dependent, or one of the
   related fields - that is set defines the size

In most cases it is not expected to matter, in that the independent
axis is most-likely to be set first, but it can lead to issues about
how we define the size of a dataset in error messages: is it just a
generic "data size" comment or do we say "the independent axis"?

**Question** Should a data object be fixed in size once set?

If not, then we have to decide how a used can change the size of the
object, and what should happen when it is changed (e.g. do we
invalidate all the fields)?

I believe that once the object size is set, however it is decided by
the answer to the previous question, it should not be possible to
change it. The idea is that the size of the object in some sense
defines the object, and so it should not be changed. This then
simplifies the code since we do not have to worry about what happens
if a user tries to change the size.

I am slightly concerned that this could stop certain approaches, where
a Data object can be passed around and then worked on. However, the
only classes that carry around sufficient metadata that we might want
to do this are ones where the metadata is highly-dependent on the size
of the object (e.g. PHA values are strongly dependent on the number of
channels and WCS data relies on pixel size and coordinates).

Note that the `DataPHA` class complicates the understanding of this,
since by changing the grouping column a user can change the effective
size of the data, even though the number of channels has not changed.

**Question** what fields can be cleared?

We definitely want to allow the related fields to be cleared - for
example, removing the systematic error values - but do we want the
dependent or independent axis to be cleared? This is related to the
previous question.

**Question** what are stored in fields?

Should we convert fields to NumPy ndarray objects on input? Originally
we did not, but then we had code that would fail if a user had used a
list. This lead to some code converting values to a ndarray in places,
but it was hap-hazard. The data class rework by Omar in #614 and then
follow up work by Moritz in #793 did add some conversion to ndarray,
but only for the independent and dependent axes.

I suggest we ensure all the fields are ndarray values.

We have code that warns users that we are converting to ndarray,
but only for some fields. My suggestion is that we remove this
warning as we can document the conversion.

One issue becomes whether we always copy the input argument or not?
This partly depends on questions below.

**Question** What about NumPy masked arrays?

Moritz added basic support for masked arrays in #793, but only to
essentially warn users. We could use the idea of the quality field
from the PHA class to support masked arrays, but would then need to
decide how to handle situations like:

1. if the statistical error column has different masked values to
   the dependent axis, do they combine
2. if the masked fields are changed, what happens

I do not use masked arrays and so am not suggesting any changes
here. I feel that they could be added afterwards, if needed, and I am
guessuing they do not really add any new issues to this work.

**Question** Should the independent axis be read-only?

NumPy arrays let you change a subset of the elements, unless you
explictly mark the array as read-only. The advantage of doing this is
that it forces any attempt to change the independent axis to do so by
changing the whole field, which will trigger the setter property for
the independent axis. This means we can do things like "reset the
mask" if the independent axis is changed.

I suggest we make the independent axis read-only. However, there are
some surprising parts of the code that may need to be re-worked
because of this (for instance, we use 2D objects to handle 1D PSF
cases, which seems sub-optimal).

This means that we would always explcitily copy the independent axis,
as we don't want to change the input argument to read-only mode.

**Question** Should we ensure the independent axes are "sensible"?

At the moment you can have things like the independent axis
being un-sorted:

```python
data = Data1D('x', [1, -5, 3, 2, 15], ...)
```

or the low and high edges not being sensible

```python
data = Data1DInt('x', [10, 20, 30], [22, 15, 30])
```

It would be nice to catch these, but

- although parts of our system prefer the values to be sorted, such
  as plotting, most parts of the system do not
- support for n>=2 dimensions means we can't enforce sorted axes
- technically we can allow overlapping integrated bins, even if this
  means they are no-longer independent

I would like to add such checks - at least for the integrated axes -
but I think this needs more thought and can be done in the future.

**Question** What happens when the independent axis is changed?

One option is that when the independent axis is changed we clear out
all the other fields. For instance, if the data has been partially
filtered then if the independent axis has changed then the mask
is no-longer valid, so should be cleared.

Surprisingly enough the main problem here is the `DataIMG` class, not
`DataPHA`. The coordinate handling means that the independent axis
gets changed whenever the coordinate setting is changed. Now, given
that the region filter currently is not changed to match the new
coordinate setting, technically it's correct to clear out the mask,
but it is surprising.

There are changes we could make to allow the 2D filter expression to
be updated to match the new coordinate system (at least for non-WCS
systems), but it would require extensive additions to the region
library code (there have been changes in CIAO that would allow this
but we don't provide any of this in the existing region OTS code).
Similarly we could change the notice/ignore system to record the
ranges requested so we can re-apply them to a new independent axis,
but previous attempts to do this have not been successful and it's not
clear if it is worth it.

If we have made the independent axis read-only then things get a bit
simpler, as we can know whether the independent axis has changed or
not, and so whether these mask/region filters should be cleared.

**Question** What happens when the dependent axis is changed?

If a user changes the dependent axis - say from `[1, 2, 3]` to `[3, 2,
7]` - then should the statistical error column be cleared?  What about
the systematic error? For the PHA case, should the grouping column be
cleared?

My suggestion is that we do not do anything special here.

**Question** Should we make the dependent axis and related fields be read-only?

This is similar to the independent axis quesiton, but I think it's
less clear-cut here, as do we want to change something like

```python
data.mask[idx] = False
```

to

```python
newmask = data.mask.copy()
newmask[idx] = False
data.mask = newmask
```

This would be very helpful fom the validation viewpoint, as it would
help to ensure that the object remains consistent. For example, the
mask created by a set of `notice` and `ignore` calls depends on the
independent axis, so if this changes we should really replace the mask.

Unfortunately I think that this would hinder some potential use cases,
and would not solve everything.

My suggestion is that we do not do this at this time.

**Question** notice handling for 2D data sets

In looking at the code I have seen that we have existing questions
about how notice/ignore should work for the 2D case.

I am currently ignoring this as I don't think it's relevant to this
work.

**Question** Should we support grouping outside of the PHA class

#1450

We could move the idea for grouping support to the `Data` class
from `DataPHA`.

I don't think this changes this work, as we need to support grouping
anyway.

**Question** Should we support quality outside of the PHA class

#1449

We could move the idea for quality support to the `Data` class
from `DataPHA`.

I don't think this changes this work, as we need to support quality
anyway. There might be a reason to do this if we added support for
NumPy masked arrays.

**Question** Should we support background datasets outside of the PHA class

#1466

We could move the idea for background datasets to the `Data` class
from `DataPHA`.

I don't think this changes this work, as we need to support grouping
anyway.

**Question** Should the API be cleaned up?

There are a number of ways of getting and setting information that
are essentially duplicates. Should we decide which ones we want to
keep and deprecate the other methods?

I have not spent any time on this as it can be done separately
from the validation work.

---

# Object hierarchy

This is the rough class diagram, where I try to point out those
methods that are re-defined in sub-classes. Not all attributes are
included (for example, there are many methods in the `DataPHA` class
related to the response, and the response classes are not really
looked at here). I'm also not using UML properly here.

```mermaid
  classDiagram
      NoNewAttributesAfterInit <|-- Data
      NoNewAttributesAfterInit <|-- DataSimulFit
      BaseData <|-- Data
	  Data <|-- Data1D
	  Data <|-- Data2D
	  Data1D <|-- Data1DAsymmetricErrors
	  Data1D <|-- Data1DInt
	  Data2D <|-- Data2DInt
	  Data1DInt <|-- DataOgipResponse
	  DataOgipResponse <|-- DataARF
	  DataOgipResponse <|-- DataRMF
	  DataRMF <|-- DataRosatRMF
	  Data1D <|-- DataPHA
	  Data2D <|-- DataIMG
	  DataIMG <|-- DataIMGInt

	  DataSpaceND
	  EvaluationSpace1D <|-- DataSpace1D
	  EvaluationSpace1D <|-- IntegratedDataSpace1D
	  DataSpace2D
	  IntegratedDataSpace2D

	  class Data {
	      name
	      _data_space DataSpaceND
		  y
		  staterror
		  syserror
		  mask()
		  indep()
		  dep()
		  get_dims()
		  get_indep()
		  set_indep()
		  get_dep()
		  set_dep()
		  get_y()
		  get_staterror()
		  get_syserror()
		  get_error()
          get_yerr()
		  get_ylabel()
		  apply_filter()
		  notice()
		  ignore()
		  eval_model()
		  eval_model_to_fit()
		  to_guess()
		  to_fit()
	  }

	  class DataSimulFit {
          name
		  datasets
		  numcores
		  eval_model_to_fit()
		  to_fit()
		  to_plot()
	  }

	  class Data1D {
	      _data_space DataSpace1D
		  get_x()
		  get_xerr()
		  get_xlabel()
		  get_dims()
		  get_y()
		  get_bounding_mask()
		  get_img()
		  get_imgerr()
		  get_filter()
		  get_filter_expr()
		  to_plot()
		  to_component_plot()
		  get_evaluation_indep()
		  notice()
		  x
      }
	  class Data1DInt {
	      _data_space IntegratedDataSpace1D
		  get_x()
		  get_xerr()
		  get_filter()
		  notice()
		  xlo
		  xhi
      }
	  class Data2D {
	      _data_space DataSpace2D
		  shape
		  get_x0()
		  get_x1()
		  get_x0label()
		  get_x1label()
		  get_axes()
		  get_dims()
		  get_filter_expr()
		  get_filter()
		  get_max_pos()
	      get_img()
	      get_imgerr()
		  to_contour()
		  notice()
		  x0
		  x1
      }
	  class Data2DInt {
	      _data_space IntegratedDataSpace2D
		  shape
		  get_x0()
		  get_x1()
		  notice()
		  x0lo
		  x0hi
		  x1lo
		  x1hi
      }
	  class DataIMG {
	      sky
		  eqpos
	      coord
		  get_logical()
		  get_physical()
		  get_world()
		  get_image()
		  get_wcs()
		  set_coord()
		  get_filter_expr()
		  get_filter()
		  notice2d()
		  get_bounding_mask()
		  get_img()
		  get_axes()
		  get_x0label()
		  get_x1label()
		  to_contour()
		  filter_region()
	  }
	  class DataIMGInt {
	      _data_space IntegratedDataSpace2D
		  get_x0()
		  get_x1()
		  x0lo
		  x0hi
		  x1lo
		  x1hi
		  get_logical()
		  get_physical()
		  get_world()
		  get_axes()
      }

	  class Data1DAsymmetricErrors {
	      elo
		  ehi
		  get_yerr()
      }

	  class DataPHA {
	      channel()
		  counts()
	      bin_lo
		  bin_hi
		  quality
		  grouping
		  backscal
		  areascal
		  grouped()
		  subtracted()
		  units()
		  get_indep()
		  get_backscal()
		  get_areascal()
		  apply_filter()
		  apply_grouping()
		  ignore_bad()
		  eval_model()
		  eval_model_to_fit()
		  get_dep()
		  set_dep()
		  get_staterror()
		  get_syserror()
		  get_x()
		  get_xlabel()
          get_y()
		  get_yerr()
		  get_xerr()
		  get_ylabel()
		  get_noticed_channels()
		  get_mask()
		  get_noticed_expr()
		  get_filter()
		  get_filter_expr()
		  notice()
		  to_guess()
		  to_fit()
		  to_plot()
	  }

      class EvaluationSpace1D {
	      x_axis Axis
	  }

      class EvaluationSpace2D {
	      x_axis Axis
	      y_axis Axis
	  }
```

---

# Phases

## Phase 1

Add tests of a number of cases - either from first principles or ones
found in developing the code.

The largest change is re-arranging the existing "astro data" tests so
that the PHA and IMG tests are in separate files, just to make it
easier to see what is being tested.

**Question** What should they test?

Should these tests reflect the expected behavior, that is, they are
marked as `xfail`, or should they be regression tests so we can see
when the behavior changes. It probably depends on the test.

## Phase 2

The dimension checks (issue #1460) can be done by giving each `Data`
sub-class a `ndim` attribute that can be compared against the model in
the `eval_model` and `eval_model_to_fit` methods. These checks have to
support either, or both, of the `ndim` attributes being set to `None`,
or there being no `ndi,` attribute. Although the `eval_model` routines
are the main place that models are sent to `Data` objects, there are
other places, for instance `Data1D.get_x` and `Data1D.get_y`.
Unfortunately we have to manually check the code to find these
places. It might seem that we would want to also use this when setting
the independent axis, but that is handled by the `_init_data_space`
routine, and depends on whether it is an integrated data set or not.

A size property can be added to the `Data` objects that returns the
number of elements, or `None` if not set. This can be used to check
that a particular field - e.g. independent axis, dependent axis, or
related field - has the correct size (or set the size if it's the
first field being changed).

The handling of the independent axis - e.g. to check we have the
correct number of arrays, that they have the same size, to make them
read-only - is surprising hard because the logic is not in a single
place. The `_init_data_space` method would appear to be a good place
to do this, but there are a number of difficulties:

- the number of values required depends on the data class - e.g. `Data1DInt`
  and `Data2D` both require two arryas, but they have different
  meanings - which means some boiler-plate code in each class
- I've added `Data._check_data_space` which can do the size check, so it
  can be easily accessed from the individual `_init_data_space` calls
- as hopefully visible in the class diagrams, the data space design is
  not coherent, in that the 1D and 2D classes are designed differently,
  and tracking this down is currently de-railing me as it has lead to
  wondering about the PSF support (which appears to use a 2D class even
  for 1D data).

For the other cases we can generally add specific properties for them
and use the underlying same code - in this case via the newly-added
`_set_related`

```python
def _set_related(self, attr, val, check_mask=True):
    """Set a field that must match the independent axes size.

    The value can be None or something with the same length as the
    independent axis. This is intended to be use from the property
    setter. There is also a check to warn the user if the value
    contains a NumPy masked array which does not match the
    dependent axis.

    """
    if val is None:
        setattr(self, f"_{attr}", None)
        return

    if not numpy.iterable(val):
        raise DataErr("notanarray", attr)

    # Check the mask before calling _check, which could call asarray
    # and so lose the mask setting.
    #
    if check_mask and hasattr(val, "mask"):
        if not hasattr(self.y, "mask") or \
           len(self.y) != len(val) or \
               not numpy.all(self.y.mask == val.mask):

            warnings.warn(f"The mask of {attr} differs from the dependent array, only the mask of the dependent array is used in Sherpa.")

     val = _check(val, warn_on_convert=False)
     nval = len(val)

     nelem = self.size
     if nelem is None:
         # We set the object size here
         self._size  = nval
         setattr(self, f"_{attr}", val)
         return

     if nval != nelem:
         raise DataErr("mismatch",
                       f"data size ({nelem})",
                       f"{attr} ({nval})")

     setattr(self, f"_{attr}", val)
```

which can then be used to set up a related field:

```python
@property
def y(self):
    """The dependent axis.

    If set, it must match the size of the independent axes.
    """
    return self._y

@y.setter
def y(self, val):
    self._set_related("y", val, check_mask=False)
```

The `mask` field is special, as it can be set to a scalar (boolean) as
well as a sequence.  For the `DataPHA` case we need to allow some
fields to be set to a scalar, in particular the `areascal` and
`backscal` fields. There are also type conversions we want to apply -
e.g. making sure that the grouping and quality arrays are 2-byte
integer values. One option would be to error out if the arguments are
not integer values, but this may break old code - such as reading in
values from a text file which may create floating-point values rather
than integers - and does not seem to be worthwhile. These checks are
made before calling the `_set_related` method.

For the `DataPHA` case the current approach is to over-ride the
`_set_related` method to:

```python
def _set_related(self, attr, val, check_mask=True, allow_scalar=False):
    """Set a field that must match the independent axes size.

    The value can be None, a scalar (if allow_scalar is set), or
    something with the same length as the independent axis. This
    is intended to be use from the property setter.

    """
    if val is None:
        setattr(self, f"_{attr}", None)
        return

    if not numpy.iterable(val):
        if not allow_scalar:
            raise DataErr("notanarray", attr)

        setattr(self, f"_{attr}", val)
        return

    super()._set_related(attr, val, check_mask=check_mask)
```

There are some fun decisions to make here, such as what exactly the
`bin_lo` and `bin_hi` fields of the `DataPHA` object are meant to be.
Are they meant to match the size of the channel array (which would
make sense, as they seem to be to support Chandra grating data),
but we do have tests which have a different size.

**Note**

The errors raised when a user does something invalid may be changed,
both the messages for a given error type, and in many cases the actual
error type (e.g. `sherpa.utils.err.DataErr` rather than `TypeError`).
This could lead to changes in behavior in down-stream software, but
only for ones that are explicitly catching a articular error.

**Comment by hamogu** [comment]
From reading through this, I have some thoughts:

- Multi-dimensional arguments: Yes, please. I think it's much safer if we flatten the arguments then requiring the user to do so. Of course, we want to stay backwards-compatible, so one-dimensional arguments should be allowed, but we don't have to advertise them e.g. examples could use multi-D input variables.
- Masked arrays: I suggest to stay away from them except as implemented already. Conceptually, we have only one mask (in PHA that's called 'data quality') that applies to all fields: independent axis, dependent axis, syserror etc. So, let that mask be a sherpa thing and not a np.masked array. Also, the np masked implementation (used to) have some quirks that we can avoid if we don't need it. Might be easier to provide a `to_masked_array` method for users that want that for passing data to other packages that might use masked arrays.
- Should a data object know if it's multi-D? If it's integrated? I think "yes" for clarity for Users. Printing, inspecting, display in notebook can say and depend on dimensionality and if it's integrated. They behave different in some context, so we should say what it is E.g. I can imagine plotting integrated data histogram style and other data line-style. This is certainly true for dimensionality. I can be convinced that integrated is not as important.
- Should the size of an object be fixed? Sherpa has the `ignore` which effectively allows you to make an object smaller, by just reducing the area that's used. With that, we can fix the size.
- What happens if the independent axis is changed? Since the size of an object is fixed we can interpret the other fields (dependent axis, error, etc.) as "belonging to independent axis bin n" not as "belonging to independent axis value x". I see a few common astro use cases for that, for example, I might have wavelength of an optical spectrum as independent axis where I noticed a specific spectral line. Now, I want to red-shift the wavelength scale. Fluxes and errors in each bin don't change, nor do the bins I've noticed or ignored. That means we might have to do something to keep the filters in sync - they have to be "noticed bin n to m", not "noticed region x - y", so they need some conversion.

**Comment by DougBurke** [comment]
We could break up "Phase 2" into things like

- independent axis changes
- dependent axis changes
- related-field changes

which might make them a bit-easier to review. However, it depends on how some of the decisions come out.

**Comment by DougBurke** [comment]
For multi-dimensional arguments: I think we can make these changes after the data-validation changes (i.e. something to add to the to-do list).

[it would be nice if we could thread discussions on GH]

**Comment by DougBurke** [comment]
For the "what to do if the independent axis is changed" case. My current view is that the code will just clear the mask/region filter and it would be up to the user to reset it appropriately, as they are in the best place to do so. As mentioned, we could move to a system where we record the "intent" of a filter (e.g. the low and high ranges) rather than the affected bins, but

- this is **hard** to do well, particularly if you can change a `mask` element outside of `ignore`/`notice` calls (which I thing we want to keep)
- does not actually help in the "wavelength" shift example mentioned above.

**Comment by hamogu** [comment]
For the particular use case that I described (and that's probably not uncommon for spectra, could also be a wavelength -> Doppler velocity conversion or frequency -> wavelength), I suggest that there be a way to transform the filter into an array, and re-apply it, something like
```
data.notice(200, 330)
notice_mask = data.dataspace.mask
data.change_indep_axis_in_some_way()
data.dataspace.notice_mask = notice_mask
```
We may want to wrap that into a function, e.g. `data.set_indep_axis(newaxis, clear_filter=True)`.

**Comment by DougBurke** [comment]
We already can do this

```python
omask = data.mask
data.indep = (shifted_array, )
# at the moment data.mask isn't changed when the independent axis does, but let's assume it has been cleared
data.mask = omask 
```

**Comment by DougBurke** [comment]
For reference the branch I'm using to test this out is https://github.com/DougBurke/sherpa/tree/add-data-validation but it is likely to be rebased at any time.

**Comment by DougBurke** [comment]
For reference, I think I've worked out why `DataSpace1D` inherits from `EvaluationSpace1D` but `DataSpace2D` does not inherit from `EvaluationSpace2D`. The `EvaluationSpace2D` object seems to require that the axes form a grid (ie a nx by ny set of values, flattened into a 1D list) whereas the `Data2D` object does not require this - that is you can say

```python
data = Data2D("not-a-grid", [10, 10, 20, 30], [14, 15, -20, 14], [10, 12, 15, 2])
```

There is no requirement that the 2D values be on a grid, hence the disconnect. We do have the `DataIMG` class which we could require a grid, which would clean up some corner cases, but then again we could manually create something that has a physical/world transform but does not have a grid of values (even if this is not something that FITS supports). However, this is getting far away from the point of this comment.

**Comment by DougBurke** [comment]
This comment is a **WIP**

So #1477 has a large number of changes in it, which I discuss below. Things would be a lot simpler if we changed the design so that certain fields (primarily independent and dependent axes) are required when the object is created, but I do not thiink we want to do that.

- fields, when not `None` or a scalar, are converted to ndarray whihc means we don't have to litter code with conversions (and there's at least one case where we currently don't which causes problems)
 
- the `Data` objects gain a `ndim` attribute which lets us catch 2d vs 1d cases
- the `Data` objects can now ensure that the correct number of independent axes are sent in (e.g. Data2DInt has 4 for the x0lo, x1lo, x0hi, x1hi coordinates)
 - if we ever want a dataset with one axis integrated and one not we would need to add new code, but to be honest our current code does not handle this case anyway
- the independent axis is now marked read-only, so you can not change a subset of elements, you have to change the whole axis
 - this lets us make sure that the filter or region is cleared whenever the independent axis is changed; there are arguments for and against this
 - this time is's the `DataIMG` case that complicates things, as changing the coord setting changes the independent axis, which makes this interesting

- the `Data` objects gani a `size` attribute which reports the size of the dataset
 - grouped PHA data complicates this because there are times you need to know the number of channels and times you want the number of groups; the `size` refers to the former concept
- the size of a dataset is now considered fixed, once set, so you can't change it; if we allowed the size to change then you have to decide what to do once one field changes size: do you reset all the other fields, resize them to match the new size (adding 0's if needed), or maybe you only allow the independent axis to change size (but then still need to know what to do with other fields)
- the fields are checked against the `size` attribute when set


-

**Comment by DougBurke** [comment]
Examples of current problems. This is with CIAO 4.14 and I'm using a PHA dataset (some of them are specific to PHA, some are general). The setup is

```
sherpa-4.14.0> load_pha("acisf00658_000N024_r0033_pha3.fits.gz")
read ARF file acisf00658_000N023_r0033_arf3.fits
read RMF file acisf00658_000N023_r0033_rmf3.fits
read background file acisf00658_000N024_r0033_pha3.fits

sherpa-4.14.0> set_source(xsphabs.gal * xspowerlaw.pl)

sherpa-4.14.0> subtract()
```

This dataset happens to be ungrouped.

# example of setting a field to the wrong size

```
sherpa-4.14.0> set_backscal([1, 2])

sherpa-4.14.0> calc_stat()
ValueError: operands could not be broadcast together with shapes (2,) (1024,)
```

# example of dimension mis-match

The model is evaluated, but you have no idea what it's actually doing. In this case the model plots appear sensible, but understanding what is actually being evaluated is hard, and if I'd loaded an image and then set a 1D model you'd have got some strange `TypeError` from commands like `calc_stat` or `image_model`.

```
sherpa-4.14.0> set_source(gauss2d.bgnd)

sherpa-4.14.0> plot_model()

sherpa-4.14.0> plot_source()
```

# Here's an example where we do make a check

```
sherpa-4.14.0> set_filter([1, 0, 1, 0])
DataErr: size mismatch between 1024 and 4
```

# back to no checks

This is essentially the first case

```
sherpa-4.14.0> set_staterror([0.2, 0.3, 0.4])

sherpa-4.14.0> calc_stat()
ValueError: operands could not be broadcast together with shapes (3,) (1024,)
```

# Using methods

This is essentially the same point as the previous example (i.e. the argument is the wrong size) but using methods on the data object rather than ui routines. In this case we had not documented what `apply_fitler` or `apply_groupnig` should do when given something the wrong size, but I argue that not making this an error just makes code harder to maintain.

```
sherpa-4.14.0> data.apply_filter([20, 30])
[20, 30]

sherpa-4.14.0> data.apply_grouping([20, 30])
[20, 30]
```

Note that if we make the dataset grouped then the behavior changes (which is one of the reasons why I claim it's hard to maintain code)

```
sherpa-4.14.0> group_counts(15)

sherpa-4.14.0> data.apply_filter([10, 20])
TypeError: input array sizes do not match, data: 2 vs group: 1024

sherpa-4.14.0> data.apply_grouping([10, 20])
TypeError: input array sizes do not match, data: 2 vs group: 1024
```
