### ISSUE TITLE
minor bug with calc_chi2datavar_errors

### ISSUE THREAD

**Issue by dtnguyen2** [sherpa/sherpa#148]
The logic in the following lines
 if ( yraw[ ii ] <= 0.0 )
	return EXIT_FAILURE;
is supposed to prevent taking a sqrt of a negative number so the test of <= should be changed to < since sqrt of 0 is legit

  template <typename ArrayType, typename ConstArrayType, typename DataType,
	    typename IndexType>
  inline int calc_chi2datavar_errors( IndexType num, const ConstArrayType& yraw,
				ArrayType& err ) {

    for ( IndexType ii = num - 1; ii >= 0; --ii )
      if ( yraw[ ii ] <= 0.0 )
	return EXIT_FAILURE;
      else
	err[ ii ] = std::sqrt( yraw[ ii ] );
    
    return EXIT_SUCCESS;

  }

**Comment by anetasie** [comment]
If this is used in the denominator when calculating the statistics then there should not be 0 there, because the calculation of the statistics will fail. The check and failure should be included in that part of the code as well.

**Comment by DougBurke** [comment]
Can we close this as it looks like it was fixed by PR #153 ?

**Comment by olaurino** [comment]
Yes. Looking at the release notes we fixed this in 4.8.1.
