### ISSUE TITLE
grplib uses Python from PATH

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#15]
I'm getting this configure error for grplib when I try `python2.7 setup.py install` for Sherpa:
https://gist.github.com/cdeil/39e9404e91954cb67270#file-gistfile1-txt-L284

It tries to use python3.4, which is the `python` on my PATH.
Instead it should use the Python with which I call setup.py.

**Comment by taldcroft** [comment]
@cdeil - yeah, that looks like a problem in configure.  At least for now the easiest workflow for sherpa development is going to be an isolated Anaconda environment or something similar.

**Comment by olaurino** [comment]
@cdeil thanks for the report

I see two issues here:
  - as you reported, the build is not taking into account that you want to force python2.7, despite the fact that python3 has the precedence in your PATH setup.
  - the macro that should ensure python's version is 2.7 is not doing its job: you should get a meaningful error message if building with python3.

Regarding the first issue, here is a workaround: just `export PYTHON=python2.7` before you run `python2.7 setup.py install`. Then the `configure` script will not try to infer the Python version itself. I will take this report as a suggestion for a feature enhancement so to make this transparent to the user: if python2.7 is used to run `setup.py` it should also be used to build the python extensions built externally.

Regarding the second issue, it is an actual bug. Unfortunately, a fix would require to rerun the `autotools`, and I need to coordinate this with the `grplib` maintainers, as this code is taken from the `CIAO` codebase.

I will create two separate tickets, as I believe these two issues will be addressed separately.

**Comment by olaurino** [comment]
This issue has been replaced by #19 and #20

**Comment by olaurino** [comment]
@cdeil if you agree I would like to close this issue: your report will be addressed in #19 and #20 separately.

**Comment by cdeil** [comment]
@olaurino – Sure, splitting separate issues into different tickets is always a good idea. Closing this one now.
