### ISSUE TITLE
Something odd with our tests and matplotlib handling

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1508]
With the current main branch, with matplotlib installed, and my `~/.sherpa-standalone.rc` file containnig

```
% grep plot ~/.sherpa-standalone.rc
# plot_pkg   : pylab dummy
plot_pkg   : pylab
# plot_pkg   : dummy
```

then `pytest` likes to tell me

```
WARNING: Failed to import any usable sherpa.plotting backend. Plotting routines will not be available.
```

which is odd. I've tracked it down to

```
% pytest sherpa/static
==================================================== test session starts =====================================================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dburke/sherpa/sherpa-master, configfile: pytest.ini
plugins: forked-1.4.0, xdist-2.5.0, xvfb-2.0.0, doctestplus-0.12.0
collected 0 items

=================================================== no tests ran in 0.01s ====================================================
WARNING: Failed to import any usable sherpa.plotting backend. Plotting routines will not be available.
```

So, it tries to find tests in `sherpa/static`, doesn't find anything, but thinks we don't have matplotlib available.

It is **not at all clear** what is happening here, because if I change `sherpa/plot/__init__.py` to the following:

```
 for plottry in plot_opt:
+    lgr.warning(f"XXX  .... trying <{plottry}>")
     try:
         backend = importlib.import_module('.' + plottry,
                                           package='sherpa.plot')
+        lgr.warning("XXX found it")
         break
     except ImportError:
+        lgr.warning("XXX failed")
         pass
 else:
     # None of the options in the rc file work, e.g. because it's an old file
     # that does not have dummy listed
+    lgr.warning("XXX  .... falling over to dummy")
     import sherpa.plot.dummy_backend as backend

+lgr.warning("XXX done all the things")
+
```

then re-run the above we get

```
pytest sherpa/static
==================================================== test session starts =====================================================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dburke/sherpa/sherpa-master, configfile: pytest.ini
plugins: forked-1.4.0, xdist-2.5.0, xvfb-2.0.0, doctestplus-0.12.0
collected 0 items

=================================================== no tests ran in 0.01s ====================================================
WARNING: XXX  .... trying <pylab_backend>
WARNING: XXX found it
WARNING: XXX done all the things
WARNING: Failed to import any usable sherpa.plotting backend. Plotting routines will not be available.
```

which tells me that `sherpa/plot/__init__.py` never got to the`import ... dummy_backend as backend` line, and so should never have created the "Failed to import any ..." message (which comes from `dummy_backend`).

I'm wondering if it has just decided to import `dummy_backend` as well as `pylab_backend` as it tries to find tests.

I imagine that the correct solution here is to mark `sherpa/static` as something that has no tests, but this gets mixed up in pep 517 + ...` work (e.g. the existing #1329 / #1352 work), and I'm not sure I have the energy to investigate this.

Other than the confusing message, I don't think this is a problem, in that the tests still run (and the pylab tests are run when you have matplotlib installed [modulo whatever we do in #1382 to run tests with multiple backends, but that's not relevant here].

**Comment by DougBurke** [comment]
Hmm, if I say

```
pytest --pyargs sherpa
```

then I don't seem to see this (but I am in a PR which has changed things, so can't guarantee it works for `main`)

**Comment by hamogu** [comment]
I can't reproduce this now, so I assume we fixed it when we did more work on the backends about a year ago.
