### ISSUE TITLE
Filter expression does not match region masked

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1520]
With current master, I notice the range 1-6, then ignore 2-5, yet the filter expression is `'1.0000,6.0000 x'`.
```
In [1]: import sherpa

In [2]: from sherpa.data import Data1D

In [3]: d = Data1D('example', [1., 2., 3., 5., 6., 7.], [0, .4, .5, .6, .7, .8])
/Users/guenther/code/sherpa/sherpa/data.py:91: UserWarning: Converting array [0, 0.4, 0.5, 0.6, 0.7, 0.8] to numpy array.
  warnings.warn(f"Converting array {array} to numpy array.")

In [4]: d.notice(1., 6.)

In [5]: d.mask
Out[5]: array([ True,  True,  True,  True,  True, False])

In [6]: d.ignore(2., 5.)

In [7]: d.mask
Out[7]: array([ True, False, False, False,  True, False])

In [8]: d.get_filter_expr()
Out[8]: '1.0000,6.0000 x'

In [9]: d.get_filter()
Out[9]: '1.0000,6.0000'
```

@DougBurke It looks like a bug to me, but if this is expected behavior, we definitely need to add a warning to get_filter that "regions ignored in the middle won't show up" or something like that.

**Comment by DougBurke** [comment]
So, you have points at

    1, 2, 3, 5, 6, 7 

and after the first call you have excluded the last point (as it's > 6) so you have selected

    1, 2, 3, 5, 6

Then the `ignore` call means exclude points between 2 and 5 inclusive, so this means you have selected

    1, 6

which is what the filter expression is saying. Remember, this is a `Data1D` dataset so these are points, not "ranges" as you 'd have with `Data1D` or `DataPHA`, so there really isn't anything to say for the filter expression than "1, 6".

We do assume that if there are n consecutive elements (where n > 1) that we can make a filter expression of "a-b" (where a is the coordinate of the first element in the range and b the last one. When there's only a single element we are stuck with kust giving it. Or at least, I can't see any other way to do it, but I've been wrong before!

**Comment by hamogu** [comment]
OK, I understand now, I think. I'll see if I find a way to describe this that would have helped me to see that myself.
