### ISSUE TITLE
something somewhere is doing something it shouldn't

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1527]
I have spent too long doing a manual bisect-like operation to come up with an explanation of this, so I'm just noting it here to worry about later.

With the main branch we have the following test, added in #1510 (to show off issue #1512) - it currently fails for all runs, which is expected.

```
% pytest  sherpa/ui/tests/test_ui_plot.py::test_get_foo_component_plot_recalc 
==================================================== test session starts =====================================================
platform linux -- Python 3.7.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dburke/sherpa/sherpa-xspec, configfile: pytest.ini
collected 12 items                                                                                                           

sherpa/ui/tests/test_ui_plot.py xxxxxxxxxxxx                                                                           [100%]

==================================================== 12 xfailed in 1.50s =====================================================
```

However, if I run `pytest` (with no argument) then some of the tests suddenly pass. This makes **no** sense, but I give you the following:

```
% pytest sherpa/ui/tests/test_session.py::test_paramprompt_single_parameter_works sherpa/ui/tests/test_ui_plot.py::test_get_foo_component_plot_recalc 
==================================================== test session starts =====================================================
platform linux -- Python 3.7.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dburke/sherpa/sherpa-xspec, configfile: pytest.ini
collected 13 items                                                                                                           

sherpa/ui/tests/test_session.py .                                                                                      [  7%]
sherpa/ui/tests/test_ui_plot.py xxxxxxxxXXXX                                                                           [100%]

========================================== 1 passed, 8 xfailed, 4 xpassed in 0.82s ===========================================
```

Note that the last four tests pass.

I've dug into the code and for some reason the session class seems to be keeping hold of a model labelled `bob` when it shouldn't have, and this makes the tests in `test_ui_plot` suddenly pass (by accident).

So, I need to review what's going on. I'm wondering if it's an instance of #95 (this is a complete guess, and I'm only thinking this because I was looking at this issue recently).

**Comment by DougBurke** [comment]
So, the code in `test_session.py` - there are several that do this - calls `set_source` with a string: this then triggers the model to get added to the global symbol table. This means they persist.

For example:

```
>>> import sherpa.models.basic
>>> from sherpa.ui.utils import Session
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: Failed to import any usable sherpa.plotting backend. Plotting routines will not be available.
>>> s = Session()
>>> s._add_model_types(sherpa.models.basic)
>>> foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'foo' is not defined
>>> globals()["foo"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'foo'
>>> s.set_source("scale1d.foo")
>>> foo
<Scale1D model instance 'scale1d.foo'>
>>> globals()["foo"]
<Scale1D model instance 'scale1d.foo'>
>>> s.list_model_components()
['foo']
>>> s.clean()
>>> s.list_model_components()
[]
>>> globals()["foo"]
<Scale1D model instance 'scale1d.foo'>
>>> foo
<Scale1D model instance 'scale1d.foo'>
```

So, the symbol `foo` is now a global. Even when `s` disappears it will remain.

The easy (I believe) fix is to change the tests as they don't need to call `set_source` with a string. 

I am not sure of the longer term.

I have long wondered about removing support for strings from the model "language", but I know there's a lot of documentation and code that use it, for some reason I've never understood (I am not sure if it was needed with the S-Lang interface, just because of reasons, but I think I'm just starting to vent and it's probably not particularly helpful now).

**Comment by hamogu** [comment]
We can have a fixture (either for all tests or for just those tests) that in set test setup makes a copy of the globals, and after the test restores it.

I don't have any love for the "string" syntax either (it's confused me to no end in some cases when I tried to switch between UI and OO layers), but I'm afraid that ship as sailed for Sherpa. If we want to ever remove it, then we should:

1) rewrite all docs so that it's not used anywhere in new code
2) wait 2-3 years, then issue a DeprecationWarning
3) and then, if nobody complains to the helpdesk in the next two years, we can actually remove it.

Is it worth it? I don't know...

**Comment by DougBurke** [comment]
Well, I think it depends on exactly which "global" namespace the damn symbol is being attached to. I don't have enough bandwidth to really address this, so it's going on my back-burner pile.
