### ISSUE TITLE
int_proj log=True does not evaluate on a logarithmic grid

### ISSUE THREAD

**Issue by nplee** [sherpa/sherpa#1561]
This comes from helpdesk ticket 024234, but it appears that `int_proj` (and subsequently `int_unc`) does not evaluate on a logarithmic grid when `log=True`.  A simple example, using the standard 3C273 thread data set, 

```
sherpa In[1]: load_data("3c273.pi")

sherpa In[2]: set_stat("wstat")

sherpa In[3]: set_method("neldermead")

sherpa In[4]: set_model(xsphabs.abs1*powlaw1d.p1)

sherpa In[5]: abs1.nH = 1.79e-2

sherpa In[6]: fit()
Out[6]:
Dataset               = 1
Method                = neldermead
Statistic             = wstat
Initial fit statistic = 1.52833e+07
Final fit statistic   = 38.1265 at function evaluation 670
Data points           = 46
Degrees of freedom    = 43
Probability [Q-value] = 0.682297
Reduced statistic     = 0.886664
Change in statistic   = 1.52833e+07
   abs1.nH        0.0177443   
   p1.gamma       1.98303     
   p1.ampl        0.000196117 

sherpa In[7]: int_proj(abs1.nH,min=0.01,max=1,nloop=3,log=True)

sherpa In[8]: int_proj_lin = get_int_proj()

sherpa In[9]: xlin = int_proj_lin.x

sherpa In[10]: ylin = int_proj_lin.y

sherpa In[11]: int_proj(abs1.nH,min=0.01,max=1,nloop=3,log=True)

sherpa In[12]: int_proj_log = get_int_proj()

sherpa In[13]: xlog = int_proj_log.x

sherpa In [14]: ylog = int_proj_log.y

sherpa In [15]: xlin
Out[15]: array([0.01 , 0.505, 1.   ])

sherpa In [16]: xlog
Out[16]: array([0.01 , 0.505, 1.   ])
```

We would expect that `xlog` look like [0.01, 0.1, 1.] if the evaluated grid is logarithmic.

This was previously reported to sherpadev (https://icxc.harvard.edu/pipe/sherpadev/2011/0287.html), but I cannot find any evidence that a fix was ever implemented based on my search through the old DS bug tracking system or in whatever bugs that were migrated into Jira.  

A workaround derived from the one mentioned in the sherpadev thread can be approached as follows:

```
def int_proj_log(modpar, id=None, parmin=None, parmax=None, nloop=20):
    
    par_bestfit = modpar.val    
    yy = []
       
    def loggrid(parmin,parmax,nloop):
        return numpy.logspace(start=numpy.log10(parmin), stop=numpy.log10(parmax), num=nloop)

    freeze(modpar)

    xx = loggrid(parmin,parmax,nloop)

    for x in xx:
        modpar.set(x)
        fit(id)
        yy.append(get_fit_results().statval)

    modpar.set(par_bestfit)
    thaw(modpar)

    plt.figure()
    plt.plot(xx,yy)
    plt.xscale("log")
    plt.axvline(par_bestfit,linestyle="dashed",color="orange")
    plt.axhline(min(yy),linestyle="dashed",color="green")
    plt.xlabel(f"{modpar.fullname}")
    plt.ylabel("Statistic Value")

    return xx,yy
```

and then run by:

```
x_bins_log,y_stat_log = int_proj_log(abs2.nH,parmin=0.01,parmax=15,nloop=50)
```

(using the parameters that the user was using), or `parmin=0.01,parmax=100,nloop=5` to get a grid spaced as [0.01, 0.1, 1.0, 10, 100].

Of course, this may not be the ideal approach to this problem.

**Comment by DougBurke** [comment]
We need to check

```
int_proj
int_inc
reg_proj
reg_unc
```

I don't think there are other examples (but should also check this statement!).

**Comment by DougBurke** [comment]
I am pretty sure we have a similar issue with `reg_proj` and `reg_unc`.

**Comment by DougBurke** [comment]
So, I'm likely to also look at the reg code, but that is "separate" from the int code so comments can be made on the existing PR if people feel like it...
