### ISSUE TITLE
How is Sherpa "versioning" done?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#157]
The file `sherpa/__init__.py` has several lines related to version numbers. Do they need cleaning up, do we need to add some documentation on how versioning is done, or perhaps both?

For instance (links are to the current `master` version)

* multiple definitions of `__version__`:

  https://github.com/sherpa/sherpa/blob/a51c6ebcfcdcfe9f9af0952157d2d52f36ddd54e/sherpa/__init__.py#L46

  which is replaced by

  https://github.com/sherpa/sherpa/blob/a51c6ebcfcdcfe9f9af0952157d2d52f36ddd54e/sherpa/__init__.py#L129

* should `__versionstr__` be removed?

  https://github.com/sherpa/sherpa/blob/a51c6ebcfcdcfe9f9af0952157d2d52f36ddd54e/sherpa/__init__.py#L45

  shows that `__versionstr__` is hard-coded, but it matches the first `__version__` setting, which is later over-written.

**Comment by olaurino** [comment]
@DougBurke These issues were all taken care of in the 4.8.0 release, branch:
https://github.com/sherpa/sherpa/blob/release/4.8.0/sherpa/__init__.py

**Comment by DougBurke** [comment]
So why are they not in the master branch as well then?

**Comment by olaurino** [comment]
Because we haven't merged the release branch just yet. We'll merge it right after we release it.
