### ISSUE TITLE
tablemodel load does not cache data

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1622]
Found as part of #1621. I've realised that the existing tablemodel code does not clear the cache when `load` is called, which means that

```
>>> from sherpa.models.basic import TableModel
>>> mdl = TableModel()
>>> mdl.load([1, 2, 3], [4, 5, 6])
>>> mdl([1, 2, 3])
array([4., 5., 6.])
>>> mdl([1, 2, 3])
array([4., 5., 6.])
>>> mdl.load([1, 2, 3], [100, 200, 300])
>>> mdl([1, 2, 3])     # THIS IS WRONG
array([4., 5., 6.])
```

You can fix this by turning off the cache by setting `_use_caching` to `False`

```
>>> mdl._use_caching = False
>>> mdl([1, 2, 3])  # THIS IS CORRECT
array([100., 200., 300.])
>>> mdl([1, 2, 3])
array([100., 200., 300.])
>>> mdl.load([1, 2, 3], [10, 20, 30])
>>> mdl([1, 2, 3])  # THIS IS CORRECT
array([10., 20., 30.])
```

**Comment by DougBurke** [comment]
@hamogu this may be an issue for you in https://github.com/hamogu/dPHA/blob/master/CasA.ipynb which is why I wanted to provide a workaround (I haven't checked your notebook closely enough to see if it is a problem or not). There's a possibility that although it technically is a problem that as soon as the fit starts and the amplitude changes that it "corrects itself".

**Comment by hamogu** [comment]
@DougBurke Thanks for letting me know. I'll be on the look-out, but I have not noticed anything strange - maybe because I don't `load` a second time, but would always make a new model. 

For any re-design I suggest we consider that the values of a Table model are essentially frozen after the model is initialized, in the spirit of `Data1D` where you can't change individual numbers in the x-axis any longer (No need to to too clever, but at least not have a public `load` method, instead require that to be passed in on model initialization.)

**Comment by DougBurke** [comment]
I have been tempted to look at a redesign but I think I am going to hold off for a while as I think I want to look at some other things first. I'll probably change my mind tomorrow!

**Comment by DougBurke** [comment]
Darn it, once you look you can't stop finding corner cases:

```
>>> from sherpa.models.basic import TableModel
>>> from sherpa import utils
>>> mdl = TableModel()
>>> mdl.load([1, 2, 3], [4, 10, 0])
>>> y1 = mdl([0.3, 2.8])
>>> mdl.method = utils.nearest_interp
>>> y2 = mdl([0.3, 2.8])
>>> y1 == y2
array([ True,  True])
>>> y2
array([-0.2,  2. ])
```

This is not write, `y2` should be using the "nearest" values (so `4` and `0`) not `y1`. The problem is that the method attribute is not included in the cache key. If we turn off the cache we can see the expected answer:

```
>>> mdl._use_caching
True
>>> mdl._use_caching = False
>>> y3 = mdl([0.3, 2.8])
>>> y2 == y3
array([False, False])
>>> y3
array([4., 0.])
```
