### ISSUE TITLE
Link model parameters with mathematical functions

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1652]
Model parameters can be linked directly to other model parameters or if they are linearly related, e.g. `g1.fwhm = 2 * g2.fwhm`, have a constant offset, or e.g. `g1.fwhm = 1 + 2 * g2.fwhm**0.5`. However, linking them with more complex expressions, e.g. exp, log, sin, cos etc. fails. The failure is different depending on if I loaded the mathematical function from `numpy` or the build-in `math` module.
```Python
from sherpa.astro import ui
import numpy as np
from math import exp
ui.load_arrays(1, [1,2,3,4,5], [1,2,3,2,1])
ui.set_source(1, ui.gauss1d.g1)

g1.fwhm = np.exp(g1.ampl)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'Parameter' object has no attribute 'exp'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In [4], line 1
----> 1 g1.fwhm = np.exp(g1.ampl)

TypeError: loop of ufunc does not support argument 0 of type Parameter which has no callable exp method
```

or, alternatively
```Python
g1.fwhm = exp(g1.ampl)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [5], line 1
----> 1 g1.fwhm = exp(g1.ampl)

TypeError: must be real number, not Parameter
```

**Comment by hamogu** [comment]
However, I just discovered, `g1.fwhm = np.e**g1.ampl` works.

**Comment by hamogu** [comment]
I looked at a few examples both the simple one above and one with > 100 DataPHA datasets and they both work, as in "give the correct results". Sometimes Sherpa is much better than we think!
```Python
from sherpa.models import model

class ModelThatHasAParameter(model.RegriddableModel1D):
    """A model that has a parameter but does not do anything
    """
    def __init__(self, name, *args):
        self.par = model.Parameter(name, 'par', 1)
        super().__init__(name, (self.par, ))

    def calc(self, *args, **kargs):
        return 1

parmodel1 = ModelThatHasAParameter(name='decay1')
parmodel2 = ModelThatHasAParameter(name='decay2')
parmodel3 = ModelThatHasAParameter(name='decay3')
ui.set_source(1, parmodel1 * parmodel2 * parmodel3 * abundfixedmodels[1][0] * abundfixedmodels[1][1] )

# abundfixedmodels is a dict of modes that are set for datasets 1,2,3,... so I don't have to call ui.get_model every time

for i in ui.list_data_ids():
    if i > 1:
        abundfixedmodels[i][1].norm_1 = abundfixedmodels[0][1].norm_1 * \
            np.e**(-(fit_res['MJD-OBS'][i]-fit_res['MJD-OBS'][0]) / parmodel1.par)
        abundfixedmodels[i][1].norm_2 = abundfixedmodels[0][1].norm_2 * \
            np.e**(-(fit_res['MJD-OBS'][i]-fit_res['MJD-OBS'][1]) / parmodel2.par)
        abundfixedmodels[i][1].norm_3 = abundfixedmodels[0][1].norm_3 * \
            np.e**(-(fit_res['MJD-OBS'][i]-fit_res['MJD-OBS'][1]) / parmodel3.par)

ui.fit(*ui.list_data_ids())
```
gives
```
Datasets              = 0, 1, 10, 100, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 3, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 4, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 5, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 6, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 7, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 8, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 9, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 107050
Final fit statistic   = 22576.5 at function evaluation 124
Data points           = 23053
Degrees of freedom    = 23044
Probability [Q-value] = 0.985718
Reduced statistic     = 0.979713
Change in statistic   = 84473.5
   temp_0.norm_1   0.00265765   +/- 8.65394e-05 
   temp_0.norm_2   0.0211818    +/- 0.000344844 
   temp_0.norm_3   0.0868254    +/- 0.000340509 
   decay1.par     8.78918      +/- 0.369928    
   decay2.par     42.0533      +/- 2.43349     
   decay3.par     2.43937      +/- 0.0175956   
   temp_1.norm_1   0.00315857   +/- 0.000284614 
   temp_1.norm_2   0.0219065    +/- 0.00219148  
   temp_1.norm_3   0.0900324    +/- 0.00211507
```
Let's look at a few spectra to make sure it's not only that the numbers look sensibly, but the data is actually fit well:
```
ui.plot_fit(1, xlog=True, ylog=True)
ui.plot_fit(60, overplot=True)
```
![image](https://user-images.githubusercontent.com/498688/207454624-6cbbbc78-aac9-4b04-ad6d-c44f6682fd04.png)

**Comment by DougBurke** [comment]
So, we have

```
In [37]: from sherpa.models.basic import Const1D

In [38]: m = Const1D()

In [39]: m.c0
Out[39]: <Parameter 'c0' of model 'const1d'>

In [40]: m.c0 + 2
Out[40]: <BinaryOpParameter '(const1d.c0 + 2)'>

In [41]: np. ** m.c0 + 2
  Cell In [41], line 1
    np. ** m.c0 + 2
        ^
SyntaxError: invalid syntax


In [42]: np.e ** m.c0 + 2
Out[42]: <BinaryOpParameter '((2.718281828459045 ** const1d.c0) + 2)'>

In [43]: def foo(x):
    ...:     return x + 3
    ...: 

In [44]: np.e ** foo(m.c0) + 2
Out[44]: <BinaryOpParameter '((2.718281828459045 ** (const1d.c0 + 3)) + 2)'>

In [45]: foo(m.c0)
Out[45]: <BinaryOpParameter '(const1d.c0 + 3)'>

```

In all these cases we are able to keep the result as a Parameter (in this case `BinaryOpParameter`).

The trouble comes in with functions that do more than just add / divide / ... (i.e. more than use the __add__/__mul__/__pow__/__mod__/... methods), such as

```
In [46]: import math

In [47]: np.e ** math.sin(m.c0) + 2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [47], line 1
----> 1 np.e ** math.sin(m.c0) + 2

TypeError: must be real number, not Parameter

In [48]: np.e ** np.sin(m.c0) + 2
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'Parameter' object has no attribute 'sin'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In [48], line 1
----> 1 np.e ** np.sin(m.c0) + 2

TypeError: loop of ufunc does not support argument 0 of type Parameter which has no callable sin method

```

Now, models let us wrap a function as a model:

```
In [52]: from sherpa.models.model import ArithmeticFunctionModel

In [53]: mm = ArithmeticFunctionModel(np.cos)

In [54]: mm([0.1, 0.2, 0.5, np.pi])
Out[54]: array([ 0.99500417,  0.98006658,  0.87758256, -1.        ])
```

So we could add a `ArithmeticFunctionParameter` class, but the problem is (both for models and parameters) there's no "nice" way (ie automatic, without the need for the user to say so) to lift [*] the function to the correct class. A statement like "2 * pl.gamma + 1", thanks to the __add__/etc methods is automatically kept as a `Parameter` instance (well, `BinaryOpParameter`, but it's a subclass), but there's no "hook" to this for generic function application. So I think we are left with having to have the user indicate this somehow.

Or I'm missing something clever.

I will work on the `ArithmeticFunctionParameter` to see if we can get something that allows us to use functions with some explicit work.

---

[*] I am abusing the terminology of category theory there: https://en.wikipedia.org/wiki/Lift_(mathematics)

**Comment by hamogu** [comment]
I found the piece of code where all that is done: https://github.com/sherpa/sherpa/blob/main/sherpa/models/parameter.py#L633

Today (since ca. numpy 1.13), there is an easy way to make that more general. I'm working on a PR right now.

**Comment by hamogu** [comment]
Today, there is [numpy's _`_array_ufunc__` mechanism](https://numpy.org/doc/stable/user/basics.dispatch.html#basics-dispatch).

**Comment by DougBurke** [comment]
That's fine for numpy ufunc's, but not other functions ;-)

**Comment by hamogu** [comment]
> That's fine for numpy ufunc's, but not other functions ;-)

True. But it vastly increases the number of links you can do. Many, many functions can be written as a combination of ufuncs; and ufuncs that are compatible with this are provided by functions beyond numpy itself, e.g. many (all?) of the functions in `scipy.special` are ufuncs. It's also not that hard to turn [any arbitrary Python function in a ufunc](https://numpy.org/doc/stable/reference/generated/numpy.frompyfunc.html#numpy.frompyfunc) or write a C extension such that function defined there [work as numpy ufuncs](https://numpy.org/doc/stable/user/c-info.ufunc-tutorial.html#creating-a-new-universal-function).

So, with `numpy.frompyfunc` that should work for any function - we just have to document that.
