### ISSUE TITLE
fake_pha background noise

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1683]
Found looking at #1682 

https://github.com/sherpa/sherpa/blob/bf6c8484b0306b393620ec41bb89c7c641db097c/sherpa/astro/fake.py#L176-L179

I think we want to call `poisson_noise` and then divide by `nbkg`.

**Comment by DougBurke** [comment]
Actually, we want the output to be poisson distributed about the average background signal, which is what this code does.

**Comment by hamogu** [comment]
I'm glad Sherpa sometimes does something right after all the review we do before we merge...
