### ISSUE TITLE
sherpa.astro.fake.fake_pha handling of backgrounds

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1685]
Found when working on fixing #1682 in #1684

There are three issues with handling background datasets with `fake_pha`. They are hopefully of limited scope, but if you are affected then you are affected...

1. when there are multiple background components the background component is too small, as it gets divided by the number of backgrounds twice, not once. This is probably fallout from #888 added in 4.12.2 where the `DataPHA.get_background_scale` command was re-worked (I have not looked into this deeply to see if there's any other issue, as the PHA fake code has been changed since, and I couldn't be bothered tracking things down any more after finding the bug and understanding it)
2. when a model is used:
  a. the handling of the background exposure times (for when the source and background exposures are not the same) is suspect (almost-certainly wrong)
  b. when a model is used the background response is used to create the model when it should be the source response
3. if the source is bright enough to require a pileup model then really it should be applied as `pileup(source + bgnd)` but instead it is added to each component individually - e.g `pileup(source) + pileup(bgnd1) + pileup(bgnd2)`,  where the appropriate scaling terms are applied to each component

There is also the question of whether we want to simulate the background component(s) when a model is given?

**Comment by DougBurke** [comment]
So, a question for @anetasie and @hamogu 

I have a PHA file with an associated background dataset. The background dataset has a different BACKSCAL, exposure time, and response to the source. I want to simulate the source region with a source model and a background model (ie the simulation includes both terms). 

So, we have source_data and bkg_data (both DataPHA objects) with

    source_data.exposure != bkg_data.exposure
    source_data.backscal != bkg_data.backscal

and the associated ARF and RMF are different. We have a source_model and a background_model - these are the inputs to a set_source and set_bkg_source call (so do not include response terms).

A lot of the issues I'm looking at are, I believe, because we are being "too clever" for this case. I claim that what we need to do for this case is

 - create combined = source_model + bgnd_model
 - evaluate combined with the source response to get the predicted counts
 - apply the poisson model to that to get the simulated data

A lot of the existing complexity is because we are trying to deal with the different scaling factors between the source and background datasets, but **in this case** I believe we can just ignore all that and follow the above strategy.

If we are not applying a background but want to simulate using the background counts then we do need to worry about the scaling difference, but that's a (slightly-different) part of the code and hence not relevant just for this question.

**Comment by DougBurke** [comment]
So, I think the current code is "doing the right thing" (at least for a single background component) but it's too complex. The following script sets up a "fake PHA + background" which we then pass to `fake_pha` with `bgnd="model"` and we compare the data/model counts before and after:

```python
import numpy as np

from sherpa.astro.ui import *
from sherpa.astro.instrument import create_arf, create_delta_rmf

# Fake up a 3-channel source and background dataset with different
# exposure times, backscal, and ARFs (the RMF will be "perfect" to
# make this simple).
#
#               Source  Bgnd
#    exposure =   100    500
#    backscal =   0.2    0.4
#         ARF =     2    0.8
#
# The RMF does not have equal-width energy bins just to show that
# this has an affect.
#
#     1.0 - 1.2, 1.2 - 1.6, 1.6 - 2.6 keV
#

egrid = np.asarray([1, 1.2, 1.6, 2.6])
elo = egrid[:-1]
ehi = egrid[1:]

arf_src = create_arf(elo, ehi, [2, 2, 2])
arf_bkg = create_arf(elo, ehi, [0.8, 0.8, 0.8])

rmf_src = create_delta_rmf(elo, ehi, e_min=elo, e_max=ehi)
rmf_bkg = create_delta_rmf(elo, ehi, e_min=elo, e_max=ehi)


load_arrays(1, [1, 2, 3], [20, 20, 20], DataPHA)
set_exposure(100)
set_backscal(0.2)

set_rmf(rmf_src)
set_arf(arf_src)

set_analysis("energy")

# We do not have a "ui" way to create the background
#
bkg = DataPHA("bkg", [1, 2, 3], [300, 300, 300], exposure=500, backscal=0.4)
bkg.set_arf(arf_bkg)
bkg.set_rmf(rmf_bkg)

set_bkg(bkg)


# Tweak plot style
for prefs in [get_data_plot_prefs(), get_bkg_plot().histo_prefs]:
    prefs["linestyle"] = "solid"
    prefs["marker"] = None
    prefs["yerrorbars"] = False
    prefs["alpha"] = 0.6


set_source(box1d.sbox)
set_bkg_source(box1d.bbox)

sbox.xlow = 0
sbox.xhi = 1.4
sbox.ampl.set(2, max=2)

bbox.xlow = 1.6
bbox.xhi = 3
bbox.ampl.set(3, max=3)


# Before the fake_pha call, we get
#
def display(arg):
    set_analysis(1, "energy", type=arg)
    print(f"# Analysis: type={arg}")
    print(f"data:       {get_data_plot().y}")
    print(f"bkg:        {get_bkg_plot().y}")
    print("-------")
    print(f"model:      {get_model_plot().y}")
    print(f"bkg_model:  {get_bkg_model_plot().y}")
    print("=======")


display("counts")
display("rate")

# Fake the data
#
try:
    fake_pha(1, arf_src, rmf_src, 100, bkg="model", simulate=lambda x: x)
    print("## fake_pha with no noise")

except TypeError:
    np.random.seed(392347)
    fake_pha(1, arf_src, rmf_src, 100, bkg="model")
    np.random.seed()
    print("## fake_pha with poisson noise")


display("counts")
display("rate")
```

The output, with CIAO 4.15, is

```
# Analysis: type=counts
data:       [20. 20. 20.]
bkg:        [300. 300. 300.]
-------
model:      [ 80.  80. 300.]
bkg_model:  [   0.    0. 1200.]
=======
# Analysis: type=rate
data:       [1.  0.5 0.2]
bkg:        [3.  1.5 0.6]
-------
model:      [4. 2. 3.]
bkg_model:  [0.  0.  2.4]
=======
## fake_pha with poisson noise
# Analysis: type=counts
data:       [ 85.  76. 297.]
bkg:        [300. 300. 300.]
-------
model:      [ 80.  80. 300.]
bkg_model:  [   0.    0. 1200.]
=======
# Analysis: type=rate
data:       [4.25 1.9  2.97]
bkg:        [3.  1.5 0.6]
-------
model:      [4. 2. 3.]
bkg_model:  [0.  0.  2.4]
=======
```

So, we can see that the data counts after the `fake_pha` call have changed, but they are about what we would expect (note that the simulated data includes the background model component, a la #1686, but it is scaled by the source exposure time, not the background exposure (the background model signal is a lot-larger since the background exposure is larger).

**Comment by DougBurke** [comment]
Ahh. We do need things to be more complex because we do have to scale by the ratio of the backscal when including the background model (we don't need to deal with the exposure-time difference because that is handled by the fact the models evaluate to a rate).

**Comment by DougBurke** [comment]
I do note there is a problem if you have set a background_model with set_bkg_model but try to simulate the model without the background (ie set `bkg=None`, which is the default): the code calls

```python
        # Calculate the source model, and take a Poisson draw based on
        # the source model.  That becomes the simulated data.
        m = self.get_model(id)

        fake.fake_pha(d, m, is_source=False, add_bkgs=bkg is not None,
                      id=str(id), bkg_models=bkg_models)
```

but unfortunately `get_model` includes the model component, so it will be simulated whatever happens. I am not sure if we want a code change or just a documentation change - i.e. if you set a background model then you just get it included in the simulation. This would then mean 

- `bkg=None`
- `bkg="model``

are the same, when a **single background component** is set.

**Comment by hamogu** [comment]
I suggest just a documentation change. If you have a model, you usually want it; if not you can remove it easily.
