### ISSUE TITLE
trig functions period hard max

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#1691]
This is really more a question than an issue ... and very low priority at that.

I'm fitting aspect solution data with a cosine() model component.  I was surprised to see that the period parameter's hard max was set to 10, since as the doc says it's in units of the independent axis.  In my case I was trying to use the TIME value, in seconds, but since the periods are typically ~700|1000, it didn't work.   It was trivial to divide TIME by 1000 to work in ksec ... but just curious if there's an actual reason that the period is capped at '10' ?

**Comment by DougBurke** [comment]
I've been meaning to look at how that code is doing the fitting...

From

```
>>> from sherpa.models.basic import Cos
>>> mdl = Cos()
>>> for p in mdl.pars:
...     print(f"{p.name:12s}  {p.val}  {p.min} {p.hard_min}  {p.max} {p.hard_max}")
... 
period        1.0  1e-10 1.1754943508222875e-38  10.0 3.4028234663852886e+38
offset        0.0  0.0 0.0  3.4028234663852886e+38 3.4028234663852886e+38
ampl          1.0  1e-05 0.0  3.4028234663852886e+38 3.4028234663852886e+38
```

you should just be able to say something like

```python
mdl.period.set(7000, max=10000)
```

to bump the limit, since `hard_max` is set to an appropriately-large value.

As to the default values, I think it's that we don't really see people using these models, so there's been no pressure to review the default parameter ranges (my personal bug-bear at the moment is Box1D's `ampl` parameter having a `max` of 1...)

**Comment by kglotfelty** [comment]
Humm ... I end up getting different fit results if I try using `.set` with values > 10.  

Using the attached data & script

```bash
% python doit.py foo
Dataset               = 1
Method                = neldermead
Statistic             = leastsq
Initial fit statistic = 0.17185
Final fit statistic   = 0.00016556 at function evaluation 314
Data points           = 20037
Degrees of freedom    = 20034
Change in statistic   = 0.171685
   wave.period    0.999404    
   wave.offset    0.43144     
   wave.ampl      0.00222818  
```
These values are good/expected.

But keeping the TIME values in units of seconds and using `.set` to set limits > 10, I get

```bash
% python doit.py sec
Dataset               = 1
Method                = neldermead
Statistic             = leastsq
Initial fit statistic = 0.17185
Final fit statistic   = 0.0501262 at function evaluation 177
Data points           = 20037
Degrees of freedom    = 20034
Change in statistic   = 0.121724
   wave.period    1003.73     
   wave.offset    0.142576    
   wave.ampl      1.00049e-05 
```

The `.period` is close, but the `.ampl` is way off.

Weird.






[cos_fit.tar.gz](https://github.com/sherpa/sherpa/files/10700356/cos_fit.tar.gz)

**Comment by DougBurke** [comment]
:boo:

**Comment by DougBurke** [comment]
So, there's a couple of things that are going on here, and I think it's down to scaling.

- my initial investigation was into the fact that the offset is actually different. Rather than 0 to 3 you'd want it to be 0 to 3000 when fitting seconds
- but then I noticed that the amplitude of ~ 2e-3 is quite small, so the least-square differences are small

So, I was able to get a good fit for this particular dataset by doing either

```python
if units == "sec":
    wave.offset.max = 3000
    wave.offset = 400
```

or, probably a better approach (but you may want to bump up to 1e4 or 1e5???) as it seems less sensitive to the offset value, at least for this dataset

```
detxy = 1000 * tab.get_column(colname).values
```

Here's the results from these two approaches:

```
-- mode=sec hack1=True hack2=False
wavebetter1
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   wavebetter1.period thawed         1000          100         3000           
   wavebetter1.offset thawed          400            0         3000           
   wavebetter1.ampl thawed        0.002        1e-05         0.01           
------------
Dataset               = better1
Method                = neldermead
Statistic             = leastsq
Initial fit statistic = 0.00233972
Final fit statistic   = 0.00016556 at function evaluation 368
Data points           = 20037
Degrees of freedom    = 20034
Change in statistic   = 0.00217416
   wavebetter1.period   999.404     
   wavebetter1.offset   431.44      
   wavebetter1.ampl   0.00222818
```

and

```  
-- mode=sec hack1=False hack2=True
wavebetter2
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   wavebetter2.period thawed         1000          100         3000           
   wavebetter2.offset thawed            0            0         3000           
   wavebetter2.ampl thawed            2         0.01           10           
------------
Dataset               = better2
Method                = neldermead
Statistic             = leastsq
Initial fit statistic = 171850
Final fit statistic   = 165.56 at function evaluation 599
Data points           = 20037
Degrees of freedom    = 20034
Change in statistic   = 171685
   wavebetter2.period   999.404     
   wavebetter2.offset   431.44      
   wavebetter2.ampl   2.22818     
```

**Comment by kglotfelty** [comment]
doh!  :disappointed:    I should have caught that.  Mea culpa.
