### ISSUE TITLE
SystemError: <built-in function dmGetDataType>returned NULL without setting an error for crates backend

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1702]
A user reported:
```
Sorry to bother you, but I'm having a problem using the
TAUS response files in sherpa... The commands I'm using
and the error are below. I get this error for all TAUS
response files. (The good news is, I can get it working
with xspec, so I can use that if I have to.)  

set_source(1,xstbabs.t1 * xspowerlaw.p1)
t1.nh = 0.1
p1.phoindex = 1
p1.norm = 1
fake_pha(1, "G140M.arf", "G140M.rmf",2e5)
SystemError: <built-in function dmGetDataType>returned NULL without setting an error 
```

The TAUS response files are here: https://www.dropbox.com/s/acyshj8dcrsf9xw/G140M.arf?dl=0 and https://www.dropbox.com/s/92xrvbl2lywrdgk/G140M.rmf?dl=0 .

TAUS is one component of the proposed Arcus missions and I generated those files, so my first suspicion was that I screwed that up. However, these files work in ISIS (which is typically pretty strict on standards), on XSPEC, and in Sherpa with the astropy backend; they only fail in Sherpa with the crates backend. That indicates that maybe the problem is with crates, not with me; thus I'm opening an issue here to at least track this - I don't really know how to debug something that's inside "dmGetDataType".

**Comment by hamogu** [comment]
This is with 4.14. I have not yet tested with CIAO 4.15.

**Comment by DougBurke** [comment]
So I don't have time to look at this today,  but

- dmGetDataType is from a low- level module (cxcdm, which is what created
is built on)
- so it's probably a ciao rather than sherpa error
- however,  it may be a combination of crates and sherpa

If run with

    Import sys
    Sys.tracebacklimit = 10

from sherpa (excuse the auto-capitalisation) we should see since more info

And definitely try with 4.15 as there have been changes

**Comment by DougBurke** [comment]
So, it's still present in 4.15.

```
sherpa-4.15.0> arf = unpack_arf("G140M.arf")

sherpa-4.15.0> rmf = unpack_rmf("G140M.rmf")
SystemError: <built-in function dmGetDataType> returned NULL without setting an exception

sherpa-4.15.0> import sys

sherpa-4.15.0> sys.tracebacklimit = 10

sherpa-4.15.0> rmf = unpack_rmf("G140M.rmf")
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-1170c50df7ea>", line 1, in <module>
    rmf = unpack_rmf("G140M.rmf")
  File "<string>", line 1, in unpack_rmf
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/astro/ui/utils.py", line 6011, in unpack_rmf
    return sherpa.astro.instrument.RMF1D(sherpa.astro.io.read_rmf(arg))
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/astro/io/__init__.py", line 407, in read_rmf
    data, filename = backend.get_rmf_data(arg)
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/astro/io/crates_backend.py", line 795, in get_rmf_data
    ebounds = _get_crate_by_blockname(rmfdataset, 'EBOUNDS')
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/astro/io/crates_backend.py", line 389, in _get_crate_by_blockname
    crate = dataset.get_crate(ii)
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/pycrates/cratedataset.py", line 175, in get_crate
    tmpcrate._read_header()
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/pycrates/tablecrate.py", line 235, in _read_header
    backend.read_subspace(self)
  File "/home/dburke/miniconda3/envs/ciao415-py310/lib/python3.10/site-packages/pycrates/io/dm_backend.py", line 1360, in read_subspace
    dtype = dm.dmGetDataType(col)
SystemError: <built-in function dmGetDataType> returned NULL without setting an exception

```

The issue is that crates tries to understand "more" of the data than XSPEC or AstroPy (ie it tries to implement a more-advanced data model thanjust basic data and a key-value store). However, the underlying library isn't being particularly helpful in explaining what the problem is. It's something to do with the subspaceof the EBOUNDS blocks but it doesbnt' look terrible:

```
% dmlist G140M.rmf blocks
 
--------------------------------------------------------------------------------
Dataset: G140M.rmf
--------------------------------------------------------------------------------
 
     Block Name                          Type         Dimensions
--------------------------------------------------------------------------------
Block    1: PRIMARY                        Null        
Block    2: MATRIX                         Table         6 cols x 29106    rows
Block    3: EBOUNDS                        Table         3 cols x 29106    rows
% dmlist G140M.rmf"[ebounds]" cols
 
--------------------------------------------------------------------------------
Columns for Table Block EBOUNDS
--------------------------------------------------------------------------------
 
ColNo  Name                 Unit        Type             Range
   1   CHANNEL                           Int8           0:2147483647         
   2   E_MIN                keV          Real8          -Inf:+Inf            
   3   E_MAX                keV          Real8          -Inf:+Inf            
% dmlist G140M.rmf"[ebounds]" subspace
 
--------------------------------------------------------------------------------
Data subspace for block EBOUNDS: Components: 1 Descriptors: 3 
--------------------------------------------------------------------------------
 
 --- Component 1 --- 
   1 CHANNEL              Int8                0:2147483647 
   2 E_MIN                Real8               DEFAULT
   3 E_MAX                Real8               DEFAULT
```

I can replicate the error slightly-more direclty with the following, but it doesn't really help

```
sherpa-4.15.0> cr = read_file("G140M.rmf[EBOUNDS]")

sherpa-4.15.0> cr._read_header()
SystemError: <built-in function dmGetDataType> returned NULL without setting an exception
```

**Comment by DougBurke** [comment]
I believe the problem is the use of `TFORM<n>=K` for the channel column. I think the OGIP standard mandates a 16-bit Int but we would probably also accept a 32-bit Integer, but CIAO doesn't yet support 64-bit ints (I assume that is what TFORM=K is, but I admit to my eye glazing over whenever I have to dig around the FITS documentation on TFORM settings).

**Comment by hamogu** [comment]
@DougBurke Thanks for investigating. With that in mind, I can fix the input file that I made for this case (which I now remember I've done before for other files I generated from scratch). That said, the world is moving to 64 bit computer systems, so CIAO just accepting 64-bit ints is a good long-term goal.

**Comment by DougBurke** [comment]
It's on the long-term plan, and changes have been made the last few
releases, but it's not as easy as saying "now there are int64"
...Unfortunately.

Doug

**Comment by hamogu** [comment]
I'll close this issue as "resolved" since it's not really something we can address in sherpa itself; we'll just have to wait for crates to deal with that - and when it does we get this in sherpa for no extra work; for now, I'm advising users who hit this to simply switch to the pyfits backend.
