### ISSUE TITLE
could set_stat accept parameters?

### ISSUE THREAD

**Issue by matteobachetti** [sherpa/sherpa#171]
Hello again,

For some complicated statistics, like the QPO statistics suggested by Barret & Vaughan, _ApJ_ **746**, 131 (2012), it may be necessary to pass dnamically a parameter to the likelihood function (in this case, the number of summed spectra). In the current situation, if I'm not mistaken, one has to create a different likelihood function for each number of summed spectra, hardcoding this value. Would it be possible to add an option to `set_stat`, that allows to pass additional parameters to the likelihood function?

Thanks in advance, 
Matteo

**Comment by DougBurke** [comment]
The following paragraph is a long way of saying that there should be a way to do this, but it may not be via the `set_stat` call!

We do have the idea of "extra info" for the methods - e.g. see `sherpa.astro.ui.set_method_opt` and `sherpa.astro.ui.get_method_opt` - so there is precedence for this idea. However, I'm not sure yet whether the info needed here to be passed through to the likelihood is the same "type" of info we have for the methods. In other words, the fact that this is "dynamic" information (e.g. the number of spectra) strikes me as a different case to something like the convergence tolerance to use in the optimizer, and perhaps there's a different way that this information should be passed through to the likelihood function.

**Comment by DougBurke** [comment]
I wonder if some of the work in PR #287 is relevant to this discussion?

**Comment by matteobachetti** [comment]
@DougBurke sorry for the late reply and thanks for the pointer. Yes, it looks very relevant to this.

**Comment by DougBurke** [comment]
@matteobachetti please don't hesitate to ask questions, but as we're currently working on the CIAO 4.9 release the response may be slower than we'd like!

As #287 has just been accepted, the `sherpa.fit.Fit` object gets the statistic value by calling it with a `sherpa.data.SimulFitData` object [1] - which is essentially a list of  `sherpa.astro.data.DataPHA` [2] objects (well, it could be any of the data objects, but I think it's safe to assume you are using PHA files here ;-). So, you should now be able to write a statistic object which can calculate the number of data sets it has been sent. This assumes that, when you say "summed spectra", you mean you are doing a simultaneous fit to n spectra.

Note that the following links are not guaranteed to stay valid, as this is not an official location for the documentation!
 
[1] http://hea-www.harvard.edu/~dburke/playground/sherpa/data/data.html
[2] http://hea-www.harvard.edu/~dburke/playground/sherpa/data/astrodata.html

**Comment by matteobachetti** [comment]
@DougBurke great! Thanks, I'll try this out (and you can close this I think).

**Comment by DougBurke** [comment]
Okay - I'll close this but re-open it, or contact me, when you hit a problem.
