### ISSUE TITLE
An error is reported when configuring xspec in Sherpa

### ISSUE THREAD

**Issue by MengJisans** [sherpa/sherpa#1713]
Hello everyone ,
I installed the latest version of [CIAO ](https://cxc.harvard.edu/ciao/) and [sherpa](https://sherpa.readthedocs.io/en/4.15.0/install.html) using the 

```
conda create -n ciao-4.15 \
  -c https://cxc.cfa.harvard.edu/conda/ciao \
  -c conda-forge \
  ciao sherpa ds9 ciao-contrib caldb_main marx
```
then,
`conda install -c sherpa sherpa` command:
Using `conda list` got
```
ciao                      4.15.1           py39h50a7cbf_0    https://cxc.cfa.harvard.edu/conda/ciao
ciao-contrib              4.15.1                     py_1    https://cxc.cfa.harvard.edu/conda/ciao
xspec-modelsonly          12.12.1c             h707b37c_0    https://cxc.cfa.harvard.edu/conda/ciao
sherpa                    4.15.0           py39h3fd9d12_0    sherpa

```
I carefully read the introduction of sherpa with [xspec](https://sherpa.readthedocs.io/en/4.15.0/install.html) and, the following variables should be configured in the setup.cfg f file.Difficulty is, I can't find the file.

**Comment by DougBurke** [comment]
Why do you have the second install line here - that is

    conda install -c sherpa sherpa

**Comment by MengJisans** [comment]
I installed ciao first and then used this command to install sherpa. I'm sorry that I didn't use github syntax to express it.

**Comment by DougBurke** [comment]
Why are you trying to build Sherpa when you have already installed a version with CIAO?

**Comment by hamogu** [comment]
Yes, but what is confusing is that this first step:
```
conda create -n ciao-4.15 \
  -c https://cxc.cfa.harvard.edu/conda/ciao \
  -c conda-forge \
  ciao sherpa ds9 ciao-contrib caldb_main marx
```
should have installed sherpa and the xspec models already (notive how "sherpa" is listed in the last line). So, if that first command was successful, you can use sherpa right away, you don't have to do `conda install -c sherpa sherpa` after that.

So, what is the error that you have?
The title of this issue says "An error is reported when configuring xspec in Sherpa". Can you post the error message tht you actually get?

**Comment by MengJisans** [comment]
Ok, thank you
```
 python -c 'from sherpa.astro import xspec'
Traceback (most recent call last):
  File "/home/mj/miniconda3/envs/ciao-4.15/lib/python3.9/site-packages/sherpa/astro/xspec/utils.py", line 24, in <module>
    from . import _xspec
ImportError: cannot import name '_xspec' from partially initialized module 'sherpa.astro.xspec' (most likely due to a circular import) (/home/mj/miniconda3/envs/ciao-4.15/lib/python3.9/site-packages/sherpa/astro/xspec/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mj/miniconda3/envs/ciao-4.15/lib/python3.9/site-packages/sherpa/astro/xspec/__init__.py", line 113, in <module>
    from .utils import ModelMeta, version_at_least, equal_or_greater_than
  File "/home/mj/miniconda3/envs/ciao-4.15/lib/python3.9/site-packages/sherpa/astro/xspec/utils.py", line 31, in <module>
    raise ImportError("XSPEC support is not enabled") from ie
ImportError: XSPEC support is not enabled
```

**Comment by hamogu** [comment]
I just repeated your steps on my computer and it all works. So, somewhere there is something missing on your side.

Are you using linux or Mac?

Did you activate the new conda environment before calling python with `conda activate ciao-4.15`?

Can you try `which python` and post the output, e.g. I get
```
(ciao-4.15) MoritzAirRoseGold ~/code/marxs> which python
/Users/guenther/mambaforge/envs/ciao-4.15/bin/python
```

**Comment by MengJisans** [comment]
@hamogu  am using linux, I have activated ciao-4.15, use `which python` to get.
`/home/mj/miniconda3/envs/ciao-4.15/bin/python`

**Comment by hamogu** [comment]
OK, can you get the output of `conda list`, which will start like this:
```
(ciao-4.15) MoritzAirRoseGold ~/code/marxs> conda list
# packages in environment at /Users/guenther/mambaforge/envs/ciao-4.15:
#
# Name                    Version                   Build  Channel
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
```
Your put will be longer, I'm just showing the first few lines, but I want to check which version of which packages you have so that I can try to reproduce your problem locally.

**Comment by MengJisans** [comment]
ok, this is part of the library I output using `conda list`
```
~$ conda list
# packages in environment at /home/mj/miniconda3/envs/ciao-4.15:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
astropy                   5.2.1            py39h389d5f1_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     22.1.0           py39h06a4308_0
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
caldb_main                4.10.2                        0    https://cxc.cfa.harvard.edu/conda/ciao
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cfitsio                   4.1.0                h9bf148f_0    https://cxc.cfa.harvard.edu/conda/ciao
ciao                      4.15.1           py39h50a7cbf_0    https://cxc.cfa.harvard.edu/conda/ciao
ciao-contrib              4.15.1                     py_1    https://cxc.cfa.harvard.edu/conda/ciao
comm                      0.1.2            py39h06a4308_0
contourpy                 1.0.7            py39h4b4f3f3_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
```

**Comment by hamogu** [comment]
Can you post your complete output? I see that you have the same version that I can see, but there must be a difference somewhere?

**Comment by MengJisans** [comment]
I put the full output above.

**Comment by DougBurke** [comment]
As @hamogu says above, if you've done

```
conda create -n ciao-4.15 \
  -c https://cxc.cfa.harvard.edu/conda/ciao \
  -c conda-forge \
  ciao sherpa ds9 ciao-contrib caldb_main marx
```

then you have Sherpa with XSPEC. I'd like to know if **just this step** lets you do the analysis you need.

Trying to re-build Sherpa is something you can do, but you have to have a very-specific reason for doing so.

**Comment by MengJisans** [comment]
Yes, I am still a beginner. For analyzing Chandra data, I can only follow the tutorial. However, there are problems in the current configuration environment, so that it cannot be performed.

**Comment by hamogu** [comment]
As @DougBurke said, something is wrong in your environment and it's likely to come from just being set up partially. However, we can't find out what exactly is wrong without the full ouput of everything you have tried to far. It's something in the way you installed sherpa separately. You cna see that in:
```
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
sherpa                    4.15.0           py39h3fd9d12_0    sherpa
sip                       6.7.7            py39h227be39_0    conda-forge
```
On my computer it says:
```
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
sherpa                    4.15.0          py310h75233e6_0    https://cxc.cfa.harvard.edu/conda/ciao
sip                       6.7.7           py310h7a76584_0    conda-forge
```

Notice that my sherpa comes straight from the CXC, while you build yours yourself.
Building Sherpa is possible, but a little more complicated and you don't have to do that unless you change the sherpa source code.

So, the fix is to delete your messed up environment and install again:

(only needed if you are in the ciao-4-15 enviroment) 
```
conda deactivate 
```
then
```
conda env remove -n ciao-4.15

conda create -n ciao-4.15 \
  -c https://cxc.cfa.harvard.edu/conda/ciao \
  -c conda-forge \
  ciao sherpa ds9 ciao-contrib caldb_main marx
```

We'll see how we can make it more clear in the documentation that building sherpa from source and all that XSPEC setup is ONLY needed when you work on developing the Sherpa source code; if you have a suggestion what we should write in the documentation, then please let us know.

**Comment by DougBurke** [comment]
I'm going to close this now. If you have issues analyzing Chandra data then I suggest you use the CXC HelpDesk at https://cxc.cfa.harvard.edu/helpdesk/ 

Good luck with those X-ray photons.
