### ISSUE TITLE
can I use pvalue plot with wstat?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1745]
I have

```python
np.random.seed(3287)
ui.set_stat("wstat")
print(f"stat = {ui.get_stat_name()}")
ui.get_pvalue_plot(null_model=null,
                   alt_model=alt,
                   conv_model=rsp,
                   num=5, numcores=1, recalc=True)
```

and this errors out with

```
stat = wstat
Traceback (most recent call last):
  File "/lagado.real/sherpa/sherpa-main/sherpa-test-data/sherpatest/testy.py", line 18, in <module>
    ui.get_pvalue_plot(null_model=null,
  File "<string>", line 1, in get_pvalue_plot
  File "/lagado2.real/local/anaconda/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/astro/ui/utils.py", line 10704, in get_pvalue_plot
    return super().get_pvalue_plot(null_model=null_model, alt_model=alt_model,
  File "/lagado2.real/local/anaconda/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/ui/utils.py", line 9173, in get_pvalue_plot
    results = pvalue(fit, null_model, alt_model,
  File "/lagado2.real/local/anaconda/envs/ciao415-py310/lib/python3.10/site-packages/sherpa/sim/simulate.py", line 233, in run
    raise TypeError("Sherpa fit statistic must be Cash or CStat" +
TypeError: Sherpa fit statistic must be Cash or CStat for likelihood ratio test
```

I would have thought we could use wstat here.

There's a larger issue here about how Sherpa gates certain functionality - in this case it's with

```python
        if not isinstance(stat, (Cash, CStat)):
            raise TypeError("Sherpa fit statistic must be Cash or CStat" +
                            " for likelihood ratio test")
```

that I have an ongoing low-level desire to improve, but there's no simple golden fix, so we need to treat each case we find.

**Comment by DougBurke** [comment]
A note about

> I guess there is a workaround and one can include a background model component in the source expression with a proper scaling of the background contribution.

This only works when the source and the background have the same response. If they have a different response then it is currently not possible (I believe). There's also #1754 (likely problems if using multiple datasets) that suffers from the same issue (that only one response can be used).

**Comment by anetasie** [comment]
@DougBurke Is the background response used in `wstat`?

**Comment by DougBurke** [comment]
No - so for wstat users it's okay as only the source response is used. It's more for #1377 that the possibility of a different response makes things tricky (well, there's a number of things that are tricky in that case).

**Comment by DougBurke** [comment]
@anetasie - from your comment above in https://github.com/sherpa/sherpa/issues/1745#issuecomment-1525718446

> Yes, it would be nice to add `wstat`. Current implementation of likelihood ratio is based on the assumption of Poisson likelihood, so `cstat` and `cash`. `wstat` treatment of the background assumes Poisson counts and it still leads to biased results ...

above. For me, there's no "real" difference between `cstat` and `wstat`, so if it works for `cstat` it should also work for `wstat`. The fact that `wstat` is biased doesn't really matter to the algorithm (in this case the LRT stuff). 

Or am I wrong?

**Comment by anetasie** [comment]
@DougBurke yes, I agree in both cases the algorithm should work.
