### ISSUE TITLE
plot_source incorrectly scaled with analysis factor >0

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#1825]
`plot_source` does not scaled properly Y values when `set_analysis` factor option is >0. 
The plot shows the source model plot with factors 0,1,2 and the curves are shifted in normalization, but the shape is the same.
E*f(E) should generate curves with varying shapes.

![plt_source_factors](https://github.com/sherpa/sherpa/assets/1213746/9c1d0a56-0b86-4c08-9f34-6c7196f8e5a9)

**Comment by DougBurke** [comment]
You can generate this with commands like

```
sherpa In [1]: load_pha("3c273.pi")
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi

sherpa In [2]: set_source(powlaw1d.pl)

sherpa In [3]: plot_source()

sherpa In [4]: plot_source(xlog=True, ylog=True)

sherpa In [5]: set_analysis("energy", factor=1)

sherpa In [6]: plot_source(overplot=True)

sherpa In [7]: set_analysis("energy", factor=2)

sherpa In [8]: plot_source(overplot=True)

```

Note that blue is factor=0, orange is factor=1, green factor=2

**Comment by DougBurke** [comment]
If you use `plot_model` you get

![sherpa](https://github.com/sherpa/sherpa/assets/224638/50e867f6-cd8f-44c5-9e7b-202b80f839c8)

```
sherpa In [9]: set_analysis("energy", factor=0)

sherpa In [10]: plot_model(xlog=True)

sherpa In [11]: plot_model(xlog=True, ylog=True)

sherpa In [12]: set_analysis("energy", factor=1)

sherpa In [13]: plot_model(overplot=True)

sherpa In [14]: set_analysis("energy", factor=2)

sherpa In [15]: plot_model(overplot=True)

sherpa In [16]: set_xlim(0.1, 12)
NameError: name 'set_xlim' is not defined

sherpa In [17]: xlim(0.1, 12)
Out[17]: (0.1, 12)

sherpa In [18]: ylim(1e-2, 1e3)
Out[18]: (0.01, 1000.0)

```

**Comment by DougBurke** [comment]
These plots are created by

https://github.com/sherpa/sherpa/blob/c0fc488832195404adeebed6106221b1771a41cb/sherpa/astro/plot.py#L264-L364

which has

```python
        xmid = abs(self.xhi - self.xlo)

        sqr = to_latex('^2')

        self.xlabel = f'{self.units.capitalize()} ({quant})'
        self.ylabel = f'%s  Photons/sec/cm{sqr}%s'

        if data.plot_fac == 0:
            self.y /= xmid
            self.ylabel = self.ylabel % (f'f({prefix_quant})',
                                         f'/{quant} ')

        elif data.plot_fac == 1:
            self.ylabel = self.ylabel % (f'{prefix_quant} f({prefix_quant})', '')

        elif data.plot_fac == 2:
            self.y *= xmid
            self.ylabel = self.ylabel % (f'{prefix_quant}{sqr} f({prefix_quant})',
                                         f' {quant} ')
        else:
            raise PlotErr('plotfac', 'Source', data.plot_fac)
```

I think I would argue about the naming of the `xmid` variable here ..., It;s currently defined as the width of the x bins. I changed that line in #107 but just adding spaces (no functional change). Prior to that it hasn't been changed since the initial commit - https://github.com/sherpa/sherpa/commit/9ccf0e72acb9f85fdd20a8feea16ea774e1288b3

I would argue that this class should ideally be getting the data to plot from the data object [so we do not replicate logic]], but this is a specialized use case that we may not have an API for in the data class.

**Comment by DougBurke** [comment]
Hmmm. This looks like it also ignores the `type=rate/counts" option.

Yup, this creates the same plot:

```
sherpa In [8]: set_analysis("energy", type="counts")

sherpa In [9]: plot_source()

sherpa In [10]: set_analysis("energy", type="rate")

sherpa In [11]: plot_source(overplot=True)
```
