### ISSUE TITLE
filtering with group/ungroup

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#1827]
This might be already noted somewhere, but I was using group/ungroup and have a comment on the current behaviour.
It is good to have the current filter information, so one can see the energy range. Thanks!

I fit data with full resolution and then group for plotting. When I ungroup the filter is not back to the initial filter of the ungroup channels. The expectation would be to have the original filter for ungroup data, but this would most likely involve a lot of additional bookkeeping. I suggest we  document this behaviour in our documentation in a more prominent location, maybe in a separate section of RTD?

```

sherpa In [169]: group_counts(5)
dataset 1: 0.511:6.9934 -> 0.0073:7.2124 Energy (keV)
sherpa In [170]: ignore(None,0.5)
dataset 1: 0.0073:7.2124 -> 0.6132:7.2124 Energy (keV)
sherpa In [171]: ungroup()
dataset 1: 0.6132:7.2124 Energy (keV) (unchanged)
sherpa In [174]: notice()
dataset 1: 0.6132:7.2124 -> 0.0073:14.9504 Energy (keV)
sherpa In [188]: ignore(7.0,None)
dataset 1: 0.0073:14.9504 -> 0.0073:6.9934 Energy (keV)
sherpa In [189]: ignore(None,0.5)
dataset 1: 0.0073:6.9934 -> 0.511:6.9934 Energy (keV)
```

**Comment by DougBurke** [comment]
Now that #1855 has been merged is this still an issue. I really do not understand what "it should just do what I want it do to" means here!

**Comment by anetasie** [comment]
@DougBurke This issues is now fixed.
