### ISSUE TITLE
save_all for 2D dataset does not save set_psf() 

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#1873]
I noticed from a CIAO helpdesk ticket that the sherpa `save_all` output does not save the equivalent of `set_psf`. 

For example:

```python
load_data('a.img')
load_psf('p0', 'a.psf')
set_source(gauss2d.g0)
set_psf(p0)

save_all('my.script')
```
and look at the `my.script` output, it loads the PSF,

```python
...
load_psf("p0", "a.psf")
p0.size = (101, 101)

p0.center = (50, 50)

create_model_component("gauss2d", "g0")
...
set_source(1, gauss2d.g0)
```

but it never runs `set_psf`.  When I run the script (well, I just cut-n-pasted it) then the PSF is not actually used.

Tested Linux RH8 CIAO 4.14, 4.15 and ciaox (Sherpa 4.15.1+196.g15479eb1)

---

#### dummy data

```bash
echo 50 50 > a
aconvolve "a[bin col1=-0.5:100.5:1,col2=-0.5:100.5:1]" a.psf "lib:gaus(2,5,5,5,5)" norm=none cl+
python << EOM
from sherpa.astro.ui import *;
load_data("a.psf")
load_table_model("pp", "a.psf")
set_source(pp)
fake()
save_data("a.img", ascii=False, clobber=True)
EOM
```

**Comment by DougBurke** [comment]
So, it's supposed to add the `set_psf` line - see

https://github.com/sherpa/sherpa/blob/b230164d33cabe3ac79ddbfd5396dd2031a2de3e/sherpa/astro/ui/serialize.py#L819-L828

but it isn't. One of the problems with a big "try/except` block - it's easy to not notice it's skipping for some other issue....

**Comment by DougBurke** [comment]
Do, it's because `id` isn't defined here, so it's using the Python `id` symbol, and causing no-end of problems.

Doh.
