### ISSUE TITLE
UI layer and multi-panel plots

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1897]
I was hoping the following would create three plots in a single column, but it created a 2 by 2 grid.

- should it have worked
- how do we ant this to work

This is related to 

- #1868 
 
but is the user experience part (for the UI layer), which can be quite different to the low-level API. 

Example

```
In [71]: get_split_plot().cols = 1

In [72]: get_split_plot().rows = 3

In [73]: print(get_split_plot())
rows   = 3
cols   = 1
plot_prefs = {'left': None, 'right': None, 'bottom': None, 'top': None, 'wspace': 0.3, 'hspace': 0.4}

In [74]: plot("data", 1, "data", 2, "data", 3)

In [75]: print(get_split_plot())
rows   = 2
cols   = 2
plot_prefs = {'left': None, 'right': None, 'bottom': None, 'top': None, 'wspace': 0.3, 'hspace': 0.4}
```

**Comment by DougBurke** [comment]
This is actually hard-coded into the `plot` code:

https://github.com/sherpa/sherpa/blob/e66449c62e6b106ffc3af92688cf87d7d4a9fb51/sherpa/ui/utils.py#L13064-L13067

**Comment by hamogu** [comment]
There are a few assumptions hardcoded. I'll have ot get to that when I get to plotting datastacks...

**Comment by DougBurke** [comment]
Coming in 4.17.0, thanks to 

- #2126

we can now do

```
In [1]: from sherpa.astro.ui import *
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'

In [2]: load_arrays(1, [1, 2, 3], [2, 4, 9]); load_arrays(2, [100,200],[400,300])

In [3]: load_arrays(3, [-400, -300, -200], [-50, -80, 2])

In [4]: plot("data", 1, "data", 2, "data", 3)

In [5]: from matplotlib import pyplot as plt

In [6]: plt.savefig("/home/dburke/sherpa-1.png")
```
![sherpa-1](https://github.com/user-attachments/assets/e0a08627-feaf-409a-97c7-3becd93aac5f)

We can change the layout directly with the `cols` and `rows` arguments:
 
```
In [7]: plot("data", 1, "data", 2, "data", 3, cols=1)

In [8]: plt.savefig("/home/dburke/sherpa-2.png")
```

![sherpa-2](https://github.com/user-attachments/assets/ed526c22-060b-4a26-9ca4-07fae6400c38)

Or using the split-plot prefs like I tried above:

```
In [9]: get_split_plot().rows = 1

In [10]: get_split_plot().cols = 3

In [11]: print(get_split_plot())
rows   = 1
cols   = 3
plot_prefs = {}

In [12]: plot("data", 1, "data", 2, "data", 3)

In [13]: plt.savefig("/home/dburke/sherpa-3.png")
```

![sherpa-3](https://github.com/user-attachments/assets/0a52a32b-00ed-4a83-b22b-0ed1761924cc)

You can even have more cells than plots, if you so wish:

```
In [15]: plot("data", 1, "data", 2, "data", 3, cols=4, rows=2)

In [16]: plt.savefig("/home/dburke/sherpa-4.png")
```

![sherpa-4](https://github.com/user-attachments/assets/0381a080-3f9e-4bff-9ff0-0561b4ea9f79)

And `overplot` now works:

```
In [17]: get_split_plot().cols = 2

In [18]: plot("data", 1, "data", 2, "data", 3, color="orange", alpha=0.4)

In [19]: plot("data", 2, "data", 1, "data", 1, color="brown", alpha=0.4, overplot=True)

In [20]: plt.savefig("/home/dburke/sherpa-5.png")
```
![sherpa-5](https://github.com/user-attachments/assets/b40ac91d-8f61-4762-920d-05a970c3a262)
