### ISSUE TITLE
add an `image` method to our plotting backends

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1902]
In #1375, I call for an `image` method to display 2D data along the same lines of `plot`, `contour`, and `histogram`. Early versions of #1382 had that, but I removed it because @DougBurke saw the need for more discussion. 
I'm opening a separate issue now to track this in more detail than in #1375.

In particular, I just discovered that this kind of exists in Sherpa, but it's not part of the plotting backend, but instead a matplotlib-specific implementation is hardwired into https://github.com/sherpa/sherpa/blob/main/sherpa/astro/data.py#L791
That code ought to be moved into the `pylab_backend` and then I can create equivalent code for other backends.

**Comment by DougBurke** [comment]
Is this conceptually any different to 

- #347
- #1517

[just trying to link together relevant discussions]

**Comment by hamogu** [comment]
Those issues are both about how to integrate that in the UI. To tackle them, the backend needs to be able to plot images, so this is a sub-set of those issues. However, it's close enough that we probably don't need a separate issue. (I searched for "image" in the list of open issues before I opened this one, but must have missed them.)

**Comment by DougBurke** [comment]
Well, this is now linked to those two issues so we don't lose your original analysis above!

**Comment by hamogu** [comment]
I also need this to make the tests in #1899 pass. So, what I'll do, is to add a image method to the plotting backend, but call it `_image` for now and we can make that an official part of the API after some more discussion (possibly involving WCS...)
