### ISSUE TITLE
are the CI:arch builds broken

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1903]
I recently had a PR labelled CI:arch fail with the following (the PR had nothing to do with parameters). I don't know if this is some oddity from merging #1653 (but I didn't thank that PR had included those changes, but I think this test was added in that PR so ..).

Leaving this here so we can refer to it if it happens again

```
_____________________ test_binop_string_with_custom_ufunc ______________________

    def test_binop_string_with_custom_ufunc():
        '''Repeat the previous test, but with a custom ufunc.'''
        def func(a, b):
            return a + b
    
        uf = np.frompyfunc(func, nin=2, nout=1)
        p, p2 = setUp_composite()
        comp = uf(p, p2)
>       assert repr(comp) == "<BinaryOpParameter 'func(model.p, model.p2)'>"
E       assert "<BinaryOpPar..., model.p2)'>" == "<BinaryOpPar..., model.p2)'>"
E         - <BinaryOpParameter 'func(model.p, model.p2)'>
E         ?                     ^^^^
E         + <BinaryOpParameter '?(model.p, model.p2)'>
E         ?                     ^

sherpa/models/tests/test_parameter.py:237: AssertionError

_____________________ test_binop_string_with_custom_ufunc ______________________

    def test_binop_string_with_custom_ufunc():
        '''Repeat the previous test, but with a custom ufunc.'''
        def func(a, b):
            return a + b
    
        uf = np.frompyfunc(func, nin=2, nout=1)
        p, p2 = setUp_composite()
        comp = uf(p, p2)
>       assert repr(comp) == "<BinaryOpParameter 'func(model.p, model.p2)'>"
E       assert "<BinaryOpPar..., model.p2)'>" == "<BinaryOpPar..., model.p2)'>"
E         - <BinaryOpParameter 'func(model.p, model.p2)'>
E         ?                     ^^^^
E         + <BinaryOpParameter '?(model.p, model.p2)'>
E         ?                     ^

sherpa/models/tests/test_parameter.py:237: AssertionError
```

**Comment by hamogu** [comment]
This test tests a custom ufunc, so it relies on numpy to give of the name of that function. If numpy does not provide it, we can't get it. I think the solution is to do something like `self.arg.fullname.replace('?', 'user_func') and special case that in the test on the aarch64 architecture or just xfail the test on arch64. Either is easy to do, but I'll wait until we see that failure at least one more time before I implement that.

**Comment by DougBurke** [comment]
So here's the weekly build that just failed - https://github.com/sherpa/sherpa/actions/runs/6266749067/job/17018352344

I don't understand why numpy doesn't set the name here....

**Comment by hamogu** [comment]
Well, I'm not going to debug numpy here. We probably have <= 1 Sherpa users on Linux ARM, so I'll declare this a numpy bug[*]. I do notice that our ARM tests run with a fairly old numpy. I'll open a PR to update that and see if it goes away. If it does, then I suggest we just update numpy or arm64 and leave it as that. If not, I'll file a bug report upstream and we can work around it in the text (e.g. xfail for certain architecture).

*: I looked in the numpy issue tracker and can't easily find it there, but with > 2k issues it's not unlikely that I missed something. There are several issues with subtle differences on exotic architectures, though. Without direct access to a machine it's hard for me to debug this though.
