### ISSUE TITLE
Move grouping methods up in in hirachy?

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1930]
I thought we had a feature request for that, but I can't find it now. 

`DataPHA` has all those nice grouping methods. However, I often find myself using Sherpa as a general fitting program, where my data is not PHA data, and does not have ARFs or RMFs attached; yet, I still want to group that data for the same reasons we often group PHA data (e.g. get a minimum number of counts/objects in one bin).

My data could be "flare energies" where I want to fit a powerlaw to the number of flares in per energy bin dN/dE, or masses of stars in a cluster (again, I want to fit the stellar mass function). All that would be easy if I had the grouping and filtering on `Data1DInt`. As it stands, I either prepare my data by making fixed bins before I convert it into a Sherpa dataclass (but than I can't change the binning later) or I pretend that this is PHA data and make fake ARF=1 and diagonal RMFs (which then makes ofr strange labels on plots etc.). Either is akward. 

Fundamentally, there is no reason why we can't move the grouping and filtering higher up in the data class hierarchy. It requires some moving code around and testing to disentangle the grouping from the PHA datamodel (e.g. can't assume we read in a default grouping column) but it should not be hard.

**Comment by DougBurke** [comment]
I think this is the same as #1450 (but too lazy to check)

**Comment by DougBurke** [comment]
And actually it is unfortunately not a "simple" change, as the two complexities of the DataPHA class are

a) the independent axis (channels) is different to the axis used to evaluate the models [which is not relevant here]
b) the fact that the number of "bins" is different to the number of "bins" in the independent axis complicates the design

Obviously it can be done, it is just not as easy as "copy a few bits of code". Especially as the existing grouping code assumes the data is 1D, not ND....

**Comment by hamogu** [comment]
It would have to be moved to either `Data1DInt` or a mix-in class that several classes can inherit from (`Data1DReGroupable`).

**Comment by hamogu** [comment]
And, yeah, #1450 is the one I remembered commenting on but could not find. So closing as duplicate.
