### ISSUE TITLE
helpdesk URL

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#1931]
https://github.com/sherpa/sherpa/blob/80b22a87b77d73f21444bd3a159f16df14af6a57/docs/bugs.rst?plain=1#L11

We should update to use the osTicket URL:  `/help/` instead of `/helpdesk/`

**Comment by DougBurke** [comment]
I assume the `/helpdesk` URL will remain as a redirect, at least for a "while"?

**Comment by kglotfelty** [comment]
Ad infinitum :infinity:  

That's the old landing page for the Wonderdesk system which has a link to the new osTicket page (so not a HTTP redirect).
