### ISSUE TITLE
ERROR: Failed building wheel for sherpa 

### ISSUE THREAD

**Issue by raviking47** [sherpa/sherpa#1955]
Failed to build sherpa
ERROR: Could not build wheels for sherpa, which is required to install pyproject.toml-based projects

**Comment by hamogu** [comment]
We're happy to try to help you, but you will have to provide a bit more information. When I install sherpa it works, so something is different on your computer.

Can you post the entire output you get? How do you install sherpa? Using pip or from source? Which operating system do you use? Which Python version?

**Comment by DougBurke** [comment]
I'm going to close this for now, but please re-open it if you can provide the information we need.
