### ISSUE TITLE
Move ignore/notice and binning from DataPHA to Data1DInt (or even higher in the hierachy)

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#2002]
One of the things Sherpa is really good at is the on-the-fly rebinning and ignoring/noticing of data. Yes, there are some remaining issues, but for the most part it works really well. We have a number of pre-defined binning solutions (by SNR, by number of counts, by bin width), our plots work this it, we have docs and tests.

Unfortunately, we provide this functionality only in `DataPHA`, while I often need it in non-PHA data. 

## Proposal
Move the binning and notice/ignore functionality from `DataPHA` to higher up in the hierarchy of data classes

## Use cases
This is just a short list of examples where I personally would have liked this functionality in `Data1dInt` recently myself. I could come up with more use cases, if we need to.

- Fit in the cross-dispersion direction of X-ray grating data: it's X-ray data, but it's not in the PHA form because I'm looking at the cross-dispersion profile.
  - either for instrumental studies (yes, I work for the CXC)
  - or because I have two close objects where the dispersed spectra partially overlap (my XMM observations of SU Aur and AB Aur)
- Fit a distribution to countable objects, in my case young stars in a star forming regions, where I want the initial mass distribution as fitted to my list of stellar masses.

## Workarounds
We can work around this. Either I use `DataPHA` is a diagonal response and some use of channel (but there are hoops if my independent axis is not all positive) or I use `Data1DInt` and just do the binning myself in numpy outside of Sherpa. Possible, but much less convenient.

### Note
I thought we had an issue about it, but I can't find it and I just run into it again, so I'm opening a new one here.

**Comment by DougBurke** [comment]
There's two related about moving logic from `DataPHA` into an "earlier" class

- #1450 
- #1466

**Comment by hamogu** [comment]
I'm closing this as a dublicate then.
