### ISSUE TITLE
FITS metadata can be wrong in FITS files created with the astropy backend (e.g. save_data)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#203]
# Overview

The Crates backend removes certain "structural" FITS keywords from the header block stored with data objects. This means that it's "safe" to copy over the remaining values to FITS output files. This filtering does not happen with the astropy backend, which can result in unwanted keywords being passed through to the output file. This can cause confusion in downstream software.
# Details

This was noticed in testing out the #102 fix in the 4.8.1 release candidate, but is separate from that code. 

The test case is basically

```
ui.load_data('bob.fits')
ui.save_data('/tmp/src.fits', ascii=False, clobber=True)
```

which I have run, for the same input file, for Sherpa in CIAO 4.8 (so using the crates backend) and using astropy 1.1.2 with the 4.8.1 release branch.
- CIAO 4.8 output

```
% dmlist /tmp/src2.fits blocks

--------------------------------------------------------------------------------
Dataset: /tmp/src2.fits
--------------------------------------------------------------------------------

     Block Name                          Type         Dimensions
--------------------------------------------------------------------------------
Block    1: PRIMARY                        Null        
Block    2: SPECTRUM                       Table         2 cols x 1024     rows
% dmlist /tmp/src2.fits cols

--------------------------------------------------------------------------------
Columns for Table Block SPECTRUM
--------------------------------------------------------------------------------

ColNo  Name                 Unit        Type             Range
   1   CHANNEL                           Real8          -Inf:+Inf            
   2   COUNTS                            Real8          -Inf:+Inf            
```
- 4.8.1 branch + AstroPy 1.1.2 output

```
% dmlist /tmp/src.fits blocks

--------------------------------------------------------------------------------
Dataset: /tmp/src.fits
--------------------------------------------------------------------------------

     Block Name                          Type         Dimensions
--------------------------------------------------------------------------------
Block    1: PRIMARY                        Null        
Block    2: SPECTRUM1                      Table         2 cols x 1024     rows
% dmlist /tmp/src.fits cols

--------------------------------------------------------------------------------
Columns for Table Block SPECTRUM1
--------------------------------------------------------------------------------

ColNo  Name                 Unit        Type             Range
   1   CHANNEL                           Real8          1.0:     1024.0      
   2   COUNTS                            Real8          1.0:     1024.0      
```

I've checked that the column data are the same in the two files; there are some header differences which are a little surprising to me but within expected bounds (I think).

The two points to note are:

1) The ranges of the columns are different: for CIAO they are undefined (not particularly useful, but it's a valid FITS file) whereas for the AstroPy output they are identical. This seems surprising, and is in fact wrong for the COUNTS column, as shown below.

2) The block name is different: `SPECTRUM` vs `SPECTRUM1`. Ideally they'd be the same, but I don't think that's too important.

Looking at the values for the two columns shows that the range for the COUNTS column is wrong, since the minimum value is 1 not 0:

```
% dmstat /tmp/src.fits  sig-
CHANNEL
    min:    1         @:    1 
    max:    1024          @:    1024 
   mean:    512.5 
    sum:    524800 
   good:    1024 
   null:    0 

COUNTS
    min:    0         @:    1 
    max:    3         @:    62 
   mean:    0.07421875 
    sum:    76 
   good:    1024 
   null:    0 

```

My guess is that the wrong range is being used when setting up the COUNTS column in the astropy backend, but I haven't looked at the code to confirm this.

**Comment by olaurino** [comment]
I can reproduce the range issue, but not the hdu name issue, with file `3c273.pi` from `sherpa-test-data`. However, I cannot say whether this is a regression because with 4.8.0 the data from this file could not even be saved using the astropy backend.

Also, it looks like the issue only applies to pha files.

**Comment by DougBurke** [comment]
I've just had a *very* quick look through the code, and it's not immediately obvious that we are doing anything to set the ranges, so there is a possibility that this is either an AstroPy issue, or a problem with how we're setting up the columns to write out. However, the code is a bit tortuous, and it's possible that my by-eye inspection has missed something, or I've assumed the code is going to be in one place when the try/except cascade in `sherpa.astro.ui.utils.save_data` actually causes it to go elsewhere.

**Comment by DougBurke** [comment]
I've added example input and output files as a gist: https://gist.github.com/DougBurke/6b6dca531e333255467f26674424f504

**Comment by DougBurke** [comment]
I believe the issue is in the header information, stored in the `sherpa.astro.data.DataPHA.header` field, is being copied over to the output file from the input file. For the crates backend, a number of FITS "structural" keywords are automatically removed from this set (and so will not get passed into the output file), but this does not happen with the astropy backend. So my guess is that the output file has these invalid keywords in them. Looking at the `out.fits` file in the gist above, I can see

```
% dmlist out.fits header,clean,raw | grep TLM
TLMAX1       = 1024                 /                     
TLMIN2       =       1.00000000     /                     
TLMIN1       = 1                    /                     
TLMIN4       = 0                    /                     
TLMAX2       =    1024.00000000     /                     
```
This matches the input file (although the ordering is different, but that's allowed):

```
% dmlist acisf01577_000N001_r0016_pha3.fits.gz header,clean,raw | grep TLM
TLMIN1       = 1                    /                     
TLMAX1       = 1024                 /                     
TLMIN2       =       1.00000000     /                     
TLMAX2       =    1024.00000000     /                     
TLMIN4       = 0                    /               
```
If I don't copy the header over, just the column data, then I don't see the problem:
```
from sherpa.astro import ui
from astropy.io import fits
ui.load_pha('acisf01577_000N001_r0016_pha3.fits.gz')
pha = ui.get_data()
col0 = fits.Column(name='CHANNEL',
                   array=pha.channel,
                   format=pha.channel.dtype.name.upper())
col1 = fits.Column(name='COUNTS',
                   array=pha.counts,
                   format=pha.counts.dtype.name.upper())
cols = [col0, col1]
tbl = fits.BinTableHDU.from_columns(cols)
tbl.name = "SPECTRUM"
tbl.writeto('test.out.fits', clobber=True)
```

Note there's no range added to the output file:

```
% dmlist test.out.fits cols
 
--------------------------------------------------------------------------------
Columns for Table Block SPECTRUM
--------------------------------------------------------------------------------
 
ColNo  Name                 Unit        Type             Range
   1   CHANNEL                           Real8          -Inf:+Inf            
   2   COUNTS                            Real8          -Inf:+Inf          
```
