### ISSUE TITLE
Fit class: what to do about changing the stats class?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#2063]
This has come out of the discussion at https://github.com/sherpa/sherpa/pull/2054#discussion_r1640438898

It could be considered a bug, a design decision, a new enhancement, or ...

The issue is that when directly using the `Fit` class you can change the statistic in use, but an internally-controlled object doesn't know about this change:

```
>>> from sherpa.data import Data1D
>>> from sherpa.models.basic import Scale1D
>>> from sherpa.stats import Cash
>>> d = Data1D('', [1, 2, 3], [3, 7, 2])
>>> m = Scale1D()
>>> from sherpa.fit import Fit
>>> f = Fit(d, m)
>>> f.fit()
<Fit results instance>
>>> f.stat.name, f._iterfit.stat.name
('chi2gehrels', 'chi2gehrels')
```

You don't need to have called the `fit` method to show this. The `_iterfit` attribute is a "hidden" part of `Fit`.

Now, I can change the `stat` attribute

```
>>> f.stat = Cash()
>>> f.stat.name, f._iterfit.stat.name
('cash', 'chi2gehrels')
```

However, note that `_iterfit` has not been updated. I believe that it should be updated too (ideally we'd be able to source the information from the same location but the current design makes that hard, as would - I think - making `_iterfit.stat` a read-only attribute to make sure users can't say `f.stat = CStat(); f._iterstat.stat = Chi2DataVar();`).

However, I am not 100% sure about this (I note that we only have two tests which would be affected by this behaviour).

I do not believe this is a problem for the UI layer since in the UI layer when we need a `Fit` object we create one on the fly, via the internal `_get_fit` method, so we never get into this situation where the stat field can get changed.

**Comment by hamogu** [comment]
I think it's a design problem and should be fixed, if possible with low effort.
We need find way for `_iterfit` to retain a reference to the "parent" `Fit` object so that we can just call whatever the statistic in that object is.

**Comment by DougBurke** [comment]
I ended up with a "simple" fix - when you change the `stat` attribute of `Fit` then you also change the `_iterfit.stat` method. It doesn't catch all cases but is a minimal fix. Ideally we'd only create the `_iterfit` object when needed (ie make it throwaway) but there's design issues that make this hard and I don't really want to spend too much time here as this is nerd-sniping myself to the nth degree...

I made the changes to #2054
