### ISSUE TITLE
asymmetric errors - notice/ignore

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#2090]
I entered a black hole  trying to work with the asymmetric errors. Our documentation definitely is lacking. My bad!

I have the data file,  but somehow I'm not able to link to this issue.

1/ 'load_ascii_with_errors()'  - I can read the file with the astropy backend, but it failed in CIAO with colkeys.  I guess this might be the crates issue?

```
sherpa In [1]: load_ascii_with_errors(1,"RLQ_81_data_ascii.dat", colkeys=['Log(X-ray_Lum)','Photon_Index','Photon_Index_min','Photon_Index_ma
          ...: x'],delta=True)
IOErr: Required column 'Log(X-ray_Lum)' not found in ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7']

sherpa In [2]: load_ascii_with_errors(1,"RLQ_81_data_ascii.dat", colkeys=['col5','col2','col3','col4'],delta=True)
```

Also the 'staterror' is set, but it is not clear how it is calculated, as the errors are asymmetric - is this an average of the input errors?
Is this staterror used in fitting?

```
Filter: 44.6993-45.7980 x
name      = RLQ_81_data_ascii.dat[opt colnames=none]
x         = Float64[52]
y         = Float64[52]
staterror = Float64[52]
syserror  = None
elo       = Float64[52]
ehi       = Float64[52]
```

2 'notice/ignore' seems to work, but actually fails when you try to display the data. 

```
sherpa In [49]: ignore()
dataset 1: 44.6993:45.798 x -> no data

sherpa In [50]: notice(45,46)
dataset 1: no data -> 45.4859:45.3843,45.6892:45.2895,45.9661:45.6546,45.9947,45.1834:45.8926,45.9442,45.8721:45.3682,45.5277,45.318:45.9423,45.2969:45.6138,45.6122:45.8463,45.3026:45.047,45.85:45.6701,45.798 x

sherpa In [51]: plot_data()
ValueError: 'yerr' (shape: (2, 52)) must be a scalar or a 1D or (2, n) array-like whose shape matches 'y' (shape: (28,))
```

**Comment by DougBurke** [comment]
The asymmetric error code is horribly untested, and horribly undocumented, so it wouldn't surprise me if there's problems. 

- the column name "Log(X-ray_Lum)" is probably not allowed by crates, but I could be wrong
- I can't remember how the "staterror" column is created
- I very-much doubt that the error bars are correctly displayed when using `plot_data`

Does `plot_data` work with no filter - i.e. after a `notice()` call?

**Comment by DougBurke** [comment]
So, #2091 will hopefully fix this issue, but just points out more issues with the asymmetric-error code ...

**Comment by anetasie** [comment]
@DougBurke yes, I was thinking that this was the case. Thanks.
