### ISSUE TITLE
link to xpa broken

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#2100]
https://github.com/sherpa/sherpa/blob/50d6bd5a79da01b2161901ba1c8ed25ad0c0e759/docs/indices.rst?plain=1#L132

(it's also broken on ds9 pages).  I'm thinking the only link left is to Eric's github page.

**Comment by DougBurke** [comment]
There's also

https://github.com/sherpa/sherpa/blob/263563093d45539c42c18a1f71faaf31f6edb7dc/sherpa/image/__init__.py#L30
