### ISSUE TITLE
Refine documentation for new smoke tests

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#212]
As mentioned by @DougBurke in https://github.com/sherpa/sherpa/pull/210#issuecomment-220151005

We need to add some documentation updates to PR #210:
- to the readme to say what users should (or shouldn't) do (it can come in after #207 and #208 are merged, to avoid conflict, but it would be good to have it on record as changes are coming)
- somewhere in the code to say what we mean by a smoke test - i.e. what level of functionality should be tested - so that anyone adding new code or a module knows whether they need to add something to the smoke-test functionality or not.

It also wasn't clear to me from the code when or how to use the "specify your own data directory" functionality you added in near the end. Is that something to be documented in the README.md?

We merged PR #210 so it could go in the next CIAOX build, but we were in the middle of the review (and of commitments to other projects).

**Comment by olaurino** [comment]
@DougBurke, I am not sure what it makes sense to advertise to the user. The changes in #210 were meant to fix some issues we were having on the CIAO side of sherpa testing, and as a bonus I think we streamlined the way the Smoke Test works as it is now a well defined subset of tests that ensures Sherpa is correctly installed along with its dependencies. I don't think end users are too much interested in the different levels of testing, but the code should be documented enough to understand what is going on, I agree, and the README should advertise the interface we want to advertise. To me, that's still the `sherpa_test` command and the test data.

I don't think developers should be too much concerned with the Smoke Test, and I don't expect it to change too often.

I will try and add some docs to the code for the `pytest` plugin and the Smoke Test functions. We can work out together what to add to the README.

**Comment by DougBurke** [comment]
We've moved to "fully embracing" `pytest`, and there have been `sherpa_test` changes, so I'm going to close this issue. There probably is still some documentation to add but let's worry about this with a more-targeted issue if anyone finds something missing.
