### ISSUE TITLE
Xspec additive model definition bug

### ISSUE THREAD

**Issue by k-egg** [sherpa/sherpa#2148]
Hello, when trying to define an additive Xspec model I came across an issue. Initializing the model was impossible, the error "norm is set but not included in pars" was always raised.

I am using AlmaLinux8 on a cluster along with Python 3.10.14 and Numpy 1.26.4. The error occurred with sherpa 4.16.1, installing 4.16.0 resolved it.

To recreate:
```
from sherpa.astro.xspec import XSpowerlaw
pl = XSpowerlaw()
```

I looked into this a little, this error seems to affect all additive Xspec models. Initializing an additive model calls the `XSAdditiveModel` class whilst defining all parameters except the norm. `XSAdditiveModel.__init__`, however, checks for the presence of a norm parameter in models that require it, and - if none is present - raises a ParameterErr.
I think this might be the source of the error, especially since the norm was defined along with the other parameters in sherpa 4.16.0, which worked for me.

Please let me know if there's anything I've missed, I hope this is helpful.
Thank you!

**Comment by DougBurke** [comment]
I can't repeat this, but I am using a post-4.16.1 branch (not quite HEAD):

```
>>> import importlib.metadata
>>> importlib.metadata.version("sherpa")
'4.16.1+325.ga3cf2531.dirty'
>>> from sherpa.astro import xspec
>>> xspec.get_xsversion()
'12.14.0i'
>>> pl = xspec.XSpowerlaw()
>>> print(pl)
powerlaw
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   powerlaw.PhoIndex thawed            1           -3           10           
   powerlaw.norm thawed            1            0        1e+24           
>>> pl([0.1, 0.2, 0.3], [0.2, 0.3, 0.4])
array([0.69314718, 0.40546511, 0.28768207])
```

Now, this could have been fixed after 4.16.1, but I'd be surprised because our test suite evaluates these models and so should have caught the problem. Or that should be the case. I've had a quick look through the changes post 4.16.1 and I don't see anything obvious (but I could have missed something).

Can you provide the traceback error you got?

**Comment by k-egg** [comment]
Hello, thanks for the quick answer!

I reinstalled 4.16.1 to recover the traceback error and now it seems I am also unable to recreate the error I experienced with it before.
My best guess is that uninstalling and reinstalling it might have solved whatever was wrong before. So for anyone experiencing a similar error that might be worth a try.

Thanks for taking the time to help with this!

**Comment by DougBurke** [comment]
Glad it's working for you now.
