### ISSUE TITLE
Why does GitHub think our conda CI runs are failing

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#2149]
If I go to

https://github.com/sherpa/sherpa#readme

the "Ci conda" badge currently fails - that is we have

# PNG (to show the failure case)

![Screenshot from 2024-09-23 09-32-08](https://github.com/user-attachments/assets/f255098b-3580-40ba-92d5-38e213b2ae5e)

# Live badges

![Build Status: Conda](https://github.com/sherpa/sherpa/workflows/Conda%20CI/badge.svg)
![Build Status: Pip](https://github.com/sherpa/sherpa/workflows/Pip%20CI/badge.svg)

The URL is https://github.com/sherpa/sherpa/workflows/Conda%20CI/badge.svg which, as far as I can tell, is the correct URL.

So why does it think it is failing (the current HEAD of main is https://github.com/sherpa/sherpa/actions/runs/10993803535 which all passed.

Note that this may be temporary, but it has been like this for a while now (I forget when I first noticed it, but there have been quite a few PRs merged since then).

I've briefly looked at https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge but I don't have the time/patience to investigate further.

**Comment by Marie-Terrell** [comment]
It looks like: https://github.com/badges/shields/issues/8671

For the status badge, I am not seeing an announcement for a change (I didn't look that hard though), but the following works instead: https://github.com/sherpa/sherpa/actions/workflows/ci-conda-workflow.yml/badge.svg
This matches their docs here: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge

**Comment by DougBurke** [comment]
we should probably apply the same change to the pip badge
