### ISSUE TITLE
Python 3.12 macOS Tests

### ISSUE THREAD

**Issue by Marie-Terrell** [sherpa/sherpa#2158]
It looks like we are now seeing this in the Conda macOS Python 3.12 tests: https://github.com/python/cpython/issues/100228

This is causing "errors" in the Conda deployments workflow (at the assert 0 warnings). As there have been many discussions of fork vs spawn for sherpa in the past and would require more investigation before making any sort of default change. With the discussion on the issue above, this is not a "deprecation" but more of a nudge to use spawn for now. So, I assume we just want to accept/filter the warning for now to give more time to review fork vs spawn (post release)?

**Comment by DougBurke** [comment]
See also #2007

**Comment by DougBurke** [comment]
There's also the "was a problem but then stopped being a problem"

- #1950

**Comment by Marie-Terrell** [comment]
> There's also the "was a problem but then stopped being a problem"
> 
> * [multiprocessing and python 3.12 #1950](https://github.com/sherpa/sherpa/issues/1950)

Thank you! I was searching through the issues, but missed this one.

**Comment by DougBurke** [comment]
The #2007 one is perhaps more relevant for the future!
