### ISSUE TITLE
BUG: the sherpa.astro.optical.LogEmission model creates an unused parameter

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#219]
The `sherpa.astro.optical` module creates a number of models which use "hidden" parameters (which aren't really used elsewhere). This includes the LogEmission model, which creates an `index` parameter but then doesn't use it.

In the current master branch, the `index` parameter is created at https://github.com/sherpa/sherpa/blob/a679e7f8dbc560eefcbead441ae571a4905ece70/sherpa/astro/optical/__init__.py#L566 but you can see that it is not used in the `calc` method - i.e. no mention of `p[4]` or `self.index` in https://github.com/sherpa/sherpa/blob/a679e7f8dbc560eefcbead441ae571a4905ece70/sherpa/astro/optical/__init__.py#L574

I think in this case we can just remove this parameter from the model since users will have had to dig around to find it in the first place (e.g. in the `.pars` attribute of the model instance) as it is not visible with a print call:

```
>>> mdl = optical.LogEmission()
>>> print(mdl)
logemission
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   logemission.fwhm thawed          100  1.17549e-38  3.40282e+38       km/s
   logemission.pos frozen         5000  1.17549e-38  3.40282e+38  angstroms
   logemission.flux thawed            1 -3.40282e+38  3.40282e+38           
   logemission.skew frozen            1  1.17549e-38  3.40282e+38           

>>> mdl.pars 
(<Parameter 'fwhm' of model 'logemission'>,
 <Parameter 'pos' of model 'logemission'>,
 <Parameter 'flux' of model 'logemission'>,
 <Parameter 'skew' of model 'logemission'>,
 <Parameter 'limit' of model 'logemission'>)
```

The alternative (which is what I would suggest doing if it were more user-visible) would be to add a deprecation warning the first time that the parameter is accessed (assuming we can do this; it might require some work to add this functionality to the model class in the first place). This deprecation would be in place for the 4.9.x series, and then the attribute removed after this.

**Comment by DougBurke** [comment]
@jbudynk would the removal of the `limit` parameter be an issue for [ChandraCXC/iris](https://github.com/ChandraCXC/iris)? I don't know how it uses these models.

**Comment by dtnguyen2** [comment]
@DougBurke  is right, the sherpa.astro.optical.LogEmission only as four parameters _(fwhm, pos, flux and skew)_ so it is a no-brainer to eliminate the fifth entry _(limit)_ in the parameter definition.
```
    def __init__(self, name='logemission'):

        self.fwhm = Parameter(name, 'fwhm', 100., tinyval, hard_min=tinyval,
                              units="km/s")
        self.pos = Parameter(name, 'pos', 5000., tinyval, frozen=True,
                             units='angstroms')
        self.flux = Parameter(name, 'flux', 1.)
        self.skew = Parameter(name, 'skew', 1., tinyval, frozen=True)

        ArithmeticModel.__init__(self, name,
                                 (self.fwhm, self.pos, self.flux,
                                  self.skew, self.limit))

    # @modelCacher1d
    def calc(self, p, x, xhi=None, **kwargs):
        x = numpy.asarray(x, dtype=SherpaFloat)

        if 0.0 == p[0]:
            raise ValueError('model evaluation failed, ' +
                             '%s fwhm cannot be zero' % self.name)

        if 0.0 == p[1]:
            raise ValueError('model evaluation failed, ' +
                             '%s pos cannot be zero' % self.name)

        if 0.0 == p[3]:
            raise ValueError('model evaluation failed, ' +
                             '%s skew cannot be zero' % self.name)

        arg = 0.69314718 / numpy.log(1.0 + p[0] / 2.9979e5 / 2.0)
        if (arg <= 1.0):
            arg = 1.0001

        fmax = (arg - 1.0) * p[2] / p[1] / 2.0

        if (p[3] == 1.0):
            return numpy.where(x >= p[1],
                               fmax * numpy.power((x / p[1]), -arg),
                               fmax * numpy.power((x / p[1]), arg))

        arg1 = 0.69314718 / numpy.log(1.0 + p[3] * p[0] / 2.9979e5 / 2.0)
        fmax = (arg - 1.0) * p[2] / p[1] / (1.0 + (arg - 1.0) / (arg1 - 1.0))

        return numpy.where(x <= p[1],
                           fmax * numpy.power((x / p[1]), arg),
                           fmax * numpy.power((x / p[1]), -arg1))
```
