### ISSUE TITLE
Plot style changes needed with matplotlib v2

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#224]
I've just checked against a pre-release version of matplotlib 2.0, and the good news is that we don't have any obvious failures like we did with version 1.5. However, the changes to the plot styles do need looking at.

```
% python -m pip install --upgrade pip # upgrade pip to latest
% pip install --pre matplotlib
Collecting matplotlib
  Downloading matplotlib-2.0.0b1-cp27-cp27mu-manylinux1_x86_64.whl (53.7MB)
...
```

I have included some of the plot outputs in https://gist.github.com/DougBurke/d85b93b200c7e0fcc1fe06c0d68056e1 - in general they are okay, but some plots - in particular `plot_fit`, but possibly also `plot_delchi` and `plot_resid` - need tweaking.

**Comment by DougBurke** [comment]
And it's now released. I suggest using 'matplotlib < 2.0' for now.

**Comment by taldcroft** [comment]
:+1: for matplotlib 2.0 compatibility (it's so nice!).  I'm using this for basic non-X-ray type work and it's OK, except that sherpa.ui sets `mpl.rcParams['figure.dpi']` from the new default of 100 back to 72, which then bungs things up elsewhere.  Does sherpa really need to fiddle with these defaults?

**Comment by taldcroft** [comment]
BTW, this is what I mean.  I searched the sherpa repo for `figure.dpi` and it doesn't show up, so that is a bit curious.

![image](https://user-images.githubusercontent.com/348089/28745357-df7d27fc-7444-11e7-8858-3d19b20ece81.png)

**Comment by DougBurke** [comment]
@taldcroft - I think all we do is 'import pylab' [*], so do you see any difference between the following (I don't with matplotlib 2.0.2 but just wanted to check your system):

    % python -c 'import matplotlib; print(matplotlib.rcParams["figure.dpi"]);'

and

    % python -c 'import matplotlib; import pylab; print(matplotlib.rcParams["figure.dpi"]);'

[*] well, actually, `sherpa/astro/datastack/plot_backend/plot_matplotlib.py` does a `import matplotlib.pyplot as plt`; not sure who to blame for that ;-)

**Comment by taldcroft** [comment]
This is indeed not related to sherpa.  In jupyter notebook just importing `matplotlib.pyplot` is enough to change the DPI setting.  However this does not happen In the standard IPython terminal console.  Interestingly `%matplotlib inline` has the same effect of setting the figure.dpi to 72.  So I don't understand anything now.

**Comment by DougBurke** [comment]
Join the club: I make an effort not to understand anything...

**Comment by DougBurke** [comment]
I'm closing this as we have matplotlib 3 to worry about now (and we are going to be focusing a lot more on the backend with the removal of chips)
