### ISSUE TITLE
XSPEC module missing nlapec model from XSPEC 12.9.0

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#228]
Two issues here:
1. the XSPEC module is missing the `nlapec` model https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSmodelNlapec.html added in XSPEC 12.9.0
2. how do we deal with "optional" models (e.g. this particular model isn't in XSPEC 12.8.2)?

At this time I would say that we drop support for XSPEC 12.8.2, since there are known issues with this version, but it is something to think about (e.g. #52), since we could come across this with a new version of XSPEC.

For this _particular_ model - e.g. `nlapec` - it is possible to use the `apec` model together with the poorly-documented `APECNOLINES` (_note_ not sure of this name) xset variable to replicate it, so there is a work around in this case.

**Comment by olaurino** [comment]
You mentioned you had a prototype that builds the xspec extension on the fly using the model.dat file. To me, that's the best approach possible, because it adapts our extension to any version of xspec.

Short of that (it may be too much work for a single iteration) we could have mechanisms for tagging certain models as unavailable depending on the xspec version detected.

Although we know 12.8.2 has issues, we could try and keep supporting it by making the nlapec model, as you say, optional, as a good excercise for the future.

**Comment by DougBurke** [comment]
I have mixed feelings about the auto-generate idea. On the positive side

* automatically up to date/reflect the XSPEC module it was compiled against

* less boilerplate code to deal with

On the negative side

* documentation: it's essentially impossible to come up with anything remotely useful, apart from a link to the XSPEC documentation (as I do in my manually-curated version e.g. https://github.com/sherpa/sherpa/blob/feature/add-model-docs/sherpa/astro/xspec/__init__.py#L417) and a list of the model parameters with no descriptive text (e.g. no description for the `Attributes` section of https://github.com/sherpa/sherpa/blob/feature/add-model-docs/sherpa/astro/xspec/__init__.py#L396). Note that the link to the documentation can not be guaranteed, so I'm being generous in saying it can be done (since multiple models can be described on the same web page and I'm unaware of anything in the XSPEC models-only distribution that contains this knowledge). I have spoken to the XSPEC team and they are not planning on distributing the XSPEC model documentation along with the code.

* complicates the build set up.

**Comment by olaurino** [comment]
Fixed by #390. The optional models improvement is addressed by #395.
