### ISSUE TITLE
pip / PyPI for Sherpa?

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#235]
I was asked if `pip install sherpa` is supposed to work. Is it?

I see that the version on PyPI is very outdated (and not a stable tag?):
https://pypi.python.org/pypi/sherpa/5d12147

Maybe you could clarify this question here?
https://github.com/sherpa/sherpa#source-build
(And maybe upload the latest stable source dist to PyPI, or if you don't want to use PyPI, remove the very old one to avoid confusion?)

**Comment by olaurino** [comment]
It was decided in the early stages of development that we would not have the package in PyPI, although I had included it in my prototyping. I think the rationale for that decision does not stand anymore and we could upload the package to PyPI.

As you know, building Sherpa requires several dependencies, so to me the advantage of `pip install sherpa` over `git clone; python setup.py install` is minimal: you need to read some docs regarding the installation process anyway.

I'll confirm that I can upload the package to PyPI. Thanks for the report.

**Comment by DougBurke** [comment]
Do build issues like #260 and #271 mean we should hold off on this? In other words, we don't want to suddenly have a "flood" of bug reports for things we already know about. Or are those issues not really relevant to the 'pip install' use case?

**Comment by DougBurke** [comment]
I also guess that a 'pip install' approach means that the user doesn't get to change the build defaults (okay for most users, but a caveat if they want to take advantage of XSPEC)?

**Comment by DougBurke** [comment]
I'm going to close this issue as we now have https://pypi.python.org/pypi/sherpa/4.9.0 and (after ensuring that numpy is installed)

```
% pip install sherpa
Collecting sherpa
  Using cached sherpa-4.9.0-1.tar.gz
Requirement already satisfied: numpy in ./miniconda2/envs/foo35/lib/python3.5/site-packages (from sherpa)
Collecting six (from sherpa)
  Using cached six-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: sherpa
  Running setup.py bdist_wheel for sherpa ... done
  Stored in directory: /home/djburke/.cache/pip/wheels/aa/2f/91/9fd77ab80480e5f148e160dc49cd3567dff634095fc1f3ec86
Successfully built sherpa
Installing collected packages: six, sherpa
Successfully installed sherpa-4.9.0 six-1.10.0
% python -c 'import sherpa; print(sherpa._version.get_versions())'
{'full': '187333e830c1cbe9413c90fc77ba52784fd6bd85', 'version': '4.9.0'}
```

**Comment by olaurino** [comment]
Does anybody know off the top of their head if binary wheels could be an option for Sherpa? From what I've heard, you can't have universal wheels because of the compiled extensions, but it's not clear whether wheels would be an option for a complex project like Sherpa with C/Fortran extensions to begin with (e.g. what about libgfortran?). Also, it looks like users need to provide pip with special switches for using wheels, for instance it looks like numpy does indeed distribute wheels, but if I try to install numpy, pip starts building it from sources.

**Comment by cdeil** [comment]
@olaurino - Thank you!

> Does anybody know off the top of their head if binary wheels could be an option for Sherpa?

I don't know. I think he's building the wheels for many projects (e.g. numpy, scipy, ...), so you could email him: https://github.com/matthew-brett

Looking at https://pypi.python.org/pypi/sherpa/4.9.0 I would have two minor suggestions for the next release:
- Change the `long_description` to something that renders correctly on PyPI
- Add the classifier that Python 3 is supported

**Comment by hibajamal** [comment]
The documentation says it requires Linux or OS-X, so sherpa can't be installed on Windows?

**Comment by DougBurke** [comment]
We haven't tried and don't have the experience of working with Windows. If
you have the time it would be great if you could try getting it to build on
Windows.

Although most of the code is python, there is some compiled code, so I
*guess* it isn't going to be easy.

**Comment by olaurino** [comment]
However it can be easily installed in the relatively new [Windows subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).
