### ISSUE TITLE
Rewrite sherpa/tests/test_stat.py so it does not depend on fits, xspec, or data

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#238]
The statistical tests require xspec, a FITS backend, and sherpa-test-data to run (see below). We should not need any of these, as it is important to be able to verify the stats when the XSPEC or the FITS backend is not available. A quick look at the tests show that they do things like run a fit and then compare results: this also seems excessive for a test of the stats, as it is more of an integration or end-to-end test.

I suggest that the tests should just be of "simple" numerical models and data, and without needing any I/O. The existing tests in this module should probably not be lost, but moved to a different location.

```
% python setup.py test -a sherpa/stats/tests/test_stats.py 
...
=========================== short test summary info ============================
SKIP [1] sherpa/stats/tests/test_stats.py:299: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:268: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:245: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:235: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:240: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:262: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:257: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:279: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:251: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:305: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:230: xspec required
SKIP [1] sherpa/stats/tests/test_stats.py:273: xspec required

========================== 12 skipped in 0.48 seconds ==========================
```

**Comment by olaurino** [comment]
I completely agree.

**Comment by DougBurke** [comment]
Note that #287 contains a number of low-level tests of the statistic code that do not depend on external data files or XSPEC (and so are always run, whatever optional functionality is available). I leave the review for #287 to determine whether it is sufficient to close this issue.

**Comment by DougBurke** [comment]
I am assuming that with #287 merged we can close this (the tests mentioned here haven't been changed, but we have since added a number of tests that are self-contained).
