### ISSUE TITLE
Allow plotting options in Sherpa commands

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#251]
I often find myself in the following situation:
I make a script in Sherpa that outputs some complicated plot (say different datasets and different models plotted on top of each other).

My main problem is that I always have to run "info()" to find out how lines are called and then change them retroactively with

```
set_curve(...)
```

or

```
set_histogram('hist2', ['*.color', 'blue'])
```

This means that my script is littered with hardcodeds string like "crv3"  or "hist1".
That's a) annoying and b) a problem if I e.g. decide to remove the plot statement that generated "crv1". Next time I run the script "crv2" will be called "crv1" and all colors etc. will be off.

It would be great if there was a way to specify properties like color, symbol etc. when making chips plots from Sherpa, e.g. something like:

```
plot_model(2, overplot=True, "color=blue")
```

Matplotlib solves that by allowing my to either set the color in the plot statement "plt.plot(... color='r')", or by returning an object I  can refer to 

   l1 = plt.plot(...)
   l1.something = "blue"

I talked to @DougBurke and he pointed out that Chips supporst different plotting backends. So, here is my suggestion how this can be done relatively easily: Chandge the signature of `plot_data`,  `plot_fit` etc. to

```
plot_data([id], **kwargs)
```

and just pass kwargs to the plotting backend.
Alternatively, accept kwargs called "chips" and "matplotlib", where only
the keyword names like the active backend has any effect. The value of these keywords need to be dictionaries in either chip or mpl style (and can be documented with just "see ahelp chipsopt or matplotlib documentation").

**Comment by DougBurke** [comment]
Just to note that this is with the chips backend - where `set_curve/histogram` are functions from ChIPS - but it is similar with the matplotlib backend, i.e. there's no easy way to override the defaults for a given plot. The current approach would be something like

    get_data_plot_prefs()['linecolor'] = 'green'
    plot_data()
    get_data_plot_prefs()['linecolor'] = <whatever the old value was>

which is not ideal.

We don't really document well out mapping from preferences (e.g. linecolor) to backend-specific option, so we need to think about whether to try and make this generic, or just pass through values for the backend to use directly (which makes the code less portable, but I'm not sure it's worth keeping the API backend-agnostic for "power" users who are unlikely to change backend; at least not until someone writes us an altair/xxx backend ;-)

**Comment by DougBurke** [comment]
I know that pandas has recently worked hard on supporting multiple back ends - e.g. https://github.com/pandas-dev/pandas/issues/26747 and https://pandas.pydata.org/pandas-docs/stable/development/extending.html#plotting-backends - but I have no experience of it, or how they pass in options to configure the visualizations.

**Comment by DougBurke** [comment]
*I am also thinking of other backends - e.g. altair*

**Comment by hamogu** [comment]
All that I suggested above is purposefully backend independent in the sherpa code. Sherpa would simply pass through the `kwargs` to the backend plotting code, and it's up to the user to specify them in a way that they work with the specific backend the user has chosen. That's how it used to work with chips - you would plot something and then later use chips commands like `set_curve()` that are backend specific. 

`plot_fit_resid` will make two plots in chips, two plots in matplotlib, and two plots in altair. So the "need to pass through two sets of kwargs" is the same in every backend for that command.

This is the same approach used before with chips. You would make a plot and then use chips-specific commands  to change it. All I'm proposing is to save me typing `ax = plt.gca(); ax.get_lines()[0].set_XXXX`.
This is a pretty small change.

Having the keyword args be entirely independent of the backend requires a "grammar of graphics" - and the only option for that is really to use an existing "grammar of graphics" specification of which there is more than one already I think (vega, http://vita.had.co.nz/papers/layered-grammar.html).  We don't want to role out (or maintain!) our own: https://xkcd.com/927/

So, would we would do is to add backend that can understand the grammar of graphics, e.g. https://plotnine.readthedocs.io 
However, for now matplotlib is far more common so I think this is more of a long term goal and should probably go into it's own issue.

**Comment by DougBurke** [comment]
So #692 allows you to say things like

    plot_data(color='green')

    plot_fit_resid(capsize=5, ecolor='orange', color='magenta')

    plot_source(xlog=True, ylog=True)
    plot_source_component(pl, linestyle='dotted')

I'd be interested to see if people find it useful.

**Comment by hamogu** [comment]
I will totally use that. That's what I had in mind when I suggested this.

**Comment by DougBurke** [comment]
#692 should be usable, in that any remaining changes are expected to be documentation related. Unless anyone finds bugs or problems or gremlins or ... that is

**Comment by DougBurke** [comment]
@hamogu - note that #692 may not go as far as you'd like to be useful, in that it only supports arguments that the plot backend code already supports, and doesn't just let any-old keyword through. Concretely, it only accepts those keywords returned by get_data_plot_prefs() or get_model_plot_prefs(), and then there's some "fun" over PHA data sets (related to #672) which makes it a bit tricky to say what keywords are actually supported: you just have to try and see what works and what errors out.

**Comment by hamogu** [comment]
I think we can basically do what I originally asked for by now, so I'm closing this issue. If anyone disagrees, you cna reopen or start a new one.
