### ISSUE TITLE
`show_all` does not work on Python3 with PHA

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#264]
To reproduce this issue:

```
from sherpa.astro.ui.utils import Session
from sherpa.astro.data import DataPHA
session = Session()
session.load_arrays(1, [1, 2, 3], [1, 2, 3], DataPHA)
session.show_all()
                                                                                                                                    
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-73d26a0302c5> in <module>()
----> 1 session.show_all()

/proj/xena/ciaod/LinuxP3/ciao_0907/lib/python3.5/site-packages/sherpa/ui/utils.py in show_all(self, id, outfile, clobber)
   1296         """
   1297         all = ''
-> 1298         all += self._get_show_data(id)
   1299         all += self._get_show_model(id)
   1300         all += self._get_show_fit()

/proj/xena/ciaod/LinuxP3/ciao_0907/lib/python3.5/site-packages/sherpa/astro/ui/utils.py in _get_show_data(self, id)
    298                 data_str += 'Noticed Channels: %s\n' % data.get_noticed_expr()
    299 
--> 300             data_str += data.__str__() + '\n\n'
    301 
    302             if isinstance(data, sherpa.astro.data.DataPHA):

/proj/xena/ciaod/LinuxP3/ciao_0907/lib/python3.5/site-packages/sherpa/astro/data.py in __str__(self)
    403         try:
    404             self._fields = filter((lambda x: x != 'header'), self._fields)
--> 405             ss = BaseData.__str__(self)
    406         finally:
    407             self._fields = old

/proj/xena/ciaod/LinuxP3/ciao_0907/lib/python3.5/site-packages/sherpa/data.py in __str__(self)
    109         """
    110 
--> 111         fields = self._fields + getattr(self, '_extra_fields', ())
    112         fdict = dict(izip(fields, [getattr(self, f) for f in fields]))
    113         return print_fields(fields, fdict)

TypeError: unsupported operand type(s) for +: 'filter' and 'tuple'

```

I could reproduce the issue on CIAOD LinuxP3 (`sherpa.__version__ = 4.8.1+133.ge819bd1`) and in standalone mode from the current tip of the master branch (`sherpa.__version__ = 4.8.1+144.g770359b`).

**Comment by olaurino** [comment]
It turns out this is the same bug as #275. I tested that this issue is gone with #284. Closing as duplicate. [Technically, this came first and #275 is the duplicate, but since I already opened a PR on that one I am closing this].

**Comment by DougBurke** [comment]
It would be nice to add some form of a test of show_all to check it's fixed.

**Comment by olaurino** [comment]
What kind of test, though? I can add a trivial test for a simple case, but that would hardly have any value, wouldn't it?

**Comment by DougBurke** [comment]
To be honest, the tests in #284 look pretty trivial to me, but they do at least test that the code doesn't fail. I admit that `save_all` has a **much** bigger surface area to test, but the question is if a simple test is better than none in this case.

**Comment by olaurino** [comment]
It's easier to write a simple test than to write this comment ;-) (and I thought you meant that it would have been good to do add some actual testing of `show_all`).

Nevertheless.

This bug is a duplicate because the error is exactly the same of another bug. I don't think you need a test for a duplicate. I should have spotted the duplication earlier.

Now, if I added a test for this duplicate, I couldn't make it fail unless I removed the fixes done for this bug's counterpart. Which means that the new test is useless in its triviality (it doesn't cover anything the other test isn't already covering) unless it actually checks the output of `show_all`.

But that's different, and made me think: it's not worth it, because if I wanted to test `show_all` I'd have to start using more complex datasets that `[1, 2], [1, 2]` and check something more than a long list of `None`s and `False`s. Which is not what this bug is about. This bug is a duplicate of #275.
