### ISSUE TITLE
Numpy VisibleDeprecationWarning

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#273]
sherpa/astro/flux.py uses a float as an index array, resulting in a deprecation warning from Numpy.

To reproduce:

``` python
from sherpa.astro import ui
ui.load_arrays(1, [1, 2], [1, 2])
ui.set_source(ui.polynom1d.p)
ui.sample_flux()
```

You would get the following warning:

>sherpa/astro/flux.py:163: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  upconfidence = sf[(1.0 - myconfidence) * size - 1]
sherpa/astro/flux.py:164: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

**Comment by DougBurke** [comment]
@jbudynk has noted in #225 some more examples of this warning.
