### ISSUE TITLE
possible difference in behavior if grouping is list or NumPy array

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#285]
Mainly a reminder to myself to investigate further.  I have seen differences in behavior (e.g. a code failure) when the grouping array below was set to a Python list rather than a NumPy array.

```
def foo(flo, fhi):

    nbins = 20
    channels = np.arange(1, nbins + 1, dtype=np.int)
    src_counts = (10 + 5 * np.sin(channels / 2.0)).astype(np.int8)
    bg_counts = np.ones(nbins, dtype=np.int8)

    # I have seen different behavior when grouping=[1,-1,..]
    # and the following code
    grouping = np.asarray([1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, -1,
                           1, 1, 1, 1, 1, -1, -1, -1])

    src = DataPHA('tst', channels, src_counts, grouping=grouping,
                  exposure=100.0, backscal=0.01)

    backscal = 0.04 - 0.00015 * channels
    bg = DataPHA('tstbg', channels, bg_counts,
                 exposure=200.0, backscal=backscal)

    src.set_background(bg)

    src.notice(lo=flo, hi=fhi)

    mdl = Polynom1D('mdl')
    mdl.c0 = 8
    mdl.c1 = 1.2

    fit = Fit(src, mdl, stat=WStat())

    src._response_ids = [1]

    print("Statistic = {}".format(fit.calc_stat()))
```

**Comment by hamogu** [comment]
SDS has decided that any input to Dataclasses for x, y, x_lo, x_hi, sys_err, stat_err etc should be converted to numpy arrays in the constructor. People should use numpy arrays anyway and
we've implicitly claimed that the type of input does not matter for the
result, so we are fixing a bug here, not "breaking people's code who
relied on having a different answer when they put in the tuple instead
of a numpy array".
