### ISSUE TITLE
support evaluating the model on a different grid to the "final" grid

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#300]
There are cases when it is necessary to evaluate a model (a single model or a composite one) on a different grid to the desired output grid. An example is convolution style models - such as PSF, RMF, or XSPEC convolution models - which can require the model they are convolving to be evaluated on an extended grid so as to account for signal "outside" the desired grid. Sherpa already has to deal with this in some manner - e.g. ignored bins need to be included when doing the convolution, then excluded from the output - but I'm not a fan of this approach, since it seems to tie a convolution component to a grid, which is not how the rest of the system works.

I have some notes on how models are evaluated on the wiki at https://github.com/sherpa/sherpa/wiki/Model-Evaluation-in-Sherpa but no real solution. I have the feeling that there needs to be some entity other than a model component that decides on the grid, sets things up: allocates memory, converts units if appropriate (such as wavelength to keV for XSPEC models), rebins and regrids the result, handles cacheing the results. However, it's not clear that it is really a viable approach, or at what level of the stack it would live (e.g. in the Model class, a layer above it, or only in the Session layer).

I believe this is relevant to:
- #43 Generalize the image PSF to allow data sub-pixel binning
- #68 Add Python classes for XSpec convolution models
- #301 support XSPEC mixing models

**Comment by DougBurke** [comment]
With #747 we seem to almost have this functionality. However, #762 (the inability to use a different grid on an expression such as `xsphabs.gal * xsvvapec.src` which then gets rebinned to the output grid) means I don't want to close this yet.

**Comment by hamogu** [comment]
This is still on Warren's list wit ha task assigned to me to "review and close out". I'm not quite sure what I'm supposed to do though...
@DougBurke #762 is closed by now. Can we close this issue and open a new one if we run into something similar in the future?

**Comment by DougBurke** [comment]
I agree that we can close this: new issues are more "this doesn't do what I expect" rather than the blanket "we can't even do this" that this issue covered.

**Comment by hamogu** [comment]
@wmclaugh : Please tick of this issue from the task list in confluence.
