### ISSUE TITLE
WStat: How to treat zero source or background counts

### ISSUE THREAD

**Issue by joleroi** [sherpa/sherpa#314]
The [Wstat docs page](http://cxc.harvard.edu/sherpa/ahelp/wstat.html) claims that

> The wstat statistic is equivalent to the XSPEC implementation of the Cash statistic

There is however one difference. The treatment of bins with 0 source and/or background counts
Quoting again the [Wstat docs page](http://cxc.harvard.edu/sherpa/ahelp/wstat.html#Zero_and_negative_value_numbers) 

>  The wstat statistic function evaluates the logarithm of each data point. If the number of counts is zero or negative, it's not possible to take the log of that number. The behavior in this case is controlled by the truncate and trunc_value settings in the .sherpa.rc file; see "ahelp sherparc" for details on this file.

> If truncate is set to True (the default), then log(<trunc_value>) is substituted into the equation, and the statistics calculation proceeds. The default trunc_value is 1.0e-25.

> If truncate is set to False, wstat returns an error and stops the calculation when the number of counts in a bin is zero or negative. The trunc_value setting is not used. 

However, the [XSPEC stats page](https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html#SECTION00124000000000000000) describes a procedure to assign a valut to WStat (and not putting it to '0', which I assume the sherpa page means instead of ``log(1.0e-25) = -57.56`` ) 

I tested some corner cases using the script https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/compare_wstat.py (you need a gammapy head version to run it)

```
[gammapy] python dev/sherpa/stats/compare_wstat.py 0.2 1 4 0.01
mu_sig: 0.2
n_on: 1.0
n_off: 4.0
alpha: 0.01

Sherpa stat: 1.33016424075
Sherpa fvec: 1.15332746466

Gammapy stat: 1.33016424075
Gammapy statsvec: [ 1.33016424]

XSPEC stat: 1.33016424075
```
which show that all three implementation are equivalent for this case. However

```
[gammapy] python dev/sherpa/stats/compare_wstat.py 0.2 1 0 0.01
mu_sig: 0.2
n_on: 1.0
n_off: 0.0
alpha: 0.01

Sherpa stat: 1.61887582487
Sherpa fvec: 1.2723505118

Gammapy stat: 0.809437912434
Gammapy statsvec: [ 0.80943791]

XSPEC stat: 0.809437912434
```
I should note that the quoted Xspec value do not come from Xspec itself but from an independent implementation of the formulas given on the [XSPEC stats page](https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html#SECTION00124000000000000000), https://github.com/gammapy/gammapy/blob/master/dev/sherpa/stats/xspec_stats.py

Is there a reason why this different procedure was adopted for Sherpa?  And/or would it be possible to change it?

cc @cdeil

**Comment by DougBurke** [comment]
The `truncate` setting is a "generic" (so, statistic-agnostic) "solution" (akak work around) for replacing problematic bins for likelihood statistics. So I assume that this was used with the wstat (and cstat) code.

I unfortunately don't have time to look at this this week (it's a short week here due to Thanksgiving), and I'm not sure who else has time. We are trying to get things ready for the CIAO 4.9 release (which includes Sherpa), so I'm not hopeful this can get addressed on a short time scale.

**Comment by joleroi** [comment]
Actually, the sherpa implementation does something about zero bins.
https://github.com/sherpa/sherpa/blob/master/sherpa/include/sherpa/stats.hh#L388
I will have a look and see if I can find the difference myself.

**Comment by DougBurke** [comment]
FYI, there's a couple of fixes in the [`release/ciao4.9` branch](https://github.com/sherpa/sherpa/commits/release/ciao4.9) that aren't yet in `master`, but they should not directly impact this.

**Comment by joleroi** [comment]
@DougBurke 

There was the same bug in our xspec implementation and in the gammapy implementation. So this issue is pointless. Sorry for that. Maybe one could remove [this](http://cxc.harvard.edu/sherpa/ahelp/wstat.html#Zero_and_negative_value_numbers) paragraph from the WStat docs page, I think it caused all the confusion in the first place?

**Comment by DougBurke** [comment]
@joleroi - I don't have the time to check at the moment, but are the docstrings for the WStat and CStat classes in `sherpa.stats` okay, or are they also confusing?

**Comment by joleroi** [comment]
No they are fine (exactly what written on https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html). Would it be possible to transfer them to the high level docs?

**Comment by DougBurke** [comment]
I am trying to remove the ahelp sherpa documentation, as it is falling out
of date. However, this is taking longer than I wanted, so we may have to
try and "back port" information onto the web pages at least. that's a
different issue (and out of scope for this issue tracker) so I'm going to
close this ticket, but feel free to re-open it.

Doug
