### ISSUE TITLE
test `test_smoke.py` imports `mock` as a python 2 dependency

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#317]
`test_smoke.py` should import `mock` from the standard library in Python 3. Since `mock` is also available as an independent package on Python 3, a workaround is to simply install `mock` as part of the dependencies, which is what happens both in CIAO and on Travis since `mock` is listed in the `test_requirements.txt` file and it is installed as part of the regression tests tools in CIAO.

**Comment by DougBurke** [comment]
@cdeil has reported a `mock`-related issue as part of #360 (Python 3.6 support); is it related to this ticket?

**Comment by DougBurke** [comment]
@olaurino - is this still an issue?

**Comment by olaurino** [comment]
I must have missed these notifications, I don't remember getting them... I am sorry for not responding, @DougBurke.

I don't think this is causing #360, although #360 is showing another instance of a call to `mock` in Python2-style. Probably #317 (this issue) would trip `sherpa_test` anyway, though.

And yes, this is still an issue.
