### ISSUE TITLE
calc_bkg_stat

### ISSUE THREAD

**Issue by JohannesBuchner** [sherpa/sherpa#333]
In sherpa, one can easily fit the background with fit_bkg, but it is remarkably hard to access the current background statistic. Adding a calc_bkg_stat as a an analog to calc_stat, similar to plot_fit->plot_bkg_fit would be great.

A workaround is:

bkg_stat = [s for s in get_stat_info() if id in s.ids and s.bkg_ids is not None and len(s.bkg_ids) > 0][0]

**Comment by olaurino** [comment]
Thanks for the suggestion! I will label it as an RFE.
