### ISSUE TITLE
remove setting propagate of logger to False in the demo notebook

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#334]
We can remove the following from `docs/SherpaQuickStart.ipynb`

    import logging
    logging.getLogger('sherpa').propagate = 0

I think it might still be needed if you use an old version of ipython, but I think that's an acceptable "loss" and not something we need to document.

**Comment by DougBurke** [comment]
This has been done some time ago.

**Comment by hamogu** [comment]
Mmm. I'm seeing that old annoying double output again in some cases. I'm not quite sure why, but in my case I had to insert those two lines again into my notebooks. Curiously, I don't get that in every notebook I'm runnning, even though they are in the same conda environment - I have not idea what makes one different, but I suspect that I've hit some function that changes the internal state of the logger and does not reset it after. I'll keep a lookout and see if I can trace which function it was, but for now I'm glad I found this old issue and could use it as a template to remove the extra double output.

**Comment by hamogu** [comment]
I can't reproduce my problem. Must have something to do with a function that I run interactively with some odd / wrong input.

**Comment by DougBurke** [comment]
I am also seeing this on SciServer with Sherpa in CIAO 4.17 which has

```
import logging
logging.getLogger("sherpa").propagate == True
```

I've come to the conclusion that there are parts of python I am just never going to understand ...
