### ISSUE TITLE
should we add html (and others?) representations of objects for ipython/jupyter

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#345]
I have some old experiments - e.g. 
https://nbviewer.jupyter.org/urls/bitbucket.org/doug_burke/ciao-notebooks/raw/917f54ecc759e94445b5f5b92b9dcbf66872d911/HTML%20output%20%28nicer%20views%29.ipynb whose raw form can be found at https://bitbucket.org/doug_burke/ciao-notebooks/src - to show how we could make HTML views of model/parameter values.

It should just be as simple as adding some `_repr_html_` methods to the desired classes - e.g. see http://ipython.readthedocs.io/en/stable/config/integrating.html 

There's some thought required - e.g. do we want to follow pandas and allow for the output "form" to be configurable or not? Also, do we want to support png/latex/svg where appropriate (e.g. DataPlot could return the plot image (once `prepare` has been called).

**Comment by DougBurke** [comment]
I have an example of how this could work for HTML output of tables (using the same code as shown in the notebook above) in the branch https://github.com/DougBurke/sherpa/tree/feature-add-repr

This is intended as a playground, to see how it works, rather than as code to be merged.

**Comment by DougBurke** [comment]
Screen output can be found at [this gist](https://gist.github.com/DougBurke/283293db14e931f1aa7a3eef878063e0) - as shown below:

![image 1](https://gist.githubusercontent.com/DougBurke/283293db14e931f1aa7a3eef878063e0/raw/8a5463cd8ba76ea65fb7bd3f44e679053920fb9e/ipy%25201.png)

![image 2](https://gist.githubusercontent.com/DougBurke/283293db14e931f1aa7a3eef878063e0/raw/8a5463cd8ba76ea65fb7bd3f44e679053920fb9e/ipy%25202.png)

**Comment by DougBurke** [comment]
The output from the ipython shell remains as it was - e.g.

```
In [1]: from sherpa.astro import ui
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: ui.set_source(ui.lorentz1d.bob + ui.gauss1d.fred)

In [3]: mdl = ui.get_source()

In [4]: mdl
Out[4]: <BinaryOpModel model instance '(lorentz1d.bob + gauss1d.fred)'>

In [5]: bob
Out[5]: <Lorentz1D model instance 'lorentz1d.bob'>

In [6]: fred
Out[6]: <Gauss1D model instance 'gauss1d.fred'>

```

**Comment by DougBurke** [comment]
It looks like table styling has improved; for example from

https://gist.github.com/DougBurke/026e23f33ee4185755e032b097cf3cbb

I get

![show-source](https://user-images.githubusercontent.com/224638/47269907-06904780-d532-11e8-8d65-8a23e9ba118d.png)

![show-model](https://user-images.githubusercontent.com/224638/47269909-0abc6500-d532-11e8-8b89-f5a9ca063474.png)

**Comment by hamogu** [comment]
:+1:
