### ISSUE TITLE
Sherpa should autodetect I/O backend

### ISSUE THREAD

**Issue by pkgw** [sherpa/sherpa#354]
I might be missing something, but it doesn't seem like there's any need for the I/O backend to be saved in a configuration file — if `pycrates` is the uniformly "better" backend.

Instead, `sherpa.astro.io` could just try importing `pycrates` and falling back to astropy or pyfits if needed. [This patch](https://github.com/pkgw/conda-recipes/blob/master/recipes/sherpa/io-backend.patch) in my Conda recipe for Sherpa (which I wrote to be able to build the XSpec model components) implements that.

**Comment by olaurino** [comment]
Thanks for the request and the pointer to the patch. This seems related to #348, although it goes into a different direction.

On an unrelated note, I like a few things you do in your conda recipe, I might end up borrowing some of that. Also, I wish I finally had time to look into the whole conda-forge business, but it looks like you did a lot of work and you also have xspec binaries for OSX, which I currently don't have. That could greatly help in improving the current building and testing infrastructure some more. So thanks for contributing :)

**Comment by DougBurke** [comment]
I prefer the solution in #348 - since this allows us to ensure we are testing a particular backend if both are available. I actually am not a fan of the use of a config file for Sherpa, but I haven't come up with a better solution!

@pkgw We'd like both backends to be "equally good", so if you can point us to the type of data that you had problems with with our "pyfits" backend we can try looking at what the problem was there.

**Comment by pkgw** [comment]
The problem was loading a standard *Swift* RMF file, `swxpc0to12s6_20130101v014.rmf`. The error message is "'swxpc0to12s6_20130101v014.rmf' is not a filename or  MATRIX column not a variable length field" ; the stack trace doesn't have anything interested in it, in my reading.

**Comment by DougBurke** [comment]
Ta. Unfortunately the OGIP standard is vague in places, and how well various missions follow the standards varies significantly. It's also true that we've less real-world testing of the pyfits/astropy backend for these files.

**Comment by DougBurke** [comment]
I think this is resolved by #1185
