### ISSUE TITLE
Sherpa Windows installation?

### ISSUE THREAD

**Issue by vorugantia** [sherpa/sherpa#355]
The Installation tab in the README says Sherpa can be download via conda, only on Linux and OS X. Is there a way I can do so on Windows?

**Comment by vorugantia** [comment]
Never mind, it seems Sherpa isn't compatible on Windows.

**Comment by DougBurke** [comment]
Just to note that we'd love someone to come along and work on windows compatability, but we don't have the resources, experience, or time to do it!
