### ISSUE TITLE
Importing Bugs: #13899 - issues with XSPEC NEI model

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#37]
I started importing the existing bugs from the older bug system. 

This bug #13899 is related to XSPEC - Seg. Fault in CIAO 4.6 version. 
I include the discussion below. @dtnguyen2 should have the test files for testing this bug.
I suggest to check if this bug has been fixed with the recent work on XSPEC build described in PR #34

----------------------------------------------- 
Using the files that you provide above, I can replicate the segv that you 
mention using the ciao4.6 version of sherpa (/soft/ciao- linux 64 bit 
installation). As you state, it is not consistent, but I've had it happen 
several times. 
From a quick peek into a generated core file- it looks like the segv is 
occurring in the XSpec code: 
Core was generated by `/soft/ciao-4.6/ots/bin/python 
/soft/ciao-4.6/ots/bin/ipython --profile sherpa -'. 
Program terminated with signal 11, Segmentation fault. 
#0 0x00007f37ea72a54a in bisearch (ne=<value optimized out>, 
ear=0x4fa5b80, 
    energy=@0x7fff63be200c) at xsgaul.f:314 
314 IF ( energy .GT. ear(bisearch) ) THEN 
We'll continue to investigate the issue and let you know when we have more 
details. 

----- 
> Hi Dan, 
> 
> I've edited: 
> 
> /pool14/nlee/helpdesk/NEI_sim.py 
> 
> to force it to point to the APEC files I've placed in: 
> 
> /pool7/nlee/apec 
> 
> which should ensure that the script executes. 
> 
> ~Nick 
> 
> 
> On Thu, Jan 16, 2014 at 10:20 AM, Nguyen, Dan <dnguyen@cfa.harvard.edu>wrote: 
> 
>> I'm not seeing the segv that you are reporting, in fact I never quite 
>> make it there: 
>> 
>> dnguyen_dev@newdevel12-10160: python -i NEI_sim.py 
>> Simulating 1 of 2000 
>> 
>> Traceback (most recent call last): 
>> File "NEI_sim.py", line 121, in <module> 
>> load_pha(filename) 
>> File "<string>", line 1, in load_pha 
>> File 
>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", 
>> line 1096, in load_pha 
>> phasets = self.unpack_pha(arg, use_errors) 
>> File 
>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", 
>> line 1031, in unpack_pha 
>> return sherpa.astro.io.read_pha(arg, use_errors) 
>> File 
>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/io/__init__.py", 
>> line 151, in read_pha 
>> datasets, filename = 
>> backend.get_pha_data(arg,use_background=use_background) 
>> File 
>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/io/crates_backend.py", 
>> line 964, in get_pha_data 
>> raise IOErr('reqcol', 'CHANNEL', filename) 
>> sherpa.utils.err.IOErr: Required column 'CHANNEL' not found in temp_1.pha 
>> >>> 
>> 
>> 
>> 
>> On Thu, Jan 16, 2014 at 10:07 AM, McLaughlin, Warren < 
>> wmclaugh@cfa.harvard.edu> wrote: 
>> 
>>> Hi Dan- 
>>> 
>>> I believe they are available for download from the table at: 
>>> 
>>> http://cxc.harvard.edu/caldb/prop_plan/imaging/index.html 
>>> 
>>> You can also access copies of them that I downloaded into /pool7/sherpa. 
>>> 
>>> -Warren 
>>> 
>>> 
>>> 
>>> On Thu, Jan 16, 2014 at 9:54 AM, Nguyen, Dan <dnguyen@cfa.harvard.edu>wrote: 
>>> 
>>>> Nick--- 
>>>> 
>>>> Can you make the files 
>>>> 
>>>> arfname="aciss_aimpt_cy16.arf" 
>>>> rmfname="aciss_aimpt_cy16.rmf" 
>>>> 
>>>> available? 
>>>> 
>>>> dnguyen_dev@newdevel12-10151: ls -l /pool14/nlee/helpdesk 
>>>> total 12 
>>>> -rw-r--r--. 1 nlee nlee 11733 Jan 15 17:02 NEI_sim.py 
>>>> 
>>>> Thanks in advance. 
>>>> 
>>>> dan 
>>>> 
>>>> dnguyen_dev@newdevel12-10148: python -i 
>>>> /pool14/nlee/helpdesk/NEI_sim.py 
>>>> Traceback (most recent call last): 
>>>> File "/pool14/nlee/helpdesk/NEI_sim.py", line 72, in <module> 
>>>> arf1=unpack_arf(arfname) 
>>>> File "<string>", line 1, in unpack_arf 
>>>> File 
>>>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/ui/utils.py", 
>>>> line 3411, in unpack_arf 
>>>> return sherpa.astro.instrument.ARF1D(sherpa.astro.io.read_arf(arg)) 
>>>> File 
>>>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/io/__init__.py", 
>>>> line 131, in read_arf 
>>>> data, filename = backend.get_arf_data(arg) 
>>>> File 
>>>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/io/crates_backend.py", 
>>>> line 673, in get_arf_data 
>>>> arf = open_crate(arg) 
>>>> File 
>>>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/io/crates_backend.py", 
>>>> line 44, in open_crate 
>>>> dataset = open_crate_dataset(filename, crateType, mode) 
>>>> File 
>>>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/sherpa/astro/io/crates_backend.py", 
>>>> line 36, in open_crate_dataset 
>>>> dataset = crateType(filename, mode=mode) 
>>>> File 
>>>> "/vobs/ASC_BUILD/lib/python2.7/site-packages/pycrates/cratedataset.py", 
>>>> line 28, in __init__ 
>>>> raise IOError("File " + input + " does not exist.") 
>>>> IOError: File aciss_aimpt_cy16.arf does not exist. 
>>>> 
>>>> 
>>>> 
>>>> On Wed, Jan 15, 2014 at 5:16 PM, Nicholas Lee <nplee@cfa.harvard.edu>wrote: 
>>>> 
>>>>> Hi sherpadev, 
>>>>> 
>>>>> I've been working on a helpdesk ticket for a user that is generating a 
>>>>> large number of synthetic spectra (2000 in this case) and repeatedly fits 
>>>>> them to a xsvnei model, and it seems there is a problem when the 
>>>>> NEIAPECROOT is set to a specific path and the NEIVERS called is AtomDB 2. 
>>>>> 
>>>>> I've placed a modified version of the user's scripts in: 
>>>>> /pool14/nlee/helpdesk/NEI_sim.py 
>>>>> 
>>>>> I've pointed the script to use the spectral model data found in the 
>>>>> HEAD installation of HEASoft. 
>>>>> 
>>>>> set_xsxset("APECROOT","/soft/heasoft/spectral/modelData/apec_v2.0.2") 
>>>>> set_xsxset("NEIAPECROOT","/soft/heasoft/spectral/ 
>>>>> modelData/APEC_nei_v11") 
>>>>> 
>>>>> and while using AtomDB 1.3.1, the scripts runs to completion; if set 
>>>>> to use 2.0, 2.0.1, or 2.0.2, the scripts will fail after a random number of 
>>>>> iterations - it can be as few as 1 or as many as 1000 - with a segv core 
>>>>> dump. Quite possibly the Python destructor not closing a file randomly? It 
>>>>> seems like a bug with how Sherpa is handling AtomDB 2. 
>>>>> 
>>>>> Thanks, 
>>>>> ~Nick 
>>>>> 
>>>> 
>>>> 
>>> 
>> 
>

**Comment by DougBurke** [comment]
I have run the test script using CIAO 4.6 and got it to crash. Fortunately, it appears that it's due to the simulated file, rather than it be run a certain number of times. I've placed a test script, along with the simulated data and ARF/RMF at https://gist.github.com/DougBurke/419ae244d24722910bc6 - to use it you need to download data from HEASARC as listed in the comments in `crash.py`.

Using this script, running with CIAO 4.6 (Linux 64-bit machine) I get

```
% python crash.py
read ARF file aciss_aimpt_cy16.arf
read RMF file aciss_aimpt_cy16.rmf
Segmentation fault (core dumped)
```

Using CIAO 4.7 (same machine) the script completes

```
% python crash.py
read ARF file aciss_aimpt_cy16.arf
read RMF file aciss_aimpt_cy16.rmf
Dataset               = 1
Method                = levmar
Statistic             = chi2xspecvar
Initial fit statistic = 10.8048
Final fit statistic   = 8.90484 at function evaluation 76
Data points           = 11
Degrees of freedom    = 7
Probability [Q-value] = 0.259561
Reduced statistic     = 1.27212
Change in statistic   = 1.89995
   abs1.nH        0.547047    
   vnei.kT        1.15179     
   vnei.Tau       4.7217e+09  
   vnei.norm      5.67551e-05 
```

The gist contains `valgrind.txt`, which is the valgrind outptu run using CIAO 4.6, but it's not very informative.

I believe that we can close this bug, as it appears to be related to the version of the XSpec library in use - as CIAO 4.6 used XSpec 12.8.0k whereas CIAO 4.7 uses 12.8.2e.

**Comment by olaurino** [comment]
@DougBurke, @anetasie shall we close this bug?

**Comment by DougBurke** [comment]
I am happy for this to be closed.
