### ISSUE TITLE
y=0 line is not drawn in residual-style plots with matplotlib 2.0

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#378]
With Sherpa 4.9.0 and matplotlib 1.5.3 the following creates a plot where there is a line drawn to indicate y=0 (as intended). If you switch to matplotlib 2.0 the y=0 line is not drawn. This behavior also holds in the 4.9.1 release candidate.

```
from sherpa import ui

ui.load_arrays(1, [1, 2, 3], [10, 17, 20])
ui.set_source(ui.const1d.mdl)
mdl.c0 = 15

ui.plot_resid()
```

**Comment by olaurino** [comment]
I would be OK with this change. However, I took the opportunity to check what it would take to add a proper test. Not much, apparently, so I am pushing a new commit to see whether Travis agrees. We can roll back the changes if needed.

The bigger issue is how to deal with the changes in CIAO-world, as the new commit introduces two new test-only dependencies: pytest-mpl and nose. But one step at a time.
