### ISSUE TITLE
Importing Bugs #13545 - grouping twice gives an IndexError exception

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#38]
This is a bug imported from an older bug tracking system.

The bug #13545 shows up in the current version in both CIAO and standalone.
Grouping twice gives an IndexError.

Here is the current output in my local version.

~~~~ python
(sherpa-test)13545 $ ipython
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:04:42) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sherpa.astro.ui import *
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: load_data("xte.pi")
read ARF file xte.warf
read RMF file xte.wrmf
read ARF (background) file xte_bkg.warf
read RMF (background) file xte_bkg.wrmf
read background file xte_bkg.pi

In [3]: notice(0.3,2)

In [4]: show_data()
Data Set: 1
Filter: 0.2993-1.9929 Energy (keV)
Bkg Scale: 0.332619
Noticed Channels: 21-137
name           = xte.pi
channel        = Float64[1024]
counts         = Float64[1024]
staterror      = None
syserror       = None
bin_lo         = None
bin_hi         = None
grouping       = None
quality        = None
exposure       = 18513.2782715
backscal       = 2.18391968294e-07
areascal       = 1.0
grouped        = False
subtracted     = False
units          = energy
rate           = True
plot_fac       = 0
response_ids   = [1]
background_ids = [1]

RMF Data Set: 1:1
name     = xte.wrmf
detchans = 1024
energ_lo = Float64[1070]
energ_hi = Float64[1070]
n_grp    = UInt64[1070]
f_chan   = UInt64[1354]
n_chan   = UInt64[1354]
matrix   = Float64[382802]
offset   = 1
e_min    = Float64[1024]
e_max    = Float64[1024]

In [5]: group_counts(30)

In [6]: import matplotlib

In [7]: plot_data()

In [8]: show_data()
Data Set: 1
Filter: 0.3322-2.1754 Energy (keV)
Bkg Scale: 0.332619
Noticed Channels: 1-165
name           = xte.pi
channel        = Float64[1024]
counts         = Float64[1024]
staterror      = None
syserror       = None
bin_lo         = None
bin_hi         = None
grouping       = Float64[1024]
quality        = Float64[1024]
exposure       = 18513.2782715
backscal       = 2.18391968294e-07
areascal       = 1.0
grouped        = True
subtracted     = False
units          = energy
rate           = True
plot_fac       = 0
response_ids   = [1]
background_ids = [1]

RMF Data Set: 1:1
name     = xte.wrmf
detchans = 1024
energ_lo = Float64[1070]
energ_hi = Float64[1070]
n_grp    = UInt64[1070]
f_chan   = UInt64[1354]
n_chan   = UInt64[1354]
matrix   = Float64[382802]
offset   = 1
e_min    = Float64[1024]
e_max    = Float64[1024]

ARF Data Set: 1:1
name     = xte.warf
energ_lo = Float64[1070]
energ_hi = Float64[1070]
specresp = Float64[1070]
bin_lo   = None
bin_hi   = None
exposure = 18513.2782715

Background Data Set: 1:1
Filter: 7.4789 Energy (keV)
Noticed Channels: 1-1024
name           = xte_bkg.pi
channel        = Float64[1024]
counts         = Float64[1024]
staterror      = None
syserror       = None
bin_lo         = None
bin_hi         = None
grouping       = Float64[1024]
quality        = Float64[1024]
exposure       = 18513.2782715
backscal       = 6.56582415104e-07
areascal       = 1.0
grouped        = True
subtracted     = False
units          = energy
rate           = True
plot_fac       = 0
response_ids   = [1]
background_ids = []

Background RMF Data Set: 1:1
name     = xte_bkg.wrmf
detchans = 1024

In [9]: group_counts(15)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-f2f20366e574> in <module>()
----> 1 group_counts(15)

<string> in group_counts(id, num, bkg_id, maxLength, tabStops)

/Users/aneta/git/sherpa/sherpa/astro/ui/utils.pyc in group_counts(self, id, num, bkg_id, maxLength, tabStops)
   7552         if bkg_id is not None:
   7553             data = self.get_bkg(id, bkg_id)
-> 7554         data.group_counts(num, maxLength, tabStops)
   7555 
   7556     ### DOC-TODO: check the Poisson stats claim; I'm guessing it means

/Users/aneta/git/sherpa/sherpa/astro/data.pyc in group_counts(self, num, maxLength, tabStops)
   1005             bkg = self.get_background(bkg_id)
   1006             if (hasattr(bkg, "group_counts")):
-> 1007                 bkg.group_counts(num, maxLength=maxLength, tabStops=tabStops)
   1008 
   1009     ### DOC-TODO: see discussion in astro.ui.utils regarding errorCol

/Users/aneta/git/sherpa/sherpa/astro/data.pyc in group_counts(self, num, maxLength, tabStops)
   1001             raise ImportErr('importfailed', 'group', 'dynamic grouping')
   1002         self._dynamic_group(pygroup.grpNumCounts, self.counts, num,
-> 1003                             maxLength=maxLength, tabStops=tabStops)
   1004         for bkg_id in self.background_ids:
   1005             bkg = self.get_background(bkg_id)

/Users/aneta/git/sherpa/sherpa/astro/data.pyc in _dynamic_group(self, group_func, *args, **kwargs)
    837                 kwargs.pop(key)
    838 
--> 839         old_filter = self.get_filter(group=False)
    840         do_notice = numpy.iterable(self.mask)
    841 

/Users/aneta/git/sherpa/sherpa/astro/data.pyc in get_filter(self, group, format, delim)
   1596             x = x[::-1]
   1597             mask = mask[::-1]
-> 1598         return create_expr(x, mask, format, delim)
   1599 
   1600     def get_filter_expr(self):

/Users/aneta/git/sherpa/sherpa/utils/__init__.pyc in create_expr(vals, mask, format, delim)
    571             expr.append(format % vals[ii])
    572             expr.append(',')
--> 573     if expr[-1] in (',',delim):
    574         expr.append(format % vals[-1])
    575 

IndexError: list index out of range

~~~~

**Comment by olaurino** [comment]
@anetasie I can reproduce this. A simple workaround is to call `ungroup()` before grouping again.

I guess it makes sense that data should be ungrouped before it can be regrouped, it this correct?

If it is, I need more information regarding the fix: the simplest fix I can think of involves refusing to apply a new group function on a dataset that has already been grouped, and showing the user a WARNING.

An alternative involves automatically calling `ungroup()` if a group function is called and the dataset has already been grouped.

I can also see possible combinations of these two possibilities (e.g. refuse to group a grouped dataset, but accept a keyword argument to force the application of `ungroup()`).

What do you think?

**Comment by anetasie** [comment]
I don't think we should refuse to apply the new grouping. Sherpa does not have support for hierarchical grouping, so the data needs to ungroup before applying a new group. I would say that this can be done automatically by calling `ungroup()`. Although, I see the reason for just refusing to apply a new grouping and exit with error. I'll discuss with SDS and come back with the final  answer.

**Comment by olaurino** [comment]
> Sherpa does not have support for hierarchical grouping,

Are there any plans to support hierarchical grouping in the foreseeable future?

**Comment by anetasie** [comment]
We did not plan on this and I don't think this is something with the high priority for the future.

**Comment by anetasie** [comment]
Kenny provided a good example for the automatically applying `ungroup` before grouping.

If you're trying to "optimize" the grouping you're likely doing something like

     group_counts(10)
     plot_data()
     group_counts(15)
     plot_data()
     group_counts(12)
     plot_data()

so this would require extra `ungroup` with each `group() ` and having sherpa automatically applying `ungroup` makes sense.

**Comment by anetasie** [comment]
Also we will follow the XSPEC convention if we `ugroup()` automatically.

**Comment by olaurino** [comment]
Sounds good. Thanks for the info.

**Comment by olaurino** [comment]
Trying to come up with a minimal set of steps to reproduce the issue (and thus a test case), I realized that the issue might have more to do with filtering rather than grouping, i.e.:

~~~~ python
In [1]: from sherpa.astro.ui import *

In [2]: load_data("sherpa-test-data/sherpatest/ciao4.3/pha_intro/3c273.pi")
KeyboardInterrupt

In [2]: load_data("sherpa-test-data/sherpatest/ciao4.3/pha_intro/3c273.pi")
WARNING: [...]

In [3]: notice(0.3,2)

In [4]: group_counts(30)

In [5]: group_counts(15)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~~~~ 

results in an error. However, the following code does not:

~~~~ python
In [1]: from sherpa.astro.ui import *

In [2]: load_data("sherpa-test-data/sherpatest/ciao4.3/pha_intro/3c273.pi")
WARNING: [...]

In [3]: group_counts(30)

In [4]: group_counts(15)

In [5]: 
~~~~

The only different is the call to `notice(0.3,2)`

**Comment by anetasie** [comment]
Yes, @DougBurke suggested that there are issues with filtering and grouping, since Sherpa always starts grouping from the first channel in the data regardless of the applied filter, while when the data is filtered the user expectation is that the grouping would be only applied to the data within the valid filter.
So the logic here may need to be reviewed in more details.

**Comment by olaurino** [comment]
@anetasie The fix to this issue might actually be simpler than I expected. I am going to issue a PR as soon as I am done with the PEP8 changes. However, we should check whether we have enough testing coverage for the grouping code, especially if we plan to make significant changes.

So far, the only test exercising the `group_counts` method is this:
https://github.com/sherpa/sherpa-test-data/blob/master/sherpatest/ciao4.3/setfullmodel/fit.py

We should make sure that is enough. If it is not, then we should add more tests. It could be a good idea to add some unit tests, as in the above thread the grouping results are only checked against the results of the fit (or they are not checked at all). So, even if the tests may cover the grouping code, it is not clear whether meaningful tests are actually executed.

In any case I created a new test as part of the patch for this bug.

In lieu of a proper PR, here is the fix:
https://github.com/sherpa/sherpa/compare/bug-%2338-grouping-twice

**Comment by DougBurke** [comment]
Just to note that this is a slightly tricky bug to tickle, since it doesn't happen if (using the example from https://github.com/sherpa/sherpa/issues/38#issuecomment-116795968 ) I don't see the error if I use `ui.notice(0.5, 8)` rather than `ui.notice(0.3, 2)`.
