### ISSUE TITLE
optfcts.py - Unnecessary Runtime warning

### ISSUE THREAD

**Issue by saoCharles** [sherpa/sherpa#402]
On lines 489 and 677 of optfcts.py, there is a check on the bounds and in parallel there is a check on whether the value is a NaN.  This check needs to be done in series to avoid the Runtime error that numpy throws in the bounds check function.  

The offending code is: 

    def stat_cb0(x_new):
        if _outside_limits(x_new, xmin, xmax) or _my_is_nan(x_new):
            return FUNC_MAX
        return orig_fcn(x_new)

A fix would look like this as an option:
    def stat_cb0(x_new):
        if _my_is_nan(x_new):
            return FUNC_MAX
        if _outside_limits(x_new, xmin, xmax) :
            return FUNC_MAX
        return orig_fcn(x_new)

**Comment by DougBurke** [comment]
We should be able to switch the two checks - i.e.

    if _my_is_nan(x_new) or _outside_limits(x_new, xmin, xmax):

Do we have an easy way to trigger the existing behavior?

**Comment by olaurino** [comment]
Even if we don't get any test cases from @saoCharles it would make sense to invert the conditions as suggested by @DougBurke because it just makes sense :)
