### ISSUE TITLE
Importing Old Issues -  incorporate the background component as an argument to calc_stat_func 

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#41]
This is an issue sent by a user to the CXC helpdesk pointing out the limitations of the calc_stat_function.
This issue limits the user_stat functionality. There is no workaround..

"So I'm trying to define a w-statistic function for use in fitting some data, and I'm trying to follow the examples and documentation at http: //cxc.harvard.edu/sherpa/faq/user_stat.html and
http: //cxc.harvard.edu/sherpa/ahelp/load_user_stat.html, and the definition of the w-statistic at
http: //heasarc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html (at
 the end of the second cstat section).

 My question is, how does a statistic-calculating function gain access to the
 backgrounds from the pha file? According to the documentation the function
 definition should look like
 ---
 def calc_stat_func(data, model, staterror=None, syserror=None, weight=None):
 ---
 and that doesn't have a "background" argument."

**Comment by DougBurke** [comment]
This is addressed in #90
