### ISSUE TITLE
filter and then group lead to inconsistent results

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#416]
The script below seems to give inconsistent results:

``` python
import numpy as np
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, ui.DataPHA)
ui.notice(3.5, 6.5)
ui.group_counts(3)
print(ui.get_data().get_dep(filter=True))
np.testing.assert_equal([0, 0, 0, 0, 0, 2, 2, 2, 2, 2], ui.get_data().quality)
np.testing.assert_array_equal([3, 1], ui.get_data().get_dep(filter=True))
```

I would have expected the resulting array to be `[3, 1]`, with channels 6 to 10 having an associated quality value of 2. While the quality array is the one I would expect, the resulting filtered, grouped dependent array is empty, which does not seem to make sense.

**EDIT:** It looks like there is more to this bug, so I am expanding it.

First, one can get a reasonable result by using `ignore_bad`, which is surprising since `ignore_bad` claims to work in a different way, i.e. it should remove the filters... it even prints out a warning about it:

```python
import numpy as np
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, ui.DataPHA)
ui.notice(3.5, 6.5)
ui.group_counts(3)
ui.ignore_bad()
print(ui.get_data().quality)
print(ui.get_data().get_dep(filter=True))
np.testing.assert_array_equal([3], ui.get_data().get_dep(filter=True))
```

The first obvious surprise is that ignoring some channels results in getting back good groups we wouldn't get without `ignore_bad`, as in the first case.

But there's more. `ignore_bad` only meets your expectations if you use the grouping function without tab stops, probably because the quality array changes in different ways when using tab stops: 

```python
import numpy as np
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, ui.DataPHA)
ui.notice(3.5, 6.5)
tab_stops = ~ui.get_data().mask
ui.group_counts(3, tabStops=tab_stops)
ui.ignore_bad()
print(ui.get_data().quality)
print(ui.get_data().get_dep(filter=True))
np.testing.assert_array_equal([3], ui.get_data().get_dep(filter=True))
```

The result in this case is `array([ 0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.])`, which is actually what one would expect from the `ignore_bad` in the previous case, at least according to the documentation and to what the code seems to be intending to do.

Note: We are closing #149 and replacing it with a number of issues found during investigations related to the `specfit` tool. One of such bugs was that `ignore_bad` removes previously set filters when acting on grouped data. However, it looks like this case is explicitly handled in the code, so it looks like the behavior is intentional. However, while investigating this apparent issue, a different issue arose.

**Comment by DougBurke** [comment]
@olaurino - a tiny nitpick: it's `ui.DataPHA` not `DataPHA`

**Comment by DougBurke** [comment]
The first program, 

```
import numpy as np
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, ui.DataPHA)
ui.notice(3.5, 6.5)
ui.group_counts(3)
print(ui.get_data().get_dep(filter=True))
np.testing.assert_equal([0, 0, 0, 0, 0, 2, 2, 2, 2, 2], ui.get_data().quality)
np.testing.assert_array_equal([3, 1], ui.get_data().get_dep(filter=True))
```

returns `[1, 3]`  with #922. So that's good.

**Comment by DougBurke** [comment]
The second program 

```
import numpy as np
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, ui.DataPHA)
ui.notice(3.5, 6.5)
ui.group_counts(3)
ui.ignore_bad()
print(ui.get_data().quality)
print(ui.get_data().get_dep(filter=True))
np.testing.assert_array_equal([3], ui.get_data().get_dep(filter=True))
```

returns with #922 (the tests pass so I assume it's the expected result):

```
WARNING: filtering grouped data with quality flags, previous filters deleted
[0. 0. 0. 0. 0. 2. 2. 2. 2. 2.]
[3.]
```

**Comment by DougBurke** [comment]
The final program fails with #922:

```
import numpy as np
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, ui.DataPHA)
ui.notice(3.5, 6.5)
tab_stops = ~ui.get_data().mask
ui.group_counts(3, tabStops=tab_stops)
ui.ignore_bad()
print(ui.get_data().quality)
print(ui.get_data().get_dep(filter=True))
np.testing.assert_array_equal([3], ui.get_data().get_dep(filter=True))
```

```
WARNING: filtering grouped data with quality flags, previous filters deleted
[0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]
[0. 0. 0. 3. 0. 0. 0. 0.]
Traceback (most recent call last):
  File "qft.py", line 12, in <module>
    np.testing.assert_array_equal([3], ui.get_data().get_dep(filter=True))
  File "/home/dburke/anaconda/envs/sherpa-master/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 930, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/dburke/anaconda/envs/sherpa-master/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 759, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(shapes (1,), (8,) mismatch)
 x: array([3])
 y: array([0., 0., 0., 3., 0., 0., 0., 0.])
```

**Comment by DougBurke** [comment]
I've added tests in #922, showing these tests, and how they get changed by #922
