### ISSUE TITLE
improve UI for grouping after filtering

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#417]
If a user filters the data and the groups it, e.g. according to the number of counts, the grouping is performed by ignoring the filter first, applying the grouping, and then applying the filter again. There is a way to apply the grouping only inside the filtered range(s), but this is hardly user friendly, i.e.:

``` python
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, DataPHA)
ui.notice(3.5, 6.5)
tab_stops = ~ui.get_data().mask
ui.group_counts(3, tabStops=tab_stops)
np.testing.assert_array_equal([3, 1], ui.get_data().get_dep(filter=True))
```

It would be useful to provide an option to the grouping functions to do this seamlessly, e.g.:

``` python
from sherpa.astro import ui
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = [0, 0, 0, 2, 1, 1, 0, 0, 0, 0]
ui.load_arrays(1, x, y, DataPHA)
ui.notice(3.5, 6.5)
ui.group_counts(3, filter=True)
np.testing.assert_array_equal([3, 1], ui.get_data().get_dep(filter=True))
```

Note: we are closing #149 and replacing it with related issues uncovered while working at `specfit`.

**Comment by DougBurke** [comment]
I think that #956 is the same as this issue but I'll leave them both open for the moment
