### ISSUE TITLE
move docstrings from sherpa.astro.xspec._xspec to sherpa.astro.xspec

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#429]
This is not a high priority - I just want to note this down whilst I remember it. It's also a small/simple project if anyone wants to do it.

A number of routines - e.g. `get_xsversion` - have the dosctring encoded in `sherpa/astro/xspec/src/_xspec.cc`, which makes sense since this is where the function is defined. However, this has a bunch of downsides, including

- editing the docstring means rebuilding the module
- the docstring is not as obvious to write in C/C++ compared to Python (in particular multi-line strings)
  which can mean multiple rebuilds to get what you want
- it complicates the documentation build, which - in https://github.com/sherpa/sherpa/pull/302 - uses mock to stub out `sherpa.astro.xspec._xspec` so you don't need XSPEC to build the module documentation

Since these routines are re-exported from `sherpa.astro.xspec`, and this is how we want people to use them, my suggestion is that we 

1. move the docstrings into `sherpa/astro/xspec/__init__.py` - for any symbol from `_xspec` re-exported by `sherpa.astro.xspec` and that has a docstring

2. add a basic docstring to the functions in `_xspec.cc` to point to this

**Comment by hamogu** [comment]
I don't know exactly when this was done and I don't want to go spelunking into old commits and documentation version now, but it's clearly done: https://sherpa.readthedocs.io/en/4.15.1/model_classes/api/sherpa.astro.xspec.get_xsversion.html?highlight=get_xsversion
