### ISSUE TITLE
RFE: asymmetric error bars

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#433]
From the CXC Help Desk.

Hi sherpadev,

We've had many questions over the years regarding the support of asymmetric error bars (and a couple for support of x-axis error bars in addition to the y-axis) in Sherpa.

A ticket came in a few minutes ago from an user that's high up in the CXC which reminded me to make sure this is on the list of enhancements (I don't see it listed on github).

Her message can be found below.

Thanks,
~Nick

*****
I have an ascii file of the form 

#MJD   Flux.   Flux upper error.   Flux lower error

i.e four columns, the last two being upper and lower errors (they are
different).

How do I read this into sherpa? The assumption seems to be that col 3 is the error, with no room for upper and lower errors.
*****

**Comment by anetasie** [comment]
Here is a possible approach that we will implement.

Read the 4 columns and recognize the low and high error as such and use
the errors in plotting, plot_data, or plot_fit etc.

There are two options to include these errors in the fit:

1/ Use an average:

Calculate an average of low/high error, associated with a given data set and use in fitting assuming that this is 1 sigma  (low+high)/2.
Use the average in the fit.

Plot should still show the original errors, and if requested by user
the average error should be plotted as an option.

2/ Bootstrap:

Use low and high errors as entered to set a range on the parameters for
bootstrap simulations.

In the script the simulations assume two normal distribution with the
variances defined by the low/high bounds. The data points (y) are
simulated for each location x and then fit with a model (the example
assumes the power law model, but the model definition is flexible and
could be any models and combinations allowed in Sherpa).

Final result contains the best fit parameters and the associated uncertainties from
the bootstrap simulations.

Plot will show the original low/high errors together with the data points.

**Comment by DougBurke** [comment]
@anetasie do you think we can close this now that #615 has been merged, or is there more we can do?

**Comment by anetasie** [comment]
Yes.
