### ISSUE TITLE
Update conda installation instructions for recent changes (e.g. source -> conda)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#448]
I don't think this needs to be done for the Sherpa 4.10.0 release, as source still works, but the "new" way of activating the environment is with

    conda activate well-thought-out-environment-name

so we should update `README.md` at some point soon.

**Comment by olaurino** [comment]
This only works if you have a specific setup in your shell startup scripts, or after you `source activate`d the first environment.

**Comment by DougBurke** [comment]
The installation documentation - both [README.md](https://github.com/sherpa/sherpa#readme) and [Sherpa on Read The Docs](https://sherpa.readthedocs.io/en/latest/install.html) - has been changed so that it no-longer talks about setting up a conda environment, so this change is no longer needed.
