### ISSUE TITLE
sample_flux ignoring flux=0 is biasing results

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#457]
From CIAO helpdesk ticket 21264, a user found that the median value returned by sample_flux was not the same as taking the median of the individual realizations.  For details and files see /data/lenin2/HelpDeskPub/21264/SampleFluxLimits.ipynb .

They surmised that flux=0 values were being excluded when the median value is computed.

Digging through the code it does look like flux values generated when the model parameter are *at* or beyond their soft limits are excluded from the median, eg

https://github.com/sherpa/sherpa/blob/d8b58d91b17e786a7f77f67d7b0241a9265d3c76/sherpa/astro/flux.py#L103-L111

Since the user is doing an upper-limits kind of analysis, their model's normalization were indeed hitting 0, which is the hard limit for the parameters.  Since 0 is the limit, all those samples were excluded when the median was computed which then biases the final flux values higher than it should be.

It's not clear if allowing model values at the limit to be included would be sufficient (ie < vs <= kind of thing).

**Comment by DougBurke** [comment]
The PR in #754 changes the above code to be inclusive, rather than exclusive, at the boundaries. So this will slightly change things. However, it still removes those points beyond the soft limits.
