### ISSUE TITLE
Should this ZeroDivisionError be caught in calc_stat_info?

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#476]
From a CIAO helpdesk ticket (number 21329) ... the user has a dataset, where after grouping there is only 1 bin.  With their model they have DOF=0.  When they do a `calc_stat_info` it returns a raw `ZeroDivisionError` exception.  Should this maybe be caught and the stats set to `NaN` ? 

Here's a mock'ed up example --

```python
>>> foo = np.arange(100)
>>> goo = np.zeros(100)
>>> goo[10]=10
>>> load_arrays(1, foo, goo, DataPHA)
>>> group_counts(1, 100)
>>> set_full_model(1,const1d.fudge)
>>> fit()
Dataset               = 1
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 442.443
Final fit statistic   = 2.08554e-29 at function evaluation 5
Data points           = 1
Degrees of freedom    = 0
Reduced statistic     = nan
Change in statistic   = 442.443
   fudge.c0       0.1         
```

So far, so good.  The `Reduces statistic` is `nan`, but then when they try:

```python
>>> calc_stat_info()
ZeroDivisionError: float division by zero
```
Should this exception be caught presumably like in the `fit()` output ? 

(Above is from sherpa in CIAO 4.10 python3, Linux64)

**Comment by olaurino** [comment]
Thanks @kglotfelty. I agree. I'll see if I can squeeze it in for the next release. Hopefully it's a small change.
