### ISSUE TITLE
Installing Sherpa and XSPEC extension

### ISSUE THREAD

**Issue by swapsha96** [sherpa/sherpa#479]
I am installing Sherpa along with XSPEC extension. I have successfully install HEASoft and XSPEC 1.12.9. The extension is not installed successfully when I tried installing Sherpa from source. It does look like the configuration is correct:
![screen shot 2018-07-30 at 03 57 30](https://user-images.githubusercontent.com/14021461/43371325-fb02bce8-93ac-11e8-9e68-270c13f88044.png)
Sherpa is installed successfully but I get this error in between the process when I run `python setup.py install`:
![screen shot 2018-07-30 at 03 42 10](https://user-images.githubusercontent.com/14021461/43371336-2874b12c-93ad-11e8-97c9-7eb8e9b7ff1a.png)
I get the following when I run `import sherpa.astro.xspec` in the Python terminal:
![screen shot 2018-07-30 at 03 42 34](https://user-images.githubusercontent.com/14021461/43371339-3097d10e-93ad-11e8-9211-4aba8ec1787f.png)
Following the conversation in issue #198, I made sure that there's not trace of Sherpa in my system before building from source, created new conda (miniconda) environment. It does seem like there is something specific to the local setup may be interfering with Sherpa that I am unable to identify. Please let me know what more information you want me to share here. Thanks!

**Comment by olaurino** [comment]
Hi @swapsha96. Is it possible you are trying to import sherpa while the current directory is the one with the source code/git repo? You can try two things:
  * cd to a different folder and try to import Sherpa
  * use `python setup.py develop` instead of `install`. In this case the import should work both inside and outside the source folder.

Please let me know if this solves your problem.

**Comment by swapsha96** [comment]
There's some progress. I did not find any error during installation. But I am getting this when I run `import sherpa.astro.xspec`:
![screen shot 2018-07-31 at 02 19 26](https://user-images.githubusercontent.com/14021461/43422909-b3ef5dd6-9468-11e8-8987-8e15290e1b97.png)

**Comment by olaurino** [comment]
You might need to add the folder with the XSPEC libraries to `$DYLD_LIBRARY_PATH` or similar.

**Comment by swapsha96** [comment]
@olaurino Setting `DYLD_LIBRARY_PATH` worked! Thank you very much! 😄
