### ISSUE TITLE
Add a zeondo link for citation/attribution

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#49]
I'd forgotten about this, but we should add a link between the sherpa github account and zenodo (for getting a DOI for citation).

An example of this integration is https://github.com/dfm/triangle.py - if you go to the bottom of the page there's an Attribution section with a doi badge - this takes you to the zenodo page (there's one for each release): https://zenodo.org/record/11020#.VYgkWZRHB2Q

I tried following the guide at https://guides.github.com/activities/citable-code/ but I think @olaurino  would have to do this, as owner of the account.

**Comment by olaurino** [comment]
I think it's an excellent idea. I'll look into it.

**Comment by olaurino** [comment]
I looked into it, and it seems like the seamless archival only happens when a new release event is triggered by GitHub upon... well... a new release. It is most likely possible to upload the archive manually, but maybe we can consider waiting for the next release?

**Comment by DougBurke** [comment]
I can talk to our chief librarian who has been involved with a lot of
Zenodo stuff when I get back from vacation. I agree it's not a high
priority at this time and can wait.

**Comment by olaurino** [comment]
In any case I did set the web hooks, so the basic configuration should be in place.
