### ISSUE TITLE
How to handle Python 2.7 support?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#498]
I think it would be useful to articulate a plan for Python 2.7 support. My suggestion would be that we keep in python 2.7 support and testing for the CIAO 4.11/Sherpa 4.11 release (as it is too dangerous to remove at this time, and we haven't announced any plans for standalone Sherpa). After release of Sherpa 4.11.0, we immediately remove python 2.7 support by

- [ ] remove testing with python 2.7
- [ ] remove 'import six' statements

This then may help with some work we'd like to do (e.g. clean up of the `BaseData` class) since we can rely on Python 3.5+ semantics.

One downside to this is that it then means that any sherpa 4.11.n (for n > 0) release would not be compatible with Python 2.7.

An alternative would be to have a "python 3" branch to work on, forward porting work to that (or however `astropy` did it), but I don't think it's worth the effort.

Thoughts and suggestions welcome.

**Comment by olaurino** [comment]
> One downside to this is that it then means that any sherpa 4.11.n (for n > 0) release would not be compatible with Python 2.7.

If we decide to drop support for Python 2.7 at any time, we can also decide to backport bug fixes or even small improvements for as long as it is feasible, before the code bases diverge too much.

It would help to have more control over the download statistics, which we currently don't have. In any case it all depends on what the demand for Python 2.7-compatible Sherpa is.

**Comment by olaurino** [comment]
I forgot to add a comment a couple of time, so here it is: when we decide to drop support for Python 2.7 I would not do any sweeps to e.g. remove all instances of usage of six, as that would make it hard to backport any bug fixes right off the bat. Obviously, as we start using Python 3.5 features that will be more and more true, especially if we tackle cleanups like the `BaseData` thing you mentioned. But hopefully by that time we'll be living in an ideal world where no-one uses Python 2.7 and Python 4 is type-safe ;)

**Comment by anetasie** [comment]
Yes, I'm still using Python 2.7 on one of my computers. I will upgrade at some point. Perhaps we should follow CIAO and have 4.11 release be only Python 3.5 and higher and drop 2.7 in early 2019. In meantime we could put a statement in our standalone 4.10.1 release readme to warn potential users.

**Comment by cdeil** [comment]
From the Gammapy side and talking to the Sherpa users I know: it's OK if you drop Python 2 support in Sherpa now, or in 2019, whatever timeline works best for you.

**Comment by hamogu** [comment]
This is an old issue... Are we dropping 2.7 at the end of 2019? I suggest sherpa to join the Python 3 statement: https://python3statement.org/

**Comment by DougBurke** [comment]
I am planning sometime soon to write and submit a PR that removes python 2.7 support for the 4.12 release

Doug

**Comment by wmclaugh** [comment]
Hi Doug-

Aneta, Janet, Dan, and I had a meeting this morning and discussed this
topic. The agreement was that we were planning on pulling the plug on
Python 2.7 at the end of this month unless we heard objections.

-Warren

**Comment by DougBurke** [comment]
I've started #665 - focussing on the documentation.
