### ISSUE TITLE
Add a "js-based plotting library" plot backend for use in Jupyter notebooks

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#499]
Should we look at Vega/Altair/Plotly/... based plot backends to provide interactive graphic capabilities from within a jupyter notebook. With the matplotlib backend you just get PNGs (at least by default).We could create more interactive visualizations with a JS-based plotting library.

I realize that Vega, Altair, and Plotly are not all the same thing (one is a specification rather than a library), and that there are likely other candidates.

**Comment by olaurino** [comment]
Could be a good gsoc project.

**Comment by DougBurke** [comment]
Maybe we need a "gsoc" label ;-)

**Comment by DougBurke** [comment]
Also, and this may deserve its own issue: it would be nice to use https://github.com/ericmandel/js9 to display images from within a notebook. I have talked to Eric about this in the past but have got lost in the attempts to integrate JS9 into Python notebooks (see https://github.com/ericmandel/js9/issues/30)

**Comment by anetasie** [comment]
When is the gsoc deadline? Do we need to post our project?

**Comment by DougBurke** [comment]
I know other projects are worrying about GSOC, but I haven't been following the Astro group this year.

**Comment by wmclaugh** [comment]
The application perioid runs from January 15 - February 6.

https://developers.google.com/open-source/gsoc/timeline


Google Summer of Code 2019 Timeline
DateEvent
2018
November 13 Program announced
2019
January 15 20:00 UTC Mentoring organizations can begin submitting
applications to Google
February 6 20:00 UTC Mentoring organization application deadline
February 6 - February 25 Google program administrators review organization
applications
February 26 12:00 UTC List of accepted mentoring organizations published
February 26 - March 25 Potential student participants discuss application
ideas with mentoring organizations
March 25 18:00 UTC Student application period begins
April 9 18:00 UTC Student application deadline
May 6 18:00 UTC Accepted student proposals announced
Community Bonding Period
<http://googlesummerofcode.blogspot.com/2007/04/so-what-is-this-community-bonding-all.html>
Students
get to know mentors, read documentation, get up to speed to begin working
on their projects
May 27 Coding officially begins!
June 24 18:00 UTC Mentors and students can begin submitting Phase 1
evaluations
June 28 18:00 UTC Phase 1 Evaluation deadline
Work Period Students work on their project with guidance from Mentors
July 22 18:00 UTC Mentors and students can begin submitting Phase 2
evaluations
July 26 18:00 UTC Phase 2 Evaluation deadline
Work Period Students continue working on their project with guidance from
Mentors
August 19 - 26 18:00 UTC Final week: Students submit their final work
product and their final mentor evaluation
August 26 - Sept 2 18:00 UTC Mentors submit final student evaluations
September 3 Final results of Google Summer of Code 2019 announced
October Mentor Summit at Google

**Comment by hamogu** [comment]
Other backend might be nice to have, but for the short-term it might be easier to make sure that "%matplotlib notebook" or "%matplotlib ipympl" works (see https://matplotlib.org/3.1.1/tutorials/introductory/usage.html) and gives you an interactive plot. (I just tried in one of my sherpa notebook and it did not work, while it does in my non-sherpa notebook, but I don't have time right now to find the difference.)

Both backends are not known by most people, although at least nbagg ships with matplotlib.
