### ISSUE TITLE
Explicitly mention gfortran requirement for installation

### ISSUE THREAD

**Issue by taldcroft** [sherpa/sherpa#5]
The current install docs don't call out the requirement for `gfortran`.  I initially tried `g77` on Mac Mavericks and this failed.

**Comment by olaurino** [comment]
Why did it fail? What was the version of g77?

We should probably start curating a table with the combinations of compilers and platforms that Sherpa has been successfully (or unsuccessfully) built with.

**Comment by taldcroft** [comment]
```
sherpa)neptune$ g77 --version
GNU Fortran (GCC) 3.4.0
Copyright (C) 2004 Free Software Foundation, Inc.
```
Here is the build log:
https://gist.github.com/taldcroft/2f5b7f3c8c4ab44361b8

**Comment by taldcroft** [comment]
An `INSTALL` file in the source directory would be nice and could be a useful place to gather compiler / platform specific instructions.
