### ISSUE TITLE
C++ warnings from compiling pileup code

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#505]
With

% g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I get the following compilation warnings from `sherpa/astro/utils/src/pileup.cc`

```
g++: sherpa/astro/utils/src/pileup.cc
sherpa/astro/utils/src/pileup.cc: In function ‘int apply_pileup(unsigned int, const double*, double*, double*, double*, double, unsigned int, unsigned int*, const double*, const double*, const double*, double, double, double, double, double, double, sherpa::usrfuncproto, sherpa::PyWrapper*)’:
sherpa/astro/utils/src/pileup.cc:509:35: warning: ‘k.pileup_kernel_t::arf_s_tmp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (k->arf_s_tmp != NULL) free (k->arf_s_tmp);
                              ~~~~~^~~~~~~~~~~~~~
sherpa/astro/utils/src/pileup.cc:606:19: note: ‘k.pileup_kernel_t::arf_s_tmp’ was declared here
   pileup_kernel_t k;
                   ^
sherpa/astro/utils/src/_pileup.cc: In function ‘PyObject* _apply_pileup(PyObject*, PyObject*)’:
sherpa/astro/utils/src/_pileup.cc:126:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr< sherpa::PyWrapper >
        ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from sherpa/astro/utils/src/_pileup.cc:22:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
```

**Comment by dtnguyen2** [comment]
auto_ptr was deprecated, either use unique_ptr or shared_ptr.  I suspect unique_ptr should be enough.

As for the k->arf_s_tmp may be used uninitialized is a bit odd since in the init_kernel function there is the following code:

  if ((NULL == (k->arf_s_fft = XMALLOC (4*NUM_POINTS, double)))
      || (NULL == (k->arf_s_tmp = XMALLOC (NUM_POINTS, double)))
      || (NULL == (k->arf_s_fft_tmp = XMALLOC (4*NUM_POINTS, double))))
    {
      delete_kernel (k);
      return NULL;
    }
I suppose one could change the XMALLOC macro to use calloc instead of malloc?

**Comment by DougBurke** [comment]
I don't know how the C++ stuff works with the compilers we use for CIAO; I would hope that ours are new enough that `unique_ptr` will work there.

**Comment by DougBurke** [comment]
Changing `std::auto_ptr` to `std::unique_ptr`` stops the warning message. You need to have XSPEC (and presumably a FITS backend) to actually check this fix - my current run looks to have failed with 

    @requires_fits
    @requires_xspec
    def test_pileup(self):
        self.run_thread('pileup')
    
        fr = ui.get_fit_results()
        covarerr = sqrt(fr.extra_output['covar'].diagonal())
>       assert covarerr[0] == approx(684.056 , rel=1e-4)
E       AssertionError: assert 694.3746848979197 == 684.056 ± 6.8e-02
E        +  where 684.056 ± 6.8e-02 = approx(684.056, rel=0.0001)

but that may not be due to to the pointer change but some other thing (strange things are afoot in this build!).

However, looking at the code it's not clear why we need this wrapper object, since all it seems to be used for is passing a function pointer between functions. So maybe we can just remove it completely?

**Comment by DougBurke** [comment]
Turns out `std::unique_ptr` isn't in gcc 4.8 (at least without trying to set flags), so we may not want to change that yet. I do now understand the "may-be-used initialized" warning - because of the chained calls in

```
if ((NULL == (k->arf_s_fft = XMALLOC (4NUM_POINTS, double)))
|| (NULL == (k->arf_s_tmp = XMALLOC (NUM_POINTS, double)))
|| (NULL == (k->arf_s_fft_tmp = XMALLOC (4NUM_POINTS, double))))
```

If the first `XMALLOC` fails then `arf_s_tmp` and `arf_s_fft_tmp` will not have been set, and so the checks in `delete_kernel` could use uninitialized memory.

**Comment by DougBurke** [comment]
I'm not sure how/if to pass the `std=c++11` flag via the python setup.py setup. Perhaps @olaurino knows. I also don't know if clang supports this flag, or whether this is a sensible thing to do.

**Comment by olaurino** [comment]
I don't think there is a way of safely doing this, because it's up to the user to set specific flags depending on the compiler they are using, just like I set them when I compile the conda binaries with the conda compilers. And yes, it depends on gcc vs clang as well as their versions.

**Comment by dtnguyen2** [comment]
Two more options:

1) add the following code and change std::auto_ptr to my_auto_ptr

template <typename Type>
class my_auto_ptr {
public:
  my_auto_ptr(Type* p = NULL):ptr(p){}
  Type* get( ) const { return ptr; }
  ~my_auto_ptr( ) {
    if(ptr)
      delete ptr;
    ptr = NULL;
  }
private:
  Type* ptr;
  my_auto_ptr(my_auto_ptr& arg);
  my_auto_ptr& operator=(my_auto_ptr& rhs);
  void reset(Type* p = NULL);
  Type* release( );
  Type& operator * ( );
  Type* operator -> ( );
};

2) We had originally extracted Boost's shared_ptr in a very early version of sherpa etc...
