### ISSUE TITLE
should MANIFEST.in mention the docs/ directory?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#511]
Something I noted over the long week-end that I don't want to forget.

**Comment by olaurino** [comment]
It probably should. If it's not in the MANIFEST it will not be in the source distribution created with `python setup.py sdist`. This is not particularly problematic, as we only publish the source distribution to the PYPI index, which is unlikely used to build the documentation. But nevertheless, it should be there.

**Comment by DougBurke** [comment]
So, based on a highly-exhaustive check of one other `MANIFEST.in` file - namely https://github.com/astropy/astropy/blob/master/MANIFEST.in#L22 - it looks like we just need a line saying

```
recursive-include docs *
```

**Comment by olaurino** [comment]
We fixed this, right?

**Comment by DougBurke** [comment]
Yup. Fixed. I just downloaded with pypi the test 4.10.1 build and it
contains a docs directory with rst files in it
