### ISSUE TITLE
module imp is deprecated (seen when building with python 3.7)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#516]
With python 3.7 we see the following message when `setup.py` is run:

```
% python setup.py develop
setup.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
...
```

It looks like we can either:

1. change from 'imp' to 'importlib' once we drop Python 2.7 support (since `importlib` in Python 2.7 only contains one routine)
 2. change how we check for NumPy - e.g. perhaps just an 'import numpy' rather than mess around with fancy tricks

I haven't a clue which is better, or if there's another option.

**Comment by olaurino** [comment]
Agreed. I think as the comment suggests this was originally meant to be more complicated. In particular option 2. should be good enough.

**Comment by DougBurke** [comment]
Oooh. I'm all excited now. In reviewing why we needed NumPy in the installation change, I came across issue #382 and your comment (@olaurino) about why we need NumPy: https://github.com/sherpa/sherpa/issues/382#issuecomment-320020291

As we have now removed the need for a Fortran compiler, can we just remove the use of NumPy `setup` and rely on the setuptools version?

**Comment by DougBurke** [comment]
Nope: I don't think so because a number of files in `helpers/` require `numpy.distutils`.

**Comment by DougBurke** [comment]
See #517 for one approach to address this.
