### ISSUE TITLE
Additional INFO line when running ipython Notebook

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#53]
I'm running an ipython notebook using the sherpa development version 
4.7+426.g6879d8d

I get additional INFO line after certain commands when I use the notebook. This does not happen when I import sherpa into my ipython session. Is this something specific to the ipython Notebook?

Here is an example of the output in the notebook, the command line gives only the standard one line information show in the second line:

        load_data("acis.pi")
        read ARF file acis.arf
        INFO:sherpa.astro.io:read ARF file acis.arf`

In case of fit() I see the double outputs:

        WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have     background models been set
WARNING:sherpa.astro.ui.utils:data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
Dataset               = 1
Method                = neldermead
Statistic             = cash
Initial fit statistic = 6.67964e+11
Final fit statistic   = -89714 at function evaluation 788
Data points           = 444
Degrees of freedom    = 442
Change in statistic   = 6.67964e+11
   p1.ampl        9.36365e-10 
   p1.index       -0.989984   
INFO:sherpa.astro.ui.utils:Dataset               = 1
Method                = neldermead
Statistic             = cash
Initial fit statistic = 6.67964e+11
Final fit statistic   = -89714 at function evaluation 788
Data points           = 444
Degrees of freedom    = 442
Change in statistic   = 6.67964e+11
   p1.ampl        9.36365e-10 
   p1.index       -0.989984   
Next get the covariance matrix with covar(). The matrix is later used in the MCMC run.

**Comment by olaurino** [comment]
This is a known issue, and can be worked around (see for instance the [ipython notebook in the source distribution](https://github.com/sherpa/sherpa/blob/master/docs/SherpaQuickStart.ipynb)) with the following code:

~~~~ python
import logging
logging.getLogger('sherpa').propagate = 0
~~~~

We probably want to fix this for good, anyway.

**Comment by anetasie** [comment]
This works. 
Yes, it will be good to fix this.

**Comment by olaurino** [comment]
@DougBurke, @anetasie I believe this was fixed in recent ipython/jupyter releases, right?

**Comment by DougBurke** [comment]
I haven't checked recently (and don't have the time to do so in the short term).

**Comment by DougBurke** [comment]
I have just tried a notebook with the release/4.8.2 branch and a recent ipython notebook and the double display no-longer occurs, so this can issue can be closed.

I do no know where the change occurred; it may be in one of the other packages, but here's some of the versions I have installed:

```
ipython                   5.1.0                    py35_0  
ipython-notebook          4.0.4                    py35_0  
ipython_genutils          0.1.0                    py35_0  
jupyter_client            4.4.0                    py35_0  
jupyter_core              4.2.0                    py35_0  
```
