### ISSUE TITLE
Undefined variable in minim in optfcts.py

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#547]
PyCharm points out to me that `var` is undefined here:
https://github.com/sherpa/sherpa/blob/e5bef961fb698d88977460d3873af8dd7e4255b5/sherpa/optmethods/optfcts.py#L414-L415
I think that's true, that code can't run. pyflakes also sees this:
```
$ pyflakes sherpa/optmethods/optfcts.py 
sherpa/optmethods/optfcts.py:414: undefined name 'var'
sherpa/optmethods/optfcts.py:415: undefined name 'var'
```
Probably should be deleted or fixed?

**Comment by olaurino** [comment]
I believe this was fixed by #558.
