### ISSUE TITLE
What's the status on getting XSPEC 12.10.0 into the Travis builds

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#553]
@olaurino - just so I don't forget, what's the status in updating the travis builds to include at least one XSPEC 12.10.0 run (and probably drop the 12.9.0 versions)?

**Comment by olaurino** [comment]
I am painfully close to make it work, so hopefully it won't be long before it's live. I have just given priority to CIAO 4.11, but hopefully that's in good shape now.
