### ISSUE TITLE
Is there a way to iterate over all loaded datasets?

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#560]
I can get the default id from `get_default_id()`, but can I get a list of all ids?
My use case is that I want to iterate over all loaded datasets, e.g.:
```
for i in range(1, xxxx):
    ungroup(i)
```
It's fine for just a few datasets, but I imaging a case where I use string labels and might have dozens of them.

**Comment by DougBurke** [comment]
list_data_ids - see
https://sherpa.readthedocs.io/en/latest/ui/api/sherpa.astro.ui.list_data_ids.html

**Comment by olaurino** [comment]
@hamogu have you tried the datastack module? http://cxc.harvard.edu/sherpa/ahelp/datastack.html

That also has a function for getting all the IDs (`get_stack_ids`), but I suspect you would not need that in the first place when using data stacks.

Please let me know if that answers your questions or you have more questions/issues.

**Comment by hamogu** [comment]
It's even in the "see also" section. I must be blind...

**Comment by DougBurke** [comment]
who reads documentation nowadays ...
