### ISSUE TITLE
Should we convert to ndarray when creating data objects or fix WStat (and other code) to work with lists?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#563]
Our documentation assumes that we support passing in lists or sequences to commands like `load_arrays` or objects like `Data1D`. Deep in other parts of the system - such as calculating stats - it makes it much-more-convenient if we can assume we have ndarrays. This can cause problems, such as shown below where `WStat` can not be used with lists. I think it would make sense for our data constructors (`sherpa.data.Data`-derived classes) to convert to ndarray automatically, but maybe there's a reason not to do this? Another option would be to document that we accepts lists (or rather sequences) and then we would have to audit the code (eg test coverage) to ensure necessary conversion routines are used to avoid problems like the following.

Problem case with current `master` (and CIAO 4.10, so this is nothing new):

```
from sherpa.data import Data1D
from sherpa.models.basic import Polynom1D
from sherpa.stats import Cash, Chi2, WStat
from sherpa.fit import Fit

d = Data1D('test', [1, 2, 3], [4, 5, 6], [1, 1, 1])
mdl = Polynom1D()
mdl.c1.thaw()
mdl.c0 = 5.1

for stat in [Cash, Chi2, WStat]:
    sobj = stat()
    print("\nStat = {}".format(sobj.name))

    fit = Fit(d, mdl, stat=sobj)
    fit.calc_stat_info()
```

Running this produces the following:

```

Stat = cash

Stat = chi2

Stat = wstat
Traceback (most recent call last):
  File "../bugs/arrays.py", line 18, in <module>
    fit.calc_stat_info()
  File "/home/djburke/sherpa/sherpa-master/sherpa/fit.py", line 1197, in calc_stat_info
    stat, fvec = self._calc_stat()
  File "/home/djburke/sherpa/sherpa-master/sherpa/fit.py", line 1128, in _calc_stat
    return self.stat.calc_stat(self.data, self.model)
  File "/home/djburke/sherpa/sherpa-master/sherpa/stats/__init__.py", line 882, in calc_stat
    nelems.append(y.size)
AttributeError: 'list' object has no attribute 'size'
```

**Comment by DougBurke** [comment]
Note that once this issue is addressed the code above will still error out with `WStat`, but this time for expected reasons (there is no background data set).

**Comment by hamogu** [comment]
:+1: to converting any array-like input to ndarrays. It's what numpy does and what python users expect - and more and more Sherpa users are in fact true Python users. People who just use command-line Sherpa are unlikely to care in detail how it's handeled - they'll just want that the syntax in the docs works and if it does without typing `np.ndarray` all the time.
