### ISSUE TITLE
You should be able to change plot or I/O backend within a Sherpa session

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#568]
I don't believe there's any reason why our current plotting or I/O backends can't be changed at runtime.

The ability to control this would be useful for us developers, but also for Jupyter notebook users (where you don't have access to the ~/.sherpa.rc file so can't change it). I'm in particular thinking of the glorious future when someone implements #499 :-)

Note there are a couple of related issues - e.g. #348 #354 - which could be replaced by this change (would need to re-read them to check).

**Comment by olaurino** [comment]
I agree, I brought it up a few years ago but it wasn't deemed a priority so never did anything about it.

**Comment by DougBurke** [comment]
See issues

- #348
- #354 

and PRs from @hamogu

- #1185 
- #1191

**Comment by DougBurke** [comment]
@hamogu - I think we can close this now (the i/o code doesn't have an explict `set_backend` type call, but we do now document how to change the backend)?
