### ISSUE TITLE
plotting issues with integrated model

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#569]
In the following the second `plot_fit`, for a fit with a model defined on arbitrary grid,  shows the model curve with a saw-like structure instead of a straight line. 

```
from sherpa.astro.ui import *
import matplotlib
import numpy as np
%matplotlib

dataspace1d(1,100,2,dstype=Data1DInt)
set_model(box1d.b1)
b1.xlow=10
b1.xhi=80
b1.ampl.max=100
show_model()
b1.ampl=10
fake()
fit()
plot_fit()
plot_source_component(b1)
grid_hi = np.linspace(2,101,600)
grid_lo = np.linspace(1,100,600)
rb1 = b1.regrid(grid_lo,grid_hi)
set_model(rb1)
show_model()
fit()
plot_fit()
```

<img width="629" alt="plot_fit" src="https://user-images.githubusercontent.com/1213746/49533827-0fdd3580-f88e-11e8-9f38-4ecdc4de2699.png">

**Comment by dtnguyen2** [comment]
I made a fix to ```rebin_histogram``` and during testing I notice the following:
```
>>> import numpy as np
>>> grid_hi = np.linspace(2,101,600)
>>> grid_lo = np.linspace(1,100,600)
>>> grid_hi[23]
5.801335559265443
>>> grid_lo[24]
4.96661101836394
```
That is the integrated bins overlapped.  I know that we want to allow the user to enter _arbitrary grid_ but this sounds a bit extreme to me.  Let me know if I should continue the fix to allow this or add code to check for overlapping integrated bins and error out.  BTW, If one had a non-overlapping grid then running sherpa with a similar script (without any modifications) yields:
 
![Figure_1](https://user-images.githubusercontent.com/12256848/65170925-b6f31e00-da17-11e9-96c8-8f704cdc32f7.png)

which I think is the correct behavior.

**Comment by DougBurke** [comment]
@dtnguyen2 so the "problem" is that the regridding code currently either assumes the bins don't overlap or some related invariant that @anetasie example doesn't follow?

For the curious, you can create the "good-looking" plot from the previous plot with a model like

```
grid2 = np.arange(1, 100, 200)                                         
rb2 = b1.regrid(grid2[:-1], grid2[1:])                                 
set_model(rb2)                                                         
plot_fit()                                                             
```

**Comment by dtnguyen2** [comment]
Yes.  I had a short discussion with @olaurino and he said that the current code has a few sanity checks for the user input grid but unfortunately it does not check for overlapping grid.  If SDS signs off on no overlapping grid then I can put in a simple check and error out.

**Comment by anetasie** [comment]
@dtnguyen2 yes, checking that the grid bins do not overlap will be good.
