### ISSUE TITLE
warning messages with different grids

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#570]
This issue is related to the new capabilities of defining model on the arbitrary grid. 

The number of warning msgs printed by sherpa when using different model grids is excessive. from 
```
sherpa.astro.ui import *
import numpy as np

dataspace1d(1,100,2,dstype=Data1D)
set_model(gauss1d.g0)
set_par(g0.fwhm,20)
set_par(g0.pos, 50)
set_par(g0.ampl, 100.)
fake()

grid=np.arange(100)
one = np.ones(100)
grid = grid+one
set_model(gauss1d.g0)
r0=g0.regrid(grid)
set_model(r0)
fit()
```
This is an example of the msg which is repeated at each step of the the fit, so 21 times in my case. The msg should be shown just once. 

```
/proj/xena/ciaot_install/LinuxP3.181205/ciao-4.11/lib/python3.5/site-packages/sherpa-
ciao4.11-py3.5-linux-x86_64.egg/sherpa/models/regrid.py:400: UserWarning: 
evaluation space does not contain the requested space. Sherpa will join the two spaces.
  warnings.warn("evaluation space does not contain the requested space. 
Sherpa will join the two spaces.")
```

**Comment by DougBurke** [comment]
I also can't replicate this behavior with the latest master, but can with the CIAO 4.11 release, so I'm closing this.
