### ISSUE TITLE
should set_ylog not change the behavior of residual plots?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#586]
If I

```
>>> set_xlog()
>>> set_ylog()
>>> plot_fit_resid()
```

then both the fit and residual plots have X and Y axes drawn with a logarithmic scale. Given that the residual (and delchi) plots are expected to contain negative values, this is not very useful.

I suggest that we make the residual-style plots (`_resid` and `_delchi`) ignore the `ylog` setting of the `ui.get_data_plot_prefs` setting. There is also the question of if they should have their own setting, but I think that's a larger change.

**Comment by DougBurke** [comment]
There is a change to support this in PR #694, which means that the residual-style plot is drawn with a y axis in the following calls

````
>>> set_ylog()
>>> plot_delchi()
>>> plot_fit_ratio()
>>> plot_bkg_fit_resid(ylog=True, xlog=True)
```

(the last one is from #692 which  #694 is built on top of)

**Comment by anetasie** [comment]
@DougBurke Has  this been propagated into the PR and code for 4.12?

**Comment by DougBurke** [comment]
The PR that contains this code fix is still marked as a work-in-progress (it was added as I was looking into the "how do I display data+model when using wstat" issue). It should be pulled out into its own PR but it needs #692 to be merged before that makes sense to do so (and is not on a 4.12.0 time scale).

**Comment by DougBurke** [comment]
I've created #709 which has just the changes needed to address just this issue (now that #692 has been merged).
