### ISSUE TITLE
move sherpa/ into src/ ?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#595]
Should we move the `sherpa/` directory into `src/sherpa/` since it *might* help avoid issues - e.g. trying to use sherpa from the installation directory can lead to errors about a missing `_utils` model. Or would this not really help there?

I don't know how related this is to #50 #133 #198

**Comment by olaurino** [comment]
I don't know how that would work with `python setup.py develop`, but it might be worth investigating.

**Comment by olaurino** [comment]
And I wouldn't think it's related to those issues. Our files are arranged in a way that is pretty standard for python packages (although not the only possible model). A developer should know the difference between `develop` and `install` and the order of priority of python modules, i.e. if you are in a folder with a `model.py` and you `import model` that folder takes the precedence over everything else. That's just the way Python works.

**Comment by DougBurke** [comment]
Note that I have seen 'pip install -e .' mentioned as the new "hotness" for
development, but have little experience with it myself.

**Comment by olaurino** [comment]
I think it's more or less the same, with some differences in the way dependencies are treated, see e.g.
https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop

**Comment by hamogu** [comment]
Can we close this? I don't see a benefit from moving the name. `pip install -e` works (at least for me) in the current configuration and, as @olaurino pointed out above, the current layout is pretty standard.

**Comment by DougBurke** [comment]
I have, over the years, read documents that have strongly suggested that the way we currently do things is not a great idea - but it is mainly an issue for the developer as @olaurino had mentioned. Whenever I've tried to try and improve our build/CI work I seem to always end up in bizarre corner cases which *might* be related to this, but might not be. Whenever I try to find clarity on-line I fail.

The trouble, as far as I can tell, is that the recent PEP work decoupling the python build process from setuptools has focused on "pure python" packages, and those that require compiling code still have "issues". I have not been keeping on top of it, so I could well have missed something recently, but I don't find the existing documentation particularly helpful.

I can close this, but I would like us to be able to make some movement on #784 - as may be evidenced from this comment I'm not sure I'm the best person to lead that work ;-)
