### ISSUE TITLE
UserModel: unable to change parameter values

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#609]
I originally thought this was a case-sensitivity, but it is more serious than that. In the following (using CIAO 4.11 but will hold for Sherpa 4.11.0 as well)

a) I can apparently change the parameter value "X", but it doesn't actually change the underlying model (i.e. print(silly) still says X is 2 even after I changed it to 4)

b) I can't use a lower case version of the parameter name to access the parameter

```
% python
Python 3.5.4 (default, Sep 14 2018, 15:42:52) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sherpa
>>> sherpa._version.get_versions()
{'version': 'ciao4.11', 'full': '29aca616db21356f16b59fab0de2a2e5590fdca7'}
>>> from sherpa.astro import ui
>>> def sillymdl(pars, xlo, *args):
...     return pars[0] * xlo
... 
>>> ui.load_user_model(sillymdl, 'silly')
>>> ui.add_user_pars('silly', ['X'], parvals=[2.0])
>>> print(silly)
usermodel.silly
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   silly.X      thawed            2 -3.40282e+38  3.40282e+38           
>>> silly.X = 4
>>> print(silly)
usermodel.silly
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   silly.X      thawed            2 -3.40282e+38  3.40282e+38           
>>> silly.x = 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dburke/local/ciao-4.11/lib/python3.5/site-packages/sherpa-ciao4.11-py3.5-linux-x86_64.egg/sherpa/models/model.py", line 199, in __setattr__
    NoNewAttributesAfterInit.__setattr__(self, name, val)
  File "/home/dburke/local/ciao-4.11/lib/python3.5/site-packages/sherpa-ciao4.11-py3.5-linux-x86_64.egg/sherpa/utils/__init__.py", line 148, in __setattr__
    (type(self).__name__, name))
AttributeError: 'UserModel' object has no attribute 'x'
>>> 
```

**Comment by olaurino** [comment]
I can reproduce the issue. I checked if fits work as expected, and they do, in the sense that the model parameter is changed during the fit. So it looks like the interface is not working correctly, but internally Sherpa knows how to deal with the parameters. Can we assume this used to work at some point and it's a regression?

**Comment by DougBurke** [comment]
It's definitely a regression (I noted this in a sherpa notebook)

**Comment by DougBurke** [comment]
Looking at `sherpa.models.basic.UserModel` I see it doesn't inherit from `RegriddableModelxD` - which is understandable since `UserModel` can be used for 1D, 2D, ... data - but is presumably a limitation. This was probably mentioned in the release notes but I missed this.

**Comment by olaurino** [comment]
> Looking at `sherpa.models.basic.UserModel` I see it doesn't inherit from `RegriddableModelxD` - which is understandable since `UserModel` can be used for 1D, 2D, ... data

The current way of loading a user model might probably be improved (and I believe there are currently multiple ways of adding a model to Sherpa). Part of the improvements might be to introduce a distinction between 1D and 2D user models, and possibly make user models regriddable. On the other hand the latter is really a different requirements, as maybe a user model that is just a simple python function should not be regriddable anyway. You'd probably need a class (or a fairly complex decorator) for that.
