### ISSUE TITLE
The computed monochromatic fluxes are 0.0, issue with the mask computation?

### ISSUE THREAD

**Issue by rarcodia** [sherpa/sherpa#619]
Hello,

I am using Sherpa (4.11.0+0.g838bd12b.dirty) on an Anaconda environment with Python 3.6.7 and Numpy 1.15.4.

I encountered the following problem: when computing a monochromatic flux with the function calc_energy_flux [e.g. at 10 keV asking: calc_energy_flux(lo=10.,hi=None, id=data_id) ] the result is 0.

I believe I narrowed down the problem digging into the code here, that is what the function calls:

https://github.com/sherpa/sherpa/blob/41809de1a2a2f596deb87e3fdf3ccceb0902a6ca/sherpa/astro/utils/__init__.py#L116-L162

Line 121 causes "dim" (line 130) to be 2. There are 'if' conditions here and there accounting for this dim=2, but I think there should be one also for computing the mask (line 148).  The mask in my example has only "False". What I think it's happening, code-wise, is that there is no energy bin containing the monochromatic energy at which I want to compute the flux.
Line 148 calls this function:
https://github.com/sherpa/sherpa/blob/41809de1a2a2f596deb87e3fdf3ccceb0902a6ca/sherpa/utils/__init__.py#L991-L1055

where at line 1047 the mask is computed: I think that "axis"  here should be different for the match for 'lo" and "hi": in the first case it should be the array containing the low-end of the energy bins (axislist[0] at line 148 above), in the second case it should be the array containing the high-end (so axislist[1]). 

In my example, the mask is "False" because "lo"='hi'=10. (or whatever energy) and the "&" at 1047 is not satisfied. Maybe adding an "if" to compute the mask in a different way with dim=2 would solve it.

It is not a problem of monochromatic fluxes only. In fact, also computing a narrow-band flux with both extremes (lo and hi) within the same energy bin results in a flux=0, for the same problem.

I hope my message was not too confusing and thank you in advance for your help!

**Comment by olaurino** [comment]
Riccardo, thanks for your report and sorry for the issues you experienced. Your analysis seems sound but I'll have to look more into it. I hope we can have a fix soon.

**Comment by rarcodia** [comment]
Thanks for your prompt reply. I started digging more and I am afraid I have something else to report, still related to the mask an its impact on the computed fluxes.

I briefly describe what I think the mask in the _flux function (reported in my first comment above) is doing:
- the user gives two energies (lo and hi), between which he/she wants the integrated flux (e.g. in ergs cm-2 s-1)
- in _flux the eneg_lo (and energ_hi) array of the rmf file is taken from the _get_indep function (line 121)
- then the mask is narrowing down a few bins, onto which the flux is summed over to give the integrated flux. This is the step in which there is another issue in my opinion. The mask is taking the first element of the array energ_lo after the provided "lo" value (let's call it a, in Kev) and the last element of energ_hi before the provided "hi" value (let's call it b, in Kev) . This already suggests that the flux is not taken exactly from "lo" to "hi", but it's taken in the closest bins. And always a>lo and b<hi, although the full bin starting from b is taken, so the flux is alway computed up to energies > than hi. In fact, no matter where "lo" and "hi" really are, there will always be a fraction of flux between lo and a that is overlooked, and a fraction of flux between hi and b that should not be there. This might be a small effect if, for instance, a broadband 2-10 keV flux is computed, but it can be high if a flux in a narrow range (spanning on a few energy bins only) is computed. Even a range wide 1 keV is not big enough, specially if the energy bin in the rmf are log-spaced and you want the flux at high energies.

I try to show something with an example. For instance, I have a spectrum in which energ_lo from the rmf is from ~ 3-80 keV, cut around some 15-25 keV for simplicity:

[ ... 15.12231731 15.32684708 15.53414249 15.74424171 15.95718193
 16.17300224 16.39174271 16.61343956 16.83813667 17.06587219 17.29668808
 17.5306263  17.7677269  18.00803566 18.25159454 18.49844742 18.74863815
 19.00221252 19.25921822 19.5196991  19.78370285 20.05127716 20.32246971
 20.59733009 20.87590981 21.15825653 21.44442177 21.73445702 22.02841568
 22.32634926 22.62831306 22.9343605  23.24454689 23.55892944 23.87756348
 24.20050812 24.52781868 24.85955811 25.19578171 ...]

If I compute fluxes (on a powerlaw with Gamma~1.6), say between a np.linspace(3,25,23), so between 3-4,  4-5 up to 24-25 keV, with both sherpa and xspec, the result is the figure attached:

[test_sherpa.pdf](https://github.com/sherpa/sherpa/files/3107213/test_sherpa.pdf)

Sherpa is currently masking bins, with the issues reported above. So according to where lo and hi are with respect to a and b, a fraction of flux is added or removed and the weird zig-zag of the orange points is obtained.

I don't really know in details what xspec does, but it must interpolate to some extent. As you can see from the blue points there is no issue apparently.

For instance, let's have a look at the third last flux computation, i.e. flux within 22-23 keV (third last orange and blue point on the x-axis). From the energy bins shown above, the mask computes the flux actually within 22.028 and 23.244, so in this case sherpa's flux is higher with respect to xspec (see orange point above the blue point). The case between 21-22 keV is the opposite, since the mask will compute the flux actually between 21.15 and 22.03, thus missing the fraction from 21 to 21.15, i.e. the bit of powerlaw with more flux in that range. That is why the fourth last orange point is lower than the fourth last blue point.

I hope this report was again not too confusing. 

As it is right now, either the user is aware of this and uses some workarounds (e.g. defining manually a dummy response with a lot of narrow energy bins, or he/she uses pyxspec only for computing fluxes) or if the user is not aware incorrect fluxes can be obtained.

What do you think?

Is it possible to compute fluxes with an interpolation step? or with a much more finer energy array with respect to the rmf one? I am sorry I am not providing more quantitative suggestions, I know it's not easy. But in the meantime I think users should be at least aware that currently fluxes are reliable only if the number of energy bins spanned by their "lo" and "hi" is big enough...and how big it needs to be depends on the instrument and on the model (if it's steep or flatter in energy the difference is huge).

Thanks for your work,  hope this can be helpful!

**Comment by JohannesBuchner** [comment]
I think it is easier to compute monochromatic fluxes with the model itself:

```
# get model 
s = get_source()
# get parameters
pvec = [p.val for p in s.pars]

# some energy bins of interest:
energies =  [0.99, 1.0, 1.01, 1.02]
# compute photon flux integrated between left and right bin edges 
s.calc(pvec, energies[:-1], energies[1:])
# returns: array([ 0.01005034,  0.00995033,  0.0098523 ])
```

So the photon flux integrated from 0.99 to 1.0 is 0.01, therefore the flux density is 1, consistent with my chosen model (powerlaw norm=1, Gamma=1).

**Comment by JohannesBuchner** [comment]
So you could define a function:

```
def calc_monochromatic_flux(E, dE=0.01):
     s = get_source()
     pvec = [p.val for p in s.pars]
     hi = E - dE / 2
     lo = E + dE / 2
     return s.calc(pvec, [lo], [hi]) / dE
```

**Comment by DougBurke** [comment]
I haven't followed the details above, so not sure if it's already been mentioned, but it looks like the flux density is only calculated when you pick an energy that matches the edge of the response. Using the `3c273.pi` dataset from the `sherpa-test-data/sherpatest` directory, whose responses were generated over 0.1 to 11 keV with a bin-size of 0.01 keV (modulo float32/64 issues), we have

```python
import logging
from sherpa.astro import ui

# hide the messages from load_pha
logging.getLogger('sherpa').setLevel(logging.ERROR)
ui.load_pha('sherpa-test-data/sherpatest/3c273.pi')

ui.set_source(ui.powlaw1d.pl)
pl.ampl = 1e-4
pl.gamma = 1

# should be a better way to get this

rgrid = ui.get_data()._get_indep(filter=False)
print("Response grid:")
print("  {}".format(rgrid[0][0:5])) # low edges (start of array)
print("..")
print("  {}".format(rgrid[1][-5:])) # high edges (end of array)
print("")

energy = 0.998
de = 0.002
while energy < 1.11:
    pflux = ui.calc_energy_flux(energy)
    print(" E = {:3f}  photon flux density = {:.4e}".format(energy,
                                                            pflux))
    energy += de
```

which creates the following - note how the calculated flux densities are 0 when the energy does not map to a bin edge (ie is divisible by 0.01):

```
Response grid:
  [0.1  0.11 0.12 0.13 0.14]
..
  [10.96000004 10.97000027 10.97999954 10.98999977 11.        ]

 E = 0.998000  photon flux density = 0.0000e+00
 E = 1.000000  photon flux density = 1.6022e-13
 E = 1.002000  photon flux density = 0.0000e+00
 E = 1.004000  photon flux density = 0.0000e+00
 E = 1.006000  photon flux density = 0.0000e+00
 E = 1.008000  photon flux density = 0.0000e+00
 E = 1.010000  photon flux density = 1.6022e-13
 E = 1.012000  photon flux density = 0.0000e+00
 E = 1.014000  photon flux density = 0.0000e+00
 E = 1.016000  photon flux density = 0.0000e+00
 E = 1.018000  photon flux density = 0.0000e+00
 E = 1.020000  photon flux density = 1.6022e-13
 E = 1.022000  photon flux density = 0.0000e+00
 E = 1.024000  photon flux density = 0.0000e+00
 E = 1.026000  photon flux density = 0.0000e+00
 E = 1.028000  photon flux density = 0.0000e+00
 E = 1.030000  photon flux density = 1.6022e-13
 E = 1.032000  photon flux density = 0.0000e+00
 E = 1.034000  photon flux density = 0.0000e+00
 E = 1.036000  photon flux density = 0.0000e+00
 E = 1.038000  photon flux density = 0.0000e+00
 E = 1.040000  photon flux density = 1.6022e-13
 E = 1.042000  photon flux density = 0.0000e+00
 E = 1.044000  photon flux density = 0.0000e+00
 E = 1.046000  photon flux density = 0.0000e+00
 E = 1.048000  photon flux density = 0.0000e+00
 E = 1.050000  photon flux density = 1.6022e-13
 E = 1.052000  photon flux density = 0.0000e+00
 E = 1.054000  photon flux density = 0.0000e+00
 E = 1.056000  photon flux density = 0.0000e+00
 E = 1.058000  photon flux density = 0.0000e+00
 E = 1.060000  photon flux density = 1.6022e-13
 E = 1.062000  photon flux density = 0.0000e+00
 E = 1.064000  photon flux density = 0.0000e+00
 E = 1.066000  photon flux density = 0.0000e+00
 E = 1.068000  photon flux density = 0.0000e+00
 E = 1.070000  photon flux density = 1.6022e-13
 E = 1.072000  photon flux density = 0.0000e+00
 E = 1.074000  photon flux density = 0.0000e+00
 E = 1.076000  photon flux density = 0.0000e+00
 E = 1.078000  photon flux density = 0.0000e+00
 E = 1.080000  photon flux density = 1.6022e-13
 E = 1.082000  photon flux density = 0.0000e+00
 E = 1.084000  photon flux density = 0.0000e+00
 E = 1.086000  photon flux density = 0.0000e+00
 E = 1.088000  photon flux density = 0.0000e+00
 E = 1.090000  photon flux density = 1.6022e-13
 E = 1.092000  photon flux density = 0.0000e+00
 E = 1.094000  photon flux density = 0.0000e+00
 E = 1.096000  photon flux density = 0.0000e+00
 E = 1.098000  photon flux density = 0.0000e+00
 E = 1.100000  photon flux density = 1.6022e-13
 E = 1.102000  photon flux density = 0.0000e+00
 E = 1.104000  photon flux density = 0.0000e+00
 E = 1.106000  photon flux density = 0.0000e+00
 E = 1.108000  photon flux density = 0.0000e+00
```
