### ISSUE TITLE
XSpec model evaluation for non-continuous grids (Xspec models that call sumdem, such as apec, can crash)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#62]
# Summary

XSpec models that call the SUMDEM routine - e.g. `xsapec` but many others - can cause a crash if called with only one bin, as shown below ("XSpec model crash" section). This has been reported to the XSpec team, but is unlikely to be a major problem for Xspec. It is a *serious* issue for Sherpa than XSpec due to the way that the wrapper code that interfaces to the XSpec model library is written; in particular, how it handles being given a non-continuous grid ("Sherpa model crash" and "What causes the crash (in Sherpa)?" sections).

It is not clear to me how many of the existing issues are affected by this: #55 and #56 may be but I'm not convinced that #42 is, because the test code isn't written to test out this behavior (and so doesn't show it).

# Plan

I am going to update the xspec test code to make sure it compares the results from  model comparisons run with a single grid (contiguous) and xlo,xhi grids (made to be non-contiguos) and compare the overlap. I've already done this in off-to-the-side work and it shows the crash behavior for some models, as well as other differences which I believe to be down to the fact that many models involve interpolating between grids, so if you run with different grids you can get different results.

Once the test suite has been improved I plan to change the wrapper code so that it deals with non-contiguous grids by only calling the XSpec function once, with extra bins added to make it contiguous, and then remove them on output. Unless someone wants to do this before me ;-)

# Details

## XSpec model crash

```
% uname -a
Linux madeupname 3.19.0-21-generic #21-Ubuntu SMP Sun Jun 14 18:31:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
% xspec

		XSPEC version: 12.8.2q
	Build Date/Time: Wed Jun 24 12:42:59 2015

XSPEC12>energies 0.1 0.2 1

Models will now use energy array created from:
   0.1 - 0.2   1 linear bins

XSPEC12>mo apec

Input parameter value, delta, min, bot, top, and max values for ...
              1       0.01(      0.01)      0.008      0.008         64         64
1:apec:kT>/*
Segmentation fault (core dumped)
```

## Sherpa model crash

```
% python
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import sherpa
>>> sherpa.__version__
'4.7+475.g0ee48e5.dirty'
>>> from sherpa.astro import xspec
>>> xspec.get_xsversion()
'12.8.2q'
>>> mdl = xspec.XSapec()
>>> mdl([0.1,0.2,0.3,0.4,0.5])
array([ 2.01070237,  0.31376797,  0.21693133,  0.12136491,  0.        ], dtype=float32)
>>> mdl([0.1,0.2,0.3,0.4], [0.2,0.3,0.4,0.5])
array([ 2.01070237,  0.31376797,  0.21693133,  0.12136491], dtype=float32)
>>> mdl([0.1,0.3,0.4], [0.2,0.4,0.5])
Segmentation fault (core dumped)
```

So, when given `xlo` and `xhi` grids which are *not* continuous, we see a crash. 

# What causes the crash (in Sherpa)?

The Sherpa behavior is down to `sherpa/include/sherpa/astro/xspec_extension.hh`, which has templates that include some variant of

```
		// Suppose the data were filtered, such that there is a gap
		// in the middle of the energy array.  In that case *only*,
		// we will find that xlo[i+1] != xhi[i].  However, XSPEC models
		// expect that xlo[i+1] == xhi[i].
		//
		// So, if we pass in filtered data and xlo[i+1] != xhi[i],
		// then at energy bin i we will end up calculating an energy
		// flux that is far too great.  We will correct that by gathering
		// information to allow us to recalculate individual bins, with
		// boundaries xlo[i], xhi[i], to correct for cases where
		// boundaries xlo[i], xlo[i+1] results in a bin that is too big.
		//
		// We will gather the locations of the gaps here, and calculate
		// actual widths based on xhi[i] - xlo[i] downstream.
		//
		// If we are working in wavelength space we will also correct for that.
		// SMD 11/21/12.

		for (int i = 0; i < nelem-1; i++) {
			double cmp;
			if ( is_wave ) {
				cmp = sao_fcmp(xlo[i], xhi[i+1], DBL_EPSILON);
			} else {
				cmp = sao_fcmp(xhi[i], xlo[i+1], DBL_EPSILON);
			}
			if (0 != cmp) {
				gaps.push_back(i);
				double width = fabs(xhi[i] - xlo[i]);
				if( is_wave ) {
					width = hc / width;
				}
				gap_widths.push_back(width);
			}
		}
```

and then, after evaluating the model

```

		// If there were gaps in the energy array, because of locations
		// where xlo[i+1] != xhi[i], then this is place where we recalculate
		// energy fluxes for those bins *only*.
		//
		// For each such location in the energy grid, construct a new
		// 2-bin energy array, such that the 2-bin array is [xlo[i],
		// xhi[i]].  This is accomplished by:
		//
		// ear2[0] = ear[location of gap]
		// ear2[1] = ear[location of gap] + abs(xhi[location of gap] -
		//                                      xlo[location of gap])
		// The locations of the gaps, and the actual widths of the energy
		// bins at those locations, were calculated above.  So use the
		// gaps and gap_widths vectors here to recalculate energy fluxes
		// at affected bins *only*. SMD 11/21/12

		while(!gaps.empty()) {
			std::vector<FloatArrayType> ear2(2);
			int bin_number = gaps.back();
			ear2[0] = ear[bin_number];
			ear2[1] = ear2[0] + gap_widths.back();
			int ear2_nelem = 1;
			XSpecFunc( &ear2[0], &ear2_nelem, &pars[0], &ifl, &result[bin_number],
					&error[bin_number]);

			gaps.pop_back();
			gap_widths.pop_back();
		}
```

where you can see that there are calls to evaluate the model for grids with 1 bin, which triggers the crash.

**Comment by DougBurke** [comment]
As an example of how the current scheme can give surprising results, I show the model evaluation for the `xskerrdisk` model using a continuous grid (which has then been filtered to remove points) and the equivalent results from using a non-continuous grid: https://gist.github.com/DougBurke/d9a0074489b6d1de108e

This is one of the more obvious differences (and is down to how the model works, since it really relies on having a large grid of input values). More common is that the bins that are at the end of a contiguous sequence show differences but the other bins have the same result.

**Comment by DougBurke** [comment]
Just to note that Keith Arnaud tells me that this crash is fixed in the not-yet-released next release of XSpec.

**Comment by olaurino** [comment]
Any chances we could get a patch for testing?

**Comment by DougBurke** [comment]
Keith is going to be sending me the code soon. I'm also working at changing `xspec_extension.hh` to avoid this problem (although the simplest fix has lead to more strange bugs, so something is rotten in the state of Denmark): https://github.com/DougBurke/sherpa/tree/xspec-contiguous

**Comment by DougBurke** [comment]
I have also come across another bug in the non-contiguous case, this time when the input array is in Angstroms. The error is shown in https://gist.github.com/DougBurke/b70485a9280f1b52a83e
