### ISSUE TITLE
values read in from configuration file should always have a default value

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#623]
At present the code that reads in configuration values does not always provide a default value (e.g. if the input value is missing). This is probably because the API of the configuration class didn't easily support this until Python 3.

I believe we should always have a fallback/default option for these configuration values, since this makes it easier to remove settings in the future. The problem we currently have is that we can't easily remove a setting from the configuration file because then it means that older versions of Sherpa will error out if run with the updated config file (as the old code doesn't have a fallback value to use). We already have had to do this once recently (I forget what the setting is).

If we update the config code now to always supply a default for any config value, we make it easier to make changes in the future.

**Comment by DougBurke** [comment]
I have argued for this.

**Comment by olaurino** [comment]
I know you have, but we never reached a conclusion. Also, it makes a difference if we just deprecate it or we drop it altogether.

[Something is weird... github is saying I added my previous comment "4 hours from now" and shows it after subsequent comments.]

**Comment by DougBurke** [comment]
Closed by #684
