### ISSUE TITLE
Multiple models on one data set?

### ISSUE THREAD

**Issue by ivalaginja** [sherpa/sherpa#624]
Hello again,

I have a general question about using several models on the same data set. I have one data object and I want to use a model to perform a fit, but I want to do that several times while I vary which model parameters are fixed and which ones are thawed in order to compare the results. Is there a more economic way of doing this than to set up a loop in which I freeze and thaw my parameters as I wish and to save the results at the end of each iteration, and then resetting my model? I did find the class `sherpa.models.model.SimulFitModel`, but from the documentation it seems like it only works with a concatenation of data sets in an instance of the class `sherpa.data.DataSimulFit` - but I have only one data set that doesn't change from fitting round to fitting round.

I can brute force my way around this with for loops and if statements, but I was wondering if anybody knew a better solution.

Cheers!

**Comment by DougBurke** [comment]
I may be missing the point of your question, so apologies if the following is not helpful.

The `sherpa.fit.Fit` object takes in data and model objects, and optional optimizer (method) and statistic options. You can have multiple `Fit` objects which all use the same data object but have different combination of model, optimization, and statistics objects. So you could create multiple fit objects, wach with a different model (the models can be the same class in all cases, you just make sure you create different instances). So, if `d` is your data and `SuperDuperModel` is the model class, then something like

```
fits = [Fit(d, SuperDuperModel(str(i))) for i in range 5]
for f in fits:
    f.fit()
```

might help (although you'd want to change the model parameters before the fit otherwise the result is going to be the same in each element).

Whether this is "better" than your current "brute force" way is a judgement call I think.

**Comment by ivalaginja** [comment]
That already helps, thank you for that! Yeah it's definitely a judgement call and will also depend on what the code architecture around it looks like. I guess my main point was that I actually have the same model each time, but a different combination of free and fixed parameters. It will be up to me if I want to have that in separate model instances (and hence separate fit instances), or just in the same model instance that I carry around.

On a side note, if I freeze and thaw parameters in my `Model`, I have to instantiate a new `Fit` object in order to capture those changes, is that correct?

**Comment by dtnguyen2** [comment]
I haven't tested the following response, but I would think that @DougBurke's code sample:

```
fits = [Fit(d, SuperDuperModel(str(i))) for i in range 5]
for f in fits:
    f.fit()
```

should work.  That is one does not have to instantiate the Fit class

**Comment by ivalaginja** [comment]
Sure, but that's because it actually creates 5 distinct fit instances in the above example, or is it not? I am thinking more of something like:

```py
model = MyModel()        # instantiate the model
fit1 = Fit(d, model)     # instantiate the fit
res1 = fit.fit()         # perform fit

model.pars[0].freeze()   # freeze one parameter
fit2 = Fit(d, model)     # do I need this, or does fit1 adopt the frozen parameter in the model?
res2 = fit2.fit()        # perform fit with one parameter frozen
```

**Comment by DougBurke** [comment]
@ivalaginja - no, the Fit object contains a reference to the data and model, so if you change them then it is also reflected the next time you do a fit. This is very useful, but you can mess up: e.g. if you filter a data object then this will affect all future fits that use that data object, which is normally what you want but not always!

(this was also written before your last comment)

```
from sherpa.data import Data1D
from sherpa.models.basic import Const1D
from sherpa.fit import Fit
from sherpa.utils.err import FitErr

d = Data1D('', [1, 2, 3], [4, 3, 5])
m = Const1D()
m.c0.freeze()
print(m)

f = Fit(d, m)

print("# Fit should 'fail' as no free parameters")
try:
    f.fit()
except FitErr as e:
    print(" --> {}".format(e))

print("---")
print(f)
print("---")


print(">> thawing")
m.c0.thaw()
print(m)

print("# Fit should run")
res2 = f.fit()
print(res2)
```

which is a not-very-realistic example gives for me

```
const1d
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   const1d.c0   frozen            1 -3.40282e+38  3.40282e+38           
# Fit should 'fail' as no free parameters
 --> model has no thawed parameters
---
data      = 
model     = const1d
stat      = Chi2Gehrels
method    = LevMar
estmethod = Covariance
---
>> thawing
const1d
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   const1d.c0   thawed            1 -3.40282e+38  3.40282e+38           
# Fit should run
datasets       = None
itermethodname = none
methodname     = levmar
statname       = chi2gehrels
succeeded      = True
parnames       = ('const1d.c0',)
parvals        = (3.9026285756630643,)
statval        = 0.19972187881886824
istatval       = 2.739962776980769
dstatval       = 2.54024089816
numpoints      = 3
dof            = 2
qval           = 0.904963254011
rstat          = 0.09986093940943412
message        = successful termination
nfev           = 4

```

**Comment by ivalaginja** [comment]
Ha! Thanks so much!!

**Comment by DougBurke** [comment]
It should do, but I always suggest testing it out before re-writing your code to make sure!

**Comment by ivalaginja** [comment]
Will do. You guys are awesome, thanks for the help!

**Comment by DougBurke** [comment]
```
In [1]: from sherpa.data import Data1D

In [2]: from sherpa.models.basic import Const1D

In [3]: from sherpa.fit import Fit

In [4]: d = Data1D('', [1, 2, 3], [5, 10, 20])

In [5]: m = Const1D()

In [6]: f = Fit(d, m)

In [7]: f.calc_stat()
Out[7]: 17.508039177283102

In [8]: d.staterror = [3, 3, 3]

In [9]: f.calc_stat()
Out[9]: 50.888888888888886
```

So, changing the staterror "column" has been picked up by the fit object.
