### ISSUE TITLE
more numpy warnings (numpy 1.16): sctypeNA and typeNA will be removed in 1.18

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#653]
I just tried a build of #647 and a simple test run failed 5 times - I didn't check all of them, but it looks to be a NumPy 1.16 (ish) warning:

```
% conda list numpy
# packages in environment at /home/dburke/anaconda3/envs/sherpa-647:
#
# Name                    Version                   Build  Channel
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
```

and here's an example failure

```
______________ ERROR at teardown of test_utils.test_print_fields _______________

    def fin():
        warnings = [w for w in recwarn.list
                    if type(w.message) not in known_warnings or not known(w)]
    
        nwarnings = len(warnings)
        if nwarnings > 0:
            # Only print out the first time a warning is seen; we could
            # report this to the user explicitly, but rely on the
            # counter information (i.e. i+1/nwarnings) to show that
            # there were repeats.
            #
            swarnings = set([])
            print("*** Warnings created: {}".format(nwarnings))
            for i, w in enumerate(warnings):
                sw = str(w)
                if sw in swarnings:
                    continue
                print("{}/{} {}".format(i + 1, nwarnings, w))
                swarnings.add(sw)
    
>       assert 0 == nwarnings
E       assert 0 == 1

sherpa/conftest.py:175: AssertionError
--------------------------- Captured stdout teardown ---------------------------
*** Warnings created: 1
1/1 {message : VisibleDeprecationWarning('sctypeNA and typeNA will be removed in v1.18 of numpy'), category : 'VisibleDeprecationWarning', filename : '/home/dburke/sherpa/sherpa-647/sherpa/utils/__init__.py', lineno : 1349, line : None}
```

**Comment by DougBurke** [comment]
I downgraged to 'numpy 1.15' and re-built and the test failures went away, so it is a new thing to 'numpy 1.16'

**Comment by olaurino** [comment]
Hmm.. Unless I am missing something I don't think this is Sherpa, but in any case I am surprised the warning is there in the first place, as we have the warning whitelisted (no reason to keep it whitelisted since we fixed the issue).

See #605 and #606.

I think #606 should have removed the whitelisted warning, not sure why it didn't.

**Comment by DougBurke** [comment]
Was #647 based on code from before #606 was merged (ie does not contain the fix)?

**Comment by olaurino** [comment]
The code is there. Looking again at your error report, it looks like you are running a version that does not include #606. There might be a number of reasons for this. Does the output of `python -c "import sherpa; print(sherpa.__file__)"` make sense to you? Also `python -c "import sherpa; print(sherpa.__version__)"`?

**Comment by DougBurke** [comment]
DOh. I was building against your master branch, not the branch with #647 in ...
