### ISSUE TITLE
Cannot specify dataset id when loading pha2 files

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#666]
I cannot find a way to assign ids when reading a pha type II file. This is relevant for grating data, where CIAO by default builds PHA II files, with spectra for each order, and for the HETGS for HEG and MEG. 

Is there a way of reading in a PHA II file without overwriting a previously loaded one? I've tried to pass in a number like `load_data(100, 'pha2.fits')` hoping I would then get ids 100, 101, 102, ... but that did not work. I also tried passing in a list of names, but I always get:
`Multiple data sets have been input: 1-12` and  Ioose the previously loaded dataset.

I know I can split a PHA II file into PHA I files (that's what I'm doing now), but it sure would be useful if there was a documented way to tell Sherpa which dataset ids to load the data into.

**Comment by DougBurke** [comment]
The current "load PHA" code hard-codes the range when given a PHA2 file. It should be [*] very easy to change this so that the id argument is the first one loaded - i.e. so load_pha(200, "pha2.fits") would give 200, 201, ...

[*] not tried but it really does look easy
