### ISSUE TITLE
ylog setting of model plot prefs not honored for PHA data sets

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#672]
I haven't actually checked the chips backend to see if this is an issue with the PHA plot classes the backend code, or somewhere in the UI code (the last seems unlikely given the behavior below) but the `yscale` setting of the model plot is not being honored for PHA data sets but it is for other data:

```
sherpa In [1]: from matplotlib import pyplot as plt

sherpa In [2]: get_model_plot_prefs()['ylog']
Out[2]: False

sherpa In [3]: load_arrays(1, [1, 2, 3], [4, 3, 2])

sherpa In [4]: load_arrays(1, [1, 2, 3], [400, 300, 200])

sherpa In [5]: set_source(polynom1d.mdl)

sherpa In [6]: mdl.c0 = 10

sherpa In [7]: mdl.c1 = 100

sherpa In [8]: plot_model()

sherpa In [9]: %matplotlib inline
UnknownBackend: No event loop integration for 'inline'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx

sherpa In [10]: %matplotlib
Using matplotlib backend: TkAgg

sherpa In [11]: plot_model()

sherpa In [12]: plt.gca().get_yscale()
Out[12]: 'linear'

sherpa In [13]: get_model_plot_prefs()['ylog'] = True

sherpa In [14]: plot_model()

sherpa In [15]: plt.gca().get_yscale()
Out[15]: 'log'

sherpa In [16]: load_pha('sherpa-test-data/sherpatest/3c273.pi')
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file sherpa-test-data/sherpatest/3c273.arf
read RMF file sherpa-test-data/sherpatest/3c273.rmf
WARNING: systematic errors were not found in file 'sherpa-test-data/sherpatest/3c273_bg.pi'
statistical errors were found in file 'sherpa-test-data/sherpatest/3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file sherpa-test-data/sherpatest/3c273_bg.pi

sherpa In [17]: set_source(powlaw1d.pl)

sherpa In [18]: plot_model()

sherpa In [19]: plt.gca().get_yscale()
Out[19]: 'linear'

sherpa In [20]: plt.gca().set_yscale('log')

sherpa In [21]: plt.gca().get_yscale()
Out[21]: 'log'

```

Note that the plot created in line 18 has a `linear` y scale when it should be `log` (and line 21 just shows that you can turn this axis to `log` scale).

**Comment by DougBurke** [comment]
I believe this is backend-specific, and comes about because

 - `sherpa.ui.utils.get_model_plot_prefs` accesses the `_session._modelplot.plot_prefs` structure

 - `sherpa.astro.ui.plot_model` looks at the data set and if it is `DataPHA`, then it uses `_session.modelhisto` rather than `_session.modelplot` to create the plot.

So, we would need to be able to change the preferences of the model histogram class, as well as/instead of the model plot class. It is not-at-all obvious how to handle this with the current design.

**Comment by DougBurke** [comment]
One way to "work around" this is to use `get_model_plot` to get the actual plot object, and then change its preferences directly - noticing in this case it's `histo_prefs` and not `plot_prefs`

```
In [23]: get_model_plot()                                                       
Out[23]: <sherpa.astro.plot.ModelHistogram at 0x7fdc8201acd0>

In [24]: get_model_plot().histo_prefs['ylog'] = True                            

In [25]: plot_model()

In [26]: plt.gca().get_yscale()                                                 
Out[26]: 'log'
```

This is **not** at all user friendly!

**Comment by anetasie** [comment]
@DougBurke Can this be closed?

**Comment by DougBurke** [comment]
I haven't looked for a long while, but given my notes above I would expect it is still an issue.

**Comment by DougBurke** [comment]
I've removed the matplotlib label since it's a backend-agnostic problem.
