### ISSUE TITLE
Ever compared to MPFIT (IDL)?

### ISSUE THREAD

**Issue by ivalaginja** [sherpa/sherpa#679]
I was wondering if anybody ever compared the results from using the `LevMar` optimizer in Sherpa to results from the MPFIT fitting routine (originally in Fortran, we used it in IDL, see [here](https://www.harrisgeospatial.com/docs/mpfit.html)).

MPFIT is a fairly standard Levenberg-Marquardt least-squares minimization, so any results should be very similar, however we are (still) transitioning from one to the other and wondering how much of a result discrepancy we can expect or allow for, since the implementation will be slightly different. We are getting results that are close enough to make us believe this works fine, but different enough (especially the error results from the Hessian) to make us doubt it.

We are currently setting up the tests for this, but I was wondering if anybody has made any experience with this.

**Comment by dtnguyen2** [comment]
The following is an excerpt
```
Perform Levenberg-Marquardt least-squares minimization (MINPACK-1)
```
from the URL you posted; Moreover, there is a python translation of the same package from the same author at: _https://github.com/segasai/astrolibpy/blob/master/mpfit/mpfit.py_ in it you will find the following:
```
Perform Levenberg-Marquardt least-squares minimization, based on MINPACK-1.
								   AUTHORS
  The original version of this software, called LMFIT, was written in FORTRAN
  as part of the MINPACK-1 package by XXX.
  Craig Markwardt converted the FORTRAN code to IDL.  The information for the
  IDL version is:
	 Craig B. Markwardt, NASA/GSFC Code 662, Greenbelt, MD 20770
	 craigm@lheamail.gsfc.nasa.gov
	 UPDATED VERSIONs can be found on my WEB PAGE:
		http://cow.physics.wisc.edu/~craigm/idl/idl.html
```
and if you look into the following url:
https://github.com/sherpa/sherpa/blob/master/sherpa/optmethods/src/minpack/LevMar.hh
you will find that sherpa ships the same package.  Sherpa used to ship the original Fortran version, the current shipped version is a similar version to the ```C``` (I translated it to C++ for reasons which I will explain later) which was taken from the following url:
https://github.com/devernay/cminpack.
However, there are a few differences to the _mpfit_ vs sherpa's _LevMar_ simply because the original MINPACK lmdif version is an implementation of the **unconstrained** Levenberg-Marquardt algorithm.  Sherpa's current implementation of the boundary constraints could be improved upon, there is an internal discussion from time to time about adding coordinate transformations but that has a few other headaches that comes with it.
Note, it is not as though we are not actively improving the optimization algorithms that are shipped; For example: 1) sherpa now enables the _LevMar_  to fit using multiple cores (useful only if the model function evaluation is _very_ time consuming). 2) The more interesting project, at least to me anyway, is: PR #577. 3) using _LevMar_ but with python autograd (https://github.com/HIPS/autograd) etc...

**Comment by dtnguyen2** [comment]
I read through the ```calc_covar``` function of the **updated** python version of mpfit (_translated from Numeric to numpy_) which can be found at: https://www.ast.cam.ac.uk/~rcooke/python/packages/mpfit.py
to sherpa's ```covar```.  As far as I can tell, the two functions are identical (unless of course the fit ended up near the parameter(s) boundary limit(s)). If you trust the mpfit's translation of the original MINPACK's implementation of ```lmdif``` then it will not be too difficult for you to incorporate into sherpa.

I'm not sure what you intend to do with the covariance matrix from ```LevMar``` but you might want to read the section titled 
**Parameter confidence regions** 
at the following url:
https://heasarc.gsfc.nasa.gov/xanadu/xspec/manual/XSappendixStatistics.html
specifically the subsections: 
**Fisher Matrix**
```...these estimates should be considered lower limits to the true uncertainty.``` 
 **Delta Statistic**
```The next most reliable method for deriving parameter confidence regions is to find surfaces of constant delta statistic from the best-fit value, i.e. where :...```
**Monte Carlo**
```The best but most computationally expensive methods for estimating parameter confidence regions are using two different Monte Carlo techniques....```

BTW, sherpa's command ```conf``` is equivalent to XSPEC's ```error``` command.

**Comment by ivalaginja** [comment]
This has been quite a bit to dig through, and we're still working on it.

I was wondering if you would have an idea where the following differences in results could come form? One of them was done with mpfit in IDL, the other one with Sherpa.
(Note: Rp/R* is the equivalent to rl)

IDL:
<img width="734" alt="Screen Shot 2019-11-20 at 13 17 35" src="https://user-images.githubusercontent.com/29508965/69266697-a38c3c80-0b99-11ea-90f5-65e7ab1fa112.png">

Sherpa:
<img width="1109" alt="Screen Shot 2019-11-20 at 11 51 59" src="https://user-images.githubusercontent.com/29508965/69266710-a850f080-0b99-11ea-86a4-d404203f0fbc.png">

Could this be connected to what you stated above, mpfit implementing the unconstrained LM algorithm, while Sherpa (I guess) constrains chi-squared to not drop below 1?

We're a little concerned because they are not within one sigma of each other, and the analytical result for this example yields chi-squared = 0.97741 +/- 0.00238, which favors the IDL implementation.

**Comment by dtnguyen2** [comment]
I can't seem to find the sherpa code to generate the fit? Thanks in advance

**Comment by ivalaginja** [comment]
I apologies, I created a gist for it and then forgot to add the link.
Here it is:
https://gist.github.com/ivalaginja/b8fcbcb05bc7c9d2a756056f59611cb2

**Comment by dtnguyen2** [comment]
This is a quick and dirty explanation for the difference between the two versions (IDL vs sherpa).  I slightly modified your script by adding two lines:

```
(sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py my_direct_comparison_test3.py
411a412,413
>     model.rl.val = 0.10030181
>     model.m_fac.val = 0.04151974
```
That is I set the starting parameters to be at IDL's minimum parameter values
```
    model.rl.val = 0.10030181
    model.m_fac.val = 0.04151974
    # Set up fit
    tfit = Fit(data, model, stat=stat, method=opt)
    print('\nFit information:')
    print(tfit)
```
So When I run the code, I get the following output (no sense printing the whole output):
```
(sherpa) [dtn@devel12 iva]$ python my_direct_comparison_test3.py > dtn.txt
(sherpa) [dtn@devel12 iva]$ grep statval dtn.txt 
statval        = 25.299812771028982
istatval       = 774.1582701037751
dstatval       = 748.8584573327461
```

However, as one can see sherpa thinks the initial statistics, starting from IDL's parameters that yield's IDL's minimum, is ~ 774.16 and the minimum statistics is ~748.86.  So  my initial assessement is the difference might be how chi2 is defined in the two versions.

**Comment by dtnguyen2** [comment]
Will use the class LeastSq instead of Chi2:

```
(sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py my_direct_comparison_test3.py
14c14
< from sherpa.stats import Chi2
---
> from sherpa.stats import Chi2, LeastSq
406c406
<     stat = Chi2()
---
>     stat = LeastSq()
```
Running the two scripts:
```
(sherpa) [dtn@devel12 iva]$ python direct_comparison_test3.py > ivalagina.txt
(sherpa) [dtn@devel12 iva]$ python my_direct_comparison_test3.py > dtn.txt 
(sherpa) [dtn@devel12 iva]$ tail -3 ivalagina.txt 
rl = 0.09555676509116409 +/- 0.0007726208099838543
m_fac = 0.04005988473902907 +/- 9.431047697545877e-05
Reduced chi-squared: 1.0541588654590175
(sherpa) [dtn@devel12 iva]$ tail -3 dtn.txt 
rl = 0.09555676615901845 +/- 1.9315540231317292
m_fac = 0.04005990020346872 +/- 0.23577618526392152
Reduced chi-squared: None
```
As you can see they give identical, within tolerance, fitted parameters

**Comment by dtnguyen2** [comment]
Regarding your question:

> Could this be connected to what you stated above, mpfit implementing the unconstrained LM 
> algorithm, while Sherpa (I guess) constrains chi-squared to not drop below 1?

sherpa does not place any such restriction, sherpa ships with a test script called _pha_intro-fit.py_ and as you can see:

```
(sherpa) [dtn@devel12 sherpatest]$ python pha_intro-fit.py 
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi' 
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi' 
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi
Dataset               = 1
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 6.84134e+10
Final fit statistic   = 37.4897 at function evaluation 22
Data points           = 44
Degrees of freedom    = 42
Probability [Q-value] = 0.669101
Reduced statistic     = 0.892612
Change in statistic   = 6.84134e+10
   p1.gamma       2.15012      +/- 0.0786161   
   p1.ampl        0.000222778  +/- 1.43833e-05 
Dataset               = 1
Confidence Method     = covariance
Iterative Fit Method  = None
Fitting Method        = levmar
Statistic             = chi2gehrels
covariance 1-sigma (68.2689%) bounds:
   Param            Best-Fit  Lower Bound  Upper Bound
   -----            --------  -----------  -----------
   p1.gamma          2.15012   -0.0821768    0.0821768
   p1.ampl       0.000222778 -1.46276e-05  1.46276e-05
```
the reduced statistics is ~0.89.

BTW now back to the _direct_comparison_test3.py_, using NelderMead instead of LevMar gives identical reduced stat.

(sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py nm_direct_comparison_test3.py
13c13
```
< from sherpa.optmethods import LevMar
---
> from sherpa.optmethods import LevMar, NelderMead
407,408c407,408
<     opt = LevMar()
<     opt.config['epsfcn'] = np.finfo(float).eps  # adjusting epsfcn to double precision
---
>     opt = NelderMead()
>     # opt.config['epsfcn'] = np.finfo(float).eps  # adjusting epsfcn to double precision
424,430c424,430
<     calc_errors = np.sqrt(fitresult.extra_output['covar'].diagonal())
<     rl_err = calc_errors[0]
<     m_fac_err = calc_errors[1]
<     # Results
<     print('rl = {} +/- {}'.format(model.rl.val, rl_err))
<     print('m_fac = {} +/- {}'.format(model.m_fac.val, m_fac_err))
<     print('Reduced chi-squared: {}'.format(fitresult.rstat))
---
>     # calc_errors = np.sqrt(fitresult.extra_output['covar'].diagonal())
>     # rl_err = calc_errors[0]
>     # m_fac_err = calc_errors[1]
>     # # Results
>     # print('rl = {} +/- {}'.format(model.rl.val, rl_err))
>     # print('m_fac = {} +/- {}'.format(model.m_fac.val, m_fac_err))
>     # print('Reduced chi-squared: {}'.format(fitresult.rstat))
(sherpa) [dtn@devel12 iva]$ python direct_comparison_test3.py > lm.txt
(sherpa) [dtn@devel12 iva]$ python nm_direct_comparison_test3.py > nm.txt
(sherpa) [dtn@devel12 iva]$ grep rstat lm.txt 
rstat          = 1.0541588654590175
(sherpa) [dtn@devel12 iva]$ grep rstat nm.txt 
rstat          = 1.05415886545657
```

So I'm fairly sure sherpa's version of LevMar is not misbehaving

**Comment by dtnguyen2** [comment]
sherpa allows the user to add their own optimization routine.  Writing an optimization routine is not a trivial task but you seem to doubt our implementations so I decided to install iminuit (see:https://github.com/scikit-hep/iminuit for details). Once iminuit is installed I plagiarized the code from the file
```/export/miniconda/envs/sherpa/lib/python3.7/site-packages/iminuit/_minimize.py```
To add the following lines to the _direct_comparison_test3.py_ script:
```
(sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py minuit_direct_comparison_test3.py
(sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py minuit_direct_comparison_test3.py
16a17,65
> from sherpa.optmethods import OptMethod
> from iminuit import Minuit
> 
> class MyMinuit(OptMethod):
>     def __init__(self):
>         OptMethod.__init__(self, 'myminuit', my_minuit)
> 
> 
> def my_minuit(fcn, x0, xmin, xmax, error=None, maxfev=None, verbose=0,
>               args=(), callback=None):
> 
> 
>     def stat_cb0(pars):
>         return fcn(pars)[0]
>     
>     def wrapped(func, args, callback=None):
>         if callback is None:
>             return lambda x: func(x, *args)
>         else:
>             def f(x):
>                 callback(x)
>                 return func(x, *args)
>             return f
> 
>     # prevent warnings from Minuit about missing initial step
>     if error is None:
>         error = np.ones_like(x0)
> 
>     wrapped_fun = wrapped(stat_cb0, args, callback)
>     if maxfev is None:
>         maxfev = 1024
>     kwargs = {"print_level": verbose, "errordef": 1}
> 
>     m =  Minuit.from_array_func(wrapped_fun, x0, error=error, **kwargs)
>     m.migrad()
>     nfev = m.get_num_call_fcn()
>     fval = m.fval
>     x = m.np_values()
>     msg = "Optimization terminated successfully."
>     success = m.migrad_ok()
>     if not not success:
>         message = "Optimization failed."
>         status = 1
>     else:
>         status = 0
>     covar = m.np_covariance()
>     rv = (status, x, fval, msg, {'nfev': nfev, 'covar': covar, 'info': 1})
>     return rv
> 
407,408c456,457
<     opt = LevMar()
<     opt.config['epsfcn'] = np.finfo(float).eps  # adjusting epsfcn to double precision
---
>     opt = MyMinuit()
>     # opt.config['epsfcn'] = np.finfo(float).eps  # adjusting epsfcn to double precision
```
So when I run the modified script, I get the following results:
```
(sherpa) [dtn@devel12 iva]$ python minuit_direct_comparison_test3.py | tail -25
Fit information:
data      = example_transit
model     = transit
stat      = Chi2
method    = MyMinuit
estmethod = Covariance
datasets       = None
itermethodname = none
methodname     = myminuit
statname       = chi2
succeeded      = 1
parnames       = ('transit.rl', 'transit.flux0', 'transit.m_fac')
parvals        = (0.0955545972119733, 1.0000087444374302, 0.040053168616834736)
statval        = 25.299830813311313
istatval       = 1076.4538430102298
dstatval       = 1051.1540121969185
numpoints      = 27
dof            = 24
qval           = 0.38961688916526743
rstat          = 1.0541596172213048
message        = Optimization terminated successfully.
nfev           = 70
rl = 0.0955545972119733 +/- 0.0007726539287795822
m_fac = 0.040053168616834736 +/- 9.431127723938641e-05
Reduced chi-squared: 1.0541596172213048
```
Moreover:
```
(sherpa) [dtn@devel12 iva]$ grep parvals nm.txt 
parvals        = (0.09555676547965018, 1.0000090068444154, 0.04005990229538582)
(sherpa) [dtn@devel12 iva]$ grep parvals lm.txt 
parvals        = (0.09555676509116409, 1.0000090068413485, 0.04005988473902907)
(sherpa) [dtn@devel12 iva]$ python minuit_direct_comparison_test3.py > minuit.txt
(sherpa) [dtn@devel12 iva]$ grep parvals minuit.txt 
parvals        = (0.0955545972119733, 1.0000087444374302, 0.040053168616834736)
```
That is the three optimization methods (LevMar, NelderMead, Minuit) give identical fit parameters.  I'm confident that sherpa's implementation of minpack's lmdif is correct.  Perhaps there is an error in translating the original IDL code to Python?

**Comment by hrwakeford** [comment]
> This is a quick and dirty explanation for the difference between the two versions (IDL vs sherpa). I slightly modified your script by adding two lines:
> 
> ```
> (sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py my_direct_comparison_test3.py
> 411a412,413
> >     model.rl.val = 0.10030181
> >     model.m_fac.val = 0.04151974
> ```
> 
> Just realized that your fit has three free parameters, so can you tell me what is the idl's final fitted parameter for the `flux0` parameter? Thanks in advance.

The results from the IDL test are as follows:
Rp/R* =       0.10052301   +/-      0.00086986201
m_fac =      0.040429183   +/-       0.0023947257
e_shift =    -0.0060774008   +/-       0.0041328907
flux0 =        1.0002551   +/-      0.00019254950
Reduced chi-squared =       0.98597881
CHI-SQUARE =       22.677513          DOF = 23

**Comment by ivalaginja** [comment]
@dtnguyen2 thank you very much for looking into this! It will take us a while again to look into all of that, but it does seem like it will be something on our end when we wrote the python version of the code in the first place. Debugging has become harder so we were curious were the limitations are on both ends.

We hope to make our repository public sometime in the close future so maybe that will facilitate the exchange or our questions. Thanks in any case for spending your time on this!

**Comment by dtnguyen2** [comment]
Even though @ivalaginja has acknowledged:

> ...
> that, but it does seem like it will be something on our end when we wrote the python version of
> the code in the first place
> ...

but because it was posted:

> > This is a quick and dirty explanation for the difference between the two versions (IDL vs sherpa). I slightly modified your script by adding two lines:
> > ```
> > (sherpa) [dtn@devel12 iva]$ diff direct_comparison_test3.py my_direct_comparison_test3.py
> > 411a412,413
> > >     model.rl.val = 0.10030181
> > >     model.m_fac.val = 0.04151974
> > ```
> > 
> > 
> > Just realized that your fit has three free parameters, so can you tell me what is the idl's final fitted parameter for the `flux0` parameter? Thanks in advance.
> 
> The results from the IDL test are as follows:
> Rp/R* = 0.10052301 +/- 0.00086986201
> m_fac = 0.040429183 +/- 0.0023947257
> e_shift = -0.0060774008 +/- 0.0041328907
> flux0 = 1.0002551 +/- 0.00019254950
> Reduced chi-squared = 0.98597881
> CHI-SQUARE = 22.677513 DOF = 23

I felt compelled to answer.  The Python code that was made available has three free parameters:
```
(sherpa) [dtn@devel12 iva]$ grep parnames ivalagina.txt 
parnames       = ('transit.rl', 'transit.flux0', 'transit.m_fac')
```
However, it looks like the IDL code produces four free parameters (```Rp/R*```, ```m_fac```, ```e_shift``` and ```flux0```). It was stated that:

> (Note: Rp/R* is the equivalent to rl)

so I was able to find references to all but one of the free IDL parameter (```e_shift```).
```
(sherpa) [dtn@devel12 iva]$ grep -i e_shift direct_comparison_test3.py | wc
      0       0       0
```

It doesn't look like the parameter ```e_shift``` ever made it to the Python code

**Comment by ivalaginja** [comment]
That is just because it is a possible parameter, bu for this particular test it is not actually incorporated, neither in the IDL case, nor in the Python case; it's a leftover in IDL we didn't clean out.

Especially since e_shift doesn't influence rl in our model at all. I know that seems like a wild claim, but e_shift was a random variable we just introduced to do further tests, and is not actually included in our initial model. I am still impressed you caught that though.
