### ISSUE TITLE
Python 3.6 for Ciao/Sherpa binaries ?

### ISSUE THREAD

**Issue by facero** [sherpa/sherpa#687]
Maybe this is more a Ciao issue than a Sherpa one but I'll ask it here.

I'm currently trying to use sherpa to work together with another python library for gamma-ray astronomy ([gammapy](https://docs.gammapy.org)) that uses f-string in its print statement.
As I need the Xpsec models, I downloaded the Ciao binaries that ships with Python 3.5. I know I could build Ciao from source with my local Python but it would be easier for users that the two libraries could be used with the same Python version.

Any futur plans to ship the next Ciao release with Python 3.6 (or greater) by default ? A growing number of libraries have f-strings and require Python > 3.5. From #360 it seems that Sherpa supports 3.6. 
Thanks for the great tools you're providing !

**Comment by wmclaugh** [comment]
Thanks for the feedback. For the next CIAO release (CIAO 4.12) the standard ciao-install distribution will be built against Python 3.5. In addition, we are currently planning on releasing condo distributions for Python 3.5, 3.6, and Python 3.7.

**Comment by facero** [comment]
Thanks for the quick answer. Will the conda release come with Xspec models ?

**Comment by DougBurke** [comment]
At the moment the plan is that we will include the xspec models in the CIAO 4.12 conda release (which will be mid December).

**Comment by facero** [comment]
Looking forward for this release then. Thanks !

**Comment by DougBurke** [comment]
@facero - if you do try building your own XSPEC model library / sherpa build, let us know if you have any problems [for instance, you need #677 if you want to use XSPEC 12.10.1m or later]
