### ISSUE TITLE
Initializing generid data silently drops mask

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#695]
When I make a `Data1D` or `Data2D` dataset from a numpy masked array, Sherpa silently drops the mask and uses the values "behind the mask".
```
import numpy as np

from sherpa.data import Data1D, Data2D
from sherpa.fit import Fit
from sherpa.models import Const1D, Const2D

arr1d = np.ma.array([1.,2.,90.,3.,1.], mask=[False, False, True, False, False])
arr2d = np.ma.array([[1,1.5], [10., 1.2]], mask = [[False, False], [True, False]])

d1 = Data1D('d1', np.array([1,2,3,4,5]), arr1d)
d2 = Data2D('d2', np.array([1,1,2,2]), np.array([1,2,1,2]), arr2d.ravel())
print(d1.mask)

c1 = Const1D('c1')
fit1 = Fit(d1, c1)
print(fit1.fit())
```
The Fit results is (some non-relevant lines removed from output):
```
succeeded      = True
parnames       = ('c1.c0',)
parvals        = (2.8467372929128665,)
statval        = 69.91988835701966
numpoints      = 5
dof            = 4
qval           = 2.359979141585598e-14
rstat          = 17.479972089254915
```
Clearly, the fit is terrible (just look at qval) and the fitted values is too large. `numpoints` shows that the fit used all five datapoints, including the one that should have been masked.
However, I can manually set the mask (**note that I actually need to set the opposite of the mask** because numpy uses `True` to indicate masked values and Sherpa uses `True~ to indicate valid values and `False~ for masked values):
```
d1.mask = ~arr1d.mask
fit1 = Fit(d1, c1)
print(fit1.fit())
```
Now, the fit works better and uses only 4 unmasked datapoints:
```
succeeded      = True
parnames       = ('c1.c0',)
parvals        = (1.5945294293559473,)
statval        = 0.3833606897991587
numpoints      = 4
dof            = 3
qval           = 0.9436579269604303
rstat          = 0.12778689659971956
```

The same works for 2D datasets...
I think its very dangerous to accept masked arrays on input and silently drop the mask. That's even more confusing since there is no obvious way to pass in a mask. I had to discover the `data.mask` attribute and then figure out that the definition is exactly opposite to numpy. Very unfortunate choice!

So, what could be done? I suggest:

- Add a parameters `mask` to the initializers for the Data classes. That's analogous to `numpy.array.ma(data=..., mask=...)`. When people try to pass in a masked array and it does not work as expected, looking at the parameters for initialization is what I did first.
- Document that mask convention **WITH BIG WARNINGS**.
- Accept `np.ma.array` on input and automatically convert the mask. Alternatively, issue warning if any datatype with a `.mask` attribute is passed in and say "Dropping mask. Use mask= parameter to explicitly set mask".
- It may be to late to change Sherpa's True/False convention for masks. But it's very bad (TM) that this is opposite to numpy, in particular since Sherpa uses numpy for all numerics. In the long run, we should investigate if the Sherpa data classes could use `numpy.ma.array` as their underlying datatype instead of carrying a separate mask. I have not looked through the code, but I imagine that Sherpa must implement a lot of functions to deal with masked data itself, that we could get for free from numpy.ma, starting by simple things like sum, mean and average of an array, taking into account the mask, to matplotlib integration (matplotlib knows not to plot masked values if given a masked array).

**Comment by DougBurke** [comment]
@hamogu  if you could come up with proposed documentation changes that would be great.  For the 4.12 release I think that's about as far as we can go, apart from maybe we could add to the validation checks that were recently added as part of #614. Anything more would have to be for a later release.

**Comment by DougBurke** [comment]
See also #346  "unexpected behavior with masked arrays"
