### ISSUE TITLE
Does modelCacher1d needs a couple of deep copy()?

### ISSUE THREAD

**Issue by dtnguyen2** [sherpa/sherpa#697]
While testing to make sure that PR #616 is included the CIAO 4.12 beta 2 release I noticed the following issue:  PR #616 is included in the aforementioned release, but one of the fixes in the PR should have also be made in the ```modelCacher1d``` function in the file _sherpa/models/model.py_

One of the fixes in PR #616 is in the class ```myCacheARF``` in the file _sherpa/astro/data.py_, specifically the following lines from:
```
...
if digest in self.cache:
            return self.cache[digest]
...
            self.queue.append(digest)
            self.cache[digest] = val
```
to:
```
if digest in self.cache:
            return self.cache[digest].copy()
...
            self.queue.append(digest)
            self.cache[digest] = val.copy()
```
That is a couple of deep copies have to be be added from/to the cache;  However, the class ```myCacheARF``` was basically a cut and paste from the function ```modelCacher1d``` in the file _sherpa/models/model.py_ and they do not have the two deep ```copy()``` in them. Working from the ciao-4.12-src-sherpa tar file:

```
cp /proj/xena/ciaot_install/tarfiles.191020/ciao-4.12-src-sherpa.tar.gz .
tar -zxf ciao-4.12-src-sherpa.tar.gz
cd ciao-4.12/src/pkg/sherpa/sherpa
grep -r "cache\[digest\]"

astro/data.py:            return self.cache[digest].copy()
astro/data.py:            self.cache[digest] = val.copy()
models/model.py:                return cache[digest]
models/model.py:            cache[digest] = vals
```

As one can see, the two deep ```copy()``` are not present in the ```modelCacher1d``` in the _sherpa/models/model.py_ file.

Perhaps this is not the place to bring this up, but the class ```myCacheARF``` was only written cause @anetasie complained that PR #616 did not cached the ARF but as I recall, folding the ARF is just a straight forward element-wise vector multiplications.  Not to mention that the PR was accidentally released, just saying

**Comment by DougBurke** [comment]
@dtnguyen2 I couldn't tell if this means we should just add a .copy call to these data access routines or not?

**Comment by dtnguyen2** [comment]
The title of this PR should have been "A solution looking for a problem".  If we think that if .copy() had to be added to PR #616 then I think we should also add it to ```modelCacher1d``` also but I'm reluctant to add without a test to confirm it.

**Comment by DougBurke** [comment]
@dtnguyen2 - is this still open/relevant (with the changes you made in #759 to revert the cache changes), or am I getting confused?

**Comment by dtnguyen2** [comment]
Oops, forgot which screen I was on. The last message (The ARF caching code was removed in PR #759 so this is no longer relevant and therefore should be closed).
