### ISSUE TITLE
image_data and DS9 v8 coordinates problem

### ISSUE THREAD

**Issue by nplee** [sherpa/sherpa#702]
It seems that when image_data is used with Sherpa (on CIAO 4.11, 4.10, and 4.9), the existing build in CIAOT 4.12, and standlone 4.11.1 with DS9 8.1rc, the physical and image coordinates interpreted by DS9 are identical. If I use DS9 7.6, they differ, as expected.

```
load_image('/pool14/nlee/image2.fits')
image_data()
```
so something is going on between DS9 and Sherpa; but I don't know on which end the problem can be fixed.

If the image is opened directly with DS9, the behavior is as expected, with different image and physical coordinates. 

@DougBurke and @wjoye have made prior comments from the original sherpadev report. (https://groups.google.com/a/cfa.harvard.edu/forum/?pli=1#!topic/sherpadev/3XOzhjTXbuA)

**Comment by DougBurke** [comment]
We believe this is a DS9 issue related to not having a WCSNAMEP keyword in the "original" header (when the raw data is sent over from Sherpa to DS9 via XPA).

**Comment by DougBurke** [comment]
@nplee - can you confirm that this is fixed with the DS9 8.1 release, then I can close this?

**Comment by nplee** [comment]
@DougBurke just tested using Sherpa that comes with CIAO 4.12 and the OTS DS9 and the DS9 8.1 build on the HEAD network.  The discrepancy persists.  Switching to DS9 7.6, the load_image behaves as expected.  In all cases, directly opening the image with DS9 works as expected as well.

**Comment by DougBurke** [comment]
Darn it. I thought we'd got this sorted...

**Comment by DougBurke** [comment]
Just to note that although DS9 8.1 fixed the initial problem, I believe there turned out to be some other issue that means the problem still remains (if I correctly remember a hallway discussion with @wjoye )

**Comment by nplee** [comment]
@wjoye and I discussed this some a couple weeks ago and the fix should be in a future 8.2 beta

**Comment by DougBurke** [comment]
@nplee - do we still see this in CIAOX?

**Comment by nplee** [comment]
@DougBurke - looks like it's working as expected

**Comment by DougBurke** [comment]
I'll close this then. Ta for checking.
