### ISSUE TITLE
wavy plot with using regrid with plot_source_component

### ISSUE THREAD

**Issue by dtnguyen2** [sherpa/sherpa#708]
The following:

from sherpa.astro.ui import *
import numpy as np
dataspace1d(1,100,2, dstype=Data1DInt)
set_model(box1d.b1)
b1.xlow=10
b1.xhi=80
b1.ampl.max=200
b1.ampl=100
grid_hi = np.linspace(1.05,101.05,200)
grid_lo = np.linspace(0.55,100.55,200)
rb1 = b1.regrid(grid_lo,grid_hi)
set_model(rb1)
dataspace1d(1,102.,2,dstype=Data1DInt)
fake()
set_model(rb1)
plot_data()
fit()
plot_fit()
plot_source_component(rb1,overplot=True)

is a simplified version of @anetasie bug report about wavy result when using ```plot_source_component```.  The original bug report can be found here:

https://github.com/sherpa/sherpa/pull/685#issuecomment-551274848

**Comment by dtnguyen2** [comment]
The erroneous wavy output from ```plot_source_component``` in this issue is similar to the one reported in PR #685, that is the bins generated by the ```join``` method in the ```EvaluationSpace1D``` produces overlapping bins.  I have a simple print statement in the said method to print out the first five entries of the arrays ```new_xlo``` and ```new_xhi```:

```
diff --git a/sherpa/models/regrid.py b/sherpa/models/regrid.py
index 5dbbdec7..a8841dec 100644
--- a/sherpa/models/regrid.py
+++ b/sherpa/models/regrid.py
@@ -332,7 +332,9 @@ class EvaluationSpace1D():
             new_xhi = np.unique(np.concatenate((self.x_axis.hi, other.x_axis.hi)))
         else:
             new_xhi = None
-
+        num = 5
+        for ii in range(num):
+            print(ii, '\t', new_xlo[ii], '\t', new_xhi[ii])
         return EvaluationSpace1D(new_xlo, new_xhi)
 ```

So when I run the simplified script, I get the following:

```
0 	 0.55 	 1.05
1 	 1.0 	 1.5525125628140704
2 	 1.0525125628140704 	 2.0550251256281404
3 	 1.5550251256281407 	 2.5575376884422107
4 	 2.0575376884422107 	 3.0
```

Obviously the bins overlap, hence the wavy output.

**Comment by anetasie** [comment]
so just to make it clear to myself - the issue is in the way EvaluationSpace1d generates the grid.
This is the arrays that were entered into regrid()

```
In [16]: print(grid_lo[0],grid_hi[0])                                                 
0.55 1.05

In [17]: print(grid_lo[1],grid_hi[1])                                                 
1.0525125628140704 1.5525125628140704

In [18]: print(grid_lo[2],grid_hi[2])                                                 
1.5550251256281407 2.0550251256281404

**Comment by dtnguyen2** [comment]
> that is the bins generated by the ```join``` method in the ```EvaluationSpace1D``` produces  
> overlapping bins

Ahem, isn't that what I said

**Comment by anetasie** [comment]
@dtnguyen2 Yes!

**Comment by dtnguyen2** [comment]
I thought I had a fix for this issue  but I ran into another problem, I could not understand why the fix turned the erroneous sine-wave-like result from ```plot_source_component``` as though it was sent through a half wave rectifier.  So I simplified things further by running the following script:

```
import numpy as np
from sherpa.utils import sao_arange
from sherpa.utils._utils import rebin
from sherpa.models.basic import Box1D

def have_overlapping_bins(lo, hi):
    return np.any(lo[1:] < hi[:-1])

data = sao_arange(1.0, 101.0, 2)
data_lo = data[:-1]
data_hi = data[1:]

requested_hi = np.linspace(1.05, 101.05, 200)
requested_lo = np.linspace(0.55, 100.55, 200)

tmp = np.unique(np.append(data_lo, requested_lo))

xlo = tmp[:-1]
xhi = tmp[1:]

b1 = Box1D()
b1.xlow = 10
b1.xhi = 80
b1.ampl.max = 200
b1.ampl = 100

# sanity check to make sure the bins do not overlap
print('Are bins overlap? ', have_overlapping_bins(xlo, xhi), '\n')

myxlo = xlo[32:39]
myxhi = xhi[32:39]
y = b1(myxlo, myxhi)
print(b1)
print('\nbin\txlo\txhi\ty')
for ii in range(y.size):
    print("%d\t%.5g\t%.5g\t%.5g" % (ii, myxlo[ii], myxhi[ii], y[ii]))
```
When the script is run, one gets the following results:
```
(sherpa) [dtn@devel12 wavy]$ rebin.py
Are bins overlap?  False 

box1d
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   box1d.xlow   thawed           10 -3.40282e+38  3.40282e+38           
   box1d.xhi    thawed           80 -3.40282e+38  3.40282e+38           
   box1d.ampl   thawed          100           -1          200           

bin	xlo	xhi	y
0	13.113	13.615	50.251
1	13.615	14.118	50.251
2	14.118	14.62	50.251
3	14.62	15	37.965
4	15	15.123	12.286
5	15.123	15.625	50.251
6	15.625	16.128	50.251
```
The box1d.xlo and box1d.xhi are 10 and 80, respectively, so one expects the values return from calling box1d should return a constant if the domain is within [10, 80].  However, as one can see the third and fourth bins, which are well within the range [10, 80], have values less then  50.251 ie they are 37.965 and 12.286 respectively. 

At first I thought that there is something wrong with the sherpa's Box1d, but the culprit is a little more subtle then that:  ```regrid``` merges the data space (see the variables data_xlo and data_xhi) with the requested evaluation space (see the variables, requested_lo and requested_hi). It turns out the interleaving of the two arrays which causes the bins to have overlap hence the bug report from @anetasie.  So by fixing the bins to not-overlap does not fix all the issues (Note: the call to the function ```have_overlapping_bins``` in the script returns False, or when can see that from the output that the integrated bins are aligned correctly).  Note that the integer output of (15) of bins 3 and 4 is the contributions from the data space. I added a simple print statement in the `C++` implementation of the `Box1D`.  
```
(sherpa) [dtn@devel12 sherpa]$ git diff sherpa/include/sherpa/models.hh
diff --git a/sherpa/include/sherpa/models.hh b/sherpa/include/sherpa/models.hh
index 733365a2..e8aeab90 100644
--- a/sherpa/include/sherpa/models.hh
+++ b/sherpa/include/sherpa/models.hh
@@ -66,8 +66,9 @@ namespace sherpa { namespace models {
       val = 0.0;
     else {
       val = p[2] * ( std::min(xhi,p[1]) - std::max(xlo,p[0]) );
+      printf("xlo = %f\txhi = %f, delta = %f\tval = %f\n",
+             xlo, xhi, std::min(xhi,p[1]) - std::max(xlo,p[0]), val);
     }
-
     return EXIT_SUCCESS;
 
   }
```
Running the modified script with the modified print statement, I get the following results:
```
(sherpa) [dtn@devel12 wavy]$ rebin.py
Are bins overlap?  False 

xlo = 13.112814	xhi = 13.615327, delta = 0.502513	val = 50.251256
xlo = 13.615327	xhi = 14.117839, delta = 0.502513	val = 50.251256
xlo = 14.117839	xhi = 14.620352, delta = 0.502513	val = 50.251256
xlo = 14.620352	xhi = 15.000000, delta = 0.379648	val = 37.964824
xlo = 15.000000	xhi = 15.122864, delta = 0.122864	val = 12.286432
xlo = 15.122864	xhi = 15.625377, delta = 0.502513	val = 50.251256
xlo = 15.625377	xhi = 16.127889, delta = 0.502513	val = 50.251256
box1d
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   box1d.xlow   thawed           10 -3.40282e+38  3.40282e+38           
   box1d.xhi    thawed           80 -3.40282e+38  3.40282e+38           
   box1d.ampl   thawed          100           -1          200           

bin	xlo	xhi	y
0	13.113	13.615	50.251
1	13.615	14.118	50.251
2	14.118	14.62	50.251
3	14.62	15	37.965
4	15	15.123	12.286
5	15.123	15.625	50.251
6	15.625	16.128	50.251

```
Notice that the `delta` of bins 3 and 4 (where the interleaving from the data space) are not the same as the other bins hence the claim that the _fix_ behaves as though it was sent through a half-wave-rectifier.

SDS has two options: 1) interleave the data space and live with the not so uniform behaviour or 2) don't interleave the data spaces.  Either way, there is a lot of changes to the tests that I have to fix.

**Comment by dtnguyen2** [comment]
Turns out there is a better way (without modifying the C++ code) to see the
semi-wavy nature of the integrated Box1D function if the data space and
requested evaluation space in this issue are interleaved.  The value of the
Box1D integrated function is basically the amplitude (which in our case is 100)
multiply by xhi - xlo (assuming xlo and xhi are within the range of
[box1d.xlow, box1d.xhi] which is [10, 80]).

So by changing the following lines from:
```
myxlo = xlo[32:39]
myxhi = xhi[32:39]
```
to
```
myxlo = xlo[32:43]
myxhi = xhi[32:43]
```
and change the following lines from
```
print('\nbin\txlo\txhi\ty')
for ii in range(y.size):
    print("%d\t%.5g\t%.5g\t%.5g" % (ii, myxlo[ii], myxhi[ii], y[ii]))
```
to
```
print('\nbin\txlo\txhi\txhi-xlo\ty')
for ii in range(y.size):
    print("%d\t%.5g\t%.5g\t%.5g\t%.5g" %
          (ii, myxlo[ii], myxhi[ii], 100.* (myxhi[ii]- myxlo[ii]), y[ii]))
```
So when the rebin script is run, one gets:

```
(sherpa) [dtn@devel12 wavy]$ rebin.py
Are bins overlap?  False 

box1d
   Param        Type          Value          Min          Max      Units
   -----        ----          -----          ---          ---      -----
   box1d.xlow   thawed           10 -3.40282e+38  3.40282e+38           
   box1d.xhi    thawed           80 -3.40282e+38  3.40282e+38           
   box1d.ampl   thawed          100           -1          200           

bin	xlo	xhi	xhi-xlo	y
0	13.113	13.615	50.251	50.251
1	13.615	14.118	50.251	50.251
2	14.118	14.62	50.251	50.251
3	14.62	15	37.965	37.965
4	15	15.123	12.286	12.286
5	15.123	15.625	50.251	50.251
6	15.625	16.128	50.251	50.251
7	16.128	16.63	50.251	50.251
8	16.63	17	36.96	36.96
9	17	17.133	13.291	13.291
10	17.133	17.635	50.251	50.251
```

**Comment by dtnguyen2** [comment]
Now that @DougBurke has come around to 

> I am coming (back) to the conclusion that we should just evaluate the model on the user-requested grid, and set anything outside this to 0.

so I backed out the massive code change that I had made and use the simple tweak which will fix the wavy plot @anetasie reported.  My guess is once we finalize the what to do with the ```join``` method, this issue and PR #726 will be obsolete

**Comment by dtnguyen2** [comment]
![issue708](https://user-images.githubusercontent.com/12256848/75574419-402d6880-5a2c-11ea-8863-c7f3a9c4667f.png)

Once I check in the code, this should be the output

**Comment by DougBurke** [comment]
I've confirmed that #747 does [fix this issue](https://github.com/sherpa/sherpa/pull/747#issuecomment-603278092)
