### ISSUE TITLE
1D integrated models do not regrid properly for partial overlap of grids

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#722]
I have an example where the `regrid` method fails when the grid it is given doesn't fully cover the base grid. There's actually two cases, 

a) a run-time error where the number of array elements don't match (this looks to be from code that is trying to handle this lack of coverage, and I thought we had an issue about this already but perhaps not)

b) or a case where the model is evaluated, but calculates double the expected value

There's a Jupyter notebook, script extracted from the notebook, and HTML version of the notebook at https://gist.github.com/DougBurke/cfa5a83090b464b0875e0d08a52d8ca8

The notebook can be viewed at https://nbviewer.jupyter.org/gist/DougBurke/cfa5a83090b464b0875e0d08a52d8ca8/problems.ipynb

To simplify this I've created tests that show the failure (for the "1D integrated" case, seem to work fine for the 1D case) in #724

**Comment by DougBurke** [comment]
Could case b - the double counting - be due to the fact that Sherpa accidentally includes the predicted model values from the "base" grid in the calculation (rather than only doing this for those bins that lie outside the range given to `regrid`).

I wonder if maybe we should just set points outside the `regrid` range to 0 rather than try to correct for the missing bins?

**Comment by DougBurke** [comment]
The problem of the "double counting" is because of the following in `sherpa/models/regrid.py` in `EvaluationSpace1D.join`: https://github.com/sherpa/sherpa/blob/master/sherpa/models/regrid.py#L330

```
new_xlo = np.unique(np.concatenate((self.x_axis.lo, other.x_axis.lo)))
if self.x_axis.is_integrated:
    new_xhi = np.unique(np.concatenate((self.x_axis.hi, other.x_axis.hi)))
```

This doesn't handle edge differences due to numerical precision - for example:

```
In [16]: xgrid = np.arange(2.5, 5, 0.2)                                         

In [17]: ogrid = np.arange(2, 6,0.1)                                            

In [18]: xgrid                                                                  
Out[18]: array([2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9])

In [19]: ogrid                                                                  
Out[19]: 
array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9])

In [20]: np.unique(np.concatenate((xgrid, ogrid)))                              
Out[20]: 
array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.5, 2.6, 2.7, 2.7, 2.8, 2.9, 2.9,
       3. , 3.1, 3.1, 3.2, 3.3, 3.3, 3.4, 3.5, 3.5, 3.6, 3.7, 3.7, 3.8,
       3.9, 3.9, 4. , 4.1, 4.2, 4.3, 4.3, 4.4, 4.5, 4.6, 4.7, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9])
```

Note how the array has multiple 2.5 / 2.6 / 2.7 / ... values in them. If you compare them this is because they are different at ~ 1e-15:

```
In [21]: uns = np.unique(np.concatenate((xgrid, ogrid)))                        

In [22]: np.ediff1d(uns)                                                        
Out[22]: 
array([1.0000000e-01, 1.0000000e-01, 1.0000000e-01, 1.0000000e-01,
       1.0000000e-01, 4.4408921e-16, 1.0000000e-01, 1.0000000e-01,
       4.4408921e-16, 1.0000000e-01, 1.0000000e-01, 4.4408921e-16,
       1.0000000e-01, 1.0000000e-01, 4.4408921e-16, 1.0000000e-01,
       1.0000000e-01, 4.4408921e-16, 1.0000000e-01, 1.0000000e-01,
       4.4408921e-16, 1.0000000e-01, 1.0000000e-01, 4.4408921e-16,
       1.0000000e-01, 1.0000000e-01, 4.4408921e-16, 1.0000000e-01,
       1.0000000e-01, 1.0000000e-01, 1.0000000e-01, 8.8817842e-16,
       1.0000000e-01, 1.0000000e-01, 1.0000000e-01, 1.0000000e-01,
       8.8817842e-16, 1.0000000e-01, 1.0000000e-01, 1.0000000e-01,
       1.0000000e-01, 1.0000000e-01, 1.0000000e-01, 1.0000000e-01,
       1.0000000e-01, 1.0000000e-01, 1.0000000e-01, 1.0000000e-01,
       1.0000000e-01])

```

**Comment by DougBurke** [comment]
I do have some code that "fixes" this - it post-processes the list to look for edges close to each other - but there's some other issues with this approach (it doesn't guarantee that the number of bins in the lo and hi arrays are the same) that mean more work is needed before I want to show it.

**Comment by dtnguyen2** [comment]
Using the soon to be checked in code, the sherpa's command
```ui.plot_model(4, overplot=True, linestyle='dashed')```
 from [@DougBurke script](https://nbviewer.jupyter.org/gist/DougBurke/cfa5a83090b464b0875e0d08a52d8ca8/problems.ipynb)
yields:
![plot_model4](https://user-images.githubusercontent.com/12256848/75577275-a962ab00-5a2f-11ea-970c-b61dcbebc756.png)
```ui.plot_model(5, overplot=True, linestyle='dashed')```
![plot_model5](https://user-images.githubusercontent.com/12256848/75577286-aebff580-5a2f-11ea-9115-14919c407bd3.png)
That is they no longer error out, and finally, the sherpa command:
```ui.plot_model(6, overplot=True, linestyle='dashed')```
gives:
![plot_model6](https://user-images.githubusercontent.com/12256848/75577298-b67f9a00-5a2f-11ea-9b6a-50edb2f9a8ca.png)

**Comment by DougBurke** [comment]
I've re-run the notebook on master, now that #747 has been merged, and they now behave as I expected, so I'm closing this. There's also a bunch of tests that cover this area in #764
