### ISSUE TITLE
xerr in get_bkg_plot() is not the half-width of the bin

### ISSUE THREAD

**Issue by rarcodia** [sherpa/sherpa#748]
Hello developers,

I have encountered a minor inconsistency in xerr, namely it is the half-bin width when calling get_data_plot().xerr, but it is the entire bin width when calling get_bkg_plot().xerr, although they both end up calling the same class:

https://github.com/sherpa/sherpa/blob/ca2eae9aa9c588e469c8e58e7d741199c082e7ee/sherpa/plot/__init__.py#L893

I am using sherpa 4.11.0 but I do not think this has been updated in the newest version since the code seemed the same to me and the same inconsistency is in the examples of 4.12 (https://cxc.harvard.edu/sherpa/ahelp/get_bkg_plot.html) where it is shown:

x      = [  1.0950e-02   2.1900e-02   3.6500e-02 ...,   1.4914e+01   1.4928e+01   1.4943e+01]
...
xerr   = [ 0.0073  0.0146  0.0146 ...,  0.0146  0.0146  0.0146]

where apart from the first entry, xerr is the full bin width.

Is there something obvious I am missing?

**Comment by rarcodia** [comment]
Actually, the same seems to be occurring also in get_data_plot().xerr, which makes more sense.

It can be checked doing 
(get_data_plot(data_id).x[1:]-get_data_plot(data_id).x[:-1])/get_data_plot(data_id).xerr[:-1]
and
(get_bkg_plot(data_id).x[1:]-get_bkg_plot(data_id).x[:-1])/get_bkg_plot(data_id).xerr[:-1]

They both yield arrays of values ~1 instead of ~2.

**Comment by dtnguyen2** [comment]
Thanks for the report, will take a look at it

**Comment by DougBurke** [comment]
Just to note that there could also be documentation inconsistencies here. The ahelp pages such as https://cxc.harvard.edu/sherpa/ahelp/get_bkg_plot.html have unfortunately not been kept up to date (and some of the docstrings may also be incorrect).

**Comment by rarcodia** [comment]
> Just to note that there could also be documentation inconsistencies here. The ahelp pages such as https://cxc.harvard.edu/sherpa/ahelp/get_bkg_plot.html have unfortunately not been kept up to date (and some of the docstrings may also be incorrect).

Yes agreed, also updating the docs would solve the inconsistency. Although I assume that people use xerr (e.g. to manually work out counts from rates or to rebin or whatever) assuming it is the half of the bin width without double checking, but maybe it's me.

**Comment by DougBurke** [comment]
@rarcodia - out of interest, what are you trying to do here? There may be "better" ways to get the data you need (or, we should think about providing an API that does this).

**Comment by rarcodia** [comment]
Sherpa has a more flexible way of handling the background model component w.r.t. pyXspec.

I was doing some visualization starting from spectral fits done by somebody else (spectra, model chains and background model are available) with the aim to have customizable plots with:

- source+bkg rate (with a custom rebin on the counts applied for visualization)
- bkg-only rate (same)
- model components (with uncertainty intervals)
- total source plus bkg model  (with uncertainty intervals)
- residuals (with uncertainty intervals also on the full model)

I had simply noticed that the rebinned rates were higher that the non-binned ones because I was using 2*xerr to get from rates to cts. I just thought it was useful to report this.

**Comment by DougBurke** [comment]
Thanks for the background @rarcodia - it helps us to know how Sherpa is being used ;-)

**Comment by DougBurke** [comment]
@rarcodia - apologies for the delay, but to get back to your original question

> I have encountered a minor inconsistency in xerr, namely it is the half-bin width when calling get_data_plot().xerr, but it is the entire bin width when calling get_bkg_plot().xerr, although they both end up calling the same class:

From what you've shown, the functions return the full bin width for xerr, whether it's get_data_plot or get_bkg_plot, which doesn't match the above comment. Am I just confused?

**Comment by rarcodia** [comment]
Hi @DougBurke 

I am confused too, from my second comment I am assuming there is just an inconsistency between code and doc. It is written that it's the half-width, but instead the width is computed, something like that?

I was probably debugging a rebin code and that factor 2 was floating around due to that. I guess the doc should be corrected and that's it?

Sorry if I am vague but quite some time passed and I can't find what I was actually doing :)

**Comment by DougBurke** [comment]
No bother. It looks to me like this is "just" a documentation issue (at
least short term), but maybe there's something we create that handles xerr
differently. I think it is confusing that xerr and yerr are different (I
assume) in their meaning, which isn't great.

Doug

**Comment by DougBurke** [comment]
So, with the current code we have (from a test build of CIAO using it)

```
sherpa-4.16.1+169.g45d2379c> load_pha("3c273.pi")
WARNING: systematic errors were not found in file '3c273.pi'
statistical errors were found in file '3c273.pi'
but not used; to use them, re-read with use_errors=True
read ARF file 3c273.arf
read RMF file 3c273.rmf
WARNING: systematic errors were not found in file '3c273_bg.pi'
statistical errors were found in file '3c273_bg.pi'
but not used; to use them, re-read with use_errors=True
read background file 3c273_bg.pi

sherpa-4.16.1+169.g45d2379c> get_plot_prefs("data")["linestyle"] = "solid"

sherpa-4.16.1+169.g45d2379c> get_plot_prefs("data")["marker"] = None

sherpa-4.16.1+169.g45d2379c> get_plot_prefs("bkg")["linestyle"] = "solid"

sherpa-4.16.1+169.g45d2379c> get_plot_prefs("bkg")["marker"] = None

sherpa-4.16.1+169.g45d2379c> plot("data", "bkg", xlog=True)
```

![sherpa](https://github.com/user-attachments/assets/3ead1ab8-8bc4-45f1-a191-06f45dd29e59)

```
sherpa-4.16.1+169.g45d2379c> plot("data", "bkg")
```

![sherpa](https://github.com/user-attachments/assets/1e4aa28e-4896-4948-96a2-1538e1d3d964)

```
sherpa-4.16.1+169.g45d2379c> dp = get_data_plot()

sherpa-4.16.1+169.g45d2379c> bp = get_bkg_plot()

sherpa-4.16.1+169.g45d2379c> dp.xerr[0:5]
array([0.12337   , 0.0292    , 0.0803    , 0.0511    , 0.03650001])

sherpa-4.16.1+169.g45d2379c> bp.xerr[0:5]
array([0.12337   , 0.0292    , 0.0803    , 0.0511    , 0.03650001])

sherpa-4.16.1+169.g45d2379c> dp.y[0:5]
array([0.00178657, 0.00666023, 0.00258336, 0.00380585, 0.0056834 ])

sherpa-4.16.1+169.g45d2379c> bp.y[0:5]
array([0.00021018, 0.00044402, 0.        , 0.00025372, 0.00035521])

sherpa-4.16.1+169.g45d2379c> dp.xerr[-5:]
array([0.17519999, 0.26279998, 0.33580017, 1.64980006, 2.54040003])

sherpa-4.16.1+169.g45d2379c> bp.xerr[-5:]
array([0.17519999, 0.26279998, 0.33580017, 1.64980006, 2.54040003])
```

So you can see the `xerr` is the half-width in both cases. One other change is that things like the residual/ratio/... plots also follow this, so that

```
sherpa-4.16.1+169.g45d2379c> set_source(xsphabs.gal * xspowerlaw.pl)

sherpa-4.16.1+169.g45d2379c> fit()
WARNING: data set 1 has associated backgrounds, but they have not been subtracted, nor have background models been set
Dataset               = 1
Method                = levmar
Statistic             = chi2gehrels
Initial fit statistic = 6.37289e+10
Final fit statistic   = 34.6903 at function evaluation 89
Data points           = 46
Degrees of freedom    = 43
Probability [Q-value] = 0.81276
Reduced statistic     = 0.806752
Change in statistic   = 6.37289e+10
   gal.nH         0.0158068    +/- 0.00557097  
   pl.PhoIndex    1.95437      +/- 0.0772377   
   pl.norm        0.000186062  +/- 1.35868e-05 

sherpa-4.16.1+169.g45d2379c> plot_delchi()
```

![sherpa](https://github.com/user-attachments/assets/6ddc89b7-748b-4cb1-b318-22ecc83c978c)

Unfortunately the residual plots do not have an `xerr` field (need to look at this) but have enough info to create the "xerr" field

```
sherpa-4.16.1+169.g45d2379c> rp = get_delchi_plot()

sherpa-4.16.1+169.g45d2379c> rp.xerr
AttributeError: 'DelchiPHAPlot' object has no attribute 'xerr'

sherpa-4.16.1+169.g45d2379c> dx = rp.xhi - rp.xlo

sherpa-4.16.1+169.g45d2379c> half = dx / 2

sherpa-4.16.1+169.g45d2379c> half[:5]
array([0.12337   , 0.0292    , 0.0803    , 0.0511    , 0.03650001])

sherpa-4.16.1+169.g45d2379c> half[-5:]
array([0.17519999, 0.26279998, 0.33580017, 1.64980006, 2.54040003])
```

The documentation has also hopefully been improved so I'm closing this issue, but please create a new one if eneded.
