### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#76]
Feature request: please port Sherpa to support Python 3.

I know this is a big project that will take time and resources.

But I wanted to file the issue to make it clear that this is important to us ([Gammapy](https://github.com/gammapy/gammapy), used to analyse data from [HESS](https://www.mpi-hd.mpg.de/hfm/HESS/), [CTA](https://portal.cta-observatory.org/Pages/Home.aspx) and possibly other telescopes).
Our motivation is that we want to build Gammapy on Sherpa and it's the only package in our stack that doesn't support Python 3 (see our dependency stack [here](https://indico.cern.ch/event/344485/session/142/contribution/695/attachments/1136524/1626432/gammapy-icrc2015-poster.pdf)). If Gammapy doesn't work on Python 3 it can't in good faith be put forward as a possible analysis package for new projects like CTA. E.g. the [ctapipe](https://cta-observatory.github.io/ctapipe/) package that's being proposed as the official low-level CTA processing pipeline (doesn't use Sherpa) will be Python 3 only. So getting there within the next ~ year is important to us.

I'm willing to help with this in the coming months, but when it comes to the Fortran / C extensions, my skills and familiarity with the Sherpa code base (same for the other Gammapy developers as far as I know) are probably not sufficient to make this happen.

**Comment by anetasie** [comment]
Supporting Python 3 is in the plans and the team is evaluating the required work. At this moment there is no schedule for the update.

**Comment by cdeil** [comment]
That's great to hear, thank you!
:tada:

**Comment by matteobachetti** [comment]
+1 For this

**Comment by olaurino** [comment]
We added this issue to the 4.8.2 milestone as we are targeting this version for adding Python 3 support. Some work in this sense is currently tracked in PR #229.
