### ISSUE TITLE
Cannot regrid a composite model (BinaryOpModel)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#762]
In testing out #747 I discovered that you can't regrid a composite model, at least one that's an instance of `BinaryOpModel`, as shown below.  This is not an issue with #747 as it is also true on the master branch.

Note that `(gal * pl).regrid(...)` is technically different than `gal.regrid(..) * pl.regrid(...)`, but at the moment I can't off-hand think of a case where this makes a significant difference for Sherpa (most `regrid` uses for Sherpa will be with psf- or "convolution"- style models which accept `regrid` and can be sent a `BinaryOpModel`to run on), so I'm not sure how much of an issue this is.

# Example

In the following I can regrid one, or both, of the components of the model expression (e.g. `gal` or `pl`) but not the combination:
  
```
sherpa In [12]: smdl = get_source()

sherpa In [13]: type(smdl)
Out[13]: sherpa.models.model.BinaryOpModel

sherpa In [14]: smdl.name
Out[14]: '(xsphabs.gal * xspowerlaw.pl)'

sherpa In [15]: gal.regrid([0.1, 0.2, 0.3, 0.4])
Out[15]: <RegridWrappedModel model instance 'regrid1d(xsphabs.gal)'>

sherpa In [16]: smdl.regrid([0.1, 0.2, 0.3, 0.4])
AttributeError: 'BinaryOpModel' object has no attribute 'regrid'
```

**Comment by dtnguyen2** [comment]
Just out of curiosity, what happens with simultaneous data (especially if the different data sets have very different data-space?)

**Comment by anetasie** [comment]
@dtnguyen2 the original idea was to use the highest resolution grid. I have not checked what's happening with the current setting.

**Comment by DougBurke** [comment]
My understanding is that simultaneous fits are handled by bundling all the data into a `DataSimulFit` object and the models into a `SimulFitModel` object, and then using this with a `Fit` object. So we could add logic to the *Simul* objects to identify common grids to use.

I don't think this answers @dtnguyen2's question though.
