### ISSUE TITLE
declare build dependencies in `pyproject.toml`

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#775]
In astropy/saba#33 I'm moving saba to tox. A problem I've run into there is that sherpa does not declare numpy as a build dependency in a file that setuptool_scm reads. As a consequence, tox tries to install all saba dependencies in one go (`pip install numpy sherpa ...`), which fails, because sherpa cannot be installed unless numpy is already available (https://github.com/sherpa/sherpa/blob/master/setup.py#L50). I've worked around it, but the python default way should be (https://www.python.org/dev/peps/pep-0518/) to declare dependencies in `pyproject.toml`, while sherpa still has it in `setup.py`.

*Action*: Implement PEP 518

**Comment by DougBurke** [comment]
See also #401

**Comment by hamogu** [comment]
I knew I had seen that somewhere, but I could not find it.

closed as duplicate.
