### ISSUE TITLE
Failure with spectra that have vector-valued BACKSCAL

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#797]
Sherpa cannot display fit and data that has a background model and a vector-valued BACKSCAL column.
This is relevant, because `combine_spectra ... bscale_method='counts'` is advertised in the `combine spectra` ahelp as the correct way to handle spectra where the background will be fitted, not subtracted. Thus, it would be natural to expect that sherpa can fit backgrounds spectra made this way.

In this case, sherpa cannot even do a `show_model`, mostly because the name for the model is a string expression that includes the value of the backscal parameters, which does not work if that parameters is a vector.

While fits run, the fact that I can neither show nor plot the result does not give me confidence that sherpa treats the vector-valued BACKSCAL correctly in other methods.

See script below.
The test files are generated by the lines below and are available here: [issue.tar.gz](https://github.com/sherpa/sherpa/files/4517751/issue.tar.gz)
```
combine_spectra 17764_A_grp.pi,19980_A_grp.pi 2017_A_counts bscale_method='counts' clob+
combine_spectra 17764_A_grp.pi,19980_A_grp.pi 2017_A_asca bscale_method='asca' clob+
combine_spectra 17764_A_grp.pi,19980_A_grp.pi 2017_A_time bscale_method='time' clob+
```
Here is the script and error message:
```
from sherpa.astro import ui
ui.load_data(1, 'data/Chandra/2017_A_asca_src.pi')
ui.load_bkg(1, 'data/Chandra/2017_A_asca_bkg.pi')
ui.load_data(2, 'data/Chandra/2017_A_counts_src.pi')
ui.load_bkg(2, 'data/Chandra/2017_A_counts_bkg.pi')
ui.load_data(3, 'data/Chandra/2017_A_time_src.pi')
ui.load_bkg(3, 'data/Chandra/2017_A_time_bkg.pi')
for i in [1,2,3]:
    ui.set_bkg_source(i, ui.scale1d(name='scaleB_early') * ui.xsvapec(name='Bv1_'))
    ui.set_source(i, ui.xsvapec(name='Av1_')) 
```
`show_model` works for 1 and 3 and fails for 2:
```
ui.show_model(2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-5f5362e05497> in <module>
----> 1 ui.show_model(2)

<string> in show_model(id, outfile, clobber)

~/anaconda3/envs/ciao-4.12orig/lib/python3.7/site-packages/sherpa/ui/utils.py in show_model(self, id, outfile, clobber)
    891         """
    892         txt = self._get_show_psf(id)
--> 893         txt += self._get_show_model(id)
    894         _send_to_pager(txt, outfile, clobber)
    895 

~/anaconda3/envs/ciao-4.12orig/lib/python3.7/site-packages/sherpa/ui/utils.py in _get_show_model(self, id)
    575             if id in mdl_ids:
    576                 model_str += 'Model: %s\n' % id
--> 577                 model_str += self._get_model(id).__str__() + '\n\n'
    578         return model_str
    579 

~/anaconda3/envs/ciao-4.12orig/lib/python3.7/site-packages/sherpa/ui/utils.py in _get_model(self, id)
   5585         data = self.get_data(id)
   5586         model, is_source = self._get_model_status(id)
-> 5587         return self._add_convolution_models(id, data, model, is_source)
   5588 
   5589     def _get_source(self, id=None):

~/anaconda3/envs/ciao-4.12orig/lib/python3.7/site-packages/sherpa/astro/ui/utils.py in _add_convolution_models(self, id, data, model, is_source)
   8853                     model = (model +
   8854                              sherpa.astro.background.BackgroundSumModel
-> 8855                              (data, bkg_srcs))
   8856 
   8857             pileup_model = self._pileup_models.get(self._fix_id(id))

~/anaconda3/envs/ciao-4.12orig/lib/python3.7/site-packages/sherpa/astro/background.py in __init__(self, srcdata, bkgmodels)
     31         scale_factor = self.srcdata.sum_background_data(lambda key, bkg:1)
     32         bkgnames = [model.name for model in bkgmodels.values()]
---> 33         name = '%g * (' % scale_factor + ' + '.join(bkgnames) + ')'
     34         CompositeModel.__init__(self, name, self.bkgmodels.values())
     35 

TypeError: only size-1 arrays can be converted to Python scalars
```

The same error occurs for `ui.plot_fit(1)`.

This is with 
```
# packages in environment at /Users/guenther/anaconda3/envs/ciao-4.12orig:
#
# Name                    Version                   Build  Channel
ciao                      4.12.0           py37h6440ff4_0    https://cxc.cfa.harvard.edu/conda/ciao
ciao-contrib              4.12.1                     py_0    https://cxc.cfa.harvard.edu/conda/ciao
ds9                       8.1                           1    https://cxc.cfa.harvard.edu/conda/ciao
sherpa                    4.12.0           py37h6440ff4_0    https://cxc.cfa.harvard.edu/conda/ciao

System information:
Darwin anyone 17.7.0 Darwin Kernel Version 17.7.0: Tue Feb 18 22:51:29 PST 2020; root:xnu-4570.71.73~1/RELEASE_X86_64 x86_64
```

**Comment by DougBurke** [comment]
A long time ago I started #435 but quickly ran out of steam (as it is a surprisingly tricky thing to fix given Sherpa's implementation); there may well be improvements we can make that don't solve all the problems though.

**Comment by hamogu** [comment]
And, as usual, my bug is not new, but @DougBurke has worked on it already. Note that #435 talked about grating data, while this is pure ACIS imaging data. The underlying problem (and thus the fix) seem to be same though.

**Comment by DougBurke** [comment]
Arrgh. So, we have a method to create the expression that is used to describe the full model that is used, and it'll look something like

    rmf(arf(source_model + bscale * background_model))

The issue is that the contents of `rmf(arf(...))` are evaluated on the response grid (i.e. the energy grid) and not the PI/PHA channel grid. This means that if bscale is an array then it has to match the response grid, and it's not obvious to me that we have existing functionality to do this (we have code to filter/group arrays to handle the channel grid, but gor your data here that will just filter down from 1024 channels, when the response grid has 1070 elements).

For my sanity, wondering how on earth backscale arrays can work at all: it's only an issue for cases where we want to include the background component into the model expression. If we have background subtraction then the bscale is applied to the counts (and so is the correct size).

**Comment by DougBurke** [comment]
So, if the response is linear (e.g. no jdpileup, but to be honest I don't know how jdpileup is implemented as it's done in a manner I didn't expect, so maybe it still can work) then we can rewrite

```
rmf(arf(source_model + bscale * background_model))
```

to

```
rmf(arf(source_model)) + bscale_chans * rmf(arf(background_model))
```

where `bscale_chans` is in channels (i.e. a value we can calculate). This should be workable, but isn't a really-easy change.

**Comment by DougBurke** [comment]
Note to self: the model descriptions (eg __str__) are approximations of the truth once responses or the background component come into play.

**Comment by DougBurke** [comment]
@hamogu - a question about your dataset 2, from above. The DataPHA class has a get_background_scale method that calculates the correction factor to convert the background to match the source. For datasets 1 and 3 it returns a scalar. For dataset 2 it returns a 1024 element array, but it has an odd distribution of values: 924 have the 10e-8 value and the other 100 channels have the ~0.145 value. Does this distribution make sense?

```
In [40]: set(ui.get_data(2).get_background_scale())
Out[40]: {5.6393272776031e-08, 0.14580000583200298, 0.14580000583200303}

In [41]: ui.get_data(2).get_background_scale().shape
Out[41]: (1024,)

In [44]: bscale = ui.get_data(2).get_background_scale()

In [45]: bscale[bscale < 0.1].size
Out[45]: 924

In [46]: 1024 - 924
Out[46]: 100

In [47]: np.where(bscale > 0.1)
Out[47]:
(array([  39,   43,   44,   45,   47,   48,   49,   50,   51,   52,   53,
          55,   56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
          66,   67,   68,   69,   70,   71,   72,   73,   74,   75,   76,
          77,   78,   80,   81,   82,   83,   84,   85,   86,   87,   88,
          89,   90,   92,   94,   95,   96,   97,   98,   99,  100,  101,
         102,  103,  106,  109,  110,  113,  115,  117,  118,  119,  121,
         122,  124,  125,  126,  128,  129,  131,  132,  133,  135,  141,
         144,  145,  150,  165,  169,  172,  173,  214,  215,  241,  244,
         246,  248,  294,  313,  452,  460,  467,  679,  844,  895,  988,
        1012]),)
```

**Comment by hamogu** [comment]
The `combine_spectra` is from https://github.com/cxcsds/ciao-contrib/blob/ed83f481ce1ea2addc5caa4a323cc071dc611f9b/bin/combine_spectra

I did not check the source code of that script - and you might be more familiar with it than I am anyway. My guess is that the 1e-8 is for channels where the background has no counts, thus the scaling does not matter, but you don't what to set to 0 to avoid "divide by zero" errors? That guess is based on the fact that the number of counts is not big, but I did not actually check the spectra and see. Would you like me to send you the input spectra or the CIAO scripts I use to generate the spectra from the evt2 files?

**Comment by DougBurke** [comment]
I think I know where the 1e-8 values are coming from: each time a scale value (e.g. correct by the BACKSCAL array) is applied it goes through a helper function (the DataPHA ._check_scale routine) which has a "safety" feature where any value <= 0 is replaced by 1. For your background data 924 bins are 0. This then gets replaced by a 1 ,and then divided/multiplied by correction factors.

I don't understand the logic for this replacement (ie why is it done, but I can imagine it's to avoid division by zero), which makes this potentially tricky to work with. Oh well, I wasn't doing anything tonight anyway ...

**Comment by hamogu** [comment]
I never claimed it would be easy...
I wonder if this should be worked into the dataspace/evalspace concept as I suggested here: 
https://github.com/sherpa/sherpa/pull/435#issuecomment-618082781

We would then have a dataspace of:

- independent array
- a filter
- a grouping
- data that is either a number or an array and (if it's an array) is subject to grouping and filtering:
  - the dependent data
  - the stat err
  - the systemtic err
  - the backscal
  - the areascal
  - other things that come up in the future

Each of the later would have an associated function that says how values within a grup are aggregated, e.g.:

- PHAdata, sum
- syserr, mean
- backscal, mean weighted by photons (some something).

That's beyond this PR though. Thoughts?

**Comment by DougBurke** [comment]
I don't have the time to look into https://github.com/sherpa/sherpa/pull/435#issuecomment-618082781 just now to know whether it would improve things or not. My concerns are that the existing code has acreted functionality over time, and it's sometimes hard to know how it all hangs together.

**Comment by DougBurke** [comment]
@hamogu - for your dataset

```
b2 = ui.get_bkg(2)
```

then we have

```
In [51]: b2.counts[b2.counts > 0]
Out[51]:
array([3., 2., 1., 1., 1., 2., 1., 1., 3., 2., 2., 2., 1., 1., 1., 2., 2.,
       2., 4., 3., 1., 7., 2., 2., 6., 3., 2., 6., 1., 1., 3., 4., 2., 1.,
       2., 1., 1., 4., 3., 2., 4., 2., 3., 2., 1., 1., 2., 1., 2., 1., 2.,
       1., 4., 2., 1., 1., 3., 1., 1., 1., 2., 3., 1., 1., 1., 3., 1., 1.,
       2., 1., 1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 1., 1., 1., 1., 1.,
       1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]: b2.backscal[b2.counts > 0]
Out[52]:
array([3.8678512e-07, 3.8678512e-07, 3.8678512e-07, 3.8678512e-07,
       3.8678512e-07, 3.8678512e-07, 3.8678512e-07, 3.8678512e-07,
...
```

So, where there are any counts in the background we get a value if ~1e-7, and then all bins with 0 in them have a value of 1

```
In [54]: set(b2.backscal[b2.counts == 0])
Out[54]: {1.0}
```

I guess the point is that the 0-count bins are not going to contribute to the data, so it doesn't matter what the scaling in (when physically subtracting the background signal from the data).

Unfortunately when trying to *fit* a model to the background we need to decide what to do for all channels, not just those with counts. I'm struggling to see what to do here (this is a general issue - ie how to handle channels where we can't calculate a scaling) rather than anything specific to the sherpa code.

**Comment by hamogu** [comment]
Sounds like a question for @anetasie  (see last paragraph of @DougBurke comments above).

**Comment by anetasie** [comment]
There should be no scaling in fitting the background model to the background data. The backscale is relevant in accounting in the background model contribution to the total model when calculating the statistics, so having 0 counts in a background bin should not be a problem.

**Comment by DougBurke** [comment]
@anetasie - this is not about fitting the background model to the background data. It's how to scale the background model by an array with ill-defined values in it to match the source region.
