### ISSUE TITLE
staterrors in PHA files with RATE column

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#800]
Some PHA spectra have `RATE` column instead of `COUNTS`. This is allowed by the FITS OGIP standard. Sherpa reads the 'RATE column' and converts the rates per channel to counts per channel. However, by default the `STAT_ERR` is not used and the statistical weights are computed within `fit()` by the selected statistics. For background subtracted data, such as for example in Swift BAT spectra, the calculated errors from rates will not be correct, as this calculation will be performed on the counts (calculated from rates) and the contribution to the error from the background counts will be ignored. There is no background spectrum, or background array available to account for the errors. The `STAT_ERROR` column is present in the PHA file and these errors  should be used. One can read the error using `use_errors` option in `load_pha`, which inputs the error array, but then these input errors are used incorrectly because the exposure factor is being ignored. 

```
load_pha('bat_index_862.pha')
load_pha('bat_index_862.pha', use_errors=True)
set_model(powlaw1d.p1)                                           
fit()
print(get_data().staterror)
print(get_data().counts)
```

The fit returns a huge value of the statistics indicating that the sqrt is taken from the supplied error which is read as 'RATE', so the exposure factor has been ignored.

```
Dataset               = 1
Method                = levmar
Statistic             = chi2
Initial fit statistic = 3.41608e+26
Final fit statistic   = 8.86361e+16 at function evaluation 53
Data points           = 8
Degrees of freedom    = 6
Probability [Q-value] = 0
Reduced statistic     = 1.47727e+16
Change in statistic   = 3.41608e+26
   p1.gamma       2.19094      +/- 3.92428e-09 
   p1.ampl        0.00256067   +/- 3.43976e-11 
```

```
print(get_data().staterror)                                             
[1.5736572e-06 9.5879363e-07 1.2671527e-06 1.0345638e-06 1.0883365e-06
 7.4098654e-07 7.5431592e-07 4.8542256e-07]

print(get_data().counts) 
[631.63786804 187.89412226 254.27311475 168.07048241 150.80228231
 237.09933564  67.56084161 -10.02169898]
```
The workaround exist and one can correct the error array:

```
sherpa In [11]: er=get_data().staterror*get_exposure()                                                  
sherpa In [12]: er                                                                    
Out[12]: 
array([291.8991634 , 177.84754024, 235.04535511, 191.90221112,
       201.87656716, 137.44629504, 139.91877508,  90.04149099])

sherpa In [14]: get_data().staterror=er                                               
sherpa In [15]: get_data().staterror                                                  
Out[15]: 
array([291.8991634 , 177.84754024, 235.04535511, 191.90221112,
       201.87656716, 137.44629504, 139.91877508,  90.04149099])
```

The question is if for the `load_pha()` option with `use_errors=TRUE` Sherpa should check the header HDUCLAS KEYWORD  for RATE instead of COUNT and in case RATE convert the STAT_ERR in the same way as the RATE to COUNT per channel, so the units of the data and the error match. 
Sherpa should do that to be consistent with the OGIP standards.

The data and response file is in 
`/data/sherpa/TestIssues/BAT`

**Comment by hamogu** [comment]
I've just run into the same thing last night with simulated IXPE data and I can confirm your diagnosis of the problem. (Of course, I could have saved a lot of time if I had seen this issue earlier).

I've started on a PR to fix (most of) this issue. There is (as always) a subtlety here: OGIP *recommends* a rate unit of counts/s, but other units are technically possible (e.g. counts/ks or counts/week). In that case, scaling with the exposure time in seconds won't get you an integer number of counts, but at least we can scale rate and STAT_ERR consistently.
