### ISSUE TITLE
Plot attributes

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#808]
A user asked whether there is an equivalent of `set_current_plot()` function in 4.12 version with `matplotlib` plotting. This allowed for modification of the multiple plots obtained with `plot_fit_resid()` for example. In this specific question the user wanted to change the title from the standard generated title by `plot_fit_results()` to their favorite one. `plt.title('my plot')` places the title in the middle of the plot, so above the lower subplot. I'm wondering if there is a way to modify the title without regenerating the plots.

Is it possible to have `set_current_plot` - type function in `Sherpa` now,  with no `chips`

**Comment by DougBurke** [comment]
I strongly believe that we rely on matplotlib functions with the malplotlib
backend. It has a different way of working to chips. We should not be
adding chios-lije functionality .

I don't have the energy to explain at the moment, but there are ways to
change the title or axis labels in each of the plots in a multi-plot
display.  You can read any plot example, not just Sherpa.

**Comment by anetasie** [comment]
@DougBurke Yes, I agree. We should not add this type of functionality.

I had an email exchange on sherpadev with @hamogu yesterday. Here is a copy of that exchange for the record:

@hamogu email:

> matplotlib has a set_current_plot-type functionality, called plt.sca(ax) (sca stand for "set current axes", which is pretty close to the old chips command in wording).
> 
> Now, how do you get the `ax` object that you need to pass into the plt.sca(ax) function? matplotlib has plt.gcf().axes (gcf for "get current figure" and "axes" is a list of all axes objects in that figure). I've forgotten how the chips command for listing all axes in the current plot was called, but conceptually, it's the same.
> 
> So the script would be:
> 
> ax = plt.gcf().axes[0]  # The user probably needs the first axis with index 0
> 
> plt.sca(ax)
> 
> plt.title('my plot')
> 
> Note that at this point it might be easier to operate directly on the axis object instead of going through the functional interface:
> 
> ax = plt.gcf().axes[0]
> 
> ax.set_title('my plot')
> 
> Do we need a set_current_plot - type function in Sherpa? My personal opinion is "not currently". As long as we only have one backand and no immidiate plans to add a second one (I know Doug would like an Altair backend, but I don't think that is high enough on the priority list to happen any time soon) I think it's a waste of time to write functions for all sorts of different plot modifications. At some point, users have to drop down and use the backend directly, just like that had to drop down an use chips commands to e.g. move the position of the axes labels. Specifically, in this case plt.title is already a matplotlib command, so I don't see any problem in telling the user to use plt.sca .
> Once (If?) we have multiple backends, we can see if set_current_plot makes it onto the list of functions that we need to provide backend-agnostic.
> 

my response:

> I  was looking at the Sherpa thread https://cxc.harvard.edu/sherpa4.12/threads/setplot_manual/index.html#multi_plot_faq
> Figure 10 shows two panels with modification examples using plt.gcf()
> so I was playing with matplotlib  options. I agree, we don't need a separate function 'set_current_plot'  if we can update the plots using the existing methods. 
> Updating the current threads with additional modification would be better in terms of helping users and showing them the matplotlib way of plotting. 
> 
> This worked for in my case:
> 
> ax1, ax2 = plt.gcf().axes
> ax1.set_title('my plot top')

**Comment by DougBurke** [comment]
I am going to close this since I don't think it's part of Sherpa - we do have the just-added https://cxc.cfa.harvard.edu/ciao/visualization/chips/#changing-plots section.

It can be re-opened if someone has a suggestion for what could be added to Sherpa.
