### ISSUE TITLE
sherpa-test-data empty

### ISSUE THREAD

**Issue by anetasie** [sherpa/sherpa#819]
My git repository shows `empty sherpa-test-data` directory. It is git submodule which I'm not able to clone. It always remains empty. How can I clone into my local 'sherpa' repository?

here is the command history 

```
   464	18:00	git clone https://github.com/sherpa/sherpa.git
   465	18:00	cd sherpa
   467	18:00	more sherpa-test-data
   469	18:00	git submodule update
   470	18:01	ls sherpa-test-data
   471	18:05	pwd
```

The submodule is not updated and the directory remains empty.

**Comment by hamogu** [comment]
That is default git behavior. Submodules are only cloned if you explicitly ask for it.
Use `git clone https://github.com/sherpa/sherpa.git --recursive`
or, in your case where you cloned it already, use `git submodule update --init` inside the normal sherpa module to populate the submudule.

See https://git-scm.com/book/en/v2/Git-Tools-Submodules (section "Cloning a Project with Submodules")

**Comment by anetasie** [comment]
@hamogu Thanks. I was able to get the submodule etc
