### ISSUE TITLE
variable backscale as model parameter

### ISSUE THREAD

**Issue by rhuang-astro** [sherpa/sherpa#824]
Hi ,

I want to fit a spectrum with background.
But I want the backscale to be variable parameter, which is close to 0.81.
I know it's not a standard way. but I have such requirement for my work.

The statistics should be:

chi = (data-b*back-model)/sqrt(data_err^2+ (b * back_err)^2 )

For code, chi can be set as 
    chi = (data-my_model)/sqrt(data_err^2+ (my_model_err)^2 )
    my_model = b*back-model
    my_model_err = b*back_err

```python
rsp = ui.get_response(1)
src_model = rsp(mymodel)
ui.set_full_model(1,src_model + b*back)  # b can be the parameter of user defined model, just constant.
```
But I don't know whether can I set error of model?  

If not, load_user_stat can help?

I notice that the [manual of load_user_stat](https://cxc.cfa.harvard.edu/sherpa/ahelp/load_user_stat.html) give following example:
load_user_stat(statname, calc_stat_func, calc_err_func=None, priors={})
def calc_stat_func(data, model, staterror=None, syserror=None, weight=None, **bkg**=None):
def calc_err_func(data)

Maybe I can insert the error of background/model to here?

**Comment by hamogu** [comment]
Yes, it does. 
Thanks for keeping on, if I understand you correctly, you do **not** want to model the background, but just subtract it with a scale factor that you pick yourself (instead of just scaling by area)?

I'm sure there is a way in sherpa to do it, but if you only need this one, it's probably the easiest to just "cheat" and modify the fits file. I think you could just modify the "BACKSCAL" keyword in either source or header, e.g. multiply the "BACKSCAL" in the background spectrum by 0.81 using dmhedit or ftools or astropy or some other method. Then, you read the modified file into Sherpa and Sherpa would just use that value to scale the background counts, so you can simply "ui.subtract". A word of caution though: I don't fully understand your science case, so I don't know if this methods will do what you want. If you have both instrumental (Gaussian lines) and astrophysical background in your background spectrum, then this method will scale both with the same factor, which might not be correct.

**Comment by rhuang-astro** [comment]
Yes, I can set BACKSCAL inside/outside sherpa.
```python
ui.set_backscal(1,0.81741198)
ui.subtract()
ui.set_source(1,xpo)
ui.fit(1)
```
I already mentioned this way before.
I can fit with scale first like you do, then get the scale as backscale to subtract background.
The reducechi  is really much better than the first one.  
Th only drawback here is that I can't check the covariance bewteen backscale and other model parameter which can help me to discuss how backscale affect the fiiting result. 

You are right about the concern of instrumental (Gaussian lines) and astrophysical background.
In my case, just particle background plus instrumental lines.

**Comment by hamogu** [comment]
I'm unclear if you want to fit the background or not. If you fit it, then it's not subtracted, but is included in the source model. On the plus side, you get the covariance. But then you also say that that scale cannot be a model component, it has to be the backscale, which implies that you want to subtract the background. Conceptually, I don't understand how that could work. Either you fit the background or you subtract it but not both, or am I missing something?

It seems that you say that your background model does not describe the background features very well (because of the instrumental Gaussians) and thus the redchi^2 is higher, but you would like the lower redchi^2 value? 

I don't think you can have both. If you want the covariance, you will have to fit the background. That means improving your background model (add more Gaussians e.g. at fixed locations if you know what instrumental features exist) or simply accepting a larger number for redchi^2. That larger number does not mean that your source model is good or bad by itself. You could have a perfect source model, but still a larger chi^2 if the background model is not as good, but that does not prevent you from getting astrophysical information from fitting the source. 

In some sense, your redchi^=0.9 for subtracting the background is a little "cheated". If you rely on the background model to determine how it's subtracted, then it should be included in the fit. On the other hand, simply subtracting the background is similar to assuming that the measured background has zero uncertainty. In that case, you don't need a model and no covariance (since the background has no errors, there is no covariance).

Or maybe I'm still not understanding what you actually want sherpa to do?

Of course, you can also go back to your first suggestion and make a custom statistic or a custom error function in any way you like. Since these can be arbitrary functions, you can put anything you like in there, but you would of course have to know how you want to treat the background. Is it perfect (=can be subtracted) or should it be fitted? I'm not a statistician, but I would not know how to define a custom statistic for your case.

**Comment by rhuang-astro** [comment]
Thank you!

Yes, I understand it's an unusual requirement.

I have source and background, which actually observed with the same detector but different time and direction. (background is the observation from space to earth).

I think there are two typical way.
1. as you said: not subtracted, included in the source model
       source and background both need model, it can be separately, but share some links.
      or  include background model in source model.  

2. set the backscale, subtract the background
    only "source"  model is required now, the "source" here is the background subtracted source.


What I want is still different from the first one.
I want to include background **data**  instead of background **model** in source model.
        chi = (data-b*back-model)/sqrt(data_err^2+ (b * back_err)^2 )

now the "new model"(b*back-model) here is not only  folded spectrum, it is folded spectrum plus scaled background data. (the scale is also free parameter).

I can translate  "(data-b*back-model)"  to code with:
```python
rsp = ui.get_response(1)
src_model = rsp(mymodel)
ui.set_full_model(1,src_model + b*back) 
```
But I faild to find a way to transfer the back_err inside.
The chi stat  is  (data-model)/data_error, after  ui.set_full_model(1,src_model + b*back)  , it is  (data-b*back-model)/data_error, not    (data-b*back-model)/sqrt(data_err^2+ (b * back_err)^2 ).

I wrote an experimental spectrum fitting script based on emcee in the past.
So I can realize such weird stat, and give comfortable distribution.
But It's painful for me that I have to write all code to read the compressed response(I'not confident in this part), write necessary model and the fold the model .... 
The work is too much for me if I try to add more features (like read grppha flagged pha). 
I feel very satisfied  after I try sherpa several week ago. 
So I want to rerealize such requirement in sherpa.

> your redchi^=0.9 for subtracting the background is a little "cheated"
I shorten the energy range to check will it improve the redchi^2.  I will set to full in future.

> simply subtracting the background is similar to assuming that the measured background has zero uncertainty.
I don't think so, such subtraction is conducted within sherpa(or xspec), I didn't check the detail, but I think the error of background should be recalculated with new_error^2 = data_error^2+(backscale*back_error)^2 for the simplest case.

**Comment by hamogu** [comment]
I think I understand now. Sorry, I'm not a core sherpa developer (although I do work on other Chandra stuff), I'm just trying to help out. I don't think there is an out-of-the-box way to do that (as you say, it's unusual), but I think I have an idea that's only ~10 lines of code or so. I'll see if I can make that work, and let you know what I find, but it might take me a day or two.

> I don't think so, such subtraction is conducted within sherpa(or xspec), I didn't check the detail, but I think the error of background should be recalculated with new_error^2 = data_error^2+(backscale*back_error)^2 for the simplest case.

You are correct that code is around this line: https://github.com/sherpa/sherpa/blob/d944601c1f92bfd45f183ee93ca6729ddb4dc01d/sherpa/astro/data.py#L1931

**Comment by rhuang-astro** [comment]
It's great, you are so nice!

I tried, but failed. 
There is so few example of load_user_stat.

Thank you again!

**Comment by hamogu** [comment]
Ok, I'll sketch the basic idea below. It does partially work as written, meaning I could make it run with no exception on unbinned, unfiltered data. It fails as soon as I bin data though. The binning and filtering is a mess and I don't fully understand how that's handled internally, so I punt on that for now. Please see if this works for you or at least helps you with the next step. Another caveat: I'm not sure it is correct, i.e. I don't know if it does what I think it does. You might want to insert a few print statements into the code to see if the intermediate results make sense for you. I don't have a dataset where I know what he answer should be which makes it harder to see if this code is right, is mostly here (e.g. I just forgot a sqrt somewhere) or if it's total garbage.

Ok, the basic idea is this: For "load_user_stat" you pass in two Python functions (calc_stat_func and calc_err_func). The parameter with which those functions are called do not include the information that you want. However, in Python, everything (with few exceptions) is an object, that means that those functions are Python objects, too. Objects can have additional attributes. This is a little advanced Python and I don't know of you are a Python beginner or expert, so just cone simple example (google for "python __call__ object" for more on this) of a Python object that behaves like a function that adds tow number and adds 4 to the result:
```
class LikeAFunction():
    constant = 4
    def __call__(self, a, b):
        return a+ b + self.constant

myfunc = LikeAFunction()
myfunc(1,2)
>>> 7
```
So, we will make an object that has a reference to the data, background and the scale. That way, we can use the data, model and scale when we calculate the statistic, *even if they are not passed in*.
```
rsp = ui.get_response(1)
bkg_rsp = ui.get_response(bkg_id=1)
bkg_scale = ui.get_bkg_scale(1)

bkg_model = bkg_rsp(poly)
src_model = rsp(xpo)

ui.set_bkg_full_model(1, bkg_model)
ui.set_full_model(1, src_model + con * bkg_scale * bkg_model)

import numpy as np

# here we define that object in general
class MyErrFunc():
    def __init__(self, data, bkg, bkgscale):
        self.data = data
        self.bkg = bkg
        self.bkgscale = bkgscale
        
    def __call__(self, data):
        # Assuming the data error is sqrt(count number)
        dataerr = np.sqrt(self.data.get_dep(filter=True))
        b = self.bkgscale.c0.val
        back_err = np.sqrt(self.bkg.get_dep(filter=True))
        return np.sqrt(dataerr**2 + (b * back_err)**2)

# here we make a specific instance of the object and pass in our data, bgk and scale
# This now looks and behaves like a function
myerrfunc = MyErrFunc(ui.get_data(1), ui.get_bkg(1), con)

# Simple Chi^2 statistic with your model trick and my staterror trick
def mystat(data, model, staterror, syserror=None, weight=None, bkg=None):
    fvec = (data - model) / staterror
    stat = (fvec**2).sum()
    return (stat, fvec)

myerrfunc = MyErrFunc(ui.get_data(1), ui.get_bkg(1), con)

ui.load_user_stat("mystat", mystat, myerrfunc)
ui.set_stat(mystat)

ui.fit(1)
```

OK, this is as far as I'll go for now. As I said, it's not complete (e.g. if you bin up the data the number of channels in the reposne and the number of channels in the data does not match any longer), but it's a start. Let me know what you think and please @anetasie chime in if you have any easier solutions.

**Comment by rhuang-astro** [comment]
Yeah, pretty cool.
This solved the problem that myerrfunc(data) can only accept data.

Another difficulty should be binned, filtered data, I printed input "data" within my defined "mystat", it turned out to be unfamiliar compared to original one. 
I will also try to figure the process how sherpa bin and filter data.
If I can get that data, I think it will work!

Suddenly, I come up that I can access bined and filtered data and error  from get_fit_plot or other get*plot. I will have a try.

**Comment by rhuang-astro** [comment]
It worked!!!

```python 
ui.clean()
ui.load_pha(1,'LE_ELVp10-grp.pha',use_errors=True)
ui.load_pha(2,'LE_ELVn6-grp.pha',use_errors=True)
ui.ignore_id(1,":3, 9.8:",1)
ui.ignore_id(2,":3, 9.8:",1)

data = ui.get_data(1).get_dep(filter=True)
data_err = ui.get_error(id=1,filter=True)
bkg = ui.get_data(2).get_dep(filter=True)
bkg_err = ui.get_error(id=2,filter=True)

backscale = ui.get_exposure(1)/ui.get_exposure(2)

ui.clean()
ui.load_pha(1,'LE_ELVp10-grp-no_back.pha',use_errors=True)
ui.ignore_id(1,":3, 9.8:",1)

def const(pars,xlo,xhi):
    return pars
ui.load_user_model(const, "con")
ui.add_user_pars("con", ["a"],[0.81], parfrozen=[False])
con.a = 0.81 * backscale

# def const(pars,xlo,xhi):

ui.create_model_component("xspowerlaw", "xpo")
xpo.PhoIndex = 1.41431
xpo.norm = 10.
FoV = ((1.6*np.mean([5.824,5.868,5.856]))/np.square(180/np.pi))
ui.set_source(1,FoV*xpo*con/con)

print(data.shape)
print(data_err.shape)
print(bkg.shape)
print(bkg_err.shape)

class MyErrFunc():
    def __init__(self, data_err, bkg_err, bkgscale):
        self.data_err = data_err
        self.bkg_err = bkg_err
        self.bkgscale = bkgscale
        
    def __call__(self, data):
#         print('MyErrFunc is called')
#         print('bkgscale:',self.bkgscale.a.val)
#         print('MyErr:',np.hypot(self.data_err,self.bkgscale.a.val*self.bkg_err)[:10])
        return np.hypot(self.data_err,self.bkgscale.a.val*self.bkg_err)

myerrfunc = MyErrFunc(data_err, back_err, con)
class MyStatFunc():
    def __init__(self, data, bkg, bkgscale):
        self.data = data
        self.bkg = bkg
        self.bkgscale = bkgscale
        
    def __call__(self, data, model, staterror, syserror=None, weight=None, bkg=None):
#         if staterror is not None:
#             print('staterror is here')
#             print(staterror[:10])
#             print('sqrt(data) is here')
#             print(np.sqrt(data)[:10])
#         if syserror is not None:
#             print('syserror is here')
#             print(syserror[:10])
#         if bkg is not None:
#             print('bkg is here')
#         print('bkgscale:',self.bkgscale.a.val)
#         print('data:',data[:10])
#         print('model:',model[:10])
#         print('bkg:',self.bkg[:10])
#         print('scaled bkg:',self.bkgscale.a.val*self.bkg[:10])
        fvec = (data -self.bkgscale.a.val*self.bkg - model)/staterror
        stat = (fvec**2).sum()
        return (stat, fvec)
        
mystatfunc = MyStatFunc(data, bkg, con)
ui.load_user_stat("mystat", mystatfunc, myerrfunc)
ui.set_stat(mystat)
ui.fit(1)

ui.set_stat("chi2datavar") #chi2constvar #chi2xspecvar chi2datavar
ui.plot_fit(1)
fplot = ui.get_fit_plot(1)
model_x = fplot.modelplot.x
model_y = fplot.modelplot.y
scale = con.a.val/backscale
plt.show()
```
![image](https://user-images.githubusercontent.com/46291749/84346241-8347bd80-ab7d-11ea-84b1-555a3717214e.png)

```python 
# ui.clean()
ui.load_pha(1,'LE_ELVp10-grp.pha',use_errors=True)
ui.load_pha(2,'LE_ELVn6-grp.pha',use_errors=True)
ui.ignore_id(1,":3, 9.8:",1)
ui.ignore_id(2,":3, 9.8:",1)

fplot = ui.get_data_plot(1)
print(fplot.y.shape)
print(fplot.yerr.shape)
x = fplot.x
x_err = fplot.xerr
data = fplot.y 
data_err = fplot.yerr 

fplot = ui.get_data_plot(2)
print(fplot.y.shape)
print(fplot.yerr.shape)
back = fplot.y 
back_err = fplot.yerr 

backscale = ui.get_exposure(1)/ui.get_exposure(2)
plt.figure(figsize=(5,5))
ui.plot_fit_delchi(1)
plt.cla()
fig = plt.gcf()
ax1,ax2 = fig.axes
plt.sca(ax1)
ui.plot_data(2,overplot=True)
back_err.shape
plt.errorbar(x=x,y=data-scale*back,xerr=x_err/2,yerr=np.hypot(data_err,scale*back_err),linestyle='')
plt.plot(model_x,model_y)
plt.legend(loc=0,labels=['model','','source','back','source-scale*back'])

plt.sca(ax2)
plt.errorbar(x=x,y=(data-scale*back-model_y)/np.hypot(data_err,scale*back_err),xerr=xerr/2,yerr=np.hypot(data_err,scale*back_err)/np.hypot(data_err,scale*back_err),linestyle='')
plt.hlines(0,2,10)
plt.ylabel('Sigma')
plt.xlabel('Ebergy (keV)')

degree_freedom = 72
print('reducechi2:',np.sum(np.square((data-scale*back-model_y)/np.hypot(data_err,scale*back_err)))/degree_freedom)
```
![image](https://user-images.githubusercontent.com/46291749/84347391-6d87c780-ab80-11ea-8f4c-d33a5daf4660.png)

reducechi2: 1.067

**Comment by hamogu** [comment]
Great! Maybe we should have a page "unusual Sherpa solutions for unusual problems somewhere" ;-)

**Comment by rhuang-astro** [comment]
haha Thanks!
I am also interested in how to take mcmc into this scenario.
I will update and close this issue after I finished it.

**Comment by anetasie** [comment]
I missed the entire conversation! Great that you have a way to fit the data and the background. Good idea for a web page @hamogu.

**Comment by rhuang-astro** [comment]
I failed to try mcmc.
```python 
> ui.get_draws()

ValueError: Fit statistic must be cash, cstat or wstat, not mystat
```
Maybe it's impossible in this scenario.


This figure is created by my fitting script.
It is what I initially expected with sherpa.
![image](https://user-images.githubusercontent.com/46291749/84447258-868e8800-ac15-11ea-946a-ea8e8748ac27.png)

**Comment by anetasie** [comment]
Thanks. Yes, the current implementation of mcmc in Sherpa is specific to the Poisson likelihood and will not work with other statistics.

**Comment by rhuang-astro** [comment]
Thank you for your help!
