### ISSUE TITLE
datastack: show_stack should show grating and order for grating data

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#834]
If I load grating data, I currently get datastacks that look all the same, because show_stack currently only prints OBSID and MJD_OBS from the metadata and the filename, which, in the case of a pha2 files is the same for all orders. Adding the TG_PART and TG_M to the printout would be very useful.

**Comment by DougBurke** [comment]
I'm conflicted on this one. Yes we need more useful metadata, but how do we make it generic (e.g. XMM orders?).

**Comment by hamogu** [comment]
I suggest a list of keywords, and the first 5 that exist, are not empty, and are not identical for the entire datastack get displayed. We could have a header line that lists the first 3 keywords that are identical between all spectra in the datastack. This is for convenience, al the keywords are there for user inspection if they are displayed here or not. 
Suggested list: TELESCOP, OBSID, EXPOSURE, TARGET, INSTRUME, TG_PART, TG_M, (XMM gratings), then other stuff we can think off.

**Comment by hamogu** [comment]
I'm extending datastack for a specific project. That project it not general enough to be of much use for Sherpa right now,  but I did write a `_repr_html_` for that. I don't have time to turn into into a PR right now, but since it's realted to this issue, I'll just dump the code here so that I find it again when I'm addressing this issue.

```
    def show_stack(self):
        """Display basic information about the contents of the data stack.
        A brief summary of each data set in the stack is printed to the
        standard output channel. The information displayed depends on the
        type of each data set.
        """
        cols, vallist = self._stack_repr_list()
        print(('{:<8} ' * len(l)).format(*cols))
        for l in vallist:
            print(('{:<8} ' * len(l)).format(*l))
            
    def _stack_repr_list(self):
        cols = ['id', 'name', 'OBJECT', 'OBS_ID', 'TELESCOP', 'INSTRUME', 'LIVETIME', 'MJD-OBS', 'XFLT0001']
        vallist = []
        for dataset in self.filter_datasets():
            values = [dataset['id'], dataset['data'].name]
            hdr = dataset['data'].header if hasattr(dataset['data'], 'header') else {}
            for k in cols[2:]:
                values.append(hdr.get(k, 'N/A'))
            vallist.append(values)
        return cols, vallist
    
    def _repr_html_(self):
        cols, vallist = self._stack_repr_list()
        out = '<table style="width:100%">'
        out = out + '<tr>' + ('<th>{}</th>' * len(cols)).format(*cols) + '</tr>'
        for l in vallist:
            out = out + '<tr>' + ('<td>{}</td>' * len(l)).format(*l) + '</tr>'
        out = out + '</table>'
        return out
```

**Comment by DougBurke** [comment]
Is this issue fixed now with your recent changes, @hamogu?
