### ISSUE TITLE
Grouping and datasets: Idea

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#838]
There are several issues related to grouping and filtering, but this question does not seem to fit to any particular one of them, so I'll just open it as a new issue.

Why is there a grouped flag for datatsets at all? Why not just use the grouping all the time and set it to use every bin initially? That would make the code a lot less complex by removing a lot of if grouped ... else ..., I guess there is a performance penalty, but is it severe enough to justify that added code complexity?

**Comment by hamogu** [comment]
@DougBurke : Thoughts?

**Comment by anetasie** [comment]
In the current implementation grouping is specific to counts data and it is based on the GROUP column defined in OGIP standards for PHA files. If there is no GROUP column in a PHA file all the channels are noticed and not grouped.  If the GROUP column is supplied with the data this column is used by default, so the grouping flag is set. You can overwrite this grouping using `group` functions. So, to answer the question - the grouping flag is supplied (or not) with a PHA file and Sherpa already uses all the bins if there is no initially supplied GROUP flags.

**Comment by hamogu** [comment]
This is more a question of implementation. We have a group array and the grouping flag than can be True/False. If the flag is True, then the grouping array is used (as far as I understand it), if it is False, then the grouping array is not used (and all data is fitted). Why do we need both? `ungroup` could just set the grouping array to all `1` ( = every bin is the start of a new group = no binning) which is equivalent to the current flag=False.

(Note that I may have misunderstood the implementation.)

**Comment by hamogu** [comment]
It's to make it easy to toggle on/off grouping for e.g. plots and, as explained to me by @DougBurke and @anetasie, really makes sense.
