### ISSUE TITLE
parameter sampling, soft and hard limits, and the sample*flux functions

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#846]
So, `sample_energy_flux` creates `num` realizations of the free-parameter distribution (e.g. if the model has nh, gamma, and ampl free then you get a num by 3 array of numbers) which is used to calculate the flux distribution. Since the numbers are generated using a normal distribution (either with correlated parameters or not) then you can end up with parameter values outside the hard-limit range (often seen with the nh parameter), so the code goes through and makes sure the parameters are clipped to the hard limits (that is, values outside the hard-limit range get replaced with values at the hard limit).

The `sample_flux` function currently post-processes this array to remove any flux values with parameters outside the soft-limit range (internally `sample_flux` calls `sample_energy_flux` to do most of the work). Unfortunately there are issues with how this is done (e.g. #751).

I suggest that add an option to `sample_energy_flux` that lets you chose whether to clip the parameters by the soft or hard limit (this would leave in those rows where values are outside the limits but replaces the problem value with the limit). This would then avoid the problem in #751 (and avoids `sample_flux` doing excess work).

One question is that I have left the bins in (since they provide some information related to upper limits, e.g. #457). However, maybe you would want to remove the clipped bins. One thought I have is to add an extra column indicating whether the row was "okay" or "clipped"  (e.g. 1 or 0) so users could filter out the clipped values if they wanted.

**Comment by DougBurke** [comment]
My thought is that we add a parameter to control the behavior - e.g. values like "none", "soft", "hard" to say no restriction, soft, or hard limits. When a parameter value lies outside the range it is clamped to that value **and** we add a column to the output which indicates if any parameter in that iteration had to be clamped. This would let users post-process to remove clamped rows, but keep in by default to support upper limits (e.g. #457).

This would be added to `sample_energy_flux`, `sample_photon_flux`, and `sample_flux`. There may be other functions that do similar things, but that should be decided on a case-by-case basis (e.g. `resample_data`).

**Comment by anetasie** [comment]
@DougBurke that sounds good and allows the flexibility that user may want to have.

**Comment by DougBurke** [comment]
#866 is my first look at this. It is built on top of #803 which I'm waiting to get reviewed. With it you can say

```
v1 = sample_energy_flux(0.5, 7, num=10000)
v2 = sample_energyflux(0.5, 7, num=10000, clip='soft')
```

which uses the hard-limits (default) for v1 and soft limits for v2. The return array now has Nfree+2 rows (Nfree is the number of free parameters): flux, par1, ..., parNfree, clipped where clipped is 1 if the row was clipped and 0 otherwise. If we had used a structured array it would be a nicer interface (e.g. column name and keep a boolean datatype) but I don't think it's worth the change (and really it should be a higher-level object than a structured array, but that would require extra dependencies eg panda or xarray or ...)
