### ISSUE TITLE
Importing sherpa.astro.ui generates deprecation warnings in IPython 4.0.0

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#85]
If you are using the master branch, and have IPython 4.0.0 and astropy 1.0.4 installed, then you will see this message on importing `sherpa.astro.ui`:

```
% ipython
Python 2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sherpa.astro import ui
/home/user/local/anaconda/envs/sherpa/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

```

This comes from astropy, not sherpa. It looks to have been recently fixed upstream (see astropy/astropy#4078).

**Comment by DougBurke** [comment]
This appears to have been fixed in a recent astropy release as 1.1 doesn't seem to cause the problem. This can probably be closed now that numpy 1.10 and matplotlib 1.5 can be used (i.e. #103 and #113 are closed by PR #109), as I think astropy 1.1 on anaconda requires one or both of these.

**Comment by olaurino** [comment]
I agree, please feel free to close this issue!

**Comment by DougBurke** [comment]
I'll do some checks with master and when I've confirmed things are okay I'll close it.

**Comment by DougBurke** [comment]
I don't see the message with IPython 4.0.1 and astropy 1.1, so I'm closing this issue.
