### ISSUE TITLE
change random sampling to use the new numpy 1.17 generators

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#867]
NumPy 1.17 has introduced an improved way to generate random numbers. It would be good to switch to this once we can drop pre-1.17 support. Information at https://numpy.org/doc/stable/reference/random/index.html

**Comment by DougBurke** [comment]
I wonder if we can use this new functionality to make the testing of our MonteCarlo-related routines more robust, by allowing a known (or fixed) generator to be used when testing these routines (like `get_draws` or `sample_energy_flux`)?

**Comment by hamogu** [comment]
I suggest that we just use the new system whenever we touch code anyway or when a test breaks and we need to examine it more closely. We could go back and change any occurrences in Sherpa, but that's not a high priority item.

**Comment by DougBurke** [comment]
That's okay for the tests. For actual code we'll need to think about how we want to do it - probably just add a parameter, but then what's the default yadda yadda.

**Comment by DougBurke** [comment]
Argh - how do I tell GH that #1753 is not going to magically fix this. Grrr.
