### ISSUE TITLE
Should we make Model1D + Model2D an error?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#872]
Given the work regrid support by @olaurino has now made it (a bit) clearer/cleaner on combining 1D and 2D models, should we now make it an error to combine models of different dimensionality? Ideally at creation time, like

    set_source(beta2d.src + const1d.bgnd)

but it could instead be a runtime error when it is evaluated.

**Comment by olaurino** [comment]
This is also known as `SH-55` in Jira.

**Comment by DougBurke** [comment]
Closed by #900.
