### ISSUE TITLE
ui.set_bkg does more than datapha.set_background; should it?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#879]
You can see subtle differences if you have two DataPHA objects, `src` and `bkg`, and say

    sherpa.astro.ui.set_data(src)
    sherpa.astro.ui.set_bkg(bkg)

and

    pha.set_background(bkg)
    sherpa.astro.ui.set_data(src)

Now, there are legitimate reasons for the ui layer to do extra things, since it is a convenience layer, and if so we should try to be explicit in the documentation. However, I am trying to make it easier to use the object API, and it may make sense to move some functionality into set_background (or other methods).

In this case, the extra functionality that set_bkg adds is that

 - it copies over the grouping and quality data from the source if there is no information in the background
 - if there's no background response it copies over the source response and matches the units setting
 - it copies over the rate and plot_fac settings

I believe that this makes sense to be in the lower-level set_background routine (there may be times the user doesn't want this but it is likely to be a rare occurrence, and so can be  handled by the user post-processing the data).

**Comment by hamogu** [comment]
👍

**Comment by DougBurke** [comment]
I do think we have a lot of logic in the ui layer that would be better handled at a lower level (to make it easier for users using direct access to the objects to recreate a "ui" analysis), and will probably try to fix things in piece-meal fashion rather than several surgical PRs.

**Comment by DougBurke** [comment]
See also #629
