### ISSUE TITLE
sherpa.astro.ui.utils.fake_pha - slightly strange behavior if id is None

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#890]
The start to `fake_pha` is shown below. If the id argument is set to None then - unlike many functions - will not switch over to using the default id, but instead will trigger generating a fake PHA dataset (since None is never included in the self._data dictionary).

We could make None an error (since the id argument is required), or we can just add a check of id - e.g. the standard `id = self._fix_id(id)` check.

Existing code for `fake_pha`:

        d = sherpa.astro.data.DataPHA('', None, None)
        if id in self._data:
            d = self._get_pha_data(id)
        else:
            # Make empty header OGIP compliant
            # And add appropriate values to header from input values
            d.header = dict(HDUCLASS="OGIP", HDUCLAS1="SPECTRUM",
                            HDUCLAS2="TOTAL", HDUCLAS3="TYPE:I",
                            HDUCLAS4="COUNT", HDUVERS="1.1.0")
            self.set_data(id, d)

**Comment by DougBurke** [comment]
As a note I've got a test of the current behavior included in PR #888.

**Comment by hamogu** [comment]
This was fixed in #1073.
