### ISSUE TITLE
how do we combine parameter values

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#915]
From a helpdesk ticket

> Is it possible to use numpy functions with the "set_par" function in Sherpa? For example, in the following:
> 
> set_par(mycomponent.par1, val = mycomponent.par2 * np.exp(mycomponent.par3)),
> 
> I get the error:
> AttributeError: 'BinaryOpParameter' object has no attribute 'exp'

It's not immediately obvious how to handle this - it seems like we might want to provide a [`__array_ufunc__` method](https://numpy.org/doc/stable/reference/arrays.classes.html#numpy.class.__array_ufunc__), noting the "I am not a ndarray subclass" issues, but it needs thinking about.

**Comment by DougBurke** [comment]
I think this was addressed by #1653 . Do you agree @hamogu?

**Comment by hamogu** [comment]
I agree.
