### ISSUE TITLE
DataPHA.get_filter(group=False) seems odd

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#917]
This may come down to the definition of the `group` parameter to `get_filter` as it is undocumented.

```
>>> from sherpa.astro import ui
>>> ui.load_pha('sherpa-test-data/sherpatest/3c273.pi')
>>> d = ui.get_data()
>>> d.get_filter()
'0.124829999695:12.410000324249'
>>> d.get_filter(group=False)
'0.008030000201:14.943099975586'
```

This is a grouped dataset, so maybe there's a reason the `group=False` returns a larger range than the default, but there's been no filter applied here. so it's not clear (this could point to issues with `group=True` instead?).

**NOTE** `get_filter` notes that the bin locations reference the center of the bin, which explains the difference above. Whether that's a good idea is a different question...

If we add a simple filter, we again see that the `group=False` range is larger, why is this?

```
>>> d.notice(0.5, 7)
>>> d.get_filter()
'0.518300011754:8.219800233841'
>>> d.get_filter(group=False)
'0.474500000477:9.862299919128'
```

And I now ignore the 2-3 keV range, and things get odd for `group=False`:

```
>>> d.ignore(2, 3)
>>> d.get_filter()
'0.518300011754:1.919900000095,3.233900070190:8.219800233841'
>>> d.get_filter(group=False)
'0.474500000477:0.781100004911,0.795699983835:9.862299919128'
```

Why is the grouping 0.47:0.78 and 0.79:9.8 ?

**EDITED TO ADD** The reason for the last question is "it's a bug", and the fix is in #918

**Comment by DougBurke** [comment]
So, from looking at the code of `sherpa.utils.create_expr`, I believe it is intended to work in channel space, since the comment mentions the name "channels", and the code is looking for a `diff` value of 1 to the next bin. However, we can see from the tests that create_expr gets called with energy values - e.g. vals is `[ 0.29549946  0.29553468  0.29556991...]`. Ugh.

```
def create_expr(vals, mask=None, format='%s', delim='-'):
    """
    collapse a list of channels into an expression using hyphens
    and commas to indicate filtered intervals.
    """
    expr = []

    if len(vals) == 0:
        return ''
    elif len(vals) == 1:
        return format % vals[0]

    diffs = numpy.apply_along_axis(numpy.diff, 0, vals)
    if mask is not None:
        index = numpy.arange(len(mask))
        diffs = numpy.apply_along_axis(numpy.diff, 0, index[mask])

    for ii, delta in enumerate(diffs):
        if ii == 0:
            expr.append(format % vals[ii])
            if delta != 1 or len(diffs) == 1:
                expr.append(',')
            continue
        if delta == 1:
            if expr[-1] == ',':
                expr.append(format % vals[ii])
            if expr[-1] != delim:
                expr.append(delim)
        else:
            if not expr[-1] in (',', delim):
                expr.append(',')
            expr.append(format % vals[ii])
            expr.append(',')
    if len(expr) and expr[-1] in (',', delim):
        expr.append(format % vals[-1])

    return ''.join(expr)
```

**Comment by anetasie** [comment]
hmm... Based on the user filtering on energy or channel there must be some relation between these two via an `rmf`.

**Comment by DougBurke** [comment]
My guess is that it's code originally written for channel space, and then it got used for other units incorrectly. However, this is a hypothesis at the moment - I've just started #918 for my explorations (which hasn't got very far).

**Comment by DougBurke** [comment]
Hmm, it's actually okay as long as there's a mask (although there are still some issues to resolve).

**Comment by DougBurke** [comment]
These calls make sense to me:

```
>>> from sherpa.utils import create_expr
>>> create_expr([1, 2, 3, 4])
'1-4'
>>> create_expr([1, 2, 3, 4], [True, True, True, True])
'1-4'
>>> create_expr([0.1, 0.2, 0.4, 0.8], [True, True, True, True], format='%.1f')
'0.1-0.8'
>>> create_expr([0.1, 0.2, 0.4, 0.8], [True, False, False, True], format='%.1f')
'0.1,0.8'
```

I don't understand the following:

- why not '1-3'

```
>>> create_expr([1, 2, 3, 4], [True, True, True, False])
'1-4'
```

- why not '2-4'

```
>>> create_expr([1, 2, 3, 4], [False, True, True, True])
'1-4'
```

- why not '1-2'

```
>>> create_expr([1, 2, 3, 4], [True, True, False, False])
'1,4'
```

One issue is how are ranges meant to be interpreted, both for non-integrated and integrated bins (this code is assumed to be sent the mid-point of the bin for integrated cases, but then asks as it does for the non-integrated case, which may make sense).

Here's a slightly larger example (just to increase the number of bins:

```
>>> x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> y = [True] * 9
>>> y[4] = False
>>> create_expr(x, y)
'1-4,5-9'
>>> x[4]
5
```

So bin 5 has been excluded, and we get `1-4`, which makes sense, but why is it not `6-9'?. Is it to do whether the check is inclusive (<=) or exclusive (<)?

**Comment by DougBurke** [comment]
It seems to assume the first bin is always included - e.g.

```
>>> import numpy as np
>>> xx = np.arange(100)
>>> yy = np.zeros(100, dtype=np.bool)
>>> yy[-5:] = True
>>> xx[yy]
array([95, 96, 97, 98, 99])
>>> create_expr(xx, yy)
'0-99'
```

**Comment by DougBurke** [comment]
**HOLD ON** I'm being stupid and calling it incorrectly...

**Comment by DougBurke** [comment]
So, I believe that `create_expr` is intended to be used with a mask array whose selected values match the input values - that is

```
>>> from sherpa.utils import create_expr
>>> create_expr([0.2, 0.3, 0.4, 0.5, 0.6], [True, True, True, False, True, True])
'0.2-0.4,0.5-0.6'
```

That is, the first value only has numbers where the mask array is True.

However, a number of tests cause this function to be called when this condition does not hold. I am investigating.
