### ISSUE TITLE
PHA: plot_model oddly affected by change in analysis setting

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#920]
The following call shows that the last `plot_model` call has changed the energy range used by plot_model when it should use the same range as the first call:

```
import logging

from matplotlib import pyplot as plt

from sherpa.astro import ui

logging.getLogger('sherpa').setLevel(logging.ERROR)
ui.load_pha('/home/dburke/sherpa/sherpa-master/sherpa-test-data/sherpatest/3c273.pi')
logging.getLogger('sherpa').setLevel(logging.INFO)

ui.notice(0.5, 7)

ui.set_source(ui.powlaw1d.pl)

pl.gamma = 1.93
pl.ampl = 1.74e-4

ui.plot_model()

ax = plt.gca()
print(ax.get_xlim())

ui.set_analysis('channel')

ui.plot_model()

ax = plt.gca()
print(ax.get_xlim())

ui.set_analysis('energy')

ui.plot_model()

ax = plt.gca()
print(ax.get_xlim())
```

The output is

```
(0.005110004544258084, 10.331689915060997)
(1.3500000000000014, 708.65)
(0.23652000352740288, 0.654080007225275)
```

The last line shows that the energy used by the third plot_model call is 0.23 to 0.65 keV, which makes *no sense*.
```

**Comment by anetasie** [comment]
Is this related to #921?

**Comment by DougBurke** [comment]
No. This is related to the fact that `get_filter` returns group number rather than channel number when analysis==channel. The file shown below has 46 groups and the code used in plot_model causes the group numbers to be interpreted as channel numbers. I'll look at making get_filter return channel numbers tomorrow, and what damage that causes...

```
>>> ui.load_pha('sherpa-test-data/sherpatest/3c273.pi')
>>> ui.set_analysis('channel')
>>> ui.get_filter()
'1:46'
```
