### ISSUE TITLE
DataPHA.get_ebins() with analysis=channel returns +- 0.5 bin widths

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#921]
```
ui.load_pha(..)
d = ui.get_data()
d.set_analysis('channel')
xlo, xhi = d._get_ebins(group=False)
```

xlo is [0.5, 1.5, ...]
xhi is [1.5, 2.5, ...]

In other places we use channel, channel + 1 rather than channel-0.5, channel+0.5

Which is best?

**Comment by anetasie** [comment]
hmm.... interesting question.  I guess this is mainly relevant to plotting, while in the analysis it should follow the translation between the channel number and the energy range for the channel. How is the channel defined in the response files?

**Comment by DougBurke** [comment]
I agree that this is primarily a plotting issue (although channel numbers do get used in filtering, so something to keep aware of).

This was mainly something I noted but am not planning on addressing right now. Unless by accident because of something else ;-)
