### ISSUE TITLE
check stats docs for invalid escape sequence

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#923]
From a test run on Travis (Python 3.7) I saw

```
=============================== warnings summary ===============================
sherpa/stats/__init__.py:546
  /home/travis/build/sherpa/sherpa/sherpa/stats/__init__.py:546: DeprecationWarning: invalid escape sequence \s
    """
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by anetasie** [comment]
Is this from the recent PR #899?

**Comment by DougBurke** [comment]
That would be my guess - probably from

```
L = (prod)_i 1/(\sigma^2 sqrt(2 \pi)) exp[(N(i) - M(i))^2/2 sigma(i)^2]
```

but this sort of thing is easy to accidentally introduce (line 546 reported as the problem line is the last line of the multi-line docstring that includes this).

You can either change the text to remove \sigma or change this to a r-quoted string. You can trigger this warning if you have python 3.7 by calling

    python -We -c 'import sherpa.stats'

Unfortunately you don't see the warning in Python 3.8
