### ISSUE TITLE
list of docstring/ahelp issues

### ISSUE THREAD

**Issue by nplee** [sherpa/sherpa#948]
@DougBurke this is just a backed up location of notes of typos/weirdness of the docstring to ahelp review I've been looking through.  Content-wise, no real problems from the initial reading.

notice.xml typo ex.1 'choses' --> 'chooses'

load_pha typo ex.5 'identtifier' --> 'identifier'

plot_* partable 'overplot' typo "exsiting" --> "existing"

get_energy_flux_hist/get_photon_flux_hist/plot_energy_flux/plot_photon_flux/sample_energy_flux/sample_photon_flux/sample_flux partable 'hi' typo "guven"

schechter.xml inconsistency between Schechter/schechter/Schecter/schecter

set_iter_method.xml "hige" --> "high", "chi-square2" --> "chi-square"

set_model.xml "cacheing" --> "caching"

set_rmf/set_arf/load_arf/load_rmf "efect" --> "effect"

show_model.xml Desc: "that is that is"

get_error.xml Desc: "dependent acis" --> "dependent axis"

get_grouping.xml Par: "(is is a..." --> "(it is a..."

get_int_proj/get_int_unc/get_reg_proj/get_reg_unc/int_proj/int_unc/reg_proj/reg_unc instances of "calcutation" --> "calculation" in the min/max partable

get_data_contour/get_model_contour/get_ratio_contour/get_resid_contour/get_source_contour par resid_data: "... arrays the..." missing words?

get_bkg_source_plot ex.4/get_source_plot ex.3: "Retrive" --> "retrieve"
get_xsxset.xml: "retrive" -- > "retrieve"

get_xs* Xspec version for 4.13 is noted as 12.11.1 not 12.10.1?

xsbexrav/xsbexriv/xsireflect/xspexmon/xspexrav/xspexriv/xsreflect/xsrefsch "heaver" --> "heavier"

xsc6pmekl/xsc6pvmkl Desc: "by by"

xscemekl/xscevmkl/xscflow/xsmkcflow/xsvmcflow   "maxmimum" --> "maximum" in partable

xspec convolution models use "rather then" --> "rather than"

xskyconv.xml "axisymmetric"?
partable: "theta_o" has "inclinitation" --> "inclination"

xskyrline.xml "axisymmetric"?
 
xsnsmax.xml Desc: "superceeded" --> "superseded"

xsredden/xsuvred/xszredden/xszsmdust partable: "E(B-v)" --> "E(B-V)"

xsrfxconv/xsxilconv: "ALl" --> "All"

xsslimbh.xml partable "vflag": "contorl" --> "control"

xssnapec.xml partable "R": "SN1a" --> "SNIa", "SNIIa" --> "SNII"

xssresc.xml partable "norm": "Ghz" --> "GHz"

xsxion.xml partable "outer": "The er radius" --> "The outer radius"

**Comment by DougBurke** [comment]
@nplee - if you want to try fixing some of these then the xs*xml files come from

    sherpa/astro/xspec/__init__.xml

(there are classes called XSxxx - so XSsxion as an example - that contain the docstrings).

The XSPEC version number is added by my code and the decision to go out with XSPEC 12.10.1 in CIAO 4.13 was made after the XML files you reviewed were made. They have been updated now (well, the code has).

schecter is sherpa/astro/models.html or sherpa/astro/models/__init__.py in a class called 'Schechter'.

The other symbols are in either of (check the astro version first as the same function can appear in both)

    sherpa/astro/ui/utils.py
    sherpa/ui/utils.py
