### ISSUE TITLE
plotting PHA data/models when the grids don't quite match

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#977]
This is the output of

    plot_data(color='green', 'linestyle='-', marker='', yerrorbars=False)
    plot_model(overplot=True)

for a PHA dataset (HRC-S grating). Note that this doesn't happen for all such datasets.

![FIG](https://user-images.githubusercontent.com/224638/96120882-35411e80-0ebd-11eb-8b57-76f8fb7a9abc.png)

You can see that the vertical line between some, but not all, bins is missing. This is because the `BIN_LO/BIN_HI` sets of data in the PHA file don't quite match up:

```
sherpa In [34]: d = get_data()

sherpa In [35]: idx = np.arange(8462, 8466)

sherpa In [36]: for x in zip(d.bin_hi[idx], d.bin_lo[idx]):
           ...:     print(x[0], x[1])
           ...:
100.025 100.0125
100.0125 100.0
100.00000000000001 99.98750000000001
99.98750000000001 99.97500000000001

```

You can see that the bin at 100 Angstroms doesn't quite match.

This messes up the code added in #906 / #931, which assumes that the bins exactly match. So, there's two things to think about here:

a) a fix in the plotting code that uses `sherpa.utils.sao_fcmp` to identify bins that are close enough together

b) think about changes to the DataPHA/ARF/RMF classes to insert some validation stage that "corrects" for bins that don't match (in a perfect world with a warning to users that this has happened, but in reality they do not know how to fix this, and the upstream producers of the data may not be able to fix this, so it's not clear it is that useful).

**Comment by anetasie** [comment]
@DougBurke This looks like the numerical mismatch at the 'non-important' scales. Is there a way to drop the precision in such cases and treat the bin edges at the last valid/important digit? What is the internal data precision in the PHA/ARF/RMF file and is this reflected in our I/O?

**Comment by DougBurke** [comment]
@anetasie - that's what point a describes. There's always the issue of what size a tolerance we use - I'm looking at the float32 "eps" size since we use it elsewhere. I would not want to code up a "let's guess the number of significant figures this value has" type routine as I think it would be more troublesome than you'd anticipate, given IEEE floating-point data. Instead I'm just  identifying close values and making sure they use the same values for the two edges.

The data difference I show above are encoded in the PHA file, which is why I think a long-term fix is to apply fixes when we create the PHA/ARF/RMF objects, but that is a longer term issue. I have no idea how this PHA file was created (I just found it no my disk from some previous issue I no-longer remember).

**Comment by DougBurke** [comment]
Here's the behavior after applying #979

![FIG](https://user-images.githubusercontent.com/224638/96165849-30935f00-0eeb-11eb-9351-1fffae5c3c8b.png)

**Comment by anetasie** [comment]
It looks good.

**Comment by DougBurke** [comment]
We have evidence that this is quite prevalent in XMM gratings...
