### ISSUE TITLE
Doc for load_multi_arfs / rmfs confusing or even wrong

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#982]
This was brought up by a Sherpa I communicated with:

The docstring for `load_multi_arfs` / `rmfs` seems to indicate that this function is useful for e.g. Chandra HETG observations.
The docstring says: ```A grating observation - such as a Chandra HETG data set - may require multiple responses. This function lets the multiple ARFs for such a data set be loaded with one command.```
https://github.com/sherpa/sherpa/blob/master/sherpa/astro/ui/utils.py#L5728

I read this as "If you have a PHA2 files from the HETG, then will load all your arfs at once". This impression is strengthened by an example that seems to load the  arfs for positive and negative orders into dataset 1 and 2:
```
>>> arfs = ['m1.arf', 'p1.arf']
>>> load_multi_arfs(arfs, [1,2])
```
Only after I read the code fir this function I realized that that's not what it's doing. Instead it's loading two arfs for the same dataset (here defailt_id=1 because it's not given.)

I have no idea when I would possibly use `load_multi_xxx`, but certainly not for HETG data. That comes as a phaII file, so what I need to do for HETG is something like:

```
for i, arf_file in zip([3, 4, 9, 10], arf_list):
    load_arf(i, arf_file)
```
or use a datastack.

This is an issue and not a PR because:

- The example is so explicit that I wonder it I'm too confused. Is what I wrote above right?
- I don't know what these functions might be useful for at all (I've never seen or used multiple arfs or rmfs for the same dataset), so I can't make a more meaningful example.

**Comment by DougBurke** [comment]
The documentation could be confused. I think it's really for LETG data and not HETG data (unless you are being sneaky and combining orders, but who would do that?)  - e.g. https://cxc.cfa.harvard.edu/sherpa/threads/grating_hrcsletg/
