### ISSUE TITLE
How can I turn off the error bars in residual plots?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#986]
So I don't forget this:

The UI layer has `get_data_plot_prefs` and `get_model_plot_prefs`. Do we want a "residual" version (for resid, ratio, and delchi)? Is there any other way we could do this instead.

**Comment by hamogu** [comment]
how about `get_plot_prefs(plottype)` so we don't have to add a new function for every plot?

**Comment by DougBurke** [comment]
One complication - for any approach - is that we now - as of Sherpa 4.12.2 - can have "different" preferences depending on the data type (DataPHA and Data1DInt are different to other datasets). At the moment `get_data_plot_prefs` now has an `id` argument which is used to work out what to return, but this whole approach probably needs a review (e.g. `get_xxx_plot` routines too) [to note, `get_plot_prefs` would add the same argument to address this].

**Comment by DougBurke** [comment]
We added `get_plot_prefs` in 4.16.0 / #1839 so I'm closing this.
