### ISSUE TITLE
sherpa.optmethods.opt should really be in the tests/ directory

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#995]
There's a bunch of code in `sherpa/optmethods/` that should really be in the test directory. Let's review when we have time.

**Comment by DougBurke** [comment]
@dtnguyen2 - am I right in thiniking that sherpa.optmethods.opt is just for testing things and could be moved to scripts/test_opt.py (for example)? Or do we need it in the sherpa namespace?

**Comment by dtnguyen2** [comment]
The python test functions in the _sherpa/optmethods/opt.py_ file were written because during the development of the optimization methods I wanted to be able to use the python autodiff module to test something that I was working on but I sort of loss interest in it.  I suppose we should delete it since It is no longer being used.

**Comment by DougBurke** [comment]
It turns out that `sherpa.optmethods.optfcts` uses

```
from sherpa.optmethods.ncoresde import ncoresDifEvo
from sherpa.optmethods.ncoresnm import ncoresNelderMead
```

and these two use `sherpa.optmethods.opt` via

```
# ncoresde

from sherpa.optmethods.opt import Opt, SimplexRandom

# ncoresnm

from sherpa.optmethods.opt import MyNcores, Opt, SimplexNoStep, SimplexStep, \
    SimplexRandom
```

so it doesn't look like we can remove this code.

**Comment by DougBurke** [comment]
@dtnguyen2 - looking at https://github.com/sherpa/sherpa/blob/441f7becaca52b9d867b659520678110c0ff6026/sherpa/optmethods/optfcts.py#L670-L698 - which is part of `montecarlo`, the section seems odd when `numcores` is not equal to 1. I would have expected the code to do something related to `ncores_de` (or something else), but it does nothing. Is this an error in the code or does it not matter here?

It looks like our tests all have `numcores` set to 1 so we don't have tests that cover this behavior.

**Comment by DougBurke** [comment]
Note to self: `NelderMeadBase` in `ncoresnm.py` calls `np.seterr` during it's `__init__` method. This is not ideal as it suddenly changes the numpoy setting for the whole code. If we keep `NelderMeadBase` then we'll need to think about how to handle this (see also #1238 )

**Comment by DougBurke** [comment]
closing this as I've done some work on the opt code (moving tests around) and am unlikely to do anything else.
